- internship/templates/internship_detail.html
Inform the ticket you are solving in this pull request: #1261 
Le fait d'avoir {% if student.choice == i %} ne fonctionnait pas, car i était le nombre d'étudiant qui avait fait ce choix de stage et non leur ordre de préférence. 
Maintenant oui avec forloop.parentloop.counter0 car on regarde l'itération du tableau des choix
> Affichage de la liste des étudiants dans le détail d'un stage

- assessments/tests/views/test_pgm_manager_administration.py
- assistant/tests/utils/test_get_persons.py
- assistant/tests/utils/test_send_email.py
- assistant/tests/views/test_assistant_form.py
- assistant/tests/views/test_messages.py
- dissertation/tests/views/test_dissertation.py
- dissertation/tests/views/test_proposition_dissertation.py
We don't need to instanciate a new client for the tests, because the TestCase class from django.test, has already done that for us.
> Remove the self.client in the tests

- assistant/forms.py
Inform the ticket you are solving in this pull request: #2484 
person must be removed from ReviewerReplacementForm
reviewer must be hiddenInput in ReviewForm
> remove reviewer and person fields from forms

- base/templates/learning_unit/pedagogy.html
Inform the ticket you are solving in this pull request: #2422
> #2422 Remove tabindex=-1 because conflict with link tab CKEDITOR plugin

- assistant/templates/pst_form_view.html
Inform the ticket you are solving in this pull request: #OSIS-166
When a reviewer look at the assistants files, the research tab should not be visible for teaching assistants
> OSIS-166 Hide researchs tabs for teaching assistants

- base/models/entity_version.py
> OSIS-47 Fix bug : bad use of __contains_given_date in entity_version

- base/business/learning_unit_proposal.py
- base/tests/business/test_learning_unit_proposal.py
> OSIS-852 Suppression de la learning unit quand on annule une proposition

- dissertation/models/dissertation.py
Référence Jira : OSIS- 603
Ajout d'une exclusion pour le comptage des places disponibles pour le mémoire. 
Modification effectué suite à un test failed.
> Osis 603 - ajout d'une exclusion pour le comptage des places disponibles pour le mémoire

- base/tests/business/test_learning_unit_proposal.py
> OSIS-1035 Fix end_year anac (randomly) to prevent None

- base/forms/learning_unit/edition_volume.py
- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/tests/forms/test_edition_form.py
- base/tests/views/test_learning_unit_edition.py
Référence Jira : OSIS-1210 : Volumes in partim can be equal to corresponding in parent
> OSIS-1210 Volumes in partim can be equal to corresponding in parent

- base/utils/cache.py
The cache utils returns a simple dict in place of a querydict.
> Fixed error with debug toolbar and cache

- base/templates/education_group/pdf_content.html
- base/tests/views/education_groups/group_element_year/test_read.py
- base/views/education_groups/group_element_year/read.py
…lément du PDF
Référence Jira : OSIS-1925
> OSIS-1925 Fixed problème d'affichage des contrainte pour le premier élément du PDF

- base/business/learning_units/edition.py
- base/models/learning_component_year.py
- base/tests/business/learning_units/test_edition.py
> OSIS-2118 fixed duplication of LearningComponents when extending a LearningUnitYear

- base/fixtures/groups.json
> IUFC - Add continuing_education_managers to groups

- base/forms/education_group/training.py
Pour les gestionnaires facultaires et centraux, remplacer le champ "Validité" par "Début"à l'écran de création d'une formation
Référence Jira : OSIS-2622
> OSIS-2622 remplacer le champ "Validité" par "Début"

- base/templatetags/education_group.py
> Osis 2748 Empêcher la modal de souvrir pour les centrals

- base/tests/views/test_learning_unit_edition.py
- base/views/learning_units/update.py
> OSIS-2849 order UCL entities by acronym and order external entities by title

- base/business/learning_units/automatic_postponement.py
> OSIS-3229 ignoring Learning units of 'mobility' for automatic postponement

- base/templatetags/education_group.py
- base/views/education_groups/update.py
> [QA] OSIS-3242 prevent from updating an EducationGroup before 2019

- base/forms/learning_achievement.py
- base/tests/views/test_learning_achievement.py
(cherry picked from commit 9d3b2f22495c1876369964a45bcaab4f39b9ff1f)
Référence Jira : OSIS-3240
> [to qa] OSIS-3240 Trigger save on cms  when learning_achievement saved

- base/models/learning_unit_year.py
- base/tests/models/test_learning_unit_year.py
> #OSIS-3297 Lors de la visualisation d'une partim, je ne veux pas voir des warning portant sur les autres partims

- base/models/group_element_year.py
- base/tests/models/test_group_element_year.py
> #OSIS-3325 Si un groupement a 0 crédit: je ne dois pas voir affiché "0 crédit" à coté du groupement dans le PDF

- assessments/api/serializers/scores_responsible.py
>  OSIS-3299 : Filter double person in attribution of a luy 

- base/business/education_groups/group_element_year_tree.py
- base/tests/business/education_groups/test_build_tree.py
> OSIS-3431 do not show |E| for LU of mobility + test

- base/business/learning_units/xls_comparison.py
- base/forms/learning_unit/search/external.py
- base/static/js/osis_datatable.js
- base/templates/learning_unit/search/base.html
- base/templates/learning_unit/search/description_fiche.html
- base/templates/learning_unit/search/external.html
- base/templates/learning_unit/search/proposal.html
- base/views/learning_units/search/borrowed.py
- base/views/learning_units/search/common.py
- base/views/learning_units/search/proposal.py
- base/views/learning_units/search/service_course.py
- base/views/learning_units/search/simple.py
- Reduce the time to show the learning unit search pages by removing duplicate queries execution.
- Also, show a "laoding..." message when retrieving the learning units via ajax.
- Fix the sort by campus in external learning unit search.
> [OSIS-2973] Optimize query execution + show spinner when retrieving data

- base/business/education_groups/perms.py
- base/tests/business/education_groups/test_perms.py
- base/tests/forms/education_group/test_training.py
for mini-trainings and groups
Référence Jira : OSIS-3413
> OSIS-3413 block modify button to not show modal of certificate aims

- base/fixtures/groups.json
Pull request automatique de hotfix/OSIS-3368 vers QA
> [hotfix/OSIS-3368 => QA] Le groupe _expert_users_ n_est plus utile

- base/fixtures/groups.json
> [hotfix/OSIS-3368 => DEV] Le groupe _expert_users_ n_est plus utile

- learning_unit/api/serializers/learning_unit.py
Pull request automatique de hotfix/OSIS-3763 vers QA
> [hotfix/OSIS-3763 => QA] UE Externes: toutes les UE externes doivent avoir un code qui commence par E (> 2018): reprise de données

- learning_unit/api/serializers/learning_unit.py
Pull request automatique de hotfix/OSIS-3763 vers MASTER
> [hotfix/OSIS-3763 => MASTER] UE Externes: toutes les UE externes doivent avoir un code qui commence par E (> 2018): reprise de données

- learning_unit/api/serializers/learning_unit.py
Pull request automatique de hotfix/OSIS-3763 vers DEV
> [hotfix/OSIS-3763 => DEV] UE Externes: toutes les UE externes doivent avoir un code qui commence par E (> 2018): reprise de données

- program_management/forms/group_element_year.py
- program_management/templates/group_element_year/group_element_year_comment_inner.html
- program_management/tests/forms/test_group_element_year_form.py
Pull request automatique de improvement/OSIS-3701 vers DEV
> [improvement/OSIS-3701 => DEV] Afficher les crédits absolus de l_UE à côté des crédits relatifs lorsqu_on attache l_UE à un groupement

- webservices/api/views/general_information.py
- webservices/tests/api/views/test_general_information.py
Pull request automatique de hotfix/OSIS-3892 vers QA
> [hotfix/OSIS-3892 => QA] Webservice V3 ne renvoie plus d’information pour les mineures

- webservices/api/views/general_information.py
- webservices/tests/api/views/test_general_information.py
Pull request automatique de hotfix/OSIS-3892 vers MASTER
> [hotfix/OSIS-3892 => MASTER] Webservice V3 ne renvoie plus d’information pour les mineures

- base/templates/education_group/blocks/modal/custom_xls.html
Lorqu'on clique sur  "Sélectionner tout" et qu'ensuite on désélectionne une entrée, le "Sélectionner tout" doit se décoché.
> OSIS-3979 :  liste xls des ues d'une formation

- base/models/abstracts/abstract_achievement.py
- base/models/learning_achievement.py
- base/tests/views/test_learning_achievement.py
- base/views/learning_achievement.py
> OSIS-4095 prevent learning achievement ordering postponement when order is different in future luys

- program_management/forms/group_element_year.py
- Add width sur l'imput des crédits relatifs pour garder une valeur fixe lors de la modification de taille d'écran
Référence Jira : OSIS-4471
> OSIS-4471 Fixer la taille de l'input crédit relatif pour voir sa valeur à chaque fois

- base/templates/learning_unit/blocks/titles.html
- Ajout des tooltips et italic dans les formulaires de creations et editions
Référence Jira : OSIS-4498
> OSIS-4498 Ajout des tooltips et italic dans les formulaires de creations et editions

- base/forms/learning_unit/edition.py
- base/tests/views/test_learning_unit_edition.py
- base/tests/views/test_learning_unit_proposal.py
- Utilisation de postpoment_form pour vérifier que les éléments devant être créé le sont
> OSIS-4214 Utilisation de postpoment_form pour vérifier que les éléments devant être créé le sont

- osis_role/contrib/permissions.py
- osis_role/tests/contrib/test_permissions.py
Référence Jira : OSIS-4440 (part of this ticket has yet to be done in IUFC)
> OSIS-4440 add has_module_perms logic relative to roles

- base/templates/learning_unit/identification.html
- Enlever l'italique pour les remark et remark_english
- Mettre le tiret quand None
- Uniformiser l'emplacement des remark et remarks_english entre externe et normal
Référence Jira : OSIS-4554 
> OSIS-4554 Uniformiser les valeurs remark et remark english des UEs externe avec les UEs

- base/forms/education_group/coorganization.py
- base/tests/forms/education_group/test_coorganization.py
- base/tests/views/education_groups/test_update.py
> OSIS-4701 init field with pk rather than using to_field_name

- base/tests/views/education_groups/test_update.py
- education_group/auth/roles/central_manager.py
- program_management/tests/views/prerequisite/test_update.py
- program_management/tests/views/test_groupelementyear_update.py
- program_management/tests/views/test_perms.py
- program_management/tests/views/tree/test_attach.py
> OSIS-3717 central can add education group/change link data when attached to entity

- base/tests/views/test_learning_achievement.py
- base/tests/views/test_learning_unit_pedagogy.py
- base/tests/views/test_teaching_material.py
- base/views/learning_unit.py
- base/views/learning_units/pedagogy/update.py
- Modification du message enc as de non report
Référence Jira : OSIS-3784
> [QA] OSIS-3784 Vérifier les reports et accès édition journalière dans le passé

- education_group/views/mini_training/common_read.py
Pull request automatique de feature/OSIS-3483 vers DEV
> [feature/OSIS-3483 => DEV] En tant que gestionnaire central du catalogue de formation, je veux visualiser une version des formations

- base/templates/learning_unit/blocks/titles.html
Pull request automatique de hotfix/OSIS-4608 vers QA
> [hotfix/OSIS-4608 => QA] Enlever lastérisque à côté de _Intitulé en anglais_ sur lUE complet et partim, la zone nest pas obligatoire

- learning_unit/api/views/learning_unit.py
- learning_unit/tests/api/views/test_learning_unit.py
Pull request automatique de hotfix/OSIS-4941 vers QA
> [hotfix/OSIS-4941 => QA] [WS] Le endpoint learning_units ne doit pas contenir les UE externe de mobilité

- program_management/ddd/domain/node.py
Old way resulted by having node_type = None in instantiated NodeLearningUnitYear
Référence Jira : OSIS-4926
> OSIS-4926 Correctly set node_type

- program_management/ddd/domain/exception.py
- program_management/ddd/validators/_match_version.py
- program_management/locale/en/LC_MESSAGES/django.po
- program_management/locale/fr_BE/LC_MESSAGES/django.po
- program_management/tests/ddd/validators/test_match_version.py
- program_management/tests/views/tree/test_paste.py
- program_management/views/tree/paste.py
> OSIS-4964 validate before opening modal when pasting into tree

- program_management/forms/version.py
- program_management/tests/views/tree_version/test_create.py
- Changer l'affichage du choix de end_year on devrait voir les années académiques
Référence Jira : OSIS-1826-issue6
> OSIS-1826-issue6 on devrait voir les années académiques

- education_group/ddd/service/write/postpone_group_modification_service.py
- education_group/ddd/service/write/postpone_mini_training_and_group_modification_service.py
- education_group/ddd/service/write/postpone_training_and_group_modification_service.py
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/tests/ddd/service/write/test_create_orphan_mini_training_service.py
- education_group/tests/ddd/service/write/test_create_orphan_training_service.py
- education_group/tests/ddd/service/write/test_postpone_group_modification_service.py
- education_group/tests/ddd/service/write/test_postpone_mini_training_and_group_modification_service.py
- education_group/tests/ddd/service/write/test_postpone_training_and_group_modification_service.py
- program_management/ddd/domain/service/calculate_end_postponement.py
- program_management/ddd/domain/service/identity_search.py
- program_management/ddd/service/read/get_end_postponement_year_service.py
- program_management/ddd/service/write/postpone_program_tree_service.py
- program_management/ddd/service/write/postpone_program_tree_service_mini_training.py
- program_management/ddd/service/write/postpone_tree_version_service.py
- program_management/ddd/service/write/postpone_tree_version_service_mini_training.py
- program_management/ddd/service/write/update_program_tree_version_service.py
- program_management/tests/ddd/domain/service/test_calculate_end_postponement.py
- program_management/tests/ddd/service/read/test_get_end_postponement_year_service.py
> OSIS-4995 fixed calculation of end postponement year for eauch domains (training, minitraining, group, programtree...)

- base/auth/roles/program_manager.py
- education_group/ddd/domain/training.py
- education_group/tests/ddd/domain/test_training.py
> OSIS-4954 validate type 2 max aims before updating

- program_management/serializers/node_view.py
- program_management/tests/serializers/test_node_view.py
Pull request automatique de technical/OSIS-5180 vers DEV
> [technical/OSIS-5180 => DEV] Formation > Arbre > les icônes des propositions ne sont plus visibles sur les UE en proposition

- program_management/ddd/repositories/load_tree.py
- program_management/ddd/validators/_has_or_is_prerequisite.py
- program_management/ddd/validators/validators_by_business_action.py
- program_management/locale/en/LC_MESSAGES/djangojs.po
- program_management/locale/fr_BE/LC_MESSAGES/djangojs.po
- program_management/static/js/program_management/education_group_tree.js
Check that the node to detach is not a prerequisite in other
trees containing the parent node.
Also disable possibility to detach or cut a node which
have prerequisites on the js tree and display a tooltip
showing why.
Référence Jira : OSIS-5281
> OSIS-5281 check prerequisites on parent trees + enhance js tree

- base/tests/utils/test_cache.py
- base/utils/cache.py
- program_management/templates/quick_search_egy_inner.html
- program_management/templates/quick_search_luy_inner.html
- program_management/tests/views/test_quicksearch.py
- program_management/views/quick_search.py
Pull request automatique de technical/OSIS-5270 vers DEV
> [technical/OSIS-5270 => DEV] Formations > Arbre > Rechercher : la modale n_est plus indépendante Formations/UE

- assessments/locale/fr_BE/LC_MESSAGES/django.po
- assessments/templates/blocks/deadline_tutor_display.html
- assessments/templates/scores_encoding.html
- assessments/views/score_encoding.py
- base/static/css/osis.css
- display badges in place of label for scores missing
- display grey badge on learning unit with no scores encoded
- align teacher deadline cells
- display also teacher deadline for tutors
- compute progression based on whole data and not only incomplete
Référence Jira : OSIS-4243
> OSIS-4243 fix display issues with score encoding landing page

- attribution/tests/views/test_manage_my_courses.py
- base/templates/learning_unit/pedagogy.html
- base/tests/views/test_learning_unit.py
- base/views/learning_units/pedagogy/read.py
> OSIS-5141 Disable publish button only for past LUYs

- program_management/ddd/repositories/persist_tree.py
- program_management/tests/ddd/repositories/test_persist_tree.py
> OSIS-5372 do not call 'persist prerequisite' if node does not have prerequisites

- base/forms/learning_unit/search/borrowed.py
- base/tests/views/learning_units/search/test_borrowed.py
When giving a borrowing faculty that had all of its formations
not containing any Learning Units, the borrowing search would
return all Learning Units for a given year.
Référence Jira : OSIS-4205
> OSIS-4205 return none LUs when borrowing faculty has none inside OF

- program_management/views/groupelementyear_read.py
Pull request automatique de hotfix/OSIS-5627 vers QA
> [hotfix/OSIS-5627 => QA] [Echec Qa] - Formation > Générer le PDF > AttributeError > _list_ object has no attribute _root_node_

- education_group/tests/views/admission_condition/test_common.py
- education_group/views/admission_condition/common.py
- education_group/views/admission_condition/create.py
- education_group/views/admission_condition/delete.py
- education_group/views/admission_condition/order.py
- education_group/views/admission_condition/update.py
If the education group year is a common, we should check if the
user has the right to modifiy the admission condition with the
following permission: 'base.change_commonadmissioncondition'.
Otherwise the following permission is used:
'base.change_admissioncondition'.
Référence Jira : OSIS-5634
> OSIS-5634 adapt permission if common for admission condition modifications

- program_management/ddd/repositories/persist_tree.py
- program_management/ddd/repositories/program_tree.py
- program_management/ddd/service/write/detach_node_service.py
- program_management/ddd/service/write/down_link_service.py
- program_management/ddd/service/write/up_link_service.py
- program_management/tests/ddd/repositories/test_persist_tree.py
- program_management/tests/ddd/service/test_detach_node_service.py
- program_management/tests/ddd/service/write/test_down_link_service.py
- program_management/tests/ddd/service/write/test_up_link_service.py
- program_management/views/prerequisite_update.py
> OSIS-5649 : deprecated persist_tree

- program_management/ddd/domain/service/get_node_publish_url.py
- program_management/tests/ddd/domain/service/test_get_node_publish_url.py
> [hotfix/OSIS-5682 => QA] Le bouton réactualiser la publication ne fonctionne pas sur les mineures

- base/forms/learning_unit/search/external.py
When filtering by country or city, duplicate rows appeared.
This is due to the fact that we do a join with entity and
entity version. An entity could potentially have more than
one version, thus leading to similar rows that differs only
by entity version.
Référence Jira : OSIS-5712
> OSIS-5712 fix duplicate rows for external lu search

- assessments/templates/admin/pgm_manager.html
Pull request automatique de hotfix/OSIS-5803 vers QA
> [hotfix/OSIS-5803 => QA] Acteurs académiques > Désignation des gestionnaires de parcours > le type de formation et l_entité sont toujours vides

- education_group/views/mini_training/general_information_read.py
Pull request automatique de hotfix/OSIS-5836 vers QA
> [hotfix/OSIS-5836 => QA] onglet « infos générales » des mineures n_est plus modifiable

- base/auth/roles/program_manager.py
- base/fixtures/groups.json
- base/templates/learning_unit/components.html
- learning_unit/auth/roles/central_manager.py
- learning_unit/auth/roles/faculty_manager.py
- learning_unit/views/learning_unit_class/identification_read.py
> OSIS-5882  base.can_access_class -> learning_unit.view_learningclassyear (use default model perm)

- backoffice/settings/base.py
- backoffice/urls.py
Vérifier les points suivants :
> Move osis-document urls under API to bypass shibboleth

- osis_role/contrib/views.py
- osis_role/tests/contrib/test_views.py
Some use cases require logic given request method and object, that cannot be implemented from a single permission, so we process the normal behavior from DRF by mocking a request
> Check traditional DRF permissions when no mapping is given

- requirements.txt
Quelques personnes utilisent Black (https://pypi.org/project/black/) et pylint a une version un peu trop ancienne et nous sort des erreurs de bad-continuation (fixé en [2.6.0](https://github.com/PyCQA/pylint/releases/tag/pylint-2.6.0))
> Upgrade pylint

- program_management/ddd/repositories/tree_prerequisites.py
- program_management/ddd/validators/_has_or_is_prerequisite.py
When detaching a node from a program, we should check that
we are not breaking prerequisites. However, we should only
check for the academic year on which we are working.
> OSIS-6430 filter on academic year when searching prerequisites
