dissertation/locale/en/LC_MESSAGES/django.po, dissertation/locale/fr_BE/LC_MESSAGES/django.po, dissertation/static/css/dissertation_style.css, dissertation/templates/manager_students_list.html
changement de place de la select box: recherche sur les offers + modifictation du style
Référence Jira : OSIS-354
=> Osis-354 dissertation: changement de place de la select box: recherche sur les offers + modifictation du style

assistant/models/assistant_mandate.py, assistant/tests/factories/tutoring_learning_unit_year.py, assistant/tests/models/test_assistant_mandate.py, assistant/tests/utils/test_export_utils_pdf.py, assistant/utils/export_utils_pdf.py
=> Osis 1085 : Exclude from pdf exportation assistants who have declined their renewal

assistant/templates/reviewer_mandates_list.html, assistant/views/reviewer_mandates_list.py
=> OSIS-1129 add column reviews in mandate_list

base/locale/en/LC_MESSAGES/djangojs.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/djangojs.po, base/templates/learning_unit/blocks/panel/educational_informations.html
modifié :         base/locale/en/LC_MESSAGES/djangojs.po
modifié :         base/locale/fr_BE/LC_MESSAGES/django.po
modifié :         base/locale/fr_BE/LC_MESSAGES/djangojs.po
Référence Jira : OSIS-1136
=> OSIS-1136 Correction de traductions

base/locale/fr_BE/LC_MESSAGES/django.po
=> fix translation

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/learning_unit.py, base/models/learning_unit_year.py, base/tests/forms/test_learning_unit_partim.py, base/tests/model_forms/learning_unit/test_learning_unit.py
=> Osis 1034 Corrections

base/templates/organizations.html
=> #OSIS-1142 Liste des organisations, le type apparait comme 'UNKNOWN'

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=>  OSIS-1141 IL manque une traduction pour COURSE_ENROLLMENT

base/templates/learning_unit/blocks/save_cancel_buttons.html, base/templates/learning_unit/blocks/save_cancel_buttons_with_modal.html, base/templates/learning_unit/learning_unit_layout.html, base/templates/learning_unit/simple/update.html
=> #OSIS-942 Remonter le bouton SAVE

base/views/learning_units/search.py
modifié :         base/views/learning_units/search.py
Référence Jira : OSIS-1146
=> OSIS-1146 Correction d'un erreur d'affichage du message No Result

base/models/learning_unit.py
modifié :         base/models/learning_unit.py
Référence Jira : OSIS-1140
=> OSIS-1140 Ajout de specific_title dans le search

base/forms/learning_unit_pedagogy.py, base/views/learning_units/update.py
modifié :         base/forms/learning_unit_pedagogy.py
modifié :         base/views/learning_units/update.py
Référence Jira : OSIS-1167
=> OSIS-1167 Correction des permissions pour corriger le bug

base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-941 Modification traduction

base/business/learning_units/perms.py, base/forms/learning_unit/learning_unit_postponement.py, base/models/academic_year.py, base/models/learning_unit_year.py, base/templates/learning_unit/blocks/save_cancel_buttons_with_modal.html, base/tests/forms/test_learning_unit_postponement.py
=> OSIS-597 No postponement when the learning unit is in the past

base/forms/learning_unit/learning_unit_create.py, base/tests/model_forms/learning_unit/test_learning_unit_year.py
=> OSIS-1175 Correct display warning messages

base/templates/learning_unit/blocks/form/volumes_management_form.html
=> OSIS-1155 management_form only needed once

base/forms/learning_unit/learning_unit_postponement.py, base/tests/forms/test_learning_unit_postponement.py
=> OSIS-1176 Prevent postponement non important fields

base/templates/learning_unit/summary_list.html
=> #OSIS-1181 Suppression de l'affichage du None quand on a un somebody

base/forms/learning_unit/learning_unit_postponement.py, base/tests/forms/test_learning_unit_postponement.py
=> OSIS-1183 Add translation to bool value in check consistency warning

base/forms/learning_unit/learning_unit_postponement.py
=> OSIS-1176 Correct dict to Querydict

base/forms/learning_unit/learning_unit_postponement.py, base/tests/forms/test_learning_unit_postponement.py
=> OSIS-1183 Correct None value to display

base/business/learning_unit.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-1179 Added translation

base/templates/learning_unit/blocks/save_cancel_buttons.html
=> Fix save button for proposal learning unit year

base/forms/learning_unit/learning_unit_postponement.py, base/tests/forms/test_learning_unit_postponement.py
=> OSIS-597 Fixed UE creation in past

base/forms/learning_unit/learning_unit_postponement.py, base/tests/forms/test_learning_unit_postponement.py
=> removed var to value assignment in class description

base/templates/learning_unit/simple/creation_external.html
=> OSIS-1150 Button save with submit type

base/models/learning_unit_year.py
modifié :         base/models/learning_unit_year.py
Référence Jira : OSIS-1219
=> Correction bug when childs credits doesn'not exist

base/templates/learning_units.html, base/urls.py
=> OSIS-1200 two URL linked the same page

backoffice/settings/base.py, base/utils/cache.py
=> Set memory cache as default

base/models/learning_unit_year.py, base/tests/forms/test_learning_unit_partim.py
=> OSIS-940 Remove clean_status

backoffice/settings/local.py, webservices/urls.py
=> Add webservice application

base/forms/learning_unit/learning_unit_postponement.py, base/tests/forms/test_learning_unit_postponement.py
=> Osis 1235 fix queryset error in postponement

backoffice/settings/base.py
=> Add the 'contacts_introduction' style for CKEditor

base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-1233 Il manquait 2 traductions

scripts/load_offers.py
Deplacement de la logique html de load_offers vers l'outil composer.py 
Référence Jira : OSIS-1192
=> Move the html logic to the composer tool.

base/templates/learning_unit/by_external.html
=> #OSIS-1196 Ajout du lien sur le code pour aller en consultation de l'UE

base/forms/learning_unit/learning_unit_create.py, base/forms/learning_unit/learning_unit_create_2.py, base/models/learning_unit_year.py, base/templates/learning_unit/identification.html, base/templates/learning_unit/learning_unit_layout.html, base/tests/views/test_learning_unit_edition.py
=> #OSIS-1225 Ajout du champ intégration professionelle à l'écran

base/templatetags/learning_unit.py
es title des labels
modifié :         base/templatetags/learning_unit.py
Référence Jira : OSIS-1232
=> OSIS-1232 Ajout de la traduction pour le label

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_units.html
=> #OSIS-1270 Renommer onglets de recherche

base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_units.html
=> #OSIS-1271 Recherche UE: ré-aménagement du menu actions

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/simple/creation_external.html
=> #OSIS-1274 Modification Titre + breadcrumb création UE externe

base/tests/model_forms/learning_unit/test_learning_unit.py
=> #OSIS-1269 Correction du test qui plante aléatoirement

assessments/business/score_encoding_list.py, assessments/tests/business/test_score_encoding_list.py
=> [PATCH QA] OSIS-1280 fixed float to Decimal conversion

backoffice/urls.py
Pour permettre l'utilisation de l'app `partnership`.
=> Added partnership urls

base/forms/learning_unit/edition_volume.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/components.html, base/templates/learning_unit/components_identification.html
=> Osis 1210c

base/views/learning_unit.py, cms/models/text_label.py
=> #OSIS-1290 Problème de modification du CMS (infos pédagogiques)

base/business/learning_unit_year_with_context.py
=> OSIS-1210 Keep 0 planned classes in volume edition when value is 0 in db

base/forms/learning_unit/learning_unit_create.py, base/forms/learning_unit/learning_unit_create_2.py, base/static/js/learning_unit_creation.js
=> OSIS-1292 Disable internship_subtype when the user is faculty manager

base/views/learning_unit.py, cms/models/text_label.py
=> #OSIS-1290 Modification pour l'édition du cahier des charges

base/templates/learning_unit/by_external.html
=> OSIS-1294 change columns for external_learning_unit search

.travis.yml, base/templates/learning_unit/by_external.html
=> Travis pip cache

base/forms/learning_unit/learning_unit_partim.py, base/tests/forms/test_learning_unit_partim.py
=> OSIS-1209 Select default campus when create partim

base/forms/learning_unit/edition_volume.py
=> OSIS-1210 Add rules in tooltips for vol_total and vol_global

base/tests/business/learning_units/test_edition.py
=> OSIS-1210 Add tests cases for postponement (vol_tot, vol_q1, vol_q2)

base/models/learning_unit_component.py, base/tests/factories/learning_unit_component.py
=> #OSIS-1297 Delete duration field in learning_unit_component.

base/templates/learning_unit/blocks/form/search_form_learning_unit.html
=> OSIS-1211 Fixed missing tutor value

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/by_activity.html
=> #OSIS-1276 Améliorations dans le menu d'exportation des xls pour les lu

base/templates/learning_unit/simple/creation.html
=> #OSIS-1299 Correction du breadcrumb pour la création de proposition

base/models/learning_unit_year.py, base/templates/learning_unit/identification.html, base/templatetags/learning_unit.py, base/tests/models/test_learning_unit_year.py
=> #OSIS-1203 Afficher les changements sur le code

base/templates/learning_unit/breadcrumb.html
=> #OSIS-1277 modification breadcrumb pour la consultation de UE

base/templates/learning_unit/blocks/form/search_form_learning_unit.html, base/templates/learning_unit/by_activity.html, base/templates/learning_units.html, base/views/learning_units/search.py
=> OSIS-1301 Download xls on POST instead of GET

base/forms/learning_unit/edition_volume.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/learning_component_year.py, base/tests/forms/test_edition_form.py, base/tests/views/test_learning_unit_edition.py
=> Osis 1210 Remove consistency check on volumes save + add warnings

base/forms/learning_unit/search_form.py, base/templates/learning_unit/blocks/form/search_form_learning_unit.html
=> OSIS-1287 Hide search tutor + revert ent.subord checkbox

base/models/learning_unit_year.py
=> OSIS-1211 Added regex search for tutor

base/models/external_learning_unit_year.py, base/tests/forms/test_external_learning_unit.py
=> OSIS-1303 Search by acronym for external learning unit.

base/forms/learning_unit/search_form.py
=> OSIS-1211 Fixed search lu emprunted

backoffice/settings/base.py, base/static/css/osis.css, base/templates/learning_unit/blocks/create_form_learning_unit_external.html, base/templates/learning_unit/simple/creation.html
=> OSIS-1298 Show required field with an asterisk

base/models/learning_unit_year.py, base/templatetags/learning_unit.py, base/tests/templatetags/test_learning_unit.py
=> #OSIS-1203

base/forms/learning_unit/learning_unit_create_2.py, base/templates/learning_unit/blocks/modal/modal_modification_ask_to_report.html
=> OSIS-1215 Fixed cannot save modification form for faculty

base/templates/learning_unit/blocks/components.html
=> #OSIS-1300

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/templates/assistant_mandates.html, assistant/tests/utils/test_export_utils_pdf.py, assistant/urls.py, assistant/utils/export_utils_pdf.py
=> OSIS-1264 Assistant must be able to generate a summary PDF file of all his application form

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-1244 Modifier l'intitulé du champ 'mise à jour bloquée'

base/forms/education_group/create.py
modified:   base/forms/education_group/create.py
Référence Jira : OSIS-1327
=> OSIS-1327 education group type required

base/forms/learning_unit/search_form.py, base/models/learning_unit_year.py, base/tests/models/test_learning_unit_year.py
=> Osis 1358 Solve search error on UE with starting *

base/templates/learning_unit/blocks/panel/educational_informations.html
=> OSIS-1305 Show all summary_responsibles

base/forms/learning_unit/edition_volume.py
=> OSIS-1364 Use of zip in place of enumerate

base/templates/education_groups.html
modifié :         base/templates/education_groups.html
Référence Jira : OSIS-1376
=> OSIS-1376 Correction template

base/templates/education_group/blocks/dropdown/identification_actions_bar.html, base/views/education_groups/create.py
modified:   base/templates/education_group/blocks/dropdown/identification_actions_bar.html
modified:   base/views/education_groups/create.py
Référence Jira : OSIS-1373
=> OSIS-1373 Keep education group tree after creating

base/business/entity_version.py, base/tests/business/test_entity_version.py
**A NE PAS MERGER AVANT AUTORISATION LOUIS**
=> [MERGE TO DEV] Fix bad entity version query

base/templates/learning_unit/blocks/form/volumes_management_form.html
=> OSIS-1382 Fix attribute error when quadrimester is none

.codeclimate.yml, .coveragerc, .gitignore, .travis.yml, README.md
=> Updated codeclimate test reporter

attribution/business/manage_my_courses.py, attribution/models/attribution.py, attribution/templates/manage_my_courses/blocks/list/learning_units_summary_editable.html, attribution/templates/manage_my_courses/list_my_courses_summary_editable.html, attribution/tests/views/test_manage_my_courses.py, attribution/views/manage_my_courses.py, base/business/institution.py, base/models/entity_calendar.py, base/tests/business/test_institution.py, base/tests/models/test_entity_calendar.py
=> Osis 1266bis

base/templates/learning_unit/blocks/panel/educational_informations.html
=> OSIS-1410 Display "None" instead of "-"

base/business/learning_units/perms.py, base/models/entity_version.py, base/tests/models/test_entity_version.py
=> OSIS-1266 Fix query in order to take account only on requirement entity

base/templates/education_group/tab_admission_conditions.html
=> Show the free text and not the standard

backoffice/settings/base.py
=> OSIS-1414 Enabled pastefromword plugin

base/forms/learning_unit_pedagogy.py, base/tests/forms/test_learning_unit_pedagogy.py, cms/models/translated_text.py
=> OSIS-1411 Make postponement for learning unit pedagogy

base/templates/education_group/identification_group_details.html, base/templates/education_group/identification_mini_training_details.html, base/templates/education_group/identification_training_details.html, base/templates/education_groups.html
=> OSIS-1423 Adapt templates with new management & administration entities

base/templates/learning_unit/components_identification.html, base/views/learning_unit.py, base/views/learning_units/common.py
=> OSIS-1416 Add button Manage Volumes on identification

base/business/learning_unit.py, base/templates/learning_unit/components.html
=> OSIS-1418 Order components in list regarding to component usage by luy

base/templates/learning_unit/blocks/manage_volumes_button.html, base/templates/learning_unit/components.html, base/templates/learning_unit/components_identification.html, base/templates/learning_unit/volumes_management.html, base/tests/views/test_learning_unit_edition.py, base/urls.py, base/views/learning_units/update.py
=> Osis 1451 Simple or full volumes management form

base/templates/learning_unit/blocks/panel/educational_informations.html
modifié :         base/templates/learning_unit/blocks/panel/educational_informations.html
Référence Jira : OSIS-1460
=> OSIS-1460 Ajout d'un border

base/templates/learning_unit/blocks/form/volumes_management_form.html, base/templates/learning_unit/volumes_management.html, base/views/learning_units/update.py
=> OSIS-1461 Cancel button redirects to correct page

base/fixtures/unauthorized_relationship.json, base/management/commands/dump_unauthorized_relationship.py, base/models/education_group_type.py
=> #OSIS-1445 Add fixture for unauthorized_relationship model.

base/static/js/education_group/tbl_coorganization.js, base/templates/education_group/identification_group_details.html, base/templates/education_group/identification_mini_training_details.html, base/templates/education_group/identification_training_details.html, base/templates/education_group/tab_identification.html, base/views/education_group.py
nouveau fichier : base/static/js/education_group/tbl_coorganization.js
modifié :         base/templates/education_group/identification_group_details.html
modifié :         base/templates/education_group/identification_mini_training_details.html
modifié :         base/templates/education_group/identification_training_details.html
modifié :         base/templates/education_group/tab_identification.html
modifié :         base/views/education_group.py
Référence Jira : OSIS-1392
=> OSIS-1392 Refactoring des templates

base/forms/learning_unit/learning_unit_create.py, base/tests/forms/test_learning_unit_create_2.py, base/tests/forms/test_learning_unit_partim.py
=> Osis 1345 - Update DEFAULT_ACRONYM_COMPONENT

base/templates/education_group/training_tree.html
modifié :         base/templates/education_group/training_tree.html
Référence Jira : OSIS-1392
=> OSIS-1392 Correction Collapse close by default

base/templates/education_group/blocks/dropdown/identification_actions_bar.html
=> OSIS-1397 Adding missing whitespace

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/learning_component_year.py, base/models/learning_unit_year.py, base/tests/models/test_learning_unit_year.py
=> OSIS-1415 warning messages : acronym+ warnings of volumes for all container components

base/templates/learning_unit/summary_list.html
=> OSIS-1482 Correct template var for length property

base/templates/blocks/span/span_status.html
=> OSIS-1479 Correct sorting on status column in summary list

base/forms/education_group/training.py, base/tests/views/education_groups/test_update.py
=> OSIS-1388 Manage delete m2m

base/templates/learning_unit/blocks/panel/mobility_modality.html
=> OSIS-1452 Correct None mobility to ''

base/templates/education_group/blocks/form/group.html, base/templates/education_group/blocks/form/training.html, base/templates/education_group/blocks/informations.html
modifié :         base/templates/education_group/blocks/form/group.html
modifié :         base/templates/education_group/blocks/form/training.html
modifié :         base/templates/education_group/blocks/informations.html
Référence Jira : OSIS-1394
=> OSIS-1394 Modification du formulaire de création/Edition pour les groups

base/models/education_group_year.py, base/tests/views/education_groups/test_delete.py, base/views/common_classes.py, base/views/education_groups/delete.py
=> Osis 1403 Remove education_group when it has no more children.

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/education_group/blocks/dropdown/identification_actions_bar.html, base/views/common_classes.py, base/views/education_groups/delete.py
=> OSIS-1403 Add missing translations

.codeclimate.yml
Set method complexity to 8 and also decrease code duplication to 3.
=> Updated codeclimate configuration

base/fixtures/groups.json
=> OSIS-1408 Added permission for faculty permission to modify educationgroup

base/templates/education_group/blocks/hamburger_button.html
=> OSIS-1521 Fix button

base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/education_group/blocks/form/training.html, base/templates/education_group/identification_training_details.html
=> OSIS-1522 swap entities

base/templates/blocks/modal/modal_ajax.html, base/templates/education_group/blocks/dropdown/identification_actions_bar.html, base/templates/education_group/delete_inner.html, base/templatetags/education_group.py, base/tests/templatetags/test_education_group.py, base/views/common_classes.py
=> OSIS-1509 Display modal when deleting education group year

base/locale/en/LC_MESSAGES/djangojs.po, base/locale/fr_BE/LC_MESSAGES/djangojs.po, base/static/js/education_group/education_group_tree.js, base/templates/education_group/branch.html
=> Osis 1490 : Clic droit dans l'arbre des Formations

base/templates/learning_unit/summary_list.html, base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/educational_information.py
=> OSIS-1541 Add Feature flag on educational_information_mailing

base/templates/learning_unit/summary_list.html
=> OSIS-1462 UE summary_list redirect to pedagogy

base/templates/learning_unit/blocks/panel/teaching_material.html
=> OSIS-1535 Add tooltip to mandatory icon on teaching materials

base/forms/learning_unit/search_form.py, base/models/academic_calendar.py, base/tests/models/test_academic_calendar.py, base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/educational_information.py, base/views/learning_units/search.py
=> OSIS-1538 Correct default date for UE pedagogy info

base/business/entity.py, base/business/learning_unit.py, base/models/academic_year.py, base/models/entity_calendar.py, base/tests/business/test_entity.py, base/tests/factories/business/learning_units.py, base/tests/models/test_academic_year.py, base/tests/views/test_learning_unit_pedagogy.py
=> OSIS-1536 Fix education information status

attribution/tests/views/test_manage_my_courses.py, base/business/learning_units/perms.py, base/fixtures/waffle_flags.json
=> OSIS-1544 Disabled feature block UE

base/templates/layout.html
=> Fix conflict with jquery UI

webservices/tests/test_ws_catalog_offer.py, webservices/views.py
=> OSIS-1549: Return the right acronym for the requested offer

base/fixtures/groups.json
=> OSIS-1552: Fix the permissions for the central managers

base/business/education_group.py, base/tests/business/test_education_group.py
=> #OSIS 1546

base/templates/education_group/blocks/dropdown/identification_actions_bar.html
Référence Jira : OSIS-1523 et OSIS-1525
=> Osis 1523/1525 fix links

base/templates/education_group/branch.html
=> OSIS-1490 Fix for right clic in formations tree

base/business/education_groups/perms.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/person.py, base/models/person_entity.py, base/templates/education_group/blocks/content_actions.html, base/templates/education_group/blocks/dropdown/education_groups_action_button.html, base/templates/education_group/blocks/dropdown/identification_actions_bar.html, base/templates/education_groups.html, base/templatetags/education_group.py, base/tests/business/education_groups/test_perms.py, base/tests/templatetags/test_education_group.py, base/tests/views/education_groups/test_create.py, base/tests/views/education_groups/test_delete.py, base/tests/views/education_groups/test_update.py, base/views/common_classes.py, base/views/education_groups/group_element_year/update.py, base/views/education_groups/perms.py, base/views/education_groups/search.py, base/views/education_groups/update.py, base/views/learning_units/perms.py
=> Osis 1505 Buttons with permissions

base/templates/education_group/group_element_year_comment_inner.html
=> OSIS-1532 Adapt ajax modal to update comments

base/views/education_groups/search.py
=> OSIS-1564 Restore permission in context

base/tests/views/group_element_years/test_detach.py, base/views/education_groups/group_element_year/update.py
=> OSIS-1574 Correct get_success_url for detach view

attribution/models/attribution.py
=> OSIS-1576 Correct attribution on learning unit year

base/templates/education_group/delete_inner.html, base/templates/education_group/group_element_year/confirm_detach_inner.html
=> OSIS-1579 Fix submit button outside <form> tag support IE11/edge

base/forms/education_group/group_element_year.py, base/templates/blocks/forms/create_cancel_buttons_modal.html, base/views/education_groups/group_element_year/update.py
=> OSIS-1512 modal form to update comment

base/templates/blocks/modal/modal_ajax.html
=> OSIS-1532 Can click on if button is enabled

base/templates/education_group/blocks/content_actions.html, base/templatetags/education_group.py, base/tests/templatetags/test_education_group.py
=> OSIS-1532 Disabled does not work with <a>

base/forms/education_group/training.py, base/templates/blocks/modal/modal_ajax.html, base/templatetags/education_group.py, base/tests/templatetags/test_education_group.py
=> OSIS-1495 Disable modal when class disabled

base/templates/blocks/modal/modal_ajax.html, base/views/common_classes.py
=> OSIS-1495 Modal-form can now manage errors

base/forms/education_group/training.py, base/models/education_group_year.py, base/templates/education_group/blocks/form/training.html, base/templates/education_group/blocks/remarks.html
=> #OSIS-1573

base/templates/blocks/modal/modal_ajax.html, base/views/common_classes.py
=> OSIS-1580 Modal redirection

base/static/css/custom.css
=> OSIS-1570 Replace ui-trash-icon to fa fa-close icon in custom css

base/forms/education_group/training.py
=> OSIS-1570 Correct display for autocomplete select

base/views/education_groups/group_element_year/read.py
Signed-off-by: Aurelien De Ryck <deryck.aurelien@gmail.com>
Référence Jira : OSIS-1387
=> OSIS-1387 missing root_id in pdf_content

base/templates/education_group/tab_content.html
=> OSIS-1594 Correct tab content display data

base/fixtures/waffle_flags.json, base/views/education_groups/group_element_year/update.py
=> OSIS-1489 waffle flags

base/models/entity_version.py, base/templates/entity/identification.html, base/templates/entity/organogram.html, base/views/institution.py
=> Create a recursive query for entity diagram

base/static/js/education_group/education_group_tree.js
=> OSIS-1489 fix templatetag name in jstree

base/business/education_groups/perms.py, base/forms/education_group/common.py, base/models/education_group_type.py, base/tests/forms/education_group/test_common.py, base/tests/models/test_education_group_type.py
=> Osis 1587 Fetch authorized types from parents

base/business/education_groups/perms.py, base/templates/education_group/blocks/dropdown/identification_actions_bar.html, base/templatetags/education_group.py, base/tests/templatetags/test_education_group.py
Different permissions for each type of creative
Référence Jira : OSIS-1587
=> OSIS-1587 Different permissions for each type of creative

base/tests/templatetags/test_education_group.py
=> OSIS-1587 Remove print

base/templates/education_group/blocks/dropdown/identification_actions_bar.html
=> OSIS-1591 Fix delete URL

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-1489 Recover missing translations

base/views/education_groups/urls.py
=> OSIS-1591 Add TODO for delete URL refactoring

base/business/education_groups/perms.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/templatetags/test_education_group.py
=> OSIS-1567 Improve translation for unauthorized type

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/static/js/education_group/education_group_tree.js, base/templates/education_group/blocks/dropdown/identification_actions_bar.html, base/templatetags/education_group.py, base/tests/templatetags/test_education_group.py, base/views/education_group.py, base/views/education_groups/detail.py
=> Osis 1489 Update attach/detach 

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/views/education_groups/group_element_year/update.py
=> Osis 1489 Missing translation

base/forms/education_group/common.py, base/tests/forms/education_group/test_common.py
=> #OSIS-1614 Disable start_year for an education group creation.

base/fixtures/authorized_relationship.json, base/models/education_group_type.py
=> OSIS-1656 Rewrite get_by_natural_key for external_id

base/management/commands/load_validation_rules.py
=> OSIS-1655 Use strip for csv

base/forms/education_group/common.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/blocks/modal/modal_ajax.html, base/templates/education_group/layout_detail.html
=> Osis 1661 bis

base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-1661-bis Correction faute d'orthographe

base/forms/education_group/common.py, base/templates/blocks/modal/modal_ajax.html, base/templates/education_group/layout_detail.html
=> #OSIS-1661

base/forms/education_group/mini_training.py, base/forms/education_group/training.py
=> OSIS-1655 Remove diploma field

base/static/js/education_group/education_group_tree.js
=> OSIS-1630 Fix attach to root of tree

base/static/js/education_group/education_group_tree.js
=> OSIS-1669 remove icons from tree right clic menu

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/education_group_year.py, base/tests/factories/education_group_year.py, base/tests/forms/education_group/test_common.py
=> Osis 1596 Add clean on min/max constraint

base/templates/education_group/blocks/informations.html
=> OSIS-1596 Adapt informations.html

base/templates/education_group/blocks/form/group.html, base/templates/education_group/blocks/form/minitraining.html, base/templates/education_group/blocks/form/training.html
=> OSIS-1596 Adapt forms

base/templates/education_group/blocks/dropdown/identification_actions_bar.html, base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html
=> Osis 1672 Reorder select/attach/detach in menus

base/templates/learning_unit/comparison.html, base/templates/learning_unit/components_comparison.html
=> OSIS-1671 append headers in comparison table

base/business/education_groups/shorten.py, base/forms/education_group/common.py, base/forms/education_group/mini_training.py, base/forms/education_group/training.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/education_groups/test_shorten.py, base/tests/forms/education_group/test_group.py, base/tests/forms/education_group/test_mini_training.py, base/views/education_groups/update.py
=> OSIS-1615 Implement shorten functionalities

base/static/css/custom.css, base/templates/layout.html
=> Use container-fluid in order to gain space

base/models/education_group.py, base/tests/models/test_education_group.py
=> OSIS-1676 Add check on end_year/start_year education group

base/business/learning_unit.py, base/views/learning_unit.py
=> #OSIS-1670 Ajout de la comparaison sur l'entité d'allocation

base/templates/education_group/blocks/form/training.html
=> OSIS-1681 Delete space between panels

base/views/learning_unit.py, base/views/learning_units/common.py, base/views/learning_units/educational_information.py, base/views/learning_units/pedagogy/read.py
=> OSIS-1707 removed 'experimental_phase' into summary responsibles screens

base/business/group_element_years/management.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/authorized_relationship.py, base/models/exceptions.py, base/tests/views/education_groups/test_update.py, base/views/education_groups/group_element_year/update.py
=> Osis 1668 Check authorized_relationships to attach

base/business/learning_units/xls_comparison.py, base/tests/business/learning_units/test_xls_comparison.py, base/tests/business/test_education_group.py, base/tests/business/test_proposal_xls.py, base/tests/views/test_learning_unit.py
=> #OSIS-1623 Afficher les champs modifiés en vert

base/templates/education_group/tab_utilization.html
=> OSIS-1704 Modification du titre de la page

.gitmodules, backoffice/settings/local.py, backoffice/urls.py
=> IUFC - creating submodule

base/models/group_element_year.py, base/templates/education_group/blocks/content_actions.html, base/templates/education_group/tab_content.html, base/tests/models/test_group_element_year.py, base/tests/views/education_groups/test_detail.py, base/views/education_groups/detail.py
=> Osis 1713 Add filter on learning units in content

backoffice/settings/local.py
=> [QUICK FIX] Comment continuing_education app

base/forms/education_group/common.py, base/forms/education_group/group.py, base/forms/education_group/mini_training.py, base/forms/education_group/training.py, base/tests/forms/education_group/test_common.py, base/tests/forms/education_group/test_group.py, base/tests/forms/education_group/test_training.py, base/tests/views/education_groups/test_create.py, base/tests/views/education_groups/test_update.py, base/views/education_groups/create.py, base/views/education_groups/update.py
=> Osis 1701  Integrate rules_manager in education_group_year form and fix unittests

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/group_element_year.py, base/tests/models/test_group_element_year.py, base/tests/views/education_groups/test_update.py, base/views/education_groups/group_element_year/update.py
=> OSIS-1667 Except error and display warning.

base/templates/education_group/learning_unit/tab_prerequisite.html, base/views/education_groups/learning_unit/detail.py
=> OSIS-1697 Display on single line prerequisistes for trainings

base/views/education_groups/create.py, base/views/education_groups/update.py
=> OSIS-1740 Correct bug for group creation

base/forms/education_groups.py
=> Improve queryset

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/components.html
=> OSIS-1752 Replace column lu_usage to lu and move place

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templatetags/education_group.py, base/tests/templatetags/test_education_group.py, base/tests/views/group_element_years/test_read.py
=> OSIS-1764 Modification du titre du menu action

rules_management/fixtures/field_reference.json
=> OSIS-1778 Fix field reference json in order to add 3 fields

backoffice/settings/portal_conf.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Référence Jira : OSIS-1469
- Add translations
- Add new paragraphs in the sections
=> Osis 1469 improvements

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-1787 Correct misspelling words in french

base/templates/education_group/blocks/content_actions.html, base/templates/education_group/tab_content.html, base/views/education_groups/detail.py, base/views/education_groups/group_element_year/update.py
=> OSIS-1776 Fix attach on root with new tree generation

base/templates/education_group/tab_admission_conditions.html
Fix a bug in the template of the admissions
=> Remove the templatetag in the tab_admission_conditions

base/static/css/custom.css, base/templates/layout.html
=> Fix css jstree contextmenu

base/templates/learning_unit/formations.html
=> OSIS-1784 Add link to education group in UE used by panel

base/templates/education_group/blocks/admission_condition_table_row.html, base/templates/education_group/tab_admission_conditions.html, base/tests/views/test_education_group.py, base/views/education_group.py, base/views/education_groups/urls.py
=> OSIS-1629: Implement the order for the diploma with the tests.

base/business/entity.py, base/forms/learning_unit/search_form.py, base/forms/proposal/learning_unit_proposal.py, base/models/entity_container_year.py, base/models/learning_unit_year.py, base/models/proposal_learning_unit.py, base/tests/forms/test_learning_units.py, base/tests/models/test_proposal_learning_unit.py, base/tests/views/test_learning_unit.py, base/tests/views/test_learning_unit_proposal.py
=> Filtering EntityContainer use now querysets

base/business/education_groups/group_element_year_tree.py, base/tests/business/education_groups/test_build_tree.py, base/tests/views/group_element_years/test_detach.py, base/views/education_groups/group_element_year/update.py
=> Osis 1730  redirect to previous page after detach in tree

base/static/js/education_group/education_group_tree.js
=> OSIS-1754 Display forbidden message when trying to detach without rights

base/models/enums/education_group_types.py, base/templates/education_group/pdf_content.html
=> OSIS-1765 COrrection tradution pour minor

base/forms/education_group/common.py, base/forms/education_groups.py, base/models/education_group_type.py
=> Osis 1781 bis

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-1346 Modification de traduction

base/static/js/education_group/education_group_tree.js
=> OSIS-1754 Disable detach action on tree's root

base/static/css/custom.css
=> OSIS-1836 Fix footer's z-index

base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/educational_information.py
=> OSIS-1755 Missing form_comparison in  learning_units_summary_list

base/tests/views/education_groups/learning_unit/test_update.py, base/views/education_groups/learning_unit/update.py
=> Osis 1830 show tree in update prerequisites screen

base/business/learning_units/xls_generator.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/summary_list.html, base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/educational_information.py
=> OSIS-1756 Missing translations

base/models/education_group_year.py, base/tests/forms/education_group/test_training.py, base/tests/models/test_education_group_year.py, base/tests/views/education_groups/test_update.py
=> OSIS-1828 Clean for constraint_type

base/forms/education_group/common.py
=> OSIS-1842 Add filter on enrollment_campus

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/education_group/blocks/admission_condition_table_row.html
* Fix the translations
* Use linebreaksbr in the template of the admissions.
=> Fix display of admissions

base/business/education_group.py, base/templates/blocks/button/button_with_perm.html, base/templates/education_group/tab_administrative_data.html, base/templatetags/education_group.py, base/tests/business/test_education_group.py, base/tests/templatetags/test_education_group.py, base/views/education_group.py
=> Osis 1845 button_edit_administrative_data

base/templates/education_group/tab_admission_conditions.html
=> OSIS-1887: Show the free text for 2a and 2mc

rules_management/fixtures/field_reference.json
=> OSIS-1844 Adapt fixtures with internal_comment

base/business/education_groups/perms.py, base/forms/education_group/common.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/academic_calendar.py, base/models/academic_year.py, base/tests/business/education_groups/test_perms.py, base/tests/models/test_academic_calendar.py, base/tests/templatetags/test_education_group.py, base/tests/views/education_groups/test_delete.py, base/views/academic_calendar.py
=> OSIS-1835 Perms N+1 for education_group_year

.github/CONTRIBUTING.md
Info fournie à l'époque par Bastien, mais pas encore rajoutée.
=> [contributing] ajout section tests/vues

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/education_group/pdf_content.html
Référence Jira : Correction clé de traduction
=> Correction des clé de traduction

base/templates/learning_unit/blocks/form/simplified_volumes_management_form.html
…une UE
Référence Jira : OSIS-1804
=> OSIS-1804 Ajout du formulaire des volumes simplifié dans l'edition d'UE

base/views/learning_units/search.py
=> Correction d'un bug empêchant d'avoir la valeur d'UE par défaut dans le formulaire de création des UEs

base/templates/education_group/tab_content.html
=> OSIS-1834 normalize credits in egy content tab

base/business/education_group.py, base/tests/business/test_education_group.py
=> OSIS-1845 remove link to offeryearentity

attribution/tests/views/test_manage_my_courses.py
=> OSIS-1915 Fixed test_list_my_attributions_summary_editable

attribution/tests/views/test_manage_my_courses.py
=> Fixed setup test test_list_my_attributions_summary_editable

base/forms/academic_calendar.py
=> Osis 1905 Update choicefield content

base/tests/views/test_my_osis.py
=> OSIS-1917 Fixed test test_my_osis

base/forms/academic_calendar.py
=> Osis 1906 Select default academic year in form

base/models/group_element_year.py, base/tests/views/education_groups/group_element_year/test_read.py
=> OSIS-1932 Correction title

base/tasks.py
=> Corrected crontab for celery task

base/forms/education_group_admission.py, base/templates/education_group/blocks/admission_condition_text.html, base/templates/education_group/blocks/modal/modal_condition_text_edit.html, base/templates/education_group/tab_admission_conditions.html, base/tests/views/test_education_group.py, base/views/education_group.py
=> OSIS-1923: Show english field on the right

base/migrations/0362_auto_20181003_1534.py
=> fix migration number

base/templates/education_group/blocks/form/update_achievement_inner.html
=> OSIS-2006 nav-tabs for achievement modals.

base/static/js/modal_form_submit.js, base/templates/education_group/blocks/form/achievement_action_bar.html
=> OSIS-2007 Bug: invalid action in achievements

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2006 Missing translations

base/static/js/modal_form_submit.js, base/templates/blocks/modal/modal_ajax.html, base/templates/education_group/blocks/form/update_achievement_inner.html
=> OSIS-2014 Binding textareas with CKEDITOR during an AJAX request

base/business/education_groups/perms.py, base/forms/education_group/achievement.py, base/templates/education_group/blocks/form/achievement_action_bar.html, base/templates/education_group/blocks/panel/panel_achievements.html, base/templatetags/education_group.py, base/tests/views/education_groups/achievement/test_update.py, base/views/education_groups/achievement/delete.py, base/views/education_groups/achievement/update.py, base/views/education_groups/achievement/urls.py, base/views/mixins.py
=> Osis 2015 Confirmation modal for achievements

base/business/learning_units/edition.py
=> OSIS-2009 Fixed bug lorsqu'on extend un partim

base/templates/learning_unit/summary_list.html
=> [QA] Fix flag which englobe two features

base/templates/education_group/tab_diplomas.html
=> OSIS-2004 fixed diplay of 'joint_diploma'

base/forms/learning_unit/entity_form.py, base/static/js/learning_unit_creation.js, base/templates/learning_unit/blocks/institution.html, base/templates/learning_unit/simple/creation.html
=> Osis-2042 Ajout des listes déroulantes du choix de Pays pour les entités

base/utils/cache.py, base/utils/notifications.py
=> OSIS-2043 Fix for pickle error with redis

base/forms/learning_unit/entity_form.py
=> OSIS-2044 Correction d"un bug empechant certaines sélections d'entité

base/templates/education_group/blocks/modal/modal_pedagogy_edit.html, base/templates/education_group/tab_general_informations.html, base/views/education_group.py
=> OSIS-2058 : Titre de la modale d'édition

base/forms/learning_unit/entity_form.py, base/forms/utils/choice_field.py, base/tests/views/test_learning_unit_edition.py, base/views/learning_units/update.py
=> OSIS-2042 Ajout du label All dans les country et ajout d'order by

base/views/education_groups/detail.py
Subtasks: OSIS-2055 & OSIS-2069
=> OSIS-1501 : Check if faculty manager can edit admission conditions

base/business/education_groups/automatic_postponement.py, base/business/education_groups/postponement.py, base/business/learning_units/automatic_postponement.py, base/business/utils/model.py, base/business/utils/postponement.py, base/models/education_group_year.py, base/models/learning_unit_year.py, base/tasks.py, base/tests/business/education_groups/test_automatic_postponement.py, base/tests/business/education_groups/test_postponement.py, base/tests/business/learning_units/test_automatic_postponement.py, base/tests/forms/education_group/test_training.py
=> Osis 2066 Automatic postponement for education groups

base/templates/education_group/blocks/admission_condition_table_row.html, base/templates/education_group/blocks/modal/modal_condition_line_edit.html, base/views/education_groups/detail.py
=> OSIS-2054 : Move access field and translate column access (admission conditions)

base/tests/utils/test_cache.py, base/utils/cache.py, base/views/education_groups/create.py
=> OSIS-1799 Add default academic year

backoffice/settings/base.py, base/utils/notifications.py
=> OSIS-1965 Use pickle as serializer for redis

base/templates/education_group/tab_general_informations.html
=> OSIS-2109 : Placer le bouton d'édition à droite du titre

base/fixtures/groups.json
=> [TO QA] OSIS-2111 Add perms to dissertation_administrators group

base/fixtures/groups.json
=> [TO DEV] OSIS-2111 Add perms to dissertation_administrators group

base/views/education_groups/create.py
=> OSIS-1799 Fix default initial value

base/forms/education_group/organization.py
=> OSIS-1991 Default value for the country list

base/templates/learning_unit/attributions.html
=> OSIS-2029 Do not display edit if cannot manage charge repartition

base/templates/education_group/identification_training_details.html
=> OSIS-1991 Correct HTML datatable error on js

base/templates/education_group/tab_general_informations.html
=> OSIS-2110 Use label in modal call instead of label translation

base/templates/education_group/blocks/modal/modal_pedagogy_edit.html, base/tests/views/test_education_group.py, base/views/education_group.py, cms/models/translated_text_label.py, cms/tests/models/test_translated_text_label.py
=> Osis 2110 Display correct modal title

base/forms/education_group/common.py, base/tests/forms/education_group/test_common.py, base/tests/forms/education_group/test_group.py, base/tests/forms/education_group/test_mini_training.py
=> OSIS-2121 Inherit management entity from parent

base/business/group_element_years/postponement.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/education_group/blocks/dropdown/identification_actions_bar.html, base/tests/business/education_groups/test_postponement.py
=> OSIS-2096 Add translations for postponement

backoffice/settings/base.py, backoffice/urls.py, base/templates/layout.html, base/tests/views/education_groups/test_search.py, requirements.txt
=> Install hijack

base/templates/layout.html
=> menu added

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/remove_charge_repartition_confirmation_inner.html, base/templates/learning_unit/select_attribution.html, base/tests/views/learning_units/test_charge_repartition.py, base/tests/views/test_learning_unit.py, base/views/learning_unit.py, base/views/learning_units/charge_repartition.py, dev-requirements.txt
=> Osis 2144 Fix gérer la répartition quand attribution charges non créés

base/fixtures/groups.json
=> Release 0.47.7

base/models/organization.py
=> Correct search_fields attributes in OrganizationAdmin

base/tests/views/test_learning_unit.py, base/views/learning_unit.py
=> OSIS-2144 Fixed problem when charges are set to None

base/models/person.py, base/tests/models/test_learning_unit_year.py, base/tests/models/test_person.py
=> OSIS-2127 Permission for external learning unit through requesting entity

base/fixtures/waffle_flags.json, base/forms/learning_unit/external_learning_unit.py, base/forms/learning_unit/learning_unit_create.py, base/templates/learning_unit/blocks/create_form_learning_unit_external.html, base/views/learning_units/external/create.py
=> Osis 2126 Adapt creation view for external learning unit

base/fixtures/groups.json, base/tests/views/learning_units/external/test_create.py, base/views/learning_units/external/create.py
=> OSIS-2128 New perm to create external learning unit

base/templates/education_group/tab_content.html, base/templates/learning_unit/blocks/additional_requirement_entity_volumes.html, base/templates/learning_unit/components.html, base/templates/learning_unit/components_identification.html, base/templates/learning_unit/identification.html
=> OSIS-2129 Replace normalize by floatformat

base/business/learning_unit_year_with_context.py, base/tests/business/learning_units/test_edition.py, base/tests/business/test_learning_unit_year_with_context.py, base/tests/factories/business/learning_units.py
=> OSIS-2129 Revert modifications of OSIS-1947

webservices/tests/test_ws_catalog_offer.py, webservices/views.py
=> OSIS-2176 Correct empty string evaluated as none value

base/views/education_groups/coorganization.py, base/views/education_groups/update.py
=> OSIS-1986 Add fragment for url of coorganizations

base/views/education_groups/detail.py
=> OSIS-2153 Use settings instead of import from local.py

base/migrations/0382_auto_20181026_1500.py
=> FIx migrations

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2133 Added translations

base/management/commands/import_reddot.py, base/tests/management/test_import_reddot.py
OSIS-2057 : General information : translation of section titles
=> OSIS-2057 : section title translation

base/models/organization_address.py
=> OSIS-1986 Add search fields Organization Address admin model

base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-2150 Translation correction

base/business/learning_units/edition.py
=> OSIS-1947 Correction de duplication de learning container year

requirements.txt
=> Upgrade djangorestframework

base/forms/learning_unit/external_learning_unit.py, base/tests/forms/test_external_learning_unit.py, base/tests/forms/test_learning_unit_postponement.py
=> OSIS-59 Fix start_year bug for externals

base/forms/learning_unit/attribution_charge_repartition.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> Osis 2177 Ajout Placeholder

base/forms/learning_unit/learning_unit_postponement.py, base/views/learning_units/external/create.py
=> OSIS-59 academic_year must be analysed in the view

base/forms/learning_unit/external_learning_unit.py, base/forms/learning_unit/learning_unit_create.py, base/models/organization_address.py, base/templates/learning_unit/blocks/form/form_external.html, base/tests/forms/test_external_learning_unit.py, base/tests/views/learning_units/external/test_update.py
=> OSIS-1025 Initial values for countries and cities

base/views/education_groups/detail.py
=> OSIS-2185 : catch ConnectionError

base/business/education_groups/perms.py, base/models/education_group_year.py, base/tests/views/group_element_years/test_postpone.py, base/views/education_groups/update.py
=> OSIS-2072 Take the previous academic year to compute the postponement.

base/fixtures/groups.json
=> OSIS-2136 Add can_manage_attribution to faculty_manager

base/templates/education_group/blocks/dropdown/administrative_data_actions_bar.html, base/templates/education_group/tab_administrative_data.html, base/templatetags/education_group.py
=> #OSIS-2207 Modification de l'édition des données administratives

base/business/group_element_years/postponement.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/education_group_year.py, base/templates/education_group/blocks/dropdown/identification_actions_bar.html, base/templates/education_group/group_element_year/confirm_postpone_content_inner.html, base/templatetags/education_group.py, base/tests/views/group_element_years/test_postpone.py, base/views/education_groups/update.py
=> Osis 2072 Change button title and fix translations

base/models/entity_version.py
=> OSIS-2220 Add CCR to pedagogical entity added exception

base/business/group_element_years/postponement.py, base/locale/en/LC_MESSAGES/django.po, base/locale/en/LC_MESSAGES/djangojs.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/djangojs.po, base/templates/education_group/blocks/dropdown/administrative_data_actions_bar.html, base/templates/education_group/tab_administrative_data.html, base/templates/layout.html, base/templatetags/education_group.py, base/tests/business/education_groups/test_postponement.py, doc/technical-manual.adoc
=> Osis 2072 Check minitraining type before postponement

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2223 Use "groupement" words for education groups

base/templates/template_messages.html
=> OSIS-2224 Switch Succes message and warning message

base/management/commands/makemessages.py
=> Add --sort-ouput parameter to makemessages command as default parameters

base/business/education_groups/perms.py, base/models/education_group_year.py, base/tests/business/education_groups/test_perms.py
=> OSIS-2211 : central manager can edit common offer

.env.example, backoffice/settings/local.py, base/views/education_groups/detail.py
Refactor URL for Pedagogy Information
=> Refactor URL for Pedagogy Information

assessments/tests/views/test_scores_responsible.py, assessments/views/pgm_manager_administration.py, assessments/views/scores_responsible.py, attribution/tests/views/test_summary_responsible.py, attribution/views/summary_responsible.py, base/models/entity_manager.py, base/views/institution.py
=> [To dev] fixed access rights to academix actors views

base/static/js/education_group/education_group_tree.js
=> OSIS-2234 Fix detach modal

base/models/prerequisite_item.py, base/tests/factories/prerequisite_item.py, base/tests/models/test_prerequisite_item.py
=> OSIS-2204 Ajout fonction de recherche des prerequis par UE

base/models/prerequisite_item.py, base/tests/models/test_prerequisite_item.py
=> OSIS-2205 Add method find_by_learning_unit_year_being_prerequisite

base/urls.py
=> IUFC-101 add continuing_education api + update ref

.gitmodules
=> Remove mobility module from project

base/tests/views/test_person.py, base/views/person.py
=> OSIS-2013 Permit search via registration id

assessments/business/score_encoding_export.py, assessments/forms/score_file.py, assessments/templates/admin/modal/add_manager.html, assessments/templates/admin/modal/remove_manager_confirm.html, assessments/templates/admin/pgm_manager.html, assessments/templates/assessments.html, assessments/templates/offer/score_sheet_address_tab.html, assessments/templates/online_double_encoding_form.html, assessments/templates/online_double_encoding_validation.html, assessments/templates/online_encoding.html, assessments/templates/online_encoding_form.html, assessments/templates/outside_scores_encodings_period.html, assessments/templates/scores_encoding.html, assessments/templates/scores_encoding_by_learning_unit.html, assessments/templates/scores_encoding_by_specific_criteria.html, assessments/templates/scores_encoding_mgr_layout.html, assessments/templates/scores_responsible.html, assessments/templates/scores_responsible_edit.html, assessments/tests/views/test_score_encoding.py, assessments/tests/views/test_upload_xls_utils.py, assessments/views/pgm_manager_administration.py, assessments/views/score_encoding.py, assessments/views/score_sheet.py, assessments/views/upload_xls_utils.py, base/management/commands/makemessages.py
=> WIP OSIS- Refactor assessments translations in templates.

base/templates/layout.html
Mis à jour du menu du module Partenariat.
À merge après https://github.com/uclouvain/osis-partnership/pull/40
=> Update partnership menu

base/templates/layout.html
=> Update partnership menu (QA)

attribution/tests/views/test_attribution.py, attribution/tests/views/test_tutor_application.py, attribution/views/attribution.py, attribution/views/tutor_application.py
=> [QA] Fix Recompute_portal error

attribution/tests/views/test_attribution.py, attribution/tests/views/test_tutor_application.py, attribution/views/attribution.py, attribution/views/tutor_application.py
=> [DEV] Fix Recompute_portal Error

base/tests/views/test_person.py, base/views/person.py
=> OSIS-2013 Use icontains for registration_id search

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2237 : Faute d'orthographe

base/business/learning_units/perms.py
=> #OSIS-2150 Modification pour le message non traduit

base/forms/education_groups_administrative_data.py, base/templates/education_group/tab_edit_administrative_data.html, base/templatetags/education_group.py, base/tests/factories/education_group_year.py, base/tests/forms/test_education_groups_administrative_data.py, base/tests/templatetags/test_education_group.py, base/tests/views/test_education_group.py, base/views/education_group.py
=> #OSIS-2263 Le pavé 'infos complémentaires' est maintenant éditable

base/tests/factories/education_group_year.py, base/tests/forms/education_group/test_training.py
=> OSIS-2189: test existence of warnings.

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
=> #OSIS-2173 Ajout de validation pour la comparaison entre 2 UE

base/models/education_group_type.py, base/models/utils/utils.py, base/templates/education_group/blocks/informations.html, base/templates/education_group/blocks/remarks.html, base/templates/education_group/identification_group_details.html, base/templates/education_group/identification_mini_training_details.html, base/templates/education_group/identification_training_details.html, base/templates/education_group/search.html, base/templatetags/education_group.py, base/templatetags/learning_unit.py, base/tests/templatetags/test_education_group.py, base/views/education_groups/search.py
=> Rewrite dl_with_parent

attribution/business/xls_build.py, attribution/tests/business/test_xls_build.py, base/templates/learning_unit/by_activity.html, base/templates/learning_units.html, base/views/learning_units/search.py
=> Osis-2272 Nettoyage de fonctions inutilisé de génération de fichiers XLS pour les UEs

base/business/learning_units/comparison.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/comparison.html, base/templates/learning_unit/components_comparison.html, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
=> Osis 2238 Fix bug in comparison screen

base/business/learning_units/perms.py, base/fixtures/groups.json, base/fixtures/waffle_flags.json, base/tests/views/test_learning_achievement.py
=> OSIS-2239 add flag on learning unit achievement

base/management/commands/import_reddot.py, base/tests/management/test_import_reddot.py
=> OSIS-2286 Implement loading reddot information

base/management/commands/import_reddot.py
Cela va-t-il bien supprimer les autres offres common de la DB ainsi ?
=> OSIS-2261 : Limit types of common offer

backoffice/settings/portal_conf.py
=> OSIS-2328 Remove comp_acquis from main info tab on education group year

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/education_group_year.py
=> OSIS-2085 fixed trnaslation of field 'joint diploma'

base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-2277 Correction d'une traduction

base/forms/learning_unit/learning_unit_create_2.py, base/tests/forms/test_learning_unit_create_2.py
=> OSIS-2255 Create a global protection for formsets.

webservices/templates/comp_acquis.html
=> OSIS-2288 Correct template error

base/locale/fr_BE/LC_MESSAGES/django.po
=> Osis 2277 change tradcution xls title

assessments/business/score_encoding_progress.py, assessments/business/score_encoding_sheet.py, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/templates/online_double_encoding_form.html, assessments/templates/online_double_encoding_validation.html, assessments/templates/online_encoding.html, assessments/templates/online_encoding_form.html, assessments/templates/scores_encoding_by_specific_criteria.html, base/models/exam_enrollment.py
=> Osis 2319 - Modifier le nombre d'inscriptions/ vérifier la barre de progression

base/fixtures/validation_rules.csv
=> OSIS-2278 Corrected decree category for Master 180-240

base/templates/education_group/blocks/admission_condition_table_row.html, base/templates/education_group/tab_admission_conditions.html, base/tests/views/test_education_group.py, base/views/education_group.py, base/views/education_groups/detail.py, base/views/education_groups/urls.py
=> OSIS-2271 : Button to change language of admission condition tabs

assessments/templates/online_double_encoding_form.html, assessments/templates/online_encoding_form.html, assessments/templates/scores_encoding_by_specific_criteria.html, assessments/templatetags/enrollment_state.py, assessments/tests/templatetags/test_enrollment_state.py
=> Osis 2284 - Bloquer l'encodage des notes manquantes

assessments/business/score_encoding_sheet.py
=> Osis 2296 - Surligner les inscrits/désinscrits dans le fichier PDF

assessments/business/score_encoding_export.py, assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/templates/blocks/legend.html
=> #OSIS-2297 Modification d'une traduction pour la légende

base/models/learning_unit_year.py, base/tests/factories/education_group_type.py, base/tests/models/test_learning_unit_year.py, base/tests/models/test_prerequisite_item.py, base/tests/templatetags/test_education_group.py, base/tests/views/group_element_years/test_detach.py
=> Osis 2342 Cannot detach when prerequisite in same group but other formation

assessments/business/score_encoding_list.py, assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/tests/views/test_upload_xls_utils.py, assessments/views/upload_xls_utils.py, base/tests/models/test_exam_enrollment.py
=> #OSIS-2284 Empêcher l'injecter d'une note pour un étudiant désinscrit

base/fixtures/authorized_relationship.json
=> Osis 2196 - Adapter la fixture de AuthorizedRelationship avec les nouvelles données

base/business/education_group.py, base/business/education_groups/perms.py, base/business/institution.py, base/business/learning_unit_proposal.py, base/business/learning_units/perms.py, base/forms/education_groups_administrative_data.py, base/forms/learning_unit/edition_volume.py, base/forms/learning_unit/learning_unit_create.py, base/forms/learning_unit/learning_unit_create_2.py, base/forms/learning_unit_proposal.py, base/models/education_group_language.py, base/models/person.py, base/tests/business/education_groups/test_perms.py, base/tests/business/test_learning_unit_deletion.py, base/tests/models/test_education_group_language.py, base/tests/models/test_person.py, base/tests/views/test_education_group.py, base/views/education_groups/detail.py, base/views/learning_units/educational_information.py, base/views/learning_units/search.py
=> Decrease in the number of requests for the education group

base/templates/education_group/tab_admission_conditions.html
=> OSIS-2271 : translate header tab etc.

base/business/education_groups/perms.py, base/tests/business/education_groups/test_perms.py, base/tests/views/test_education_group.py, base/views/education_groups/detail.py
=> OSIS-2265 : sic can only edit admission conditions

base/fixtures/groups.json
=> OSIS-2265 : add perms to sic

base/templates/learning_unit/attributions.html
=> #OSIS-2321 correction de l'affichage de la fonction

base/management/commands/import_reddot.py, base/models/education_group_publication_contact.py, webservices/business.py, webservices/tests/test_business.py, webservices/tests/test_ws_catalog_offer.py, webservices/views.py
=> OSIS-2383 Adapt webservice to return contacts section in formated ways

base/middlewares/toolbar.py
=> Override SHOW_TOOLBAR_CALLBACK to ignore INTERNAL_IPS

base/forms/education_group/publication_contact.py, base/management/commands/import_reddot.py, base/tests/management/test_import_reddot.py, base/views/education_groups/detail.py
=> OSIS-2382 Implement import of Entity

backoffice/settings/portal_conf.py, base/management/commands/import_reddot.py, base/templates/education_group/blocks/contacts_general_informations.html, base/templates/education_group/blocks/row_label_general_informations.html, base/templates/education_group/tab_general_informations.html, base/views/education_groups/detail.py, webservices/business.py, webservices/views.py
=> OSIS-2381 Correct contacts sections in order to be display if asked

base/forms/learning_unit/edition_volume.py, base/tests/forms/education_group/test_common.py, base/tests/forms/test_edition_form.py
=>  OSIS-2252 Fixed bug error proc

webservices/tests/test_ws_catalog_offer.py, webservices/views.py
=> OSIS-1887 : Bug : get correct admission_condition_common ?

base/forms/education_group/publication_contact.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2381 Remove label + correct translation

base/business/education_groups/perms.py, base/business/group_element_years/management.py, base/forms/education_group/common.py, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/group_element_years/test_management.py, base/tests/factories/education_group_type.py, base/tests/views/education_groups/test_create.py, base/tests/views/education_groups/test_select_education_group_type.py, base/views/education_groups/group_element_year/update.py, base/views/education_groups/perms.py
=> OSIS-2078 Block creation when max child reached

base/views/learning_units/create.py
=> OSIS-2236 Add limitation partim creation

base/business/education_groups/perms.py, base/forms/education_group/common.py, base/tests/views/education_groups/test_select_education_group_type.py
=> Osis 2078 Fixed EducationGroupTypeForm when no parent

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/static/js/education_group/tab_content.js, base/templates/education_group/blocks/content_default_table.html, base/templates/education_group/blocks/content_minor_major_option_table.html, base/templates/education_group/tab_content.html, base/tests/views/education_groups/test_detail.py, base/views/education_groups/detail.py
=> OSIS-2360 Implement read content tab for list minor/major/option

base/tests/views/test_education_group.py
=> fix test publish

base/views/education_groups/detail.py
=> OSIS-2368 : add missing types

base/templates/education_group/blocks/content_minor_major_option_table.html
=> OSIS-2360 Preserve spaces when displaying title in content minor major

base/templates/blocks/panel/reversion.html
=> OSIS-2358 Hide version panel if empty

base/business/education_groups/perms.py, base/forms/education_group/common.py, base/forms/education_group/group.py, base/forms/education_group/mini_training.py, base/forms/education_group/training.py, base/forms/education_groups.py, base/models/education_group_type.py, base/models/enums/education_group_categories.py, base/tests/templatetags/test_education_group.py, base/views/education_groups/learning_unit/detail.py
=> OSIS-2050 Missing translations for categories

base/fixtures/validation_rules.csv
=> Osis 2078 Modification Programme de base to Partie de base

assessments/tests/business/test_scores_encodings_deadline.py, base/business/entity.py, base/business/learning_unit_xls.py, base/forms/learning_unit/search_form.py, base/models/entity_calendar.py, base/tests/views/group_element_years/test_postpone.py, base/views/learning_units/educational_information.py
=> OSIS-2373 Two way to display entity acronym

base/fixtures/authorized_relationship.json, base/forms/education_group/common.py, base/forms/education_group/training.py, base/tests/forms/education_group/test_common.py
=> OSIS-2413 Move part for create structure in common form part

base/business/education_groups/postponement.py, base/forms/education_group/common.py
=> OSIS-2413 Correct creation structure

base/templates/layout.html
=> Fix footer behavior for small screens

base/tests/forms/test_learning_unit_create_2.py, base/tests/models/test_exam_enrollment.py
Fix some tests that failed with the new year.
=> Fixed tests

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
Référence Jira : OSIS-2395
the translation issue was due to the use of a constant which wasn't taking care in the po file
=> OSIS-2395 fix translation bug in attribution page

base/templates/learning_unit/add_charge_repartition_inner.html, base/templates/learning_unit/remove_charge_repartition_confirmation_inner.html, base/templates/learning_unit/select_attribution.html, base/views/learning_units/attribution.py, base/views/learning_units/charge_repartition.py
Référence Jira : OSIS-2402
fix issue of translation of the holding title in the repartition management of a partim 
=> OSIS-2402 fix translation in repartition management page

base/tests/factories/academic_year.py, base/tests/views/test_academic_calendar.py, base/views/academic_calendar.py, base/views/common.py
=> Refactoring test academic calendar

webservices/tests/test_ws_catalog_offer.py, webservices/views.py
=> fix reddot

backoffice/settings/base.py, base/business/education_groups/general_information.py, base/tests/business/education_groups/test_general_information.py, base/tests/views/test_education_group.py, base/views/education_groups/detail.py
=> Osis 2429 Refactor general information URL

base/business/education_groups/perms.py, base/business/group_element_years/perms.py, base/tests/factories/academic_calendar.py, base/tests/views/education_groups/test_update.py, base/tests/views/group_element_years/test_detach.py, base/tests/views/group_element_years/test_edit.py, base/tests/views/group_element_years/test_perms.py, base/views/education_groups/group_element_year/common.py, base/views/education_groups/group_element_year/perms.py
=> Osis 2169 Permission pour créer, modifier et supprimer Group Element Year

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Référence Jira : OSIS-2411
Should be good now
=> OSIS-2411 forgot dissertation translation

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/views/education_groups/detail.py
=> OSIS-2432 Rename message in order to prevent error

base/models/education_group_year.py, base/templates/education_group/blocks/admission_condition_text.html, base/templates/education_group/tab_admission_conditions.html, base/tests/views/test_education_group.py, base/views/education_groups/detail.py
=> OSIS-2438 : add common admission condition to offer

base/views/education_groups/detail.py
=> remove gray lines from common-2m

base/api/serializers/person.py, base/tests/api/serializers/test_person.py
=> Username in person api

base/models/education_group.py, base/tests/models/test_education_group.py
=> add trainings manager education_group model

base/static/css/osis.css, base/templates/education_group/blocks/form/achievement_action_bar.html, base/templates/education_group/blocks/panel/panel_achievements.html
=> Osis 2460 Display code_name on panel achievements

base/business/education_groups/postponement.py
=> OSIS-2451 Correction report OFF

base/fixtures/groups.json
=> Add access to dissertation administrators group (Person + Student)

base/business/education_groups/general_information_sections.py, base/templates/education_group/tab_admission_conditions.html
=> OSIS-2467 Change display order

base/templates/education_group/blocks/informations.html
=> OSIS-1853 Add conditional in order to prevent blank line

base/business/education_groups/automatic_postponement.py, base/business/education_groups/create.py, base/business/education_groups/postponement.py, base/business/utils/postponement.py, base/tests/business/education_groups/test_automatic_postponement.py
=> OSIS-2474 Append mandatory groups during automatic postponement

base/forms/learning_unit/learning_unit_create.py, base/tests/forms/learning_unit/test_learningUnitYearModelForm.py, base/tests/forms/test_learning_unit_create_2.py, base/tests/forms/test_learning_unit_partim.py
=> #OSIS-2476 Ajout de contrainte sur l'encodage de crédits avec décimales

base/business/group_element_years/postponement.py, base/models/education_group_year.py, base/tests/business/education_groups/test_postponement.py, base/views/education_groups/detail.py
=> Osis 2490 Check if the content has been already postponed.

.gitignore
Ajout du script  `git_submodule_ref_update.py` dans le `.gitignore`
=> update gitignore with git_submodule_update_ref.py script

base/templates/learning_unit/blocks/panel/proposal.html
=> #OSIS-2436 Traduction

base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-2437 correction faute d'orthographe

base/business/proposal_xls.py, base/tests/business/test_proposal_xls.py
=> #OSIS-2439

base/business/education_group.py, base/business/proposal_xls.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-1546 Ajout des traducation pour l'xls des données administratives

base/views/education_groups/detail.py
=> #OSIS-2497 Onglet données administratives farceur

base/business/proposal_xls.py, base/templates/learning_unit/blocks/modal/modal_force_state.html, base/templates/learning_unit/by_proposal.html, base/templates/learning_units.html, base/tests/business/test_proposal_xls.py
=> #OSIS-2443

base/views/common.py
=> OD-41 Modification common.py extra_tags

base/business/education_groups/general_information.py, base/business/education_groups/general_information_sections.py, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/education_groups/test_general_information.py, base/views/education_groups/detail.py
=> OSIS-2329 Correct for common + correct translation

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Référence Jira : OSIS-2411
update translate due to old translation that have disappear
=> OSIS-2411 update translate due to old translation that have disappear

base/business/education_groups/perms.py, base/business/group_element_years/management.py, base/tests/views/education_groups/test_create.py, base/views/education_groups/perms.py
modified:   base/business/group_element_years/management.py
Référence Jira : OSIS-2169
=> OSIS-2169 Fix permission

base/static/js/learning_unit/learning_unit_update.js
Référence Jira : OSIS-2266
returned 'number' instead of 'string'
=> OSIS-2266 debug negative volume

base/business/learning_unit_proposal.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> Osis 2507 - ajout de traductions manquantes

base/views/education_groups/create.py
Référence Jira : OSIS-2522
wasn't taking academic year when cache was empty
=> OSIS-2522 debug error during creation of bachelor

base/api/serializers/person.py
=> add uuid field

base/templates/education_group/blocks/row_label_general_informations.html, base/tests/views/test_education_group.py, base/views/education_group.py
=> OSIS-2542 Keep position when save pedagogical info

base/business/education_groups/general_information_sections.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2543 Correct program label

base/forms/bootstrap.py, base/forms/education_group/training.py, base/templates/education_group/blocks/form/training.html, base/templates/education_group/blocks/form/training_tab_diploma.html, base/templates/education_group/blocks/form/training_tab_identification.html, base/views/education_groups/update.py
=> OSIS-2514 One form to rule them all (education group year)

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/education_group/tab_admission_conditions.html
=> OSIS-2532 Rename free_text to specific condition requirement

reference/api/serializers/country.py, reference/api/url_v1.py, reference/api/views/country.py, reference/tests/api/serializers/test_country.py, reference/tests/api/views/test_country.py
=> API COUNTRY

base/templates/education_group/tab_admission_conditions.html
=> OSIS-2558 Correct template incorrect variable name

webservices/tests/test_ws_catalog_offer.py, webservices/views.py
=> OSIS-2534 : Common admission condition for 2M1

doc/technical-manual.adoc
=> [doc] Move repo clone after authentication

base/forms/learning_unit/learning_unit_create_2.py, base/tests/forms/test_learning_unit_create_2.py
=> #OSIS-2551- Adapter le formulaire d'édition des propositions pour que plus de champs soient ouverts 

.github/CONTRIBUTING.md
=> Add section : PR for submodules reference updates

.github/CONTRIBUTING.md
Add 'indentation' section rule
=> Add 'coding style' section rule

base/static/css/osis.css
=> OSIS-2542 Add CSS to prevent div anchor hidden by fixed navbar

base/business/education_groups/general_information_sections.py, base/tests/views/test_education_group.py, base/views/education_groups/detail.py
=> OSIS-2512 : Section didactic

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2496 renamed message translation when constraint exists in EPC

base/tests/views/test_education_group.py, base/views/education_group.py
=> OSIS-2557 Correct permission for update text admission condition

base/business/education_groups/perms.py, base/tests/business/education_groups/test_perms.py, base/tests/views/education_groups/achievement/test_detail.py, base/tests/views/test_education_group.py, base/views/education_groups/achievement/detail.py
=> OSIS-2557 Rewrite permission class in order to be more explicit

base/templates/education_group/blocks/form/achievement_action_bar.html, base/templates/education_group/blocks/panel/panel_achievements.html, base/templates/education_group/blocks/panel/panel_additional_info_skills.html, base/templates/education_group/blocks/panel/panel_program_aims.html, base/templatetags/education_group.py
=> OSIS-2285 Add perms on skills and achievements tabs

reference/api/serializers/country.py, reference/api/views/country.py, reference/tests/api/serializers/test_country.py, reference/tests/api/views/test_country.py
=> remove validator on iso_code

base/templates/education_group/blocks/admission_condition_table_row.html
=> OSIS-2589 : remove linebreaksbr

base/business/education_groups/create.py, base/tests/business/education_groups/test_create.py
=> OSIS-2538 Avoid a crash with an empty partial acronym.

base/business/education_groups/perms.py, base/tests/business/education_groups/test_perms.py, base/tests/templatetags/test_education_group.py, base/tests/views/education_groups/test_delete.py
=> OSIS-2556 Manage perms for faculty manager

base/tests/views/education_groups/test_detail.py, base/tests/views/education_groups/test_publication_contact.py, base/views/education_groups/publication_contact.py
=> OSIS-2603 Correct permission for contacts

base/fixtures/groups.json
Référence Jira : IUFC-30
IUFC-231
IUFC-233
IUFC-240
IUFC-241 
IUFC-249
IUFC-250 
=> Update ref continuing education

base/tests/views/test_my_osis.py, base/urls.py, base/utils/send_mail.py, base/views/my_osis.py
=> Remove unused code for send message again

base/tests/forms/test_learning_unit_create_2.py, base/tests/utils/test_send_mail.py
=> Patch Internship 0.4.7

base/tests/forms/test_learning_unit_create_2.py, base/tests/utils/test_send_mail.py
- Release Internship submodule
=> Release 0.48.10 (Intership update)

base/business/education_groups/automatic_postponement.py, base/business/group_element_years/postponement.py, base/business/utils/postponement.py, base/models/education_group_year.py, base/tests/business/education_groups/test_postponement.py
=> Osis 2560 Fix bugs : during the postponement the technical parts are duplicated.

backoffice/settings/base.py
=> OSIS-2590 Prevent em tags for italic formatting on CK_EDITOR

base/business/education_groups/postponement.py
=> OSIS-2608 ignore linked_with_epc for EducationGroupYear postponement

base/business/education_groups/create.py, base/models/education_group.py, base/tests/business/education_groups/test_create.py
=> OSIS-2318 Same education_group for all groups

base/business/education_groups/general_information_sections.py, webservices/tests/test_ws_catalog_offer.py, webservices/urls.py, webservices/views.py
=> [QA] Osis 2614

base/forms/education_group_admission.py, base/templates/education_group/blocks/modal/modal_condition_line_edit.html
=> [QA] OSIS-2618 : CKEditor in admission condition tabs

base/tests/views/test_education_group.py, base/views/education_groups/detail.py
=> fix double prerequis

base/forms/education_group_admission.py, base/templates/education_group/blocks/modal/modal_condition_line_edit.html
=> OSIS-2618 : CKEditor in admission condition tabs

base/business/education_groups/postponement.py, base/business/group_element_years/postponement.py, base/tests/business/education_groups/test_postponement.py
=> Osis 2318 Copy the prerequisite too

base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-2576 Modification d'une traduction

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> [DEV] OSIS-2626 Adapt message in order to have good translation

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> [QA] OSIS-2626 Adapt message in order to have good translation

reference/api/views/country.py
=> Country : API - Autocomplete

webservices/views.py
=> [QA] OSIS-2626 Add context manager for translation

webservices/views.py
=> [DEV] OSIS-2626 Add context manager for translation

base/models/enums/education_group_types.py, base/views/education_groups/detail.py
=> [QA] OSIS-2625 Refactor show_conditions in order to be more explicit

base/models/enums/education_group_types.py, base/views/education_groups/detail.py
=> [DEV] OSIS-2625 Refactor show_conditions in order to be more explicit

.env.example, backoffice/settings/base.py
=> Add setting MAIL_SENDER_CLASS

doc/technical-manual.adoc
=> Add note for ugettext in OSIS

base/models/enums/education_group_types.py
=> [QA] Correct list of training type with admission condition

base/business/education_groups/create.py, base/business/group_element_years/postponement.py, base/models/education_group_year.py, base/templates/education_group/layout_detail.html, base/tests/business/education_groups/test_postponement.py
=> Osis 2318 Fix bug: grandchildren were not connected during the copy N-N+1

base/models/enums/education_group_types.py
=> [DEV] Correct List admission condition

base/forms/education_group/training.py, reference/models/domain.py, reference/tests/models/test_domain.py
=> OSIS-2619 show decree, code and name of the domain in the identification

base/business/education_groups/postponement.py
=> Prevent Reddot postponement for publication_contact_entity

base/models/education_group_year.py
=> Add search on education group PK for educationgroupyear admin

base/business/education_groups/general_information_sections.py, base/templates/education_group/blocks/contacts_general_informations.html, base/views/education_groups/detail.py, webservices/views.py
=> [QA] OSIS-2649 Move PRACTICAL_INFO to in practice part

base/business/education_groups/general_information_sections.py, base/templates/education_group/blocks/contacts_general_informations.html, base/views/education_groups/detail.py, webservices/views.py
=> [DEV] OSIS-2649 Move PRACTICAL_INFO to in practice part

base/business/education_groups/general_information_sections.py, base/models/enums/education_group_types.py, base/templates/education_group/blocks/contacts_general_informations.html, base/views/education_groups/detail.py, webservices/views.py
=> Release 0.49.2

base/business/education_groups/general_information_sections.py
=> [QA] Correct mistakes in ca_cond_general on common aggregation

base/business/education_groups/general_information_sections.py
=> [DEV] Correct mistakes in ca_cond_general on common aggregation

base/tests/views/test_education_group.py, base/views/education_groups/detail.py
=> [DEV] Osis 2651 Remove specific condition on common

base/tests/views/test_education_group.py, base/views/education_groups/detail.py
=> [QA] OSIS-2651 Remove specific condition on common

webservices/urls.py
=> [QA] Correct webservice URL

webservices/urls.py
=> [DEV] Correct webservice URL

.env.example, backoffice/settings/base.py, base/tests/utils/test_send_mail.py
=> Messaging refactoring

base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/education_group/blocks/coorganization.html, base/templates/education_group/organization_edit_inner.html
=> #OSIS-2586 Correction de traductions

base/templates/education_group/tab_administrative_data.html
=> #OSIS-2570 Correction traduction

base/business/education_groups/perms.py, base/business/education_groups/postponement.py, base/models/education_group_year.py, base/tests/factories/education_group_year.py, base/tests/models/test_education_group_year.py, base/tests/templatetags/test_education_group.py, base/tests/views/education_groups/test_update.py, rules_management/fixtures/field_reference.json
=> OSIS-2621 give right to faculty manager to create a mini-training

webservices/urls.py
=> Release 0.49.4

base/business/group_element_years/postponement.py, base/tests/business/education_groups/test_postponement.py, base/views/education_groups/update.py
=> Osis 2637 Attach the current children for a mandatory group during the copy.

base/fixtures/groups.json
=> #OSIS-2456 Correction de la fixture pour central_manager

base/tests/views/education_groups/test_create.py, base/views/education_groups/perms.py
linked to another PR
Référence Jira : OSIS-2621
=> OSIS-2621 debug perm after change in the enum

rules_management/fixtures/field_reference.json
for central and faculty managers
Référence Jira : OSIS-2623
=> OSIS-2623 add perm on start year on the creation of a training

base/templates/education_group/blocks/informations.html
=> [Bogue] OSIS-2571 : Remove blue text

base/business/education_groups/perms.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/templatetags/test_education_group.py
=> OSIS-2604 Add pgettext for category translations.

base/templates/learning_unit/blocks/modal/modal_back_to_initial.html
=> [Bogue] OSIS-2444 : Fix reset proposal learning unit

education_group/api/views/training.py, education_group/tests/api/views/test_training.py
=> IUFC-91 filter education group by type

assessments/business/score_encoding_export.py, assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/templates/online_double_encoding_form.html, assessments/templates/online_encoding_form.html, assessments/tests/views/test_score_encoding.py, assessments/views/upload_xls_utils.py
=> [Bogue] OSIS-2629 : Translation in xls of score encoding

.travis.yml
=> TRAVIS updated config postgresql to 9.6

base/business/education_groups/group_element_year_tree.py
=> OSIS-2634 Add year to acronym in json tree

base/business/education_groups/group_element_year_tree.py
=> OSIS-2634 Correct condition in get_acronym

base/business/group_element_years/postponement.py
=> OSIS-2318 Fix condition to create education group year

base/business/education_group.py, base/fixtures/validation_rules.csv, base/forms/education_group/group.py, base/forms/education_groups.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/education_group_year.py, base/models/enums/decree_category.py, base/templates/education_group/blocks/informations.html, base/templates/education_group/blocks/table_utilizations.html, base/templates/education_group/identification_training_details.html, base/templates/education_group/search.html, base/templatetags/education_group.py, base/tests/forms/education_group/test_group.py, base/tests/templatetags/test_education_group.py, rules_management/fixtures/field_reference.json
=> Osis 1856 Fix creation group

backoffice/settings/base.py
=> [QA] OSIS-2680 : Remove <p> in CKEditor

backoffice/settings/base.py
=> [DEV] OSIS-2680 : Remove auto <p> in CKEditor

base/templates/education_group/blocks/content_default_table.html, base/templates/education_group/blocks/content_minor_major_option_table.html, rules_management/fixtures/field_reference.json, rules_management/models.py
=> Osis 1856 Fix field reference  + labels

base/business/learning_unit_proposal.py, base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html, base/tests/views/learning_units/proposals/test_consolidate.py
=> #OSIS-2456 Correction pour la consolidation de proposition de création

base/forms/education_group/publication_contact.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/education_group/blocks/contacts_general_informations.html, base/templates/education_group/blocks/modal/modal_publication_contact_edit_inner.html
=> OSIS-2663 : Fix contacts

base/tests/views/education_groups/test_detail.py, base/tests/views/education_groups/test_update.py, base/tests/views/test_education_group.py
**Tests fixed :** 
test_user_has_not_link_to_edit_conditions
test_post_training_with_end_year
test_education_group_using_template_use
test_education_group_using_check_parent_list_with_group
=> Fix random test fails

base/tests/views/group_element_years/test_up_down.py, base/tests/views/test_learning_unit_proposal.py
test_learning_units_proposal_search_by_tutor
test_up_case_success
=> Fix test_learning_units_proposal_search_by_tutor

attribution/tests/business/test_perms.py, base/business/learning_units/perms.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> Osis 2464 Non summary responsible tutors can modify IP of LU

base/static/css/custom.css, base/static/js/education_group/education_group_tree.js, base/static/js/osis.js, base/templates/education_group/layout_detail.html, base/templates/education_group/learning_unit/layout_detail.html, base/templates/education_group/learning_unit/tab_prerequisite_group.html, base/templates/education_group/learning_unit/tab_prerequisite_training.html, base/templates/education_group/learning_unit/tab_prerequisite_update.html, base/templates/education_group/learning_unit/tab_utilization.html, base/templates/layout.html
=> OSIS-2684 Education group tree

base/locale/en/LC_MESSAGES/djangojs.po, base/locale/fr_BE/LC_MESSAGES/djangojs.po
=> OSIS-2684 Missing djangojs translations.

base/fixtures/groups.json
=> #IUFC-297 Ajout d'un group : gestionnaire IUFC

base/forms/common.py, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-1856 Modifier messages de formulaire

base/business/group_element_years/attach.py, base/business/group_element_years/detach.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> Osis 2562 Improve translation

rules_management/fixtures/field_reference.json
=> OSIS-2678 add validation rule for central managers on ISCED domain

rules_management/fixtures/field_reference.json
=> OSIS-2678 add permission denied to update ISCED domain for faculty users

base/business/learning_units/edition.py, base/forms/learning_unit/edition_volume.py, base/forms/learning_unit/learning_unit_create_2.py, base/views/learning_units/common.py, base/views/learning_units/proposal/create.py
=> Osis 2095 Retirer restrictions sur la modification des volumes en proposition

base/locale/fr_BE/LC_MESSAGES/django.po
modifié :         base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2681 - Correction d'une traduction

base/templates/education_group/tab_administrative_data.html
=> #OSIS-2615 Correction traduction

base/templates/education_group/identification_training_details.html
=> OSIS-2648 add default value to blank for isced_domain field

base/business/education_group.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-2691 Correction traductions

base/forms/learning_unit/learning_unit_partim.py, base/forms/learning_unit/learning_unit_postponement.py, base/tests/forms/test_learning_unit_postponement.py
=> Osis 2682 Error during a partim modification.

base/static/css/custom.css
=> Osis 2730 Small improvements on tree.

base/tests/views/test_learning_unit.py, base/tests/views/test_learning_unit_proposal.py
=> Refacto tests

base/business/education_groups/group_element_year_tree.py, base/tests/business/education_groups/test_build_tree.py
=> OSIS-2562 Remove taking account of link type reference

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/attributions.html, base/templates/learning_unit/blocks/panel/educational_informations.html
=> OSIS-2697 Correction de traductions

base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-2615 Changement de 'Président' à 'Président·e'

attribution/templates/manage_my_courses/blocks/list/learning_units_summary_editable.html, attribution/tests/views/test_manage_my_courses.py, attribution/views/manage_my_courses.py
=> #OSIS-2707 Retrait de la colonne score responsibles

base/management/commands/clean_placeholder_reddot.py, base/tests/management/test_clean_placeholder_reddot.py
=> OSIS-2746 Write command to clean placeholder of admission condition line

attribution/tests/views/test_manage_my_courses.py, base/forms/learning_unit_pedagogy.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/blocks/panel/educational_informations.html, base/templates/learning_unit/blocks/summary_locked.html, base/tests/views/test_learning_unit.py, base/views/learning_units/pedagogy/read.py, cms/models/translated_text.py
=> Osis 2686 Afficher auteur de la dernière modif sur les IP

base/models/teaching_material.py, base/views/learning_units/pedagogy/read.py
=> OSIS-2686 Added version on teaching material model

base/forms/education_group/group_element_year.py
=> OSIS-2761 Change NumberInput(default) to TextInput for better UX

base/static/js/education_group/education_group_tree.js
=> Fix js modal

base/views/education_groups/detail.py
=> [QA] OSIS-2763 Fix eligibleFiles which return value but not used

base/views/education_groups/detail.py
=> [DEV] OSIS-2763 Fix eligibleFiles which return value but not used

base/views/education_groups/detail.py
=> Release 0.49.10

base/templatetags/education_group.py
=> OSIS-2760 Change fa-close to fa-times

base/templates/education_group/tab_edit_administrative_data.html
=> #OSIS-2720 Correction de traduction

base/business/education_groups/automatic_postponement.py, base/business/education_groups/postponement.py, base/business/group_element_years/perms.py, base/business/group_element_years/postponement.py, base/business/learning_units/automatic_postponement.py, base/business/learning_units/edition.py, base/business/utils/postponement.py, base/forms/education_groups.py, base/forms/learning_unit/edition.py, base/forms/learning_unit/learning_unit_create_2.py, base/forms/learning_unit/learning_unit_postponement.py, base/models/academic_calendar.py, base/models/academic_year.py, base/models/education_group.py, base/models/education_group_year.py, base/models/learning_unit.py, base/tasks.py, base/tests/business/education_groups/test_automatic_postponement.py, base/tests/business/education_groups/test_postponement.py, base/tests/business/learning_units/test_automatic_postponement.py, base/tests/factories/admission_condition.py, base/views/academic_calendar.py, base/views/education_groups/achievement/detail.py, base/views/education_groups/detail.py, base/views/offer.py
=> Osis 2742 Copy Reddot data from N-1 to N 

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/views/education_groups/create.py
=> #OSIS-2671 correction traduction

base/tasks.py, base/tests/test_tasks.py
=> OSIS-2742 Add test for tasks.py

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2742 Update django.po

base/views/education_groups/update.py
=> Osis 2748 correction if

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/manage_my_courses/educational_information.html, attribution/views/manage_my_courses.py, base/static/css/osis.css, base/templates/learning_unit/specifications_all.html, base/views/learning_unit.py
=> #OSIS-2755 Affichage du cahier des charges pour le prof

base/business/education_groups/create.py, base/tests/business/education_groups/test_create.py
=> #OSIS-2765 Bug à la création d'une formation

base/fixtures/validation_rules.csv, base/forms/common.py, base/tests/factories/validation_rule.py, base/tests/forms/test_validation_rule_mixin.py
=> Osis 2670 Bug création formation

base/static/css/osis.css, base/templates/learning_unit/blocks/panel/cms_informations.html, base/templates/learning_unit/specifications_all.html
=> #OSIS-2755 Modification css

base/fixtures/validation_rules.csv, base/forms/education_group/training.py
=> Osis 2591 Fixed default value error OF

base/forms/student.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/student/exams_enrollments.html, base/templates/student/learning_units_enrollments.html, base/templates/student/offers_enrollments.html, base/templates/student/student.html, base/templates/student/students.html
=> #OSIS-2768 Traductions manquantes

base/views/education_groups/detail.py
=> OSIS-2742 Bug: missing reference for cms.

base/templates/education_group/blocks/form/training.html
=> #OSIS-2514 Correction js

attribution/templates/manage_my_courses/educational_information.html, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-2755 Corrections titre + look

base/business/education_groups/automatic_postponement.py, base/business/utils/postponement.py, base/tasks.py, base/tests/test_tasks.py
=> OSIS-2742 Copy data only for the academic year of the open calendar.

base/views/education_groups/detail.py
=> Correct admission condition bug

requirements.txt
=> Updated packages

requirements.txt
=> Updated django package

base/forms/education_group/group_element_year.py, base/models/group_element_year.py, base/templates/education_group/blocks/content_default_table.html, base/templates/education_group/blocks/table_utilizations.html, base/templates/education_group/group_element_year_comment_inner.html, base/tests/forms/education_group/test_groupElementYearForm.py, base/tests/views/group_element_years/test_edit.py
=> Osis 2776 Remove quadrimester derogation

base/fixtures/waffle_flags.json, base/templates/education_group/blocks/dropdown/administrative_data_actions_bar.html, base/tests/views/test_education_group.py, base/views/education_group.py
=> OSIS-2769 add flag to unable edit for administrative data

requirements.txt
=> [DEV] Revert Django version

base/templatetags/education_group_pdf.py
Référence Jira : Fixed-pdf-tree fixed bug
=> Fixed-pdf-tree fixed bug

base/fixtures/validation_rules.csv
=> OSIS-2591 Correctif validation_rules

base/models/enums/learning_container_year_types.py
=> OSIS-2396 Add Internship to the list of for_faculty

base/static/js/learning_unit/ckeditor.js, base/templates/learning_unit/blocks/modal/modal_pedagogy_edit.html, base/templates/learning_unit/blocks/panel/cms_informations.html, base/templates/learning_unit/specifications_edit.html, base/tests/views/education_groups/test_create.py
=> Bug edition

base/fixtures/groups.json
=> #IUFC-348 Mise à jour fixtures groups.json pour nouvelle permission

base/forms/learning_unit/attribution_charge_repartition.py, base/templates/learning_unit/add_charge_repartition_inner.html, base/templates/learning_unit/select_attribution.html, base/views/learning_units/attribution.py, base/views/learning_units/charge_repartition.py
=> OSIS-2397 Display vol 1 & vol 2 for partims

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/education_group.py, base/models/education_group_year.py, base/models/enums/education_group_types.py, base/tests/forms/education_group/test_common.py, base/tests/models/test_education_group.py
=> Osis 2795 Add validation on end date education group year

base/templates/academic_calendar/academic_calendars.html
=> OSIS-487 : Display tooltip and adapt with scrolling !

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2796 Correct translation in french

base/api/serializers/person.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2779 : Service for roles

base/fixtures/validation_rules.csv, base/static/js/learning_unit/ckeditor.js, base/tests/views/education_groups/test_create.py, base/views/education_groups/create.py
=> Osis 2591 Fixed bug redirect after create OF and modify fixture default value OF

base/templates/learning_unit/blocks/titles.html
=> OSIS-2455 : add asterisk to common title in proposal creation

base/business/group_element_years/attach.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/group_element_years/test_attach.py
=> OSIS-2824 Implement validation on attach

base/business/learning_unit.py, base/business/learning_unit_xls.py, base/tests/business/test_learning_unit_xls.py, base/tests/views/test_learning_unit.py, base/views/learning_units/search.py
=> OSIS-2710 : translate titles of column in Excel

base/business/group_element_years/attach.py
=> OSIS-2840 Remove unusefull if statement

base/business/group_element_years/detach.py
=> OSIS-2840 Correct detach algorithm

base/business/learning_units/xls_comparison.py, base/business/proposal_xls.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/learning_units/test_xls_comparison.py, base/tests/business/test_proposal_xls.py
=> OSIS-2710 : Translate comparison xls too

attribution/business/attribution_json.py, attribution/tests/business/test_attribution_json.py
=> #OSIS-2606 Ajout du title de la prochaine lu academicyr dans le json

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html
=> OSIS-2853 Modification de traduction

base/forms/education_group/common.py, base/forms/learning_unit/learning_unit_create.py, base/forms/learning_unit_component.py, base/forms/learning_unit_proposal.py
=> OSIS-2850 Suppression des spinner dans les inputs pour les nombres

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/group_element_year.py
=> OSIS-2716 correct translation

base/forms/learning_unit/edition_volume.py
=> OSIS-2850 Supprimer spiner dans les volumes

assessments/templates/admin/programmanager_confirm_delete_inner.html, assessments/templates/admin/programmanager_list.html, assessments/tests/views/test_pgm_manager_administration.py, assessments/urls.py, assessments/views/pgm_manager_administration.py
=> OSIS-2854 Adapter l'interface pour répondre au besoin business

base/forms/education_group/common.py, base/forms/education_group/group.py, base/forms/education_group/group_element_year.py, base/forms/education_group/mini_training.py, base/forms/education_group/training.py, base/forms/learning_unit/attribution_charge_repartition.py, base/forms/learning_unit/external_learning_unit.py
=> Osis-2850 Remove Spinner

assessments/templates/admin/programmanager_list.html
=> OSIS-2854 Missing bold (maybe it does not work with Chrome MacOS)

assessments/templates/admin/programmanager_list.html
=> OSIS-2854 Bold only if object_list equals selected offer_years

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/by_activity.html
=> OSIS-2710 : fix key of translation

base/forms/learning_unit/edition_volume.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2865 rename "P.C." to "Classes" and translations

attribution/templates/manage_my_courses/educational_information.html
=> OSIS-2873 : collapse cahier des charges

base/fixtures/.~lock.validation_rules.csv#, base/fixtures/validation_rules.csv
=> OSIS-2591 Switch fixture default values acronym

base/forms/learning_unit_proposal.py, base/forms/proposal/learning_unit_proposal.py, base/views/learning_units/search.py
=> OSIS-2855 Add filter in proposal form

base/static/css/custom.css, base/templates/learning_unit/blocks/form/simplified_volumes_management_form.html
=> OSIS-2866 update CSS

base/forms/learning_unit/edition_volume.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/forms/learning_unit/test_simplifiedVolumeForm.py
=> OSIS-2866 add error message when cannot add classes

base/forms/learning_unit/edition_volume.py
=> OSIS-2862 Bug dans l'encodage des volumes des UEs

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2800 Add translation

base/locale/fr_BE/LC_MESSAGES/django.po
=> Osis 2666 Traductions

base/business/education_groups/create.py, base/models/enums/education_group_types.py
=> Osis 2666 Fixed order of mandatory groups

base/forms/learning_unit_proposal.py, base/tests/forms/test_learning_unit_proposal.py, base/tests/views/learning_units/proposals/test_creation.py, base/tests/views/test_learning_unit_proposal.py
=> OSIS-2855 Filter pour n'avoir que les faculté

base/templates/learning_unit/blocks/form/simplified_volumes_management_form.html
=> OSIS-2844 update html

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/blocks/form/simplified_volumes_management_form.html
=> OSIS-2844 update html + translation

base/forms/prerequisite.py, base/tests/views/education_groups/learning_unit/test_update.py
=> Fix prerequisite update

.env.example, .gitignore, backoffice/settings/base.py, backoffice/urls.py, base/templates/layout.html, base/templates/learning_unit/blocks/modal/modal_force_state.html, base/templates/learning_unit/blocks/panel/educational_informations.html, requirements.txt
=> [TEST] Static jsi18n

base/business/learning_unit_xls.py, base/forms/learning_unit/search_form.py, base/models/learning_unit_year.py, base/templates/learning_unit/external/read.html, base/templatetags/learning_unit.py, base/tests/business/test_learning_unit_xls.py, base/tests/forms/learning_unit/test_search_form.py, base/tests/models/test_learning_unit_year.py
=> OSIS-2869 display 'Mobility' when LearningUnit is an external of subtype mobility

base/forms/learning_unit/search_form.py, base/tests/forms/test_external_learning_unit.py
=> OSIS-2869 fixed external learning unit search (only take co-graduation learningunits)

assessments/business/score_encoding_sheet.py
=> OSIS-2896 modif PDF après test utilisateur

assessments/business/score_encoding_export.py
=> OSIS-2819 fixed grey lines in xls file

backoffice/settings/base.py, base/templates/layout.html, templates/admin/base_site.html
=> [TEST] Fixed issue ckeditor and ManifestStaticFileStorage

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/views/learning_units/proposal/update.py
=> OSIS-2909 Add Warning when contains partim

base/models/education_group_year.py, base/models/enums/education_group_types.py, base/tests/views/test_education_group.py, base/views/education_groups/detail.py
=> OSIS-2669 : Add master180 for common-2m

base/business/education_groups/general_information_sections.py
=> Same sections for all minors, deepening and major

base/forms/learning_unit/edition_volume.py
=> OSIS-2916 modify PP and PM in volume managements

base/forms/learning_unit/edition_volume.py, base/static/css/custom.css
=> OSIS-2915 modify operator in title line for volume management

base/business/learning_units/perms.py, base/tests/business/test_perms.py, base/tests/templatetags/test_learning_unit_li.py, base/tests/views/test_learning_unit_edition.py
=> OSIS-2861 Central manager cannot edit luy after proposal years

base/templates/blocks/span/span_mod_status.html, base/templates/learning_unit/summary_list.html
=> OSIS-2929 Ajouter l'icone de status des informations pédagogique

base/views/learning_units/educational_information.py
=> OSIS-2914 show inactive courses

attribution/models/attribution.py, base/templates/learning_unit/blocks/panel/educational_informations.html, base/views/learning_units/pedagogy/read.py
=> OSIS-2923 Ajout du role de l'attribution

base/forms/education_group/group_element_year.py, base/templates/education_group/group_element_year_comment_inner.html, base/tests/forms/education_group/test_groupElementYearForm.py
=> Suppression de link_type pour OF > UE et de credit_relative pour OF > OF

base/business/learning_unit_proposal.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templatetags/learning_unit.py, base/tests/views/test_learning_unit_proposal.py, base/views/learning_units/proposal/update.py
=> OSIS-2766 : Add transformation proposal

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/views/test_learning_unit_proposal.py, base/views/learning_units/proposal/update.py
=> OSIS-2766 : Fix translations

assessments/templates/online_double_encoding_validation.html
=> fixed translation when re-encoding justifications

webservices/urls.py
Référence Jira : OP-271 OP-272 OP-273
=> [OP] Added urls for partnership api

webservices/urls.py
=> Revert "[OP] Added urls for partnership api"

base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/blocks/panel/educational_informations.html, base/templates/learning_unit/blocks/summary_locked.html
=> OSIS-2881 Modification template

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-2567 correct translation

base/tests/views/education_groups/test_update.py
=> Fix random test test_update.py management

webservices/urls.py
=> [QA] Add partnership app in service

base/business/learning_units/perms.py, base/models/learning_unit_year.py, base/templates/learning_unit/blocks/tabs.html, base/templates/learning_unit/identification.html, base/tests/views/test_learning_unit.py, base/views/learning_units/detail.py
=> OSIS-2900 : Consultation of external UE

base/models/group_element_year.py, base/models/prerequisite.py, base/templates/education_group/learning_unit/tab_prerequisite_training.html, base/views/education_groups/learning_unit/detail.py
=> OSIS-2930 Récupéré les OF pour les prérequis

base/forms/utils/acronym_field.py
=> OSIS-2884 Renommer "Sigle" en "Code" dans l'écran de modification
