uclouvain/osis

base/locale/fr_BE/LC_MESSAGES/django.po
base/models/enums/learning_container_year_types.py

OSIS-2882 Renommer "Thèse de master" en "Thèse"

---

base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-2883 Renommer "Réservé aux stagiaires" en "Réservé aux internes"

---

base/forms/learning_achievement.py
base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-2885 Renommer "Text" en "Texte"

---

base/templates/learning_unit/by_proposal.html

OSIS-2886 Renommer "Sigle" en "Code"

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-2900 : Missing translation

---

assessments/templates/online_double_encoding_validation.html
webservices/urls.py

Update reference to last 'dissertation' submodule version (including refactoring)

Release 0.50.1

---

backoffice/settings/base.py

[PATCH] Add STAFF_FUNDING_URL to base.py for partenrship

---

base/forms/prerequisite.py
base/models/prerequisite.py
base/tests/models/test_prerequisite.py
base/tests/views/education_groups/learning_unit/test_update.py

OSIS-2801 Allow user to type prerequisite in lower str

---

base/business/education_groups/general_information_sections.py

[QA] Osis 2943

---

base/business/education_groups/general_information_sections.py

[DEV] OSIS-2943 Correct Genral information

---

base/fixtures/groups.json

#IUFC-409 Ajout d'un groupe pour les jobistes iufc

---

attribution/business/attribution_charge_new.py
attribution/models/attribution_charge_new.py

OSIS-2807 Correct display attributions

---

base/business/group_element_years/postponement.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/tests/business/education_groups/test_postponement.py
base/tests/views/group_element_years/test_postpone.py
base/views/education_groups/update.py

Osis 2666 Modification messages report du contenu

---

base/templates/learning_unit/blocks/proposal_folder.html

OSIS-2893 : Bogue : fix position of page

---

base/models/entity_container_year.py
base/tests/model_forms/learning_unit/test_learning_unit_year.py

OSIS-2891 : Bogue : Translate requirement/allocation entities

---

base/views/learning_units/update.py

OSIS-2849 add filter on entity title in autocomplete entities selection

---

attribution/business/attribution_charge_new.py

OSIS-2807 Revert change attribution charge new

---

base/templates/entity/versions.html

OSIS-2890 : Bogue : Translation in Entities version

---

base/views/my_osis.py

IUFC-404 update ref osis_common and adapt base to it

---

assessments/locale/en/LC_MESSAGES/django.po
assessments/locale/fr_BE/LC_MESSAGES/django.po
base/business/group_element_years/detach.py
base/business/group_element_years/management.py
base/tests/business/group_element_years/test_management.py

Osis 2693 Bug détacher OF

---

base/templates/learning_unit/by_activity.html
base/templates/learning_unit/by_external.html

Référence Jira : OSIS-2961; OSIS-2962

OSIS-2961-2962 update col to add proposition and update icon

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/blocks/span/span_mod_status.html
base/templates/learning_unit/summary_list.html

Référence Jira : OSIS-2963; OSIS-2965

OSIS-2963-2965 update col to add modification and update icon

---

base/templates/learning_unit/blocks/form/search_form_external_learning_unit.html
base/templates/learning_unit/blocks/form/search_form_summary_list.html

OSIS-2964 add filter for status in search form LU

---

base/tests/views/education_groups/test_update.py

**Test failed because child end year (selected) > parent end year (target)**

OSIS-2944 : Repair test

---

base/templates/learning_unit/summary_list.html

OSIS-2965 debug color

---

assessments/locale/fr_BE/LC_MESSAGES/django.po

fixed translation of header in xls scores file

---

assessments/locale/fr_BE/LC_MESSAGES/django.po

Fixes translation into xls file (scores encoding)

Release 0.50.3

---

base/templates/learning_unit/by_activity.html
base/templates/learning_unit/by_external.html
base/templates/learning_unit/summary_list.html

OSIS-2965 change logo for inactive

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/learning_unit_year.py
base/templates/learning_unit/identification.html
base/templatetags/learning_unit.py
base/tests/models/test_learning_unit_year.py

OSIS-2900 : Fix consultation of external UE

---

base/static/js/dates-input.js

OSIS-2719 : Auto Apply

---

base/templates/education_group/group_element_year_comment_inner.html

OSIS-2995 Move mandatory button to rigth on link edit modal

---

base/templates/education_group/group_element_year_comment_inner.html

OSIS-2996 Add code to modal of link edition

---

base/views/quick_search.py

OSIS-2992 Add partial acronym in quick search filter.

---

requirements.txt

Updated django to 1.11.20

---

base/business/education_groups/group_element_year_tree.py
base/locale/en/LC_MESSAGES/django.po
base/locale/en/LC_MESSAGES/djangojs.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/djangojs.po
base/management/commands/makemessages.py
base/static/js/education_group/education_group_tree.js
base/tests/business/education_groups/test_build_tree.py
base/views/education_groups/group_element_year/update.py

OSIS-2994 Add modify button to tree contextual menu

---

base/business/learning_units/xls_generator.py

Osis 2889 - Bug lors de la création d'un fichier excel dans la recherche "statut des fiches descriptives"

---

base/tests/views/education_groups/test_update.py
base/views/education_groups/group_element_year/create.py

OSIS-3003 Add message in get request

---

base/forms/education_group/common.py
base/models/education_group_type.py

OSIS-2911 : Disable creation of Major and Mobility partnership

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/views/learning_units/search.py

#OSIS-3002 Ajout d'une traduction

---

base/business/learning_units/quadrimester_strategy.py
base/models/learning_component_year.py
base/tests/models/test_learning_unit_year.py

OSIS-2960 add 'NoStrategy' + test

---

base/business/learning_units/xls_generator.py
base/tests/views/test_learning_unit_pedagogy.py

#OSIS-2889 Tenir compte de la langue

---

base/fixtures/validation_rules.csv

OSIS-2877 les acronymes sans chiffre doivent avoir un espace

---

webservices/tests/test_ws_catalog_offer.py
webservices/views.py

[QA] OSIS-3025 Fix common webservice

---

webservices/tests/test_ws_catalog_offer.py
webservices/views.py

[DEV] OSIS-3025 : Refresh common texts

---

assessments/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/tab_admission_conditions.html
webservices/tests/test_ws_catalog_offer.py
webservices/views.py

Release 0.50.5

---

base/forms/learning_unit/external_learning_unit.py
base/forms/learning_unit/learning_unit_postponement.py

Osis 2318 Fixed bug report UE externe

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3029 update translation

---

base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3012 : Fix translation

---

base/fixtures/validation_rules.csv

OSIS-2981 : Tooltip in validation rules (Formations)

---

base/fixtures/validation_rules.csv
base/templates/education_group/blocks/form/group.html
base/templates/education_group/blocks/form/minitraining.html

OSIS-2591 : Placeholder for Group Acronym

---

base/forms/proposal/learning_unit_proposal.py

OSIS-2887 : Remove spinner

---

base/forms/learning_unit/external_learning_unit.py
base/models/campus.py
base/tests/forms/test_external_learning_unit.py
base/tests/views/test_learning_unit_proposal.py

OSIS-2818 Fixed country_external_institution default value

---

webservices/urls.py

[Test] Update ref partnership to test

---

backoffice/urls.py

Partnership add v1 API

---

backoffice/urls.py
webservices/urls.py

Move API specific to partnership app

---

base/templates/blocks/span/span_mod_status.html
base/templates/learning_unit/summary_list.html

OSIS-2457 Ajouter l'icone de status des informations pédagogique

---

attribution/models/attribution.py
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/learning_unit/blocks/panel/educational_informations.html
base/templates/learning_unit/blocks/summary_locked.html
base/views/learning_units/pedagogy/read.py

OSIS-2881 Display tutor function in description fiche

---

base/business/learning_unit_proposal.py
base/forms/learning_unit/edition_volume.py
base/forms/learning_unit/learning_unit_postponement.py
base/templates/learning_unit/blocks/form/simplified_volumes_management_form.html
base/tests/views/test_learning_unit.py
base/tests/views/test_learning_unit_proposal.py
base/views/learning_unit.py

Osis-3037 Modification du formulaire simplifié

---

base/business/group_element_years/postponement.py

OSIS-3026 Modification des permissions pour permettre de modifier N-2

---

base/migrations/0457_message_template_egys_automatic_postponement_update.py
base/models/education_group_year.py
base/tests/models/test_education_group_year.py

OSIS-3030 debug translation

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/blocks/span/span_mod_status.html
base/templates/learning_unit/blocks/form/search_form_external_learning_unit.html
base/templates/learning_unit/blocks/form/search_form_summary_list.html
base/templates/learning_unit/by_activity.html
base/templates/learning_unit/by_external.html
base/templates/learning_unit/summary_list.html

OSIS-2952 generalization of icons in learning units lists display

---

requirements.txt

[TEST] downgraded django

---

assessments/views/scores_responsible.py
attribution/business/summary_responsible.py
attribution/models/attribution.py
attribution/tests/business/test_summary_responsible.py
attribution/tests/models/test_attribution.py
attribution/views/summary_responsible.py

OSIS-3050 removed distinct('tutor') from attributions display (for summary and scores responsibles)

---

base/templates/learning_unit/by_activity.html
base/templates/learning_unit/by_external.html
base/templates/learning_unit/summary_list.html
base/views/learning_units/educational_information.py

OSIS-2952 change logo for inactive UEs

---

assessments/business/score_encoding_export.py
assessments/templates/online_encoding.html
assessments/templates/online_encoding_form.html

#OSIS-3021 Modifications du patch en dev aussi

---

base/migrations/0457_message_template_egys_automatic_postponement_update.py
base/tests/utils/test_send_mail.py
base/utils/send_mail.py

OSIS-3030 template for automatic postponement to N+6

---

base/business/education_groups/group_element_year_tree.py
base/business/group_element_years/attach.py
base/forms/education_group/group_element_year.py

OSIS-3052 Fixed bug when edit attributs To Test

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/blocks/span/span_mod_status.html

Référence Jira : OSIS-2457 OSIS-2952

PATCH-DEV_OSIS-2457-2952 update translation

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/blocks/span/span_mod_status.html

Référence Jira : OSIS-2457 OSIS-2952

PATCH-QA_OSIS-2457-2952 update translation

---

base/templates/learning_unit/blocks/panel/educational_informations.html

[PATCH To QA] OSIS-2881 Correct template

---

base/templatetags/education_group.py

[QA] OSIS-3051 Display label

---

base/fixtures/groups.json
base/models/enums/groups.py
base/models/person.py
base/tests/business/education_groups/test_perms.py
base/tests/business/learning_units/test_perms.py
base/tests/factories/group.py
base/tests/factories/person.py
base/tests/models/test_person.py

OSIS-3040 : Add AdministrativeManager Group (Read-Only access to UE/OF)

---

base/forms/learning_unit/learning_unit_create.py

#OSIS-3058 Bug sur la création d'UE externe

---

base/forms/learning_unit/learning_unit_create_2.py
base/tests/forms/test_learning_unit_create_2.py

OSIS-3023 Fixed bug

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/group_element_year_attach_type_dialog_inner.html

OSIS-3009 Added translations

---

base/migrations/0457_message_template_egys_automatic_postponement_update.py
base/utils/send_mail.py

OSIS-2979 debug after test in dev for report template

---

base/business/group_element_years/perms.py
base/business/learning_units/perms.py
base/templates/blocks/button/learning_units_action_button.html
base/templates/learning_unit/specifications_all.html
base/templatetags/education_group.py
base/tests/business/test_perms.py
base/tests/templatetags/test_learning_unit_li.py
base/tests/views/group_element_years/test_perms.py
base/tests/views/test_learning_unit.py

OSIS-3041 : fix some perms

---

base/forms/learning_unit/edition_volume.py
base/templates/learning_unit/blocks/form/simplified_volumes_management_form.html

#OSIS-3072 Modifier le label 'classes' en 'classes prévues'

---

base/fixtures/validation_rules.csv

OSIS-2981 - BOGUE : Fix mistakes in tooltip

---

base/business/group_element_years/postponement.py

OSIS-3026 Extended range report OF

---

base/templates/learning_unit/blocks/panel/educational_informations.html
base/templatetags/education_group.py

Release of internship submodule

Release 0.50.7  (internship submodule)

---

base/templates/learning_unit/simple/creation.html

#OSIS-3073 Ajouter 'Gestion par équipe' en proposition de création d'UE

---

base/models/education_group_year.py

OSIS-2656 Lors de la suppression d'une OF, il ne faut pas prendre en compte des groupements obligatoires

---

base/templates/education_group/blocks/form/training.html

OSIS-3080 debug red dot when validation error in form for training

---

base/business/education_groups/automatic_postponement.py

OSIS-3076 debug cronjob for automatic postponement (exclude common)

---

base/templates/blocks/navbar_top.html
base/templates/catalog.html
base/templates/offer/breadcrumb.html
base/templates/offers.html
base/templates/studies.html

OSIS-3079 : Simplify Formation Catalog Menu

---

base/business/education_groups/group_element_year_tree.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/learning_unit/tab_prerequisite_training.html
base/tests/business/education_groups/test_build_tree.py

#OSIS-3063 Uniformisation des phrases concernant les prérequis

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/catalog.html
base/templates/offers.html

OSIS-3070 : Rename subtitle of catalog buttons

---

base/business/education_groups/automatic_postponement.py
base/business/education_groups/create.py

 OSIS-3076 add support for postponement of common

---

base/templates/education_group/blocks/form/training_tab_identification.html

OSIS-2975 debug tab_to_show for modify

---

base/templates/education_group/identification_mini_training_details.html

Le problème de fin/début est surement du à la synchro ?  @basmot

OSIS-3062 : Acronym to Management entity (Need synchro for start/end years ?)

---

base/forms/learning_unit/entity_form.py
base/static/js/learning_unit_creation.js

OSIS-3067 Correction du champs country pour le formulaire UE

---

base/fixtures/validation_rules.csv

OSIS-2981 : PhD => Doctorat

---

base/business/group_element_years/management.py
base/tests/business/group_element_years/test_detach.py

OSIS-3060 Fix bug: min_count_authorized during a detach.

---

attribution/tests/views/test_manage_my_courses.py
base/business/learning_units/perms.py
base/templatetags/learning_unit_li.py
base/tests/business/learning_units/test_perms.py

OSIS-2545 : Block edition of UE before 2018

---

base/business/education_groups/group_element_year_tree.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/tests/business/education_groups/test_build_tree.py

#OSIS-3063 Correction d'une traduction

---

base/templates/education_group/blocks/form/create_cancel_buttons.html
base/views/education_groups/create.py
base/views/education_groups/update.py

OSIS-3048 Perdre le context de l'arbre quand on essaie de créer une OF

---

webservices/tests/test_ws_catalog_offer.py
webservices/views.py

[QA] OSIS-3088 : Webservice Error 500 for FC Offers

---

webservices/tests/test_ws_catalog_offer.py
webservices/views.py

Release 0.50.8

---

webservices/tests/test_ws_catalog_offer.py
webservices/views.py

[DEV] OSIS-3088 : Webservice Error 500 for FC Offers 

---

base/forms/learning_unit/edition_volume.py
base/forms/learning_unit/learning_unit_create.py

OSIS-3089 Create InputField to remove extra 0 after decimal

---

base/templatetags/education_group.py
base/tests/templatetags/test_education_group.py

OSIS-3019 : Disable Edit button in Administrative data

---

base/templates/education_group/blocks/content_default_table.html
base/templates/education_group/blocks/content_minor_major_option_table.html

Osis 3094 - Améliorer la navigation dans l'onglet "contenu"

---

base/templates/entities.html
base/templates/organization/organizations.html
base/templates/student/students.html
features/7_entity_search.feature
features/8_organization_search.feature
features/9_student_search.feature
features/steps/7_entity_search.py
features/steps/8_organization_search.py
features/steps/9_student_search.py
features/steps/entity_search.py
features/steps/generic.py
features/steps/learning_unit_search.py
features/steps/organization_search.py
features/steps/student_search.py
features/steps/utils/pages.py

Osis 3095 - Ajout de tests fonctionnels

---

base/business/education_groups/create.py
base/tests/business/education_groups/test_create.py

OSIS-2624 : Bogue in OF report

---

base/templates/education_group/layout_detail.html
base/templates/layout.html
base/templates/learning_unit/layout_detail.html

OSIS-3098 : Add Offer/LearningUnit acronym in Page Title

---

base/business/education_groups/general_information.py
base/models/education_group_year.py
base/tests/business/education_groups/test_general_information.py
base/tests/factories/education_group_year.py

OSIS-2664/2667 : Publish finality/option offer

---

base/templates/education_group/blocks/row_label_general_informations.html
base/templates/education_group/tab_admission_conditions.html
base/templates/education_group/tab_general_informations.html

OSIS-3100 : Improve visibility of GeneralInfo/AdmissionCond

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/group_element_year.py
base/templates/education_group/blocks/row_table_utilizations.html
base/templates/learning_unit/formations.html
base/tests/models/test_group_element_year.py
base/tests/views/learning_units/test_formations_tab.py
base/views/learning_unit.py

OSIS-3085 Add roots of each formation in formations tab

---

base/static/js/education_group/education_group_tree.js

OSIS-3096 keep tree open after restart of browser

---

base/templates/learning_unit/blocks/form/form_external.html

OSIS-3087 : Hide vacant/decision/procedure field in external UE Creation

---

base/templatetags/education_group.py
base/tests/templatetags/test_education_group.py

OSIS-3103 : Remove tooltip from enabled Modify button in administrati

---

base/forms/learning_unit/learning_unit_postponement.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/tests/forms/test_learning_unit_postponement.py

#OSIS-2610 Problème d'affichage dans les warnings

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html

Osis 3077 - Rendre inaccessible l'action 'Fiche comparative' si on est sur une proposition de création

---

base/templates/education_group/layout_detail.html

OSIS-3098 : LUY acronym if selected in tree

---

base/locale/en/LC_MESSAGES/django.po
base/locale/en/LC_MESSAGES/djangojs.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/djangojs.po
base/static/js/learning_unit_creation.js
base/templates/education_group/blocks/form/training.html

OSIS-2953 Add error message via JS and correction js translate

---

base/static/js/education_group/education_group_tree.js

OSIS-3097 Pomme (Ctrl) + click ne fonctionne pas dans l'arbre

---

base/templates/education_group/blocks/form/training.html

OSIS-2953 Correction key traduction

---

base/forms/learning_unit/search_form.py
base/tests/forms/learning_unit/test_search_form.py

OSIS-3081 : Fix Borrowed UE Search

---

base/forms/learning_unit/search_form.py

OSIS-3099 Remove * in borrow search form.

---

base/static/js/education_group/education_group_tree.js

OSIS-3097 add support for Cmd+click on mac

---

base/business/education_groups/perms.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templatetags/education_group.py
base/tests/business/education_groups/test_perms.py
base/tests/templatetags/test_education_group.py

OSIS-2978 : Faculty manager could create Groups into Offers of his entity

---

base/business/learning_units/pedagogy.py

OSIS-1558 : Remove circular import

---

base/static/js/education_group/education_group_tree.js

OSIS-3097 debug selection

---

base/api/serializers/person.py
base/models/person.py
base/templates/learning_unit/blocks/panel/educational_informations.html
base/templatetags/education_group.py
base/tests/models/test_person.py
requirements.txt

Osis 3083 (Merge to Dev)

---

base/business/learning_unit.py
base/forms/learning_unit_proposal.py
base/tests/views/education_groups/test_search.py
base/tests/views/test_learning_unit.py
base/tests/views/test_learning_unit_proposal.py
base/views/education_groups/search.py
base/views/learning_unit.py
base/views/learning_units/common.py
base/views/learning_units/detail.py
base/views/learning_units/proposal/update.py
base/views/learning_units/search.py
base/views/learning_units/update.py

OSIS-3125 removed 'experimental phase' from templates of catalog (UE/OF) features

---

base/templates/academic_actors.html

OSIS-3092 Affichages redondants, en-tête erroné

---

base/fixtures/authorized_relationship.json

OSIS-3127 Can not add subgroup in complementary module

---

base/business/education_groups/group_element_year_tree.py
base/tests/business/education_groups/test_build_tree.py

OSIS-3102 Tree: remove id in the generator

---

base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html

#OSIS-3077 Disabled du bouton(pour de vrai cette fois-ci)

---

base/business/group_element_years/attach.py
base/tests/business/group_element_years/test_attach.py

Osis 2840 Bug check options when attaching finality

---

base/templates/education_group/blocks/form/training.html

OSIS-2953 Fix double red ball and error message

---

features/6_offer_update.feature
features/steps/utils/pages.py

Fix functional

---

base/templates/education_group/blocks/form/training.html

OSIS-2953 Fix double red ball

---

assessments/tests/views/test_score_encoding.py
assessments/views/score_encoding.py

OSIS-3108 Do not consider not_enrolled students to check notes to encode

---

base/views/education_groups/group_element_year/update.py

Osis 3129 Erreur ajout mineure dans liste mineures

---

base/templates/education_group/blocks/form/training.html

OSIS-2953 Simplification du JS

---

webservices/tests/test_ws_catalog_offer.py
webservices/views.py

Release 0.50.9

---

base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-2953 Modification translate

---

backoffice/urls.py
webservices/urls.py

[QA] Release 0.50.9

---

base/static/js/education_group/education_group_tree.js

OSIS-3134 debug click in tree by remove ctrl+click

---

base/static/js/education_group/education_group_tree.js

OSIS-3134 debug on select node

---

base/business/group_element_years/management.py

OSIS-3136 : Error message if cannot detach

---

assessments/locale/en/LC_MESSAGES/django.po
assessments/locale/fr_BE/LC_MESSAGES/django.po
assessments/tests/views/test_score_encoding.py
assessments/views/upload_xls_utils.py

OSIS-3117 Explicit error message when no or 2+ session at xls injection

---

base/templates/blocks/button/action_template.html
base/templates/blocks/button/button_order.html
base/templates/education_group/blocks/admission_condition_table_row.html
base/templates/education_group/blocks/content_actions.html
base/templates/education_group/blocks/content_default_table.html
base/templates/education_group/tab_admission_conditions.html
base/templatetags/education_group.py
base/templatetags/group_element_year.py
base/tests/templatetags/test_education_group.py

OSIS-3141 Uniformiser les boutons "Actions"

---

attribution/tests/views/test_attribution.py
attribution/tests/views/test_manage_my_courses.py
attribution/tests/views/test_tutor_application.py
base/tests/business/test_education_group.py
base/tests/views/education_groups/test_update.py

Assert equal

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/search.html

OSIS-3135 : Organisation de formation ==> Formation

---

base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3135 : missing translation

---

base/templates/blocks/forms/create_cancel_buttons.html
base/templates/education_group/blocks/modal/modal_pedagogy_edit.html
base/templates/education_group/blocks/modal/modal_pedagogy_edit_inner.html
base/templates/education_group/layout_detail.html
base/templates/education_group/tab_general_informations.html
base/templates/layout.html
base/templates/learning_unit/blocks/modal/modal_modification_ask_to_report.html
base/templates/learning_unit/blocks/save_cancel_buttons_with_modal.html
base/templates/learning_unit/learning_unit_layout.html

OSIS-3145 Uniformiser les boutons Annuler et les titres

---

base/templates/blocks/button/action_template.html
base/templatetags/group_element_year.py

OSIS-3141 Use disabled for action buttons in content page

---

base/templates/education_group/blocks/content_default_table.html

OSIS-3143 Bug fix: wrong url in content table.

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html

OSIS-3137 : Fiches comparatives

---

base/tests/forms/education_group/test_common.py

OSIS-3146 : Random test fail

---

base/business/group_element_years/attach.py
base/locale/fr_BE/LC_MESSAGES/django.po
base/tests/business/group_element_years/test_attach.py

#OSIS-3147 Impossible de modifier un lien (contenu OF)

---

base/business/education_groups/perms.py
base/business/group_element_years/postponement.py
base/models/education_group_type.py
base/templates/education_group/blocks/content_default_table.html
base/templates/education_group/identification_training_details.html
base/templatetags/education_group.py
base/tests/views/education_groups/test_detail.py
base/views/education_groups/detail.py
base/views/education_groups/update.py

OSIS-3143 Optimizing queries for content page

---

base/business/learning_unit_proposal.py
base/tests/factories/business/learning_units.py
base/tests/views/test_learning_unit_proposal.py

Osis 3112 Fixed bug when type is None in Initial data

---

base/api/serializers/person.py
base/models/person.py
base/tests/models/test_person.py
requirements.txt

Osis 3083 (Merge to Qa)

---

base/business/learning_units/edition.py

OSIS-3124 Continue postponement when partim is short

---

base/models/academic_calendar.py
base/models/admission_condition.py
base/models/certificate_aim.py
base/models/education_group_language.py
base/models/education_group_publication_contact.py
base/models/education_group_type.py
base/models/entity_manager.py
base/models/entity_version.py
base/models/external_offer.py
base/models/hops.py
base/models/learning_achievement.py
base/models/offer_year_calendar.py
base/models/person_entity.py
base/models/prerequisite.py
base/models/prerequisite_item.py
base/models/program_manager.py
base/models/proposal_learning_unit.py

OSIS-3154 : Add django-reversion to models

---

base/business/learning_units/edition.py
base/tests/business/learning_units/test_edition.py

Osis 3124 Fix display error

---

backoffice/settings/base.py

OSIS-3155 : Empty CDN_URL default (remove button if not set)

---

base/business/learning_unit_proposal.py
base/templates/learning_unit/identification.html
base/templatetags/learning_unit.py

Osis-3112 Fix bug credit proposition

---

base/forms/learning_unit/edition_volume.py

Osis 3126 Save PM and PP volume together

---

base/models/utils/utils.py
base/templates/blocks/dl/dl_tooltip.html
base/templatetags/learning_unit.py

OSIS-3158 Partim sans entité de charge : ne pas afficher None

---

base/models/admission_condition.py

OSIS-3154 : Add django-reversion to AdmissionConditionLine

---

backoffice/settings/base.py

OSIS-3155 : Some changes for CDN_URL

---

base/static/js/learning_unit_creation.js

OSIS-3133 Fixed double submite

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/education_group_year.py
base/tests/factories/education_group_year.py
base/tests/models/test_education_group_year.py
base/tests/views/group_element_years/test_edit.py
base/tests/views/learning_units/test_formations_tab.py
requirements.txt

OSIS-2976 add check on valid (partial_)acronym

---

base/business/learning_container_year.py
base/business/learning_unit_year_with_context.py
base/business/learning_units/perms.py
base/forms/learning_unit/learning_unit_postponement.py
base/models/academic_year.py
base/models/learning_component_year.py
base/models/learning_unit_year.py
base/models/person.py
base/models/proposal_learning_unit.py
base/tests/models/test_tutor.py

Osis 3157 Optional entities do not need warnings when they are empty.

---

base/fixtures/validation_rules.csv
base/management/commands/load_validation_rules.py

+ update load_validation_rules to be able to run from anywhere
Référence Jira : OSIS-3164

OSIS-3164 correct regex for 2MS group type

---

base/tests/views/group_element_years/test_edit.py

intent to fix the failing test

---

base/business/learning_unit_proposal.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3165 Missing translation in consolidation report

---

.travis.yml

[Travis] Removed slack for notifications

---

base/templates/education_group/blocks/content_actions.html

[To QA] OSIS-3171 Fixed bug move element

---

base/tests/views/learning_units/test_charge_repartition.py
base/views/learning_units/charge_repartition.py

[DEV] Osis 3174 Ensure that during repartition external_ids of Attribution is not copied

---

assessments/locale/fr_BE/LC_MESSAGES/django.po
assessments/templates/outside_scores_encodings_period.html

OSIS-3177 : Outside score encoding period fixes

---

assessments/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3177 : missing 's'

---

base/templates/learning_unit/identification.html

OSIS-3166 : Duplicate block of entities

---

base/templates/base/quick_search_inner.html

OSIS-3193 : Rename trainings and learning units

---

base/business/education_groups/group_element_year_tree.py
base/templates/education_group/learning_unit/tabs.html
base/views/education_groups/learning_unit/detail.py

OSIS-3185 add support for the UEs in tree

---

base/utils/send_mail.py

OSIS-1071 Fixed column remark in report consolidation

---

base/views/education_groups/group_element_year/delete.py

OSIS-3191 add partial_acronym when available in modal

---

base/templatetags/education_group.py
base/tests/templatetags/test_education_group.py

OSIS-3195 debug button. click was available even disable

---

base/templates/learning_unit/blocks/panel/educational_informations.html
base/templates/learning_unit/blocks/summary_locked.html

OSIS-3180 : Fix Teachers blocks in 'Fiche descriptive'

---

assessments/templates/scores_encoding_by_learning_unit.html

OSIS-3217 debug warning show twice

---

base/templates/education_group/blocks/dropdown/identification_actions_bar.html

OSIS-3016 Remove restrictions on select egy

---

base/business/learning_unit_year_with_context.py
base/templatetags/learning_unit.py

 OSIS-3216 Fixed vug when create proposal

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/group_element_year_attach_type_dialog_inner.html

OSIS-3196 Modification des traductions

---

base/models/education_group.py
base/models/program_manager.py
base/templates/my_osis/profile.html
base/tests/models/test_education_group.py
base/tests/views/test_my_osis.py
base/views/my_osis.py

[DEV] OSIS-3208 : Replace offer_read by education_group_read in myProfile

---

base/tests/views/education_groups/test_detail.py
base/views/education_groups/detail.py

OSIS-3215  replaced 'current academic year' by 'starting academic year' into EducationGroupDetailView

---

base/templates/blocks/navbar_top.html

OSIS-2309 debug navbar when too long

---

base/templates/blocks/navbar_top.html
base/templates/blocks/notifications.html

OSIS-2309 redebug navbar when too long

---

base/business/education_groups/perms.py
base/business/education_groups/postponement.py
base/business/learning_unit.py
base/business/learning_units/pedagogy.py
base/business/learning_units/perms.py
base/business/learning_units/xls_comparison.py
base/forms/education_groups.py
base/forms/entity_calendar.py
base/forms/learning_unit/comparison.py
base/forms/learning_unit/edition.py
base/forms/learning_unit/learning_unit_create_2.py
base/forms/learning_unit/learning_unit_partim.py
base/forms/learning_unit_proposal.py
base/models/learning_unit.py
base/views/education_groups/create.py
base/views/education_groups/update.py
base/views/learning_units/common.py
base/views/learning_units/educational_information.py
base/views/learning_units/search.py
base/views/quick_search.py

OSIS-3182 replaced current by starting academic year in initial data of EducationGroupFilter (search form)

---

base/templates/institution.html

OSIS-3210 debug icon to close from each other

---

base/templates/learning_unit/proposal/create_modification.html
base/templates/learning_unit/proposal/update_modification.html

OSIS-3189 Remove tabs on edition/creation of proposal

---

base/forms/education_group/common.py

OSIS-3222 debug update end of offer

---

base/templates/layout.html

OSIS-3214 Fixed bug auto complete in Modal

---

base/business/education_groups/group_element_year_tree.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/static/js/education_group/education_group_tree.js
base/views/education_groups/detail.py

Osis 3130 Disabled buttons detach attach on tree

---

base/business/education_groups/group_element_year_tree.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po

Osis 3130 Disabled attach/detach/modify on tree

---

base/locale/fr_BE/LC_MESSAGES/django.po

Osis 3130 Attach/detach/modification disabling

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/group_element_year.py

OSIS-3227 rename error message

---

base/models/enums/education_group_types.py

OSIS-3229 add 'FSA Speciality' to EducationGgroupYear to potpone

---

.env.example
backoffice/settings/base.py
base/utils/cache.py

OSIS-3237 Remove double cache config

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/academic_year.py
base/templates/learning_unit/blocks/form/volumes_management_form.html
base/templates/learning_unit/simple/update.html
base/tests/views/learning_units/external/test_update.py
base/views/learning_units/update.py

Osis 2303 Remove modal and change message

---

base/forms/learning_unit/search_form.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/learning_unit_year.py
base/templates/learning_unit/blocks/form/search_form_learning_unit.html
base/templates/learning_unit/blocks/form/search_form_summary_list.html
base/tests/views/test_learning_unit.py

OSIS-3223 Add quadrimester in learning units searches 

---

base/templates/learning_unit/specifications_all.html

OSIS-3232 : Improve AA's templates

---

base/templatetags/education_group.py
base/tests/views/education_groups/test_update.py
base/views/education_groups/update.py

[To QA] OSIS-3242 fixed perm to update certificate aims if EducationGroup.year equals to working year

---

base/static/js/education_group/education_group_tree.js

OSIS-3213 : Disable "OPEN" button in contextual tree menu

---

base/models/person.py
base/tests/models/test_entity_version.py

[QA] OSIS-3241 : Add faculties even if attached to UCL or a sector

---

base/utils/send_mail.py

Osis 2977 Automatic postponement error

---

backoffice/urls.py

Django 2.0  migration

---

base/templates/education_group/blocks/content_actions.html
base/templates/education_group/blocks/content_minor_major_option_table.html

[to qa] OSIS-3212 content tab of major/minor

---

.env.example

Test workflow hotfix

---

.env.example

Mon super message

---

base/business/education_groups/general_information.py
base/models/education_group_year.py
base/tests/business/education_groups/test_general_information.py

[QA] OSIS-2667 : Fix publication of offers

---

.env.example

testSubtask

---

base/forms/learning_unit_proposal.py
base/templates/learning_unit/blocks/proposal_folder.html

OSIS-3250 put folder field mandatory in Creation Proposal

---

base/models/person.py
base/tests/models/test_person.py

#OSIS-3251 Traiter le cas si language est None

---

.env.example

Revert "test sub2"

---

dev-requirements.txt

test sub 3

---

base/templates/layout.html

OSIS-3303 Ajout |safe dans titre notice template

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/learning_unit_year.py
base/templates/learning_unit/identification.html
base/templatetags/learning_unit.py
base/tests/templatetags/test_learning_unit.py

OSIS-3277 show new code when has changed for old LU

---

base/templates/education_group/blocks/content_default_table.html
base/templates/education_group/learning_unit/tab_prerequisite_training.html
base/views/education_groups/learning_unit/detail.py

OSIS-3282 Display "prerequisites of" learning units in table + details

---

base/templates/my_osis/profile.html
base/views/my_osis.py

#OSIS-3246 Accélérer le temps de chargement de la page 'mon profil'

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/education_group.py
base/templates/education_group/identification_mini_training_details.html
base/templates/education_group/identification_training_details.html

OSIS-3293 Changer le label "Fin" en "Dernière année d'organisation"

---

backoffice/urls.py
base/forms/education_groups.py
base/templates/education_group/search.html
base/tests/utils/test_cache.py
base/tests/views/education_groups/test_search.py
base/utils/cache.py
base/views/education_groups/search.py
base/views/education_groups/urls.py

Pull request automatique de feature/OSIS-2585 vers DEV

[feature/OSIS-2585 => DEV] En tant que tous, je souhaiterais avoir un choix multiple pour le type d'offre dans la recherche d'OF

---

base/models/learning_unit_year.py
features/10_learning_unit_read.feature
features/steps/10_learning_unit_read.py

Osis 3298 - Ajout de test fonctionnels pour l'affichage des warnings d'un partim

---

.env.example

Test MAJ PR test

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/learning_unit_year.py
base/templates/learning_unit/identification.html
base/templatetags/learning_unit.py
base/tests/templatetags/test_learning_unit.py

Pull request automatique de feature/OSIS-1801 vers dev

[feature/OSIS-1801 => DEV] En tant que gestionnaire central des UEs, je veux afficher le nouveau code de l_UE

---

base/models/learning_unit_year.py
base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html
base/templates/learning_unit/layout_detail.html
base/views/learning_units/common.py
base/views/learning_units/detail.py

OSIS-3283 : Can choose academic year from detail of LUY

---

base/models/prerequisite.py
base/tests/factories/learning_unit_year.py
base/tests/models/test_prerequisite.py
base/tests/models/test_prerequisite_item.py

OSIS-3074 Enhance first list of prerequisites with tooltips on items

---

base/business/utils/postponement.py
base/templates/blocks/modal/confirmation_modal.html
base/templates/education_group/blocks/form/training.html
base/tests/business/education_groups/test_automatic_postponement.py
base/tests/business/learning_units/test_automatic_postponement.py
features/steps/utils/pages.py

[OSIS-3229] Do not report egy that ends before adjournement year

---

assessments/business/scores_responsible.py
assessments/forms/scores_responsible.py
assessments/templates/scores_responsible/list.html
assessments/templates/scores_responsible_edit.html
assessments/tests/views/test_scores_responsible.py
assessments/urls.py
assessments/views/scores_responsible.py
attribution/business/score_responsible.py
base/templates/academic_actors.html
base/tests/factories/business/learning_units.py

Osis 3299 Refactor Score Responsible view to a FilterView with pagination

---

base/templatetags/prerequisite.py

Osis 3314 Display prerequisite string

---

base/templates/base/person_list.html
base/tests/views/test_user_list.py
base/urls.py
base/views/user_list.py

avec leurs groupes et entitiés liés

OSIS-3306 visualiser la liste des utilisateurs

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3306 update translation

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/base/person_list.html

OSIS-3306 update html + translation

---

assessments/forms/scores_responsible.py
assessments/tests/views/test_scores_responsible.py
assessments/views/scores_responsible.py

OSIS-3299 : Fix and optimize

---

attribution/business/attribution_charge_new.py
base/business/learning_unit.py
base/business/learning_unit_xls.py
base/business/learning_units/xls_generator.py
base/business/xls.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/learning_unit/by_activity.html
base/templates/learning_units.html
base/tests/business/test_learning_unit_xls.py
base/tests/business/test_xls.py
base/tests/views/test_learning_unit.py
base/views/learning_units/search.py

#OSIS-3321 Ajout d'une liste d'UE avec une ligne par attribution

---

base/fixtures/groups.json
base/migrations/0467_create_permission_person_model.py
base/tests/views/test_user_list.py
base/views/user_list.py

OSIS-3322 create permission + group + add to view

---

base/templatetags/learning_unit.py

Fixed template tags

---

base/templates/layout.html
base/templatetags/learning_unit.py

Pull request automatique de hotfix/OSIS-3328 vers DEV

[hotfix/OSIS-3328 => DEV] On voit des _None_ à l_affichage

---

base/templates/base/person_list.html
base/views/user_list.py

#OSIS-3324 Optimisation de la requête

---

base/templatetags/academic_actors.py

#OSIS-3341 Correction des acces

---

base/fixtures/groups.json
base/templates/academic_actors.html
base/templates/base/person_list.html
base/templates/blocks/navbar_top.html
base/urls.py

OSIS-3343 move link to Institution

---

assessments/forms/scores_responsible.py

OSIS-3299 : Improve (reduce) Hits DB

---

base/forms/learning_unit/search_form.py
base/tests/forms/learning_unit/test_search_form.py

Pull request automatique de hotfix/OSIS-3372 vers DEV

[WIP] [hotfix/OSIS-3372 => DEV] Bug sur la recherche des cours empruntés

---

base/forms/learning_unit/search_form.py
base/models/entity_version.py

Pull request automatique de hotfix/OSIS-3372 vers QA

[hotfix/OSIS-3372 => QA] Bug sur la recherche des cours empruntés

---

base/templates/learning_unit/by_activity.html
base/templates/learning_unit/by_external.html
base/templates/learning_unit/by_proposal.html
base/templates/learning_unit/summary_list.html
base/views/learning_units/search.py

Pull request automatique de hotfix/OSIS-3371 vers QA

[hotfix/OSIS-3371 => QA] Bug de tri dans la recherche d_UE

---

base/business/education_groups/group_element_year_tree.py
base/tests/views/education_groups/group_element_year/test_read.py
base/views/education_groups/group_element_year/read.py

#OSIS-3347 Ne plus afficher de détail sous un groupement 'liste des mineures' dans le pdf

---

base/forms/learning_unit/search_form.py
base/models/entity_version.py

Pull request automatique de hotfix/OSIS-3372 vers DEV

[hotfix/OSIS-3372 => DEV] Bug sur la recherche des cours empruntés

---

base/templates/learning_unit/by_activity.html
base/templates/learning_unit/by_external.html
base/templates/learning_unit/by_proposal.html
base/templates/learning_unit/summary_list.html
base/views/learning_units/search.py

Pull request automatique de hotfix/OSIS-3371 vers DEV

[hotfix/OSIS-3371 => DEV] Bug de tri dans la recherche d_UE

---

base/business/education_groups/group_element_year_tree.py
base/business/group_element_years/attach.py
base/models/entity.py
base/models/entity_version.py
base/models/learning_unit_year.py
base/tests/business/education_groups/test_build_tree.py
base/tests/business/learning_units/test_edition.py
base/tests/factories/education_group_type.py
base/tests/models/test_entity_version.py
base/tests/models/test_learning_unit_year.py
base/tests/views/education_groups/test_update.py

OSIS-2972 Afficher les cours de service

---

base/templates/base/person_list.html
base/views/user_list.py

Osis 3385 - Améliorations design sur la page user list :  collapses + pagination

---

assessments/locale/en/LC_MESSAGES/django.po
assessments/locale/fr_BE/LC_MESSAGES/django.po
attribution/locale/en/LC_MESSAGES/django.po
attribution/locale/fr_BE/LC_MESSAGES/django.po
base/business/education_groups/group_element_year_tree.py
base/business/utils/postponement.py
base/forms/learning_unit/search_form.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/management/commands/makemessages.py
base/models/entity_version.py
base/tasks.py
base/templates/learning_unit/by_activity.html
base/templates/learning_unit/by_external.html
base/templates/learning_unit/by_proposal.html
base/templates/learning_unit/summary_list.html
base/tests/views/education_groups/group_element_year/test_read.py
base/views/education_groups/group_element_year/read.py
base/views/learning_units/search.py

OSIS-1311 : Update dev & .po

---

base/views/learning_units/educational_information.py

Pull request automatique de hotfix/OSIS-3387 vers QA

[WIP] [hotfix/OSIS-3387 => QA] L_affichage des résultats dans la recherche des UEs dans les fiches descriptives est tronqué

---

base/tests/views/education_groups/test_search.py
base/views/education_groups/search.py

Pull request automatique de hotfix/OSIS-3377 vers QA

[hotfix/OSIS-3377 => QA] L_autocomplete dans la recherche des formations ne fonctionne pas

---

base/locale/fr_BE/LC_MESSAGES/django.po
base/tests/factories/education_group_type.py
base/tests/views/education_groups/test_update.py

OSIS-3393 Fixed traduction

---

base/templates/base/person_list.html

#OSIS-3404 Amélioration des collapses

---

base/business/education_groups/group_element_year_tree.py
base/fixtures/waffle_switches.json
base/tests/business/education_groups/test_build_tree.py

OSIS-3406 add switch about showing service classes

---

base/business/education_groups/group_element_year_tree.py
base/models/learning_unit_year.py
base/tests/business/education_groups/test_build_tree.py

OSIS-3414 not taking account of US of mobility

---

base/templates/base/person_list.html

OSIS-3404 removed collapse

---

assessments/business/scores_responsible.py
assessments/tests/views/test_scores_responsible.py
base/business/education_groups/group_element_year_tree.py
base/business/group_element_years/attach.py
base/fixtures/waffle_switches.json
base/models/entity.py
base/models/entity_version.py
base/models/learning_unit_year.py
base/models/program_manager.py
base/tests/business/education_groups/test_build_tree.py
base/tests/business/learning_units/test_edition.py
base/tests/business/learning_units/test_perms.py
base/tests/factories/education_group_type.py
base/tests/models/test_entity_version.py
base/tests/models/test_learning_unit_year.py
base/tests/views/education_groups/test_search.py
base/tests/views/education_groups/test_update.py
base/views/education_groups/search.py
base/views/learning_units/educational_information.py

OSIS-3419 Correct query in score responsible edit/search

---

base/business/education_groups/group_element_year_tree.py
base/tests/business/education_groups/test_build_tree.py
base/tests/views/group_element_years/test_create.py

OSIS-3434 debug when entity is not academic

---

base/business/education_groups/group_element_year_tree.py

OSIS-1808 fix codeclimate cognitive complexity

---

base/business/education_groups/group_element_year_tree.py
base/fixtures/waffle_switches.json
base/models/education_group_year.py
base/models/entity.py
base/tests/business/education_groups/test_build_tree.py
base/tests/business/learning_units/test_perms.py
base/tests/models/test_group_element_year.py
base/tests/views/education_groups/group_element_year/test_read.py
base/tests/views/education_groups/test_search.py
base/tests/views/education_groups/test_update.py
base/tests/views/group_element_years/test_create.py
base/views/learning_units/educational_information.py

Pull request automatique de feature/OSIS-1808 vers DEV

[feature/OSIS-1808 => DEV] En tant que gestionnaire d_OF, je voudrais visualiser dans l_arbre les cours empruntés aux autres facultés (picto)

---

backoffice/settings/base.py

add django.contrib.postgres to INSTALLED_APPS

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/tests/views/education_groups/learning_unit/test_update.py
base/views/education_groups/learning_unit/update.py

Pull request automatique de hotfix/OSIS-3361 vers QA

[hotfix/OSIS-3361 => QA] impossible de modifier les prérequis

---

base/forms/learning_unit/attribution_charge_repartition.py
base/templates/learning_unit/attribution_inner.html

#OSIS-3454 Améliorations pour la modale d'attribution

---

base/forms/learning_unit/attribution_charge_repartition.py
base/static/css/osis.css
base/templates/learning_unit/attribution_inner.html

#OSIS-3454

---

backoffice/settings/base.py
base/tests/views/education_groups/test_search.py
base/tests/views/test_organization.py
requirements.txt

Pull request automatique de hotfix/OSIS-3378 vers QA

[hotfix/OSIS-3378 => QA] Problème d_affichage des dropdown list (autocomplete-light)

---

backoffice/settings/base.py
base/tests/views/education_groups/test_search.py
base/tests/views/test_organization.py
requirements.txt

Pull request automatique de hotfix/OSIS-3378 vers DEV

[hotfix/OSIS-3378 => DEV] Problème d_affichage des dropdown list (autocomplete-light)

---

base/business/learning_units/xls_comparison.py

Pull request automatique de hotfix/OSIS-3375 vers QA

[hotfix/OSIS-3375 => QA] On ne sait plus générer le fichier Excel des comparaison UE/propositions

---

.env.example
backoffice/settings/base.py
base/business/education_groups/excel.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/learning_unit_year.py
base/templates/education_group/blocks/dropdown/identification_actions_bar.html
base/tests/business/education_groups/test_excel.py
base/tests/factories/group_element_year.py
base/tests/factories/utils/fuzzy.py

[OSIS-3357] Use complete title based on language

---

base/models/proposal_learning_unit.py
base/templatetags/learning_unit.py
base/tests/templatetags/test_learning_unit.py
base/views/learning_units/detail.py

Pull request automatique de hotfix/OSIS-3373 vers QA

[hotfix/OSIS-3373 => QA] UE n affiche pas de bon information

---

base/views/learning_units/educational_information.py

[hotfix/OSIS-3440 => QA] Statut des fiches descriptives : 2020-21 par défaut

---

base/forms/education_group/common.py

OSIS-3443 Limited start_year and end_year

---

base/templates/learning_unit/blocks/form/search_form_summary_list.html
base/templates/learning_unit/summary_list.html

Pull request automatique de hotfix/OSIS-3381 vers QA

[hotfix/OSIS-3381 => QA] Recherche des fiches descriptives (UEs) m_affiche _aucun résultat alors que je n_ai fait aucune recherche

---

base/forms/learning_unit/attribution_charge_repartition.py
base/templates/learning_unit/add_charge_repartition_inner.html
base/templates/learning_unit/attributions.html
base/templates/learning_unit/select_attribution.html
features/2_learning_unit_update.feature

Pull request automatique de hotfix/OSIS-3389 vers QA

[hotfix/OSIS-3389 => QA] Problème de traduction _volume_ en _PM / PP_

---

base/forms/learning_unit/learning_unit_partim.py
base/forms/learning_unit/learning_unit_postponement.py
base/tests/forms/test_learning_unit_partim.py

Pull request automatique de hotfix/OSIS-3430 vers QA

[hotfix/OSIS-3430 => QA] Lorsque je crée un partim, je ne peux plus le supprimer

---

base/business/education_group.py
base/business/education_groups/perms.py
base/business/education_groups/postponement.py
base/business/group_element_years/postponement.py
base/business/utils/postponement.py
base/forms/education_group/coorganization.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/proposal_learning_unit.py
base/templates/learning_unit/blocks/form/search_form_summary_list.html
base/templates/learning_unit/summary_list.html
base/templatetags/learning_unit.py
base/tests/business/education_groups/test_postponement.py
base/tests/forms/education_group/test_coorganization.py
base/tests/forms/education_group/test_training.py
base/tests/templatetags/test_learning_unit.py
base/tests/views/education_groups/test_update.py
base/views/education_groups/detail.py
base/views/education_groups/update.py
base/views/learning_units/detail.py
base/views/learning_units/educational_information.py

OSIS-1311 : Resolve conflicts

---

base/forms/learning_unit/learning_unit_create_2.py
base/forms/learning_unit_proposal.py
base/templates/learning_units.html
base/tests/views/learning_units/test_search.py
base/tests/views/test_quicksearch.py
base/views/learning_units/search.py

Pull request automatique de hotfix/OSIS-3424 vers QA

[hotfix/OSIS-3424 => QA] En tant que gestionnaire central, je n_arrive pas à créer un cours en 2020-2021

---

base/views/education_groups/detail.py
base/views/education_groups/group_element_year/read.py

Refacto 2946

---

base/templates/learning_unit/by_activity.html
base/templates/learning_unit/by_external.html
base/templates/learning_unit/by_proposal.html
base/templates/learning_unit/summary_list.html
base/views/common.py
base/views/learning_units/educational_information.py
base/views/learning_units/search.py

[hotfix/OSIS-3433 => QA] Réactiver la pagination dans le recherches des UEs

---

base/forms/education_group/common.py
base/templates/education_group/blocks/form/minitraining.html
base/templates/education_group/blocks/form/training_tab_identification.html

Osis 3443 Modification template

---

base/forms/learning_unit/attribution_charge_repartition.py
base/templates/learning_unit/add_charge_repartition_inner.html
base/templates/learning_unit/attributions.html
base/templates/learning_unit/select_attribution.html
features/2_learning_unit_update.feature

Pull request automatique de hotfix/OSIS-3478 vers QA

[hotfix/OSIS-3478 => QA] P.M. devient PM (idem P.P.)

---

base/forms/learning_unit/attribution_charge_repartition.py
base/templates/learning_unit/add_charge_repartition_inner.html
base/templates/learning_unit/attributions.html
base/templates/learning_unit/select_attribution.html
features/2_learning_unit_update.feature

Pull request automatique de hotfix/OSIS-3478 vers DEV

[hotfix/OSIS-3478 => DEV] P.M. devient PM (idem P.P.)

---

base/business/learning_unit_year_with_context.py
base/models/entity_version.py
base/tests/forms/test_learning_units.py

Pull request automatique de hotfix/OSIS-3410 vers QA

[hotfix/OSIS-3410 => QA] Certaines UEs ne sont pas reprises dans la recherche des cours de service

---

base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3479 Correction traduction enum calendar descriptions

---

base/forms/learning_unit/learning_unit_create.py
rules_management/fixtures/field_reference.json

Pull request automatique de hotfix/OSIS-3427 vers QA

[hotfix/OSIS-3427 => QA] Les champs relatifs aux attributions ne devraient pas être modifiables dans OSIS 

---

base/forms/learning_unit/learning_unit_create.py
rules_management/fixtures/field_reference.json

Pull request automatique de hotfix/OSIS-3427 vers DEV

[hotfix/OSIS-3427 => DEV] Les champs relatifs aux attributions ne devraient pas être modifiables dans OSIS 

---

.gitignore

update gitignore for idea

---

learning_unit/admin.py
learning_unit/apps.py
learning_unit/models.py
learning_unit/schema.yml
learning_unit/tests.py
learning_unit/views.py

OSIS-3355 Write OpenAPI Specification for learning_unit module

---

learning_unit/api/url_v1.py

OSIS-436 : Create structure

---

base/locale/fr_BE/LC_MESSAGES/django.po

#OSIS-3492 Modification traductions

---

base/forms/learning_unit/external_learning_unit.py
base/tests/forms/test_external_learning_unit.py
base/tests/views/learning_units/external/test_create.py

Pull request automatique de hotfix/OSIS-3485 vers QA

[hotfix/OSIS-3485 => QA] interdire au gestionnaire facultaire de pouvoir créer des UE externes en 2018

---

base/forms/learning_unit/external_learning_unit.py
base/forms/learning_unit/learning_unit_create.py
base/models/learning_unit_year.py
base/tests/forms/test_external_learning_unit.py
base/tests/views/learning_units/external/test_create.py
rules_management/fixtures/field_reference.json

Pull request automatique de hotfix/OSIS-3485 vers DEV

[hotfix/OSIS-3485 => DEV] interdire au gestionnaire facultaire de pouvoir créer des UE externes en 2018

---

base/forms/learning_unit/learning_unit_create.py
base/models/learning_unit_year.py
rules_management/fixtures/field_reference.json

Pull request automatique de hotfix/OSIS-3488 vers DEV

[WIP] [hotfix/OSIS-3488 => DEV] (191319) Les enseignants ne voient plus les fiches descriptives des partim dans leur bureau virtuel

---

base/templates/institution.html
base/tests/views/test_institution.py
base/views/institution.py

OSIS-3493 Add icon on institution html

---

base/locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OSIS-3417 vers QA

[hotfix/OSIS-3417 => QA] Message d_erreur incorrect sur l_action modifier date de fin d_un cours

---

base/locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OSIS-3417 vers DEV

[hotfix/OSIS-3417 => DEV] Message d_erreur incorrect sur l_action modifier date de fin d_un cours

---

attribution/tests/views/test_manage_my_courses.py
backoffice/settings/base.py
base/business/learning_units/perms.py
base/tests/business/learning_units/test_perms.py
base/tests/factories/academic_year.py
base/tests/templatetags/test_learning_unit_li.py
base/tests/views/test_learning_unit_deletion.py
base/tests/views/test_teaching_material.py

Pull request automatique de hotfix/OSIS-3362 vers QA

[hotfix/OSIS-3362 => QA] En tant que gestionnaire central, Il est possible de modifier des UE en 18-19

---

attribution/tests/views/test_manage_my_courses.py
backoffice/settings/base.py
base/business/learning_units/perms.py
base/forms/learning_unit/learning_unit_create.py
base/models/learning_unit_year.py
base/tests/business/learning_units/test_perms.py
base/tests/factories/academic_year.py
base/tests/templatetags/test_learning_unit_li.py
base/tests/views/test_learning_unit_deletion.py
base/tests/views/test_teaching_material.py
rules_management/fixtures/field_reference.json

Pull request automatique de hotfix/OSIS-3362 vers DEV

[hotfix/OSIS-3362 => DEV] En tant que gestionnaire central, Il est possible de modifier des UE en 18-19

---

base/models/academic_calendar.py
base/tests/models/test_academic_calendar.py

OSIS-3510 Function get_academic_calendar + tests

---

base/tests/forms/test_external_learning_unit.py

[QA] Fix random test : test_creation

---

base/business/learning_units/xls_educational_information_and_specifications.py
base/tests/business/learning_units/test_xls_educational_information_and_specifications.py
requirements.txt

#OSIS-3514 Ne plus avoir d'html ou de texte formaté dans le fichier xls

---

base/business/education_groups/excel.py

#OSIS-3475

---

base/forms/prerequisite.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/tests/views/education_groups/learning_unit/test_update.py
base/views/education_groups/learning_unit/update.py

Pull request automatique de hotfix/OSIS-3505 vers QA

[hotfix/OSIS-3505 => QA] Empêcher l_ajout d_un prérequis qui n_appartient pas à l_arbre

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/views/education_groups/excel.py

#OSIS-3475 Modif traduction

---

base/models/learning_unit_year.py
learning_unit/api/serializers/learning_unit.py
learning_unit/api/url_v1.py
learning_unit/api/views/learning_unit.py
learning_unit/schema.yml
learning_unit/tests/api/serializers/test_learning_unit.py
learning_unit/tests/api/views/test_learning_unit.py

Osis 3519 Implement ListView on learning unit year

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/learning_unit/by_proposal.html

Pull request automatique de improvement/OSIS-3520 vers DEV

[improvement/OSIS-3520 => DEV] Onglet propositions : améliorer bouton export listes

---

base/business/education_groups/general_information_sections.py
education_group/api/serializers/achievement.py
education_group/api/serializers/general_information.py
education_group/api/serializers/section.py
education_group/api/views/general_information.py
education_group/tests/api/serializers/test_achievement.py
education_group/tests/api/serializers/test_general_information.py
education_group/tests/api/serializers/test_section.py
education_group/tests/api/views/test_general_information.py
webservices/business.py

OSIS-3522 : GeneralInformation & Achievement Serializers

---

base/tests/templatetags/test_learning_unit_li.py
base/tests/views/education_groups/test_detail.py
base/tests/views/education_groups/test_update.py

[To QA] Osis-3526 Fixed test

---

base/business/education_groups/group_element_year_tree.py
base/fixtures/validation_rules.csv
base/models/entity.py
base/models/entity_version.py
base/templatetags/learning_unit.py
base/tests/models/test_entity_version.py

Iufc 478 maj

---

base/business/education_groups/general_information_sections.py
base/business/education_groups/group_element_year_tree.py
base/tests/business/education_groups/test_build_tree.py
base/views/education_groups/learning_unit/detail.py
webservices/views.py

OSIS-3512 : Add intro sections

---

base/forms/learning_unit/edition.py

Référence Jira : fixed_get_academic_years

fixed_get_academic_years

---

base/business/education_groups/excel.py
base/models/group_element_year.py

#OSIS-3340 - Correction pep08

---

doc/technical-manual.adoc

add section: Installing PostgreSQL extensions

---

base/forms/learning_unit/edition.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/education_group.py
base/models/learning_unit.py
base/templates/learning_unit/blocks/form/update_proposal.html
base/templates/learning_unit/proposal/create_suppression.html
base/templates/learning_unit/proposal/update_suppression.html
base/templates/learning_unit/simple/update_end_date.html

OSIS-3583 Changer les libellés "anac de début" et "anac de fin"

---

base/business/education_groups/general_information_sections.py
base/templates/education_group/blocks/contacts_general_informations.html
base/templates/education_group/tab_general_informations.html
base/views/education_groups/detail.py
webservices/urls.py

OSIS-3590 : Add missing info in 2.0 WS

---

assessments/tests/views/test_scores_responsible.py
backoffice/settings/base.py
base/models/program_manager.py
base/tests/views/education_groups/test_search.py
base/tests/views/test_organization.py
base/utils/renderers.py
base/views/common.py
requirements.txt

Django2 enabled

---

education_group/schema.yml

OSIS-3611 Create OpenAPI schema for education_groups

---

base/forms/education_group/training.py
base/models/education_group_certificate_aim.py
base/templates/education_group/blocks/form/training_certificate.html

[hotfix/OSIS-3552 => QA] Certaines OFs possèdent plusieurs attendus de section = 2 en production

---

learning_unit/api/views/learning_achievement.py

OSIS-3491 Correct PEP8 syntax on learning_achievement

---

base/business/education_groups/group_element_year_tree.py
webservices/api/serializers/general_information.py
webservices/api/serializers/section.py

OSIS-3524 : Introduction (options/finalities/common_core) 

---

learning_unit/tests/api/views/test_learning_unit.py

OSIS-3551 : Test middleware

---

base/templates/learning_unit/identification.html

Pull request automatique de improvement/OSIS-3572 vers DEV

[improvement/OSIS-3572 => DEV] Dans le cas d_une proposition de transformation, le message apparaissant en dessous du code est ambigu

---

webservices/api/serializers/contacts.py
webservices/tests/api/serializers/test_contacts.py

OSIS-3535 : Get null instead of empty string

---

base/business/event_perms.py
base/forms/education_group/common.py
base/tests/forms/education_group/test_common.py

OSIS-3628 correct academic year on creation to show only years related to open AcaCalendar

---

base/api/serializers/campus.py
education_group/api/serializers/mini_training.py
education_group/api/serializers/utils.py
education_group/api/url_v1.py
education_group/api/views/mini_training.py
education_group/tests/api/serializers/test_learning_unit.py
education_group/tests/api/serializers/test_mini_training.py
education_group/tests/api/serializers/test_training.py
education_group/tests/api/views/test_mini_training.py
education_group/tests/api/views/test_training.py

OSIS-3613 : Mini training View & Serializer

---

education_group/api/serializers/group.py
education_group/api/serializers/utils.py
education_group/api/url_v1.py
education_group/api/views/group.py
education_group/tests/api/serializers/test_group.py
education_group/tests/api/views/test_group.py

OSIS-3612 : Group Serializer & View

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/static/js/osis_datatable.js
base/templates/learning_unit/blocks/form/search_form_learning_unit.html
base/templates/learning_unit/blocks/form/search_form_proposal.html
base/templates/learning_unit/search/base.html
base/templates/learning_unit/search/description_fiche.html
base/templates/learning_unit/search/external.html
base/templates/learning_unit/search/proposal.html
base/templates/templatetags/pagination_size_select.html
base/templatetags/pagination.py
base/views/learning_units/search/common.py

Osis 3527 Fix excel generation on luy search page + changed display of search page

---

webservices/api/serializers/common_admission_condition.py
webservices/api/serializers/common_text.py
webservices/api/views/common_admission_condition.py
webservices/api/views/common_text.py
webservices/tests/api/serializers/test_common_admission_condition.py
webservices/tests/api/serializers/test_common_text.py
webservices/tests/api/views/test_common_admission_condition.py
webservices/tests/api/views/test_common_text.py
webservices/urls.py

OSIS-3541 : Missing endpoints

---

.gitignore
.idea/externalDependencies.xml
.idea/inspectionProfiles/Default.xml
.idea/inspectionProfiles/Osis.xml
.idea/inspectionProfiles/profiles_settings.xml
.idea/vcs.xml

add config idea on qa

---

base/templates/learning_unit/formations.html

OSIS-3631 always display relative credits (even if its = to absolute)

---

education_group/api/serializers/learning_unit.py
education_group/api/views/learning_unit.py
education_group/tests/api/serializers/test_learning_unit.py
education_group/tests/api/views/test_learning_unit.py
learning_unit/schema.yml

OSIS-3642 : Add missing informations in prerequisites

---

base/views/organization.py

Pull request automatique de hotfix/OSIS-3425 vers QA

[WIP] [hotfix/OSIS-3425 => QA] UE externes : Les hautes écoles ne sont pas reprises dans les institutions partenaires

---

education_group/api/serializers/learning_unit.py
education_group/tests/api/serializers/test_learning_unit.py
learning_unit/schema.yml

OSIS-3642 : Remove credits

---

education_group/api/serializers/learning_unit.py
education_group/api/views/learning_unit.py
education_group/tests/api/serializers/test_learning_unit.py
education_group/tests/api/views/test_learning_unit.py
learning_unit/schema.yml

Pull request automatique de feature/OSIS-3641 vers DEV

[feature/OSIS-3641 => DEV] Améliorations du endpoint Prerequisites (learning_unit - FicheActivite)

---

base/locale/en/LC_MESSAGES/djangojs.po
base/locale/fr_BE/LC_MESSAGES/djangojs.po

Ajout traduction pour message de chargement lorsque les données sont requêtées par ajax.

[OSIS-2973] Ajout traduction js

---

base/fixtures/validation_rules.csv

OSIS-3647 Modification de regex Master 120 a finalité spécialisé

---

base/static/css/osis.css
base/static/js/osis_datatable.js
base/templates/layout.html
base/templates/template_nav_header.html

[OSIS-3528] display processing msg on top of search result

---

base/templates/education_group/blocks/row_table_utilizations.html
base/templates/education_group/blocks/table_utilizations.html
base/templates/education_group/learning_unit/tab_utilization.html
base/templates/learning_unit/formations.html

Pull request automatique de hotfix/OSIS-3631 vers MASTER

[hotfix/OSIS-3631 => MASTER] Problème d_affichage des crédits relatifs (dans l_arbre - onglet _utilisation_)

---

base/tests/views/education_groups/learning_unit/test_update.py
base/views/education_groups/learning_unit/update.py

Pull request automatique de hotfix/OSIS-3622 vers MASTER

[hotfix/OSIS-3622 => MASTER] Impossible d_ajouter des prérequis

---

education_group/api/serializers/education_group_title.py
education_group/api/serializers/group.py
education_group/api/serializers/mini_training.py
education_group/api/serializers/training.py
education_group/api/url_v1.py
education_group/api/views/group.py
education_group/api/views/mini_training.py
education_group/api/views/training.py
education_group/schema.yml
education_group/tests/api/serializers/test_education_group_title.py
education_group/tests/api/serializers/test_group.py
education_group/tests/api/serializers/test_mini_training.py
education_group/tests/api/serializers/test_training.py
education_group/tests/api/views/test_group.py
education_group/tests/api/views/test_mini_training.py
education_group/tests/api/views/test_training.py
learning_unit/api/url_v1.py
learning_unit/schema.yml

Pull request automatique de improvement/OSIS-3649 vers DEV

[improvement/OSIS-3649 => DEV] Renommer le path API learning_units/.../.../get_title  en title

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/learning_unit/blocks/modal/modal_confirm_cancel.html
base/templates/learning_unit/blocks/modal/modal_confirm_consolidate.html
base/views/learning_units/detail.py

Osis-3607 Modification du message de présence de partims

---

education_group/api/url_v1.py
learning_unit/api/url_v1.py

Fix url's to not redirect

---

base/forms/learning_unit/learning_unit_postponement.py

OSIS-3645 Fixed bug creation de partim

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/views/teaching_material.py

modified:   base/locale/en/LC_MESSAGES/django.po
modified:   base/locale/fr_BE/LC_MESSAGES/django.po
modified:   base/views/teaching_material.py

[OSIS-3382] translate teaching material on success messages

---

base/fixtures/validation_rules.csv

OSIS-3673 Ajout de sigle autorisé pour Doctorant et formation doctorant

---

webservices/api/serializers/achievement.py

OSIS-3696 : Edit webservices according to new rules

---

webservices/api/serializers/admission_condition.py
webservices/api/serializers/section.py
webservices/api/serializers/utils.py
webservices/tests/api/serializers/test_admission_condition.py

OSIS-3696 : Add admission conditions for iufc trainings

---

learning_unit/schema.yml

Pull request automatique de improvement/OSIS-3697 vers DEV

[improvement/OSIS-3697 => DEV] Structure de schéma LearningUnitAchievement 

---

base/business/education_groups/general_information_sections.py
base/models/education_group_year.py
base/models/enums/education_group_types.py
webservices/api/serializers/admission_condition.py
webservices/tests/api/serializers/test_admission_condition.py

OSIS-3695 : Fix missing sections

---

base/forms/learning_unit/search/simple.py
base/tests/views/test_learning_unit.py

hotfix/OSIS-3707 Fix search luy by container_type + test

---

base/models/academic_calendar.py

OSIS-3730 Make data_year editable

---

.env.docker
Dockerfile

Docker update

---

learning_unit/api/serializers/learning_unit.py
learning_unit/api/views/learning_unit.py
learning_unit/schema.yml
learning_unit/tests/api/serializers/test_learning_unit.py
learning_unit/tests/api/views/test_learning_unit.py

OSIS-3736 : ExternalLearningUnit Serializer

---

learning_unit/api/serializers/teaching_materials.py
learning_unit/api/url_v1.py
learning_unit/api/views/teaching_materials.py
learning_unit/schema.yml
learning_unit/tests/api/serializers/test_teaching_materials.py
learning_unit/tests/api/views/test_teaching_materials.py

OSIS-3739 : TeachingMaterials endpoint

---

program_management/business/excel.py

OSIS-3692 Replace / with _ in worksheet title

---

base/forms/learning_unit/search/simple.py
base/forms/proposal/learning_unit_proposal.py
base/tests/forms/learning_unit/test_search_form.py
base/tests/forms/test_learning_unit_proposal.py

OSIS-3732 Set initial True for with_entity_subordinated search fields

---

learning_unit/schema.yml

OSIS-3734 : Boolean field

---

base/models/enums/education_group_types.py
base/tests/views/test_education_group.py
base/views/education_groups/detail.py

OSIS-3735 : Show admission condition tab

---

base/business/group_element_years/management.py
base/forms/education_group/group_element_year.py
base/tests/business/group_element_years/test_management.py

[hotfix/OSIS-3715 => QA] Impossible d_éditer une ligne de l_onglet Contenu (OF)

---

base/locale/fr_BE/LC_MESSAGES/django.po

#OSIS-3740

---

base/locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de improvement/OSIS-3705 vers DEV

[improvement/OSIS-3705 => DEV] Changer l_intitulé liste excel prérequis

---

base/static/css/osis.css

Pull request automatique de improvement/OSIS-3693 vers DEV

[improvement/OSIS-3693 => DEV] Presse-papier: déplacement vers la gauche

---

base/fixtures/validation_rules.csv
base/templates/education_group/blocks/form/group.html

Pull request automatique de improvement/OSIS-3681 vers DEV

[improvement/OSIS-3681 => DEV] Arbre: partie de base: modifier l_intitulé par défaut en _Contenu:_

---

base/tests/views/learning_units/search/search_test_mixin.py
base/tests/views/learning_units/search/test_borrowed.py
base/tests/views/learning_units/search/test_educational_information.py
base/tests/views/learning_units/search/test_proposal.py
base/tests/views/learning_units/search/test_service_course.py
base/tests/views/learning_units/search/test_simple.py
base/views/learning_units/search/borrowed.py
base/views/learning_units/search/common.py
base/views/learning_units/search/service_course.py
base/views/learning_units/search/simple.py

Osis 3711 génération fichier xls ne prend plus en compte les paramètres

---

rules_management/fixtures/field_reference.json

[DEV] OSIS-3627 Allow faculty manager to modify credits on education group

---

base/tests/views/learning_units/search/test_educational_information.py
base/tests/views/test_learning_unit_pedagogy.py

fix failling test on branch dev

---

learning_unit/api/views/learning_unit.py
learning_unit/tests/api/views/test_learning_unit.py

OSIS-3736 : Fix missing entities

---

base/views/learning_units/search/common.py

[OSIS-3444] save search type in session

---

base/models/enums/education_group_types.py
base/tests/views/test_education_group.py
base/views/education_groups/detail.py
webservices/api/serializers/admission_condition.py
webservices/tests/api/serializers/test_admission_condition.py

OSIS-3748 : Adapt change from xls file

---

learning_unit/schema.yml

OSIS-3753 : Adapt schema

---

base/fixtures/validation_rules.csv
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/views/learning_units/pedagogy/update.py

Pull request automatique de hotfix/OSIS-3749 vers QA

[hotfix/OSIS-3749 => QA] OF: modification de l_intitulé par défaut et accepté des mineures

---

base/fixtures/validation_rules.csv

[hotfix/OSIS-3749 => DEV] OF: modification de l_intitulé par défaut et accepté des mineures

---

base/templates/learning_unit/components.html
base/templates/learning_unit/components_identification.html
base/templatetags/components_classes.py

Pull request automatique de improvement/OSIS-3580 vers DEV

[improvement/OSIS-3580 => DEV] Problème de classe 0/1

---

base/forms/academic_calendar.py

[hotfix/OSIS-3757 => DEV] Form modif academic_calendar vide data_year

---

program_management/business/excel.py
program_management/tests/business/test_excel.py

Pull request automatique de improvement/OSIS-3558 vers DEV

[improvement/OSIS-3558 => DEV] Rajouter les titres des colonnes à l_Excel _Générer xls des cours qui ont des prérequis_

---

base/locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OSIS-3754 vers QA

[hotfix/OSIS-3754 => QA] Erreur dans un message

---

program_management/locale/fr_BE/LC_MESSAGES/django.po

#OSIS-3754 Résolution des conflits avec dev

---

backoffice/settings/base.py
base/forms/education_group/achievement.py
base/forms/education_group_admission.py
base/forms/education_group_pedagogy_edit.py
base/forms/learning_achievement.py
base/forms/learning_unit_pedagogy.py
base/forms/learning_unit_specifications.py
base/tests/views/learning_units/search/test_educational_information.py
base/views/education_groups/detail.py

OSIS-3737 uniformize ckEditor configs into UE and OF

---

base/static/css/osis.css
base/templates/learning_unit/identification.html

OSIS-3764 Modification du template d'affichage des partims et full UE

---

base/templates/learning_unit/identification.html

OSIS-3764 Suppression d'un br

---

base/tests/views/learning_units/proposals/test_creation.py
base/views/learning_units/proposal/create.py

[hotfix/OSIS-3765 => DEV] Les propositions de creation se creent toujours en 2020-21

---

base/templates/learning_unit/blocks/panel/educational_informations.html

Pull request automatique de hotfix/OSIS-3722 vers QA

[hotfix/OSIS-3722 => QA] UE - Fiche Descriptive - Mobilité: les caractères spéciaux sont mal interprétés

---

base/templates/learning_unit/blocks/panel/educational_informations.html

[hotfix/OSIS-3722 => DEV] UE - Fiche Descriptive - Mobilité: les caractères spéciaux sont mal interprétés

---

backoffice/settings/base.py

OSIS-3773 removed default font-family into 'contentCss' config

---

base/fixtures/groups.json

Osis 3770 update perms to see academic_calendar

---

base/templates/education_group/blocks/dropdown/identification_actions_bar.html
program_management/business/group_element_years/management.py
program_management/templates/quick_search_base.html
program_management/templates/quick_search_egy_inner.html
program_management/templates/quick_search_luy_inner.html
program_management/tests/views/test_groupelementyear_create.py
program_management/views/quick_search.py

Fix osis 3540

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/learning_unit/identification.html

[QA] OSIS-3786 Fixed traduction "Parent" > "UE complète"

---

base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3658 : translations

---

base/fixtures/groups.json

OSIS-3792 add group student_update_UE_AA with permission

---

base/business/education_groups/general_information_sections.py

OSIS-3809 Renommage en anglais 'droits_inscription' en 'tuition_fees'

---

base/models/academic_calendar.py
base/templates/home.html
base/tests/models/test_academic_calendar.py
base/views/common.py

OSIS-3798 Remove calendar from homepage + clean code

---

base/fixtures/waffle_flags.json
base/templates/blocks/navbar_top.html

OSIS-3799 Set feature_flag on notification bell + add flag in fixture

---

base/business/education_groups/perms.py
base/templatetags/education_group.py
base/tests/views/education_groups/test_update.py
base/views/education_groups/update.py
base/views/education_groups/urls.py
program_management/business/group_element_years/perms.py
rules_management/fixtures/field_reference.json

Osis 3797 Remove central/faculty manager perms on certificate aims

---

base/fixtures/waffle_flags.json
base/models/academic_calendar.py
base/templates/blocks/navbar_top.html
base/templates/home.html
base/tests/models/test_academic_calendar.py
base/views/common.py

Pull request automatique de improvement/OSIS-3788 vers DEV

[improvement/OSIS-3788 => DEV] Masquer le calendrier académique de la page d_accueil Osis pour les gestionnaires facultaires et centraux

---

program_management/forms/group_element_year.py

OSIS-3812 : Edit save and is_valid formset

---

base/forms/learning_unit/learning_unit_create.py
base/tests/forms/test_learning_unit_create_2.py

Osis-3803 Répliquer la modification d'acronym sur les partims

---

base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/blocks/content_default_table.html
base/templates/education_group/blocks/form/group.html
base/templates/education_group/blocks/form/minitraining.html
base/templates/education_group/blocks/form/training_tab_content.html
base/templates/education_group/blocks/form/training_tab_identification.html

OSIS-3816 : rendering

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/learning_unit/formations.html
base/views/learning_unit.py

OSIS-3791 Modification de l'écran des inscriptions aux UEs

---

base/templates/education_group/blocks/content_default_table.html
base/templates/education_group/blocks/dropdown/identification_actions_bar.html
base/templates/education_group/blocks/form/group.html
base/templates/education_group/blocks/form/minitraining.html
base/templates/education_group/blocks/form/training_tab_content.html
base/templates/education_group/blocks/form/training_tab_identification.html

OSIS-3816 : Adapt display and remove tab if empty

---

base/templates/education_group/blocks/form/group.html
base/templates/education_group/blocks/form/minitraining.html
base/templates/education_group/blocks/form/training_tab_identification.html

OSIS-3816 : Fix little mistake

---

base/fixtures/groups.json

Pull request automatique de feature/OSIS-3710 vers DEV

[feature/OSIS-3710 => DEV] En tant qu_utilisateur, je veux avoir la possibilité de déléguer les droits de modification des AA d_une UE à des jobistes

---

base/management/commands/load_exceptions.py
base/models/__init__.py
base/models/user_group.py
base/tests/management/test_load_exceptions.py
base/tests/models/test_entity_version.py

OSIS-3744 add manage.py command to load data in DB from structured xls file

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/blocks/content_default_table.html
base/templates/education_group/blocks/form/training_tab_content.html
base/tests/views/education_groups/test_update.py
base/views/education_groups/update.py
program_management/locale/en/LC_MESSAGES/django.po
program_management/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3844 : Success messages and tooltip

---

base/templates/education_group/blocks/form/training_tab_content.html

OSIS-3844 : Edit column size

---

base/management/commands/load_extra_data_from_xls.py
base/tests/management/test_load_extra_data_from_xls.py

renamed command name to load data from xls and add 'help' arg

---

base/business/education_groups/postponement.py
base/business/utils/model.py
base/forms/education_group/training.py
base/tests/forms/education_group/test_training.py
program_management/tests/business/test_postponement.py

 OSIS-3821 Refactor check consistency on certificateAims for postponement

---

assessments/templates/online_encoding.html
assessments/templates/scores_encoding.html
assessments/templates/scores_encoding_by_learning_unit.html

Pull request automatique de hotfix/OSIS-3847 vers QA

[hotfix/OSIS-3847 => QA] Spinner bloque encodage de notes

---

base/forms/education_group/search/quick_search.py
program_management/tests/views/test_quicksearch.py

Pull request automatique de hotfix/OSIS-3819 vers QA

[hotfix/OSIS-3819 => QA] La fonction rechercher ne permet pas de trouver les formations

---

assessments/templates/online_encoding.html
assessments/templates/scores_encoding.html
assessments/templates/scores_encoding_by_learning_unit.html

Pull request automatique de hotfix/OSIS-3847 vers DEV

[WIP] [hotfix/OSIS-3847 => DEV] Spinner bloque encodage de notes

---

base/static/js/education_group/education_group_tree.js

Pull request automatique de hotfix/OSIS-3814 vers QA

[hotfix/OSIS-3814 => QA] Arbre: l_élément sélectionné dans l_arbre ne correspond pas à l_élément ouvert

---

assessments/forms/scores_responsible.py
assessments/templates/scores_responsible/list.html

Pull request automatique de hotfix/OSIS-3849 vers QA

[hotfix/OSIS-3849 => QA] Label _Sigle_ -> _Code_

---

assessments/forms/scores_responsible.py
assessments/templates/scores_responsible/list.html

Pull request automatique de hotfix/OSIS-3849 vers DEV

[hotfix/OSIS-3849 => DEV] Label _Sigle_ -> _Code_

---

base/models/enums/academic_calendar_type.py

OSIS-3515 Restore EDUCATION_GROUP_EDITION type

---

learning_unit/schema.yml

OSIS-3853 add 'organization_url' to the schema

---

learning_unit/api/serializers/learning_unit.py
learning_unit/tests/api/serializers/test_learning_unit.py

OSIS-3852 add organization_url to webservice

---

base/forms/education_group/search/quick_search.py
program_management/templates/quick_search_egy_inner.html
program_management/views/quick_search.py

OSIS-3837 Ajout de Code dans la recherche de l'arbre

---

base/forms/education_group/search/quick_search.py

OSIS-3837 Fixed bug apres triage des codes

---

.idea/sqldialects.xml

[CONFIG] add config file for sql dialects

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/layout_detail.html
base/tests/views/education_groups/test_clear_clipboard.py
base/views/education_groups/clear_clipboard.py
base/views/education_groups/detail.py
base/views/education_groups/urls.py

OSIS-3859 Add the possibility to clear clipboard (selected UE or OF)

---

base/business/education_groups/postponement.py
base/forms/education_group/training.py
base/tests/forms/education_group/test_training.py
base/tests/views/education_groups/test_update.py
base/views/education_groups/update.py

Osis 3821 Correct postponement certificate aims for program_manager + add message (error/warning)

---

base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/organization/organization_address.html

Pull request automatique de improvement/OSIS-3708 vers DEV

[improvement/OSIS-3708 => DEV] Remplacer Editer en modifier

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3874 Add translation for permission denied pgrm manager which try to edit an unauthorized education group year

---

base/locale/en/LC_MESSAGES/django.po
base/locale/en/LC_MESSAGES/djangojs.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/djangojs.po
features/6_offer_update.feature
features/steps/6_offer_update.py
program_management/locale/en/LC_MESSAGES/django.po
program_management/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3854 changed translations of 'detach' into 'remove'

---

program_management/tests/forms/test_group_element_year_form.py

OSIS-3701 Add test

---

program_management/tests/views/test_quicksearch.py

OSIS-3837 Add Test

---

base/fixtures/waffle_flags.json
base/locale/en/LC_MESSAGES/django.po
base/locale/en/LC_MESSAGES/djangojs.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/djangojs.po
base/static/js/education_group/education_group_tree.js
base/templates/education_group/blocks/dropdown/identification_actions_bar.html
base/templates/education_group/layout_detail.html
base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html
base/tests/views/education_groups/test_update.py
base/utils/cache.py
base/views/education_groups/select.py
base/views/education_groups/urls.py
program_management/locale/en/LC_MESSAGES/django.po
program_management/locale/fr_BE/LC_MESSAGES/django.po
program_management/tests/views/test_groupelementyear_create.py
program_management/views/groupelementyear_create.py
program_management/views/groupelementyear_management.py

OSIS-3855 rename 'select' to 'copy'

---

.env.example
backoffice/settings/base.py
requirements.txt
webservices/api/serializers/user.py
webservices/api/views/user.py
webservices/schema.yml
webservices/tests/api/serializers/test_user.py
webservices/tests/api/views/test_user.py
webservices/urls.py

Add user info endpoint + add CORS module 

---

base/forms/education_group/search/quick_search.py
program_management/templates/quick_search_egy_inner.html
program_management/tests/views/test_quicksearch.py
program_management/views/quick_search.py

Pull request automatique de improvement/OSIS-3837 vers DEV

[improvement/OSIS-3837 => DEV] Arbre: fonctionnalité rechercher: ajouter une recherche sur le code pour les formations

---

base/locale/fr_BE/LC_MESSAGES/django.po

OSIS-3868 Translation

---

base/locale/en/LC_MESSAGES/django.po
base/locale/en/LC_MESSAGES/djangojs.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/djangojs.po
base/static/js/education_group/education_group_tree.js
base/templates/education_group/layout_detail.html
base/tests/views/education_groups/test_detail.py
base/tests/views/education_groups/test_update.py
base/views/education_groups/detail.py
base/views/education_groups/select.py
program_management/views/groupelementyear_management.py

OSIS-3855 add new 'cut' action to tree

---

base/templates/education_group/blocks/form/training_tab_identification.html

OSIS-3886 Prevent auto-select in template if no diploma is not possible

---

base/management/commands/load_extra_data_from_xls.py

load_data_from_xls - fixed line number error print and add return type to functions

---

program_management/templates/quick_search_base.html
program_management/tests/views/test_groupelementyear_create.py
program_management/urls.py
program_management/views/groupelementyear_create.py

OSIS-2366 revert remove precheck copy selection on quick search

---

webservices/api/serializers/general_information.py
webservices/api/views/general_information.py
webservices/tests/api/views/test_general_information.py

Pull request automatique de hotfix/OSIS-3896 vers QA

[hotfix/OSIS-3896 => QA] WebService Catalogue Erreur - Module complémentaire

---

webservices/api/serializers/general_information.py
webservices/api/views/general_information.py
webservices/tests/api/views/test_general_information.py

Pull request automatique de hotfix/OSIS-3896 vers DEV

[hotfix/OSIS-3896 => DEV] WebService Catalogue Erreur - Module complémentaire

---

base/static/css/custom.css
program_management/templates/group_element_year/group_element_year_comment_inner.html

OSIS-3908 add modal-xl css component (and add it to 'attach' modal)

---

program_management/tests/views/test_groupelementyear_delete.py
program_management/views/groupelementyear_delete.py

OSIS-3909 clear clipboard when element in clipboard is detached from tree

---

base/static/js/education_group/education_group_tree.js
base/tests/views/education_groups/test_update.py
program_management/views/groupelementyear_management.py

OSIS-3913 disable 'cut' aciton if selected element has no parent

---

base/utils/cache.py
program_management/views/groupelementyear_delete.py

OSIS-3909 moved clipboard object comparison to ElementCache object

---

webservices/api/serializers/general_information.py
webservices/api/views/general_information.py
webservices/tests/api/views/test_general_information.py

Pull request automatique de hotfix/OSIS-3896 vers MASTER

[hotfix/OSIS-3896 => MASTER] WebService Catalogue Erreur - Module complémentaire

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/models/group_element_year.py
base/tests/views/education_groups/test_update.py
program_management/business/group_element_years/attach.py
program_management/business/group_element_years/management.py
program_management/locale/en/LC_MESSAGES/django.po
program_management/locale/fr_BE/LC_MESSAGES/django.po
program_management/tests/forms/test_group_element_year_form.py

OSIS-3907 fixed translations from 'attach' to 'add'

---

base/static/css/custom.css
program_management/forms/group_element_year.py
program_management/templates/group_element_year/group_element_year_comment_inner.html
program_management/tests/forms/test_group_element_year_form.py

OSIS-3908 et OSIS-3911 form template display

---

program_management/templates/group_element_year/group_element_year_comment_inner.html

OSIS-3908 adjust column block width

---

base/business/learning_units/automatic_postponement.py
base/business/utils/postponement.py
base/migrations/0486_message templates_postponements_order.py
base/tests/business/education_groups/test_automatic_postponement.py
base/tests/models/test_education_group.py
base/tests/models/test_learning_unit.py
base/tests/utils/test_send_mail.py
base/utils/send_mail.py

Osis 2977 job de report des OF

---

base/business/education_groups/perms.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/blocks/dropdown/identification_actions_bar.html
program_management/business/group_element_years/group_element_year_tree.py
program_management/locale/en/LC_MESSAGES/django.po
program_management/locale/fr_BE/LC_MESSAGES/django.po
program_management/views/groupelementyear_create.py

Osis-3921 OSI-3923 

---

program_management/forms/group_element_year.py

OSIS-2366 pep8 line too long

---

base/models/group_element_year.py
base/tests/factories/education_group_year.py
base/views/learning_unit.py
program_management/views/element_utilization.py

Pull request automatique de hotfix/OSIS-3779 vers QA

[hotfix/OSIS-3779 => QA] OF:Arbre: consultation d_une UE de 2018 dans un arbre 2019: AttributeError

---

education_group/api/serializers/learning_unit.py
education_group/api/views/learning_unit.py
education_group/tests/api/serializers/test_learning_unit.py
learning_unit/schema.yml

Pull request automatique de improvement/OSIS-3918 vers DEV

[improvement/OSIS-3918 => DEV] FicheActivite : Ajouter le code des formations au serializer

---

base/models/education_group_year.py
base/models/learning_unit_year.py

Find LUY & EGY by id in admin (for Hang)

---

backoffice/wsgi.py

IUFC-475 : Remove IUFC queue

---

base/tests/models/test_offer.py

Update ref osis_common

---

learning_unit/api/serializers/learning_unit.py
learning_unit/schema.yml
learning_unit/tests/api/serializers/test_learning_unit.py

Pull request automatique de improvement/OSIS-3916 vers DEV

[improvement/OSIS-3916 => DEV] FicheActivite : Ajouter le champ _activité d’intégration professionnelle_ au serializer

---

base/management/commands/clearcache.py
base/tests/management/test_clearcache.py

OSIS-3939 command to clear cache

---

assessments/business/score_encoding_export.py
assessments/locale/en/LC_MESSAGES/django.po
assessments/locale/fr_BE/LC_MESSAGES/django.po
assessments/tests/views/test_score_encoding.py
assessments/views/upload_xls_utils.py

Pull request automatique de hotfix/OSIS-3887 vers QA

[hotfix/OSIS-3887 => QA] Encodage des notes : problème de traduction dans le fichier Xls

---

assessments/business/score_encoding_export.py
assessments/locale/en/LC_MESSAGES/django.po
assessments/locale/fr_BE/LC_MESSAGES/django.po
assessments/tests/views/test_score_encoding.py
assessments/views/upload_xls_utils.py

Pull request automatique de hotfix/OSIS-3887 vers DEV

[hotfix/OSIS-3887 => DEV] Encodage des notes : problème de traduction dans le fichier Xls

---

base/templates/learning_unit/search/description_fiche.html

Pull request automatique de hotfix/OSIS-3959 vers QA

[hotfix/OSIS-3959 => QA] On n_arrive pas sur l_onglet _Fiche descriptive_ quand on vient de la recherche _Fiches descriptives_

---

base/templates/learning_unit/search/description_fiche.html

Pull request automatique de hotfix/OSIS-3959 vers DEV

[hotfix/OSIS-3959 => DEV] On n_arrive pas sur l_onglet _Fiche descriptive_ quand on vient de la recherche _Fiches descriptives_

---

base/business/education_groups/perms.py
base/tests/business/education_groups/test_perms.py

[hotfix/OSIS-3767 => QA] En tant que QOPA, je ne sais pas modifier les données de publicationd _offre en 2019-2020

---

base/static/css/osis.css
base/static/img/devmode.svg
base/static/img/localmode.svg
base/static/img/qamode.svg
base/static/img/testmode.svg

Pull request automatique de hotfix/OSIS-3398 vers QA

[hotfix/OSIS-3398 => QA] Le _tapis_ affichant en background l_environnement (DEV / TEST / QA) n_est pas visible sur tous les écrans

---

base/templates/education_group/blocks/dropdown/identification_actions_bar.html

Pull request automatique de hotfix/OSIS-3926 vers QA

[hotfix/OSIS-3926 => QA] Catalogue >Formation: Problème de pointeur sur certaines options du menu Actions

---

base/models/student.py
base/tests/models/test_student.py

Référence Jira : Change ref dissertation

Change Ref dissertation

---

base/templates/education_group/blocks/modal/modal_access_denied.html
program_management/locale/en/LC_MESSAGES/django.po
program_management/locale/fr_BE/LC_MESSAGES/django.po
program_management/tests/views/test_groupelementyear_delete.py
program_management/tests/views/test_groupelementyear_update.py
program_management/views/generic.py
program_management/views/groupelementyear_create.py
program_management/views/groupelementyear_delete.py
program_management/views/groupelementyear_update.py

Pull request automatique de hotfix/OSIS-3467 vers QA

[hotfix/OSIS-3467 => QA] Redirection hors modal lorsque l_utilisateur n_a pas les permissions

---

assessments/templates/admin/pgm_manager.html
base/templates/academic_actors.html

Remove useless load in template

---

program_management/business/excel.py
program_management/tests/business/test_excel.py
program_management/tests/forms/test_custom_xls_form.py
program_management/tests/views/test_excel.py

* Ajout de tests
* Refactoring

OSIS-3969 : xls des UES existantes pour une formation donnée

---

assessments/tests/views/test_scores_responsible.py
base/models/program_manager.py

Pull request automatique de hotfix/OSIS-3885 vers QA

[hotfix/OSIS-3885 => QA] Restreindre les accès du responsable parcours pour le responsable de notes

---

assessments/tests/views/test_scores_responsible.py
base/models/program_manager.py

Pull request automatique de hotfix/OSIS-3885 vers DEV

[hotfix/OSIS-3885 => DEV] Restreindre les accès du responsable parcours pour le responsable de notes

---

base/models/group_element_year.py
base/tests/models/test_group_element_year.py
education_group/api/serializers/learning_unit.py
education_group/api/views/learning_unit.py
education_group/tests/api/serializers/test_learning_unit.py
education_group/tests/api/views/test_learning_unit.py

OSIS-3960 : add boolean field to serializer educationgrouproots

---

program_management/business/excel.py
program_management/tests/business/test_excel.py

* La première ligne du fichier xls doit tj être en gras
* Ajout d'un test pour valider le point ci-dessus

OSIS-3978 : US liste xls des ues existantes dans une formation

---

learning_unit/api/serializers/summary_specification.py
learning_unit/api/views/summary_specification.py
learning_unit/tests/api/views/test_summary_specification.py

OSIS-3963 : Retrieve parent info if partim info = none

---

base/models/group_element_year.py
education_group/api/views/learning_unit.py
education_group/tests/api/views/test_learning_unit.py
education_group/tests/api/views/test_training.py

OSIS-3970 : Add filterset_class and test it

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/views/learning_achievement.py
base/views/learning_unit.py
base/views/teaching_material.py

Modifciation de traduction et de msie en forme de messages de succès
Modifications qui seront validées :
modifié :         locale/en/LC_MESSAGES/django.po
modifié :         locale/fr_BE/LC_MESSAGES/django.po
modifié :         views/learning_achievement.py
modifié :         views/learning_unit.py
modifié :         views/teaching_material.py
Référence Jira : OSIS-3991

OSIS-3991 Modification de traduction et de mise en forme messages de succès

---

webservices/api/serializers/general_information.py
webservices/api/views/general_information.py
webservices/tests/api/serializers/test_general_information.py

Pull request automatique de improvement/OSIS-3998 vers DEV

[improvement/OSIS-3998 => DEV] Web service fiche offre : envoyer le type de formation

---

base/models/group_element_year.py
base/tests/models/test_group_element_year.py
education_group/api/serializers/learning_unit.py
education_group/api/views/learning_unit.py
education_group/tests/api/serializers/test_learning_unit.py
education_group/tests/api/views/test_learning_unit.py
education_group/tests/api/views/test_training.py
learning_unit/schema.yml

OSIS-3999 : Simplify and use method to stop recursive

---

base/migrations/0057_creation_and_initialisation_of_groups.py
base/migrations/0058_add_initial_users_to_groups.py
base/migrations/0191_auto_20171122_0930.py
base/migrations/0208_create_role_executive.py

Dans l'output travis :
> Running post-migrate handlers for application sites
> Running post-migrate handlers for application dal_select2
> Running post-migrate handlers for application admin
> Running post-migrate handlers for application auth
> Running post-migrate handlers for application contenttypes
> Running post-migrate handlers for application sessions
> Running post-migrate handlers for application analytical
> Running post-migrate handlers for application osis_common
> Running post-migrate handlers for application reference
> Running post-migrate handlers for application rules_management
> Running post-migrate handlers for application base
> Running post-migrate handlers for application education_group
> Running post-migrate handlers for application learning_unit
> Running …

Verbosity level 1 for post_migrate_signal

---

base/forms/learning_unit/learning_unit_create_2.py
base/tests/forms/test_learning_unit_create_2.py

Pull request automatique de hotfix/OSIS-3988 vers QA

[hotfix/OSIS-3988 => QA] Modif gestion journalière code UE autre que cours/stage/mémoire par gestionnaire fac

---

base/templates/education_group/tab_admission_conditions.html
base/tests/views/test_education_group.py
base/views/education_groups/detail.py
webservices/api/serializers/admission_condition.py
webservices/tests/api/serializers/test_admission_condition.py

Pull request automatique de improvement/OSIS-4001 vers DEV

[improvement/OSIS-4001 => DEV] Modifier la liste des champs _condition d admission_ pour les programmes FC

---

base/business/education_groups/general_information.py
base/forms/learning_unit/search/borrowed.py
base/models/enums/education_group_types.py
base/models/group_element_year.py
base/models/learning_unit_year.py
base/tests/models/test_group_element_year.py
base/views/education_groups/detail.py
base/views/learning_unit.py
education_group/api/views/learning_unit.py
education_group/tests/api/serializers/test_learning_unit.py
education_group/tests/api/views/test_learning_unit.py
program_management/business/group_element_years/detach.py
program_management/views/element_utilization.py
program_management/views/prerequisite_read.py
program_management/views/prerequisite_update.py

Refactor OSIS-3917

---

base/forms/learning_unit/learning_unit_create_2.py
base/tests/forms/test_learning_unit_create_2.py

Pull request automatique de hotfix/OSIS-3988 vers DEV

[hotfix/OSIS-3988 => DEV] Modif gestion journalière code UE autre que cours/stage/mémoire par gestionnaire fac

---

education_group/api/views/learning_unit.py
education_group/tests/api/views/test_learning_unit.py
learning_unit/schema.yml

OSIS-3917 : Rename params

---

program_management/templates/group_element_year/group_element_year_comment_inner.html

Pull request automatique de hotfix/OSIS-4000 vers QA

[hotfix/OSIS-4000 => QA] Formation > Arbre > Copier/Couper - Coller ou Ajouter tombe en erreur pour les options: BootstrapError

---

reference/tests/management/commands/test_load_countries_continent.py
reference/tests/models/test_domain.py

reference setUpTestData

---

cms/tests/models/test_text_label.py
cms/tests/models/test_translated_text.py

Cms setUpTestData

---

program_management/templates/group_element_year/group_element_year_comment_inner.html

Pull request automatique de hotfix/OSIS-4000 vers MASTER

[hotfix/OSIS-4000 => MASTER] Formation > Arbre > Copier/Couper - Coller ou Ajouter tombe en erreur pour les options: BootstrapError

---

program_management/templates/group_element_year/group_element_year_comment_inner.html

Pull request automatique de hotfix/OSIS-4000 vers DEV

[hotfix/OSIS-4000 => DEV] Formation > Arbre > Copier/Couper - Coller ou Ajouter tombe en erreur pour les options: BootstrapError

---

assessments/tests/business/test_enrollment_state.py
assessments/tests/templatetags/test_enrollment_state.py
assessments/tests/views/test_score_encoding.py
assessments/tests/views/test_score_sheet.py
assessments/tests/views/test_upload_xls_utils.py

Assessments setuptestdata

---

rules_management/tests/test_permission_field_mixin.py

RulesManagement setUpTestData

---

program_management/tests/business/learning_units/test_prerequisite.py
program_management/tests/business/test_postponement.py
program_management/tests/forms/test_custom_xls_form.py
program_management/tests/forms/test_group_element_year_form.py
program_management/tests/views/test_groupelementyear_create.py
program_management/tests/views/test_groupelementyear_postpone.py
program_management/tests/views/test_quicksearch.py

Prog mgmt setuptestdata

---

base/business/learning_units/edition.py
base/business/learning_units/simple/deletion.py
base/models/learning_class_year.py

OSIS-4005 : Remove spaghetti code

---

base/tests/management/test_load_extra_data_from_xls.py

base_management

---

base/tests/model_forms/learning_unit/test_learning_unit.py
base/tests/model_forms/learning_unit/test_learning_unit_year.py

base_model_forms setuptestdata

---

base/tests/utils/test_notifications.py
base/tests/utils/test_send_mail.py

base utils folder

---

base/tests/templatetags/test_entity.py
base/tests/templatetags/test_model_field.py
base/tests/templatetags/test_offer_year_calendar_display.py
base/tests/templatetags/test_reference_link.py

templatetags folder

---

base/tests/business/education_groups/test_automatic_postponement.py
base/tests/business/learning_units/test_achievement.py
base/tests/business/learning_units/test_automatic_postponement.py
base/tests/business/learning_units/test_comparison.py
base/tests/business/learning_units/test_edition.py
base/tests/business/learning_units/test_perms.py
base/tests/business/learning_units/test_xls_comparison.py
base/tests/business/test_education_group.py
base/tests/business/test_entity.py
base/tests/business/test_entity_version.py
base/tests/business/test_learning_unit_proposal.py
base/tests/business/test_learning_unit_year_with_context.py
base/tests/business/test_perms.py
base/tests/business/test_proposal_xls.py
base/tests/business/test_xls.py

Base business setuptestdata

---

base/business/learning_unit_xls.py

Pour corriger une erreur pep8 dans l'improvement OSIS-3983

---

base/business/learning_units/pedagogy.py

OSIS-3914-pep8

---

base/tests/forms/learning_unit/test_common.py
base/tests/forms/learning_unit/test_learningUnitYearModelForm.py
base/tests/forms/learning_unit/test_search_form.py
base/tests/forms/learning_unit/test_simplifiedVolumeForm.py

base/tests/forms/learning_unit/* setUpTestData

---

base/tests/forms/education_group/test_achievement.py
base/tests/forms/education_group/test_common.py
base/tests/forms/education_group/test_coorganization.py
base/tests/forms/education_group/test_group.py
base/tests/forms/education_group/test_mini_training.py
base/tests/forms/education_group/test_training.py

base/tests/forms/education_group/* setUpTestData

---

base/tests/forms/test_academic_calendar.py
base/tests/forms/test_education_groups.py
base/tests/forms/test_education_groups_administrative_data.py
base/tests/forms/test_external_learning_unit.py
base/tests/forms/test_learning_achievement.py
base/tests/forms/test_learning_unit_partim.py
base/tests/forms/test_learning_unit_pedagogy.py
base/tests/forms/test_learning_unit_proposal.py
base/tests/forms/test_learning_unit_specifications.py
base/tests/forms/test_search_tutor.py
base/tests/forms/test_validation_rule_mixin.py
base/tests/forms/test_warning_mixin.py

base/tests/forms/*.py setUpTestData

---

base/tests/views/learning_units/external/test_create.py
base/tests/views/learning_units/external/test_update.py
base/tests/views/learning_units/proposals/test_creation.py
base/tests/views/learning_units/test_formations_tab.py

base/tests/views/learning_units/* setUpTestData

---

base/tests/views/test_academic_calendar.py
base/tests/views/test_common.py
base/tests/views/test_education_group.py
base/tests/views/test_entity.py
base/tests/views/test_filter.py
base/tests/views/test_institution.py
base/tests/views/test_learning_achievement.py
base/tests/views/test_learning_unit.py
base/tests/views/test_learning_unit_deletion.py
base/tests/views/test_learning_unit_proposal.py
base/tests/views/test_my_osis.py
base/tests/views/test_offer.py
base/tests/views/test_organization.py
base/tests/views/test_teaching_material.py

base/tests/views/* setUpTestData

---

base/tests/views/education_groups/achievement/test_create.py
base/tests/views/education_groups/achievement/test_detail.py
base/tests/views/education_groups/achievement/test_update.py
base/tests/views/education_groups/test_delete.py
base/tests/views/education_groups/test_detail.py
base/tests/views/education_groups/test_publication_contact.py
base/tests/views/education_groups/test_select_education_group_type.py

base/tests/views/education_groups/* setUpTestData

---

base/static/js/education_group/education_group_tree.js
base/static/js/osis.js

Pull request automatique de hotfix/OSIS-3920 vers QA

[hotfix/OSIS-3920 => QA] Presse-papier: la corbeille ne s_affiche pas

---

base/static/js/education_group/education_group_tree.js
base/static/js/osis.js

Pull request automatique de hotfix/OSIS-3920 vers DEV

[hotfix/OSIS-3920 => DEV] Presse-papier: la corbeille ne s_affiche pas

---

base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/blocks/contacts_general_informations.html
base/templates/education_group/tab_general_informations.html
base/views/education_groups/publication_contact.py

Pull request automatique de hotfix/OSIS-4016 vers QA

[hotfix/OSIS-4016 => QA] Formation > Informations Générales > Ajout d_un contact > perte du focus sur la zone Contacts

---

education_group/api/views/learning_unit.py
education_group/api/views/training.py
learning_unit/api/views/learning_unit.py

OSIS-4030 : Use booleanfilter

---

assessments/locale/en/LC_MESSAGES/django.po
assessments/locale/fr_BE/LC_MESSAGES/django.po
assessments/templates/scores_encoding_by_learning_unit.html

Pull request automatique de hotfix/OSIS-4031 vers QA

[hotfix/OSIS-4031 => QA] Ecrans d_encodage des notes : traductions

---

assessments/locale/en/LC_MESSAGES/django.po
assessments/locale/fr_BE/LC_MESSAGES/django.po
assessments/templates/scores_encoding_by_learning_unit.html

Pull request automatique de hotfix/OSIS-4031 vers DEV

[hotfix/OSIS-4031 => DEV] Ecrans d_encodage des notes : traductions

---

learning_unit/api/views/attribution.py

Pull request automatique de technical/OSIS-4054 vers DEV

[technical/OSIS-4054 => DEV] Amélioration performance endpoint /attributions

---

attribution/tests/views/test_attribution.py
attribution/views/attribution.py
base/templates/template_nav_header.html
base/tests/business/test_perms.py
base/tests/views/learning_units/test_formations_tab.py
base/tests/views/test_learning_unit.py
base/tests/views/test_learning_unit_edition.py
base/tests/views/test_learning_unit_pedagogy.py
base/views/learning_unit.py
base/views/learning_units/detail.py
base/views/learning_units/pedagogy/read.py
base/views/learning_units/update.py

Pull request automatique de hotfix/OSIS-3958 vers QA

[hotfix/OSIS-3958 => QA] On perd l_onglet courant quand on passe d_une UE à l_autre avec les flèches

---

base/models/learning_achievement.py
base/templates/learning_unit/achievement_edit.html
base/tests/models/test_learning_achievement.py
base/tests/views/test_learning_achievement.py
base/views/learning_achievement.py

OSIS-4073 report learning achievements operations + display consistency_id

---

base/forms/education_groups.py
base/tests/views/education_groups/test_search.py

- Simplification du code
- escape des squares brackets dans les query

OSIS-4060 :  utiliser les regex dans les recherches OF

---

base/templates/blocks/navbar_top.html
base/templates/institution.html

Pull request automatique de hotfix/OSIS-3841 vers QA

[hotfix/OSIS-3841 => QA] Problème d_affichage des organisations dans Osis

---

base/templates/blocks/navbar_top.html
base/templates/institution.html

Pull request automatique de hotfix/OSIS-3841 vers DEV

[hotfix/OSIS-3841 => DEV] Problème d_affichage des organisations dans Osis

---

attribution/__init__.py
base/__init__.py
base/apps.py
cms/__init__.py
education_group/__init__.py
learning_unit/__init__.py
program_management/__init__.py
reference/__init__.py
rules_management/__init__.py

Pull request automatique de hotfix/OSIS-4068 vers QA

[WIP] [hotfix/OSIS-4068 => QA] (203552, 203751, 203938) Liaison person<-->user manquante

---

attribution/__init__.py
base/__init__.py
base/apps.py
cms/__init__.py
education_group/__init__.py
learning_unit/__init__.py
program_management/__init__.py
reference/__init__.py
rules_management/__init__.py

Pull request automatique de hotfix/OSIS-4068 vers MASTER

Release 2.3.2

---

attribution/__init__.py
base/__init__.py
base/apps.py
cms/__init__.py
education_group/__init__.py
learning_unit/__init__.py
program_management/__init__.py
reference/__init__.py
rules_management/__init__.py

Pull request automatique de hotfix/OSIS-4068 vers DEV

[hotfix/OSIS-4068 => DEV] (203552, 203751, 203938) Liaison person<-->user manquante

---

base/templates/learning_unit/specifications_all.html

OSIS-4096 truncate long learning achievement code_name

---

base/tests/views/test_learning_achievement.py
base/views/learning_achievement.py

OSIS-4094 get last consistency_id among all learning unit years when creating an achievement

---

base/migrations/0494_auto_20200108_1213.py

[to OSIS-3882] transform runsql to runpython for altering code_name

---

base/templates/learning_unit/specifications_all.html
base/tests/views/test_learning_unit.py
base/views/learning_unit.py

OSIS-4129 Display en achievements even if no fr counterpart

---

base/static/css/custom.css
base/static/js/osis.js

Pull request automatique de hotfix/OSIS-4025 vers QA

[hotfix/OSIS-4025 => QA] Arbre déplié : fin cachée par le bandeau

---

assessments/business/score_encoding_list.py
assessments/locale/en/LC_MESSAGES/django.po
assessments/locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OSIS-4078 vers QA

[hotfix/OSIS-4078 => QA] injection excel avec une note décimale, message d_erreur pas traduit

---

backoffice/settings/base.py

Pull request automatique de hotfix/OSIS-4147 vers QA

[hotfix/OSIS-4147 => QA] les images ne sont pas conservées dans l_éditeur de texte

---

program_management/business/excel.py

Pull request automatique de hotfix/OSIS-4152 vers QA

[hotfix/OSIS-4152 => QA] OF > Export Liste de UE de la formation > les crédits ne devraient pas s_afficher avec des exposants (1E+1)

---

program_management/business/excel.py

Pull request automatique de hotfix/OSIS-4152 vers DEV

[hotfix/OSIS-4152 => DEV] OF > Export Liste de UE de la formation > les crédits ne devraient pas s_afficher avec des exposants (1E+1)

---

base/tests/business/test_perms.py
program_management/business/excel.py
program_management/business/utils.py
program_management/forms/custom_xls.py
program_management/locale/en/LC_MESSAGES/django.po
program_management/locale/fr_BE/LC_MESSAGES/django.po
program_management/tests/business/test_excel.py

Osis 4164  Amelioration du rendu des richtext dans les colonnes relatives au cahier des charges et à la fiche descriptive

---

attribution/business/attribution_json.py
attribution/tests/business/test_attribution_json.py

Pull request automatique de hotfix/OSIS-4162 vers QA

[WIP] [hotfix/OSIS-4162 => QA] Corrections/amélioration suite au test de la candidature en ligne

---

attribution/business/attribution_json.py
attribution/tests/business/test_attribution_json.py

Pull request automatique de hotfix/OSIS-4162 vers DEV

[hotfix/OSIS-4162 => DEV] Corrections/amélioration suite au test de la candidature en ligne

---

program_management/business/utils.py

OSIS-4182 : Chaine de caractères étrange dans certaines colonnes

---

program_management/business/excel.py
program_management/tests/business/test_excel.py

OSIS-4183 : Garder l'ordre des ues dans la liste xls

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/blocks/button/help_search_tooltip.html
base/tests/business/test_perms.py
base/tests/views/education_groups/test_search.py

OSIS-4173 : Adapter les tooltips pour ne mentionner que ^et $

---

base/forms/learning_unit/external_learning_unit.py
base/forms/learning_unit/learning_unit_create_2.py
base/tests/forms/test_learning_unit_postponement.py
program_management/tests/business/test_excel.py

Pull request automatique de hotfix/OSIS-4157 vers MASTER

[WIP] [hotfix/OSIS-4157 => MASTER] Dans les UES, interdire toute modification des champs relatifs aux attributions

---

base/migrations/0499_auto_20200128_1134.py

Script de population des données

---

learning_unit/models/learning_class_year.py

LearningClassYear : add LUY acronym into search fields

---

base/tests/views/education_groups/test_publication_contact.py
base/views/education_groups/publication_contact.py

[hotfix/OSIS-4134 => DEV] Formation > Informations Générales > Modifier ou Supprimer un contact: perte du focus sur la zone Contacts

---

assessments/locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OSIS-4171 vers QA

[hotfix/OSIS-4171 => QA] Faute de frappe dans modale d_injection des notes

---

base/tests/business/test_perms.py

Pull request automatique de hotfix/OSIS-4167 vers QA

[hotfix/OSIS-4167 => QA] Test qui plante aléatoirement dans les tests unitaires

---

base/tests/views/education_groups/test_update.py
base/views/education_groups/update.py

Pull request automatique de hotfix/OSIS-4187 vers QA

[hotfix/OSIS-4187 => QA] impossible de modifier un groupement _R_ sans contenu

---

base/tests/views/education_groups/test_update.py
base/views/education_groups/update.py

Pull request automatique de hotfix/OSIS-4187 vers DEV

[hotfix/OSIS-4187 => DEV] impossible de modifier un groupement _R_ sans contenu

---

education_group/api/views/group_element_year.py
education_group/tests/api/views/test_group_element_year.py

OSIS-4217 : accept lowercase acronym

---

base/views/education_groups/update.py
rules_management/enums.py

OSIS-3961 reduce _common_success_redirect complexity

---

assessments/forms/scores_responsible.py
assessments/locale/en/LC_MESSAGES/django.po
assessments/locale/fr_BE/LC_MESSAGES/django.po
assessments/templates/scores_responsible/list.html
assessments/tests/views/test_scores_responsible.py
base/forms/learning_unit/search/simple.py

Pull request automatique de improvement/OSIS-3850 vers DEV

[improvement/OSIS-3850 => DEV] Gestion responsables de notes : amélioration de l_écran de recherche 

---

education_group/api/serializers/education_group_title.py
education_group/api/serializers/group.py
education_group/api/serializers/learning_unit.py
education_group/api/serializers/mini_training.py
learning_unit/api/serializers/component.py
learning_unit/api/serializers/learning_unit.py
webservices/api/serializers/achievement.py
webservices/api/serializers/admission_condition.py
webservices/api/serializers/admission_condition_line.py
webservices/api/serializers/contacts.py
webservices/api/serializers/general_information.py
webservices/api/serializers/section.py
webservices/business.py
webservices/tests/api/serializers/test_general_information.py
webservices/tests/api/serializers/test_section.py

Release 2.4.5

---

education_group/api/serializers/education_group_title.py
education_group/api/serializers/group.py
education_group/api/serializers/learning_unit.py
education_group/api/serializers/mini_training.py
learning_unit/api/serializers/component.py
learning_unit/api/serializers/learning_unit.py
webservices/api/serializers/achievement.py
webservices/api/serializers/admission_condition.py
webservices/api/serializers/admission_condition_line.py
webservices/api/serializers/contacts.py
webservices/api/serializers/general_information.py
webservices/api/serializers/section.py
webservices/business.py
webservices/tests/api/serializers/test_general_information.py
webservices/tests/api/serializers/test_section.py

[WIP][DEV] hotfix/OSIS-4199 : Get Evaluation section (WS) For IUFC

---

education_group/api/serializers/education_group_title.py
education_group/api/serializers/group.py
education_group/api/serializers/learning_unit.py
education_group/api/serializers/mini_training.py
learning_unit/api/serializers/component.py
learning_unit/api/serializers/learning_unit.py
webservices/api/serializers/achievement.py
webservices/api/serializers/admission_condition.py
webservices/api/serializers/admission_condition_line.py
webservices/api/serializers/contacts.py
webservices/api/serializers/general_information.py
webservices/api/serializers/section.py
webservices/business.py
webservices/tests/api/serializers/test_general_information.py
webservices/tests/api/serializers/test_section.py

[QA] hotfix/OSIS-4199 : Get Evaluation section (WS) For IUFC

---

webservices/api/serializers/section.py
webservices/tests/api/serializers/test_section.py

Release 2.4.7

---

webservices/api/serializers/section.py
webservices/tests/api/serializers/test_section.py

[hotfix/OSIS-4221 => QA] Correction du WS de reddot 

---

webservices/api/serializers/section.py
webservices/tests/api/serializers/test_section.py

[hotfix/OSIS-4221 => DEV] Correction du WS de reddot 

---

rules_management/fixtures/field_reference.json

context: training encoding prgm period
OSIS-3961

OSIS-3961 disable field end_year for faculty managers in mini-training

---

assessments/templates/online_encoding_form.html

Pull request automatique de hotfix/OSIS-1729 vers QA

[hotfix/OSIS-1729 => QA] Problème d_affichage du popover (tronqué sur la gauche)

---

base/static/js/education_group/education_group_tree.js
base/templates/education_group/layout_detail.html
base/templates/template_nav_header.html

Pull request automatique de improvement/OSIS-4026 vers DEV

[improvement/OSIS-4026 => DEV] Lors d_un clic dans l_arbre, ne pas revenir en haut de l_arbre

---

base/views/learning_units/search/common.py
program_management/views/quick_search.py

Pull request automatique de hotfix/OSIS-4202 vers QA

[hotfix/OSIS-4202 => QA] Perte du résultat de la recherche quand on utilise le filtre _statut_ Actif, inactif 

---

base/views/learning_units/search/common.py
program_management/views/quick_search.py

Pull request automatique de hotfix/OSIS-4202 vers DEV

[hotfix/OSIS-4202 => DEV] Perte du résultat de la recherche quand on utilise le filtre _statut_ Actif, inactif 

---

base/business/education_groups/perms.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/education_group/blocks/form/group.html
base/templates/education_group/blocks/form/minitraining.html
base/tests/business/education_groups/test_perms.py
base/views/education_groups/update.py
rules_management/fixtures/field_reference.json

OSIS-4229 adapt strategy to show tabs to groups and mini-trainings 

---

base/business/education_groups/perms.py
base/forms/education_group/common.py
base/forms/education_group/training.py
rules_management/fixtures/field_reference.json

[To OSIS-3961] fix multiple roles perms

---

base/business/education_groups/perms.py
base/forms/education_group/common.py

Référence Jira : OSIS-3961 fix

OSIS-3961 fix pgm manager eligible education group

---

base/business/education_groups/perms.py
base/tests/business/education_groups/test_perms.py
base/tests/forms/education_group/test_common.py
base/tests/forms/education_group/test_group.py
base/tests/forms/education_group/test_mini_training.py
base/tests/forms/education_group/test_training.py

OSIS-3961 add tests to implemented fix for pgm manager eligible education group

---

webservices/api/serializers/general_information.py
webservices/api/serializers/section.py
webservices/tests/api/serializers/test_section.py

Release 2.5.2

---

base/forms/learning_unit/learning_unit_create.py
base/forms/learning_unit/learning_unit_partim.py
base/tests/forms/test_learning_unit_partim.py

Pull request automatique de hotfix/OSIS-4212 vers QA

[hotfix/OSIS-4212 => QA] En tant que gestionnaire central ou facultaire, quand je créé un partim, la date de fin doit être celle de l_UE

---

program_management/business/excel_ue_in_of.py

OSIS-4262 : Inverser les intitulés des colonnes crédits

---

base/forms/education_group/common.py
base/tests/forms/education_group/test_common.py

OSIS-4259 fix bug with entity select choices for faculty_managers outside their faculty

---

base/views/education_groups/update.py

OSIS-4260 fix bug occuring when a mini training groupelementyear formset is hidden

---

learning_unit/schema.yml

[QA] OSIS-4256 : Fix Learning unit schema

---

base/forms/education_group/common.py
base/tests/forms/education_group/test_common.py
base/tests/forms/education_group/test_group.py
base/tests/forms/education_group/test_mini_training.py
base/tests/forms/education_group/test_training.py
base/views/education_groups/create.py

OSIS-4261 ensure displaying fields/tabs in creation context

---

education_group/schema.yml

Pull request automatique de hotfix/OSIS-4255 vers QA

[WIP] [hotfix/OSIS-4255 => QA] Corriger le schéma du WS FicheOffre

---

base/business/education_groups/perms.py
base/tests/business/education_groups/test_perms.py

OSIS-3961 fix bug program manager perms

---

base/business/learning_units/xls_comparison.py
base/tests/business/learning_units/test_xls_comparison.py

hotfix/OSIS-4266 correct unittest +add test

---

education_group/api/serializers/group_element_year.py
education_group/schema.yml
education_group/tests/api/serializers/test_group_element_year.py
program_management/business/group_element_years/group_element_year_tree.py
webservices/api/serializers/general_information.py

[WS] OSIS-4319 :  FicheOffre - Tree Changes

---

base/models/learning_component_year.py

OSIS-4266-4 correct comparaison between None and int

---

base/tests/views/learning_units/test_search.py
base/views/learning_units/search/common.py

OSIS-4330 : Add 'no result' warning in UE search

---

base/forms/learning_unit/edition.py
base/tests/views/test_learning_unit_proposal.py

Pull request automatique de hotfix/OSIS-4363 vers MASTER

Release 2.6.1

---

base/static/js/learning_unit_creation.js

OSIS-4213 : Remove duplicate error message

---

education_group/api/serializers/training.py
education_group/schema.yml
education_group/tests/api/serializers/test_training.py

OSIS-4372 : Add domain info into serializer/schema and tests

---

base/business/learning_units/xls_comparison.py
base/business/proposal_xls.py
base/models/learning_component_year.py
base/templates/learning_unit/components_identification.html
base/tests/business/learning_units/test_xls_comparison.py
base/tests/business/test_proposal_xls.py
base/tests/views/learning_units/test_search.py
base/views/learning_units/search/common.py
education_group/api/serializers/training.py
education_group/schema.yml
education_group/tests/api/serializers/test_training.py

DEV --> feature/OSIS-4254

---

base/forms/learning_unit/learning_unit_create.py
base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/templates/learning_unit/blocks/titles.html
base/templates/learning_unit/identification.html
base/tests/forms/test_learning_unit_postponement.py
base/tests/model_forms/learning_unit/test_learning_unit_year.py

OSIS-4361 rename label + adapt templates

---

base/locale/en/LC_MESSAGES/django.po
base/locale/fr_BE/LC_MESSAGES/django.po
base/tests/views/test_learning_unit.py
base/views/learning_achievement.py
base/views/learning_unit.py
base/views/learning_units/pedagogy/update.py

Osis 4237 Update specifications and achievements message + tests

---

base/static/css/osis.css
base/templates/learning_unit/blocks/titles.html
base/templates/learning_unit/identification.html
base/templatetags/learning_unit.py

OSIS-4361 correct template after test

---

education_group/schema.yml

OSIS-4370 Write openapi schema for mini_training list

---

backoffice/settings/rest_framework/filters.py
education_group/api/serializers/mini_training.py
education_group/api/url_v1.py
education_group/api/views/mini_training.py
education_group/schema.yml
education_group/tests/api/serializers/test_mini_training.py
education_group/tests/api/views/test_mini_training.py

Osis 4371 Add MiniTraining List view with filtering

---

base/models/group_element_year.py
base/tests/models/test_group_element_year.py

Feature/osis 4311 -> DEV

---

assessments/views/score_sheet.py
base/business/education_groups/create.py
base/forms/learning_achievement.py
base/models/academic_calendar.py
base/models/education_group_year.py
base/models/entity.py
base/models/learning_achievement.py
base/models/person.py
base/models/proposal_learning_unit.py
base/models/structure.py
base/models/utils/utils.py
base/views/academic_calendar.py
base/views/education_groups/create.py
base/views/learning_achievement.py
base/views/learning_units/detail.py
program_management/views/groupelementyear_management.py
program_management/views/prerequisite_read.py
webservices/business.py

deprecate get_object_or_none

---

requirements.txt

update django to 2.2.10

---

learning_unit/api/views/learning_achievement.py

OSIS-4400 : Get correctly Learning Achievements

---

learning_unit/api/views/learning_achievement.py

Pull request automatique de hotfix/OSIS-4400 vers QA

[hotfix/OSIS-4400 => QA] [WS] FicheActivite : il manque des achievements sans code

---

base/static/js/education_group/education_group_tree.js
base/static/js/osis.js

[OSIS-4366 => hotfix/OSIS-4327] show better tree when footer on page without scroll

---

base/static/css/osis.css

[OSIS-4406 => feature/OSIS-3933] correct css tab to 95%

---

base/static/js/osis.js
base/static/js/osis_datatable.js
base/utils/search.py

Refs https://github.com/uclouvain/osis-partnership/pull/157

Improve datatable handling

---

base/forms/learning_unit/search/service_course.py
base/templates/education_group/blocks/header.html
base/templates/education_group/update_groups.html
base/templates/education_group/update_minitrainings.html
base/templates/education_group/update_trainings.html
base/templates/learning_unit/layout_detail.html
base/templates/learning_unit/learning_unit_layout.html
base/templates/learning_unit/proposal/create_suppression.html
base/templates/learning_unit/proposal/update_suppression.html
base/templates/learning_unit/simple/update_end_date.html
base/tests/views/education_groups/achievement/test_detail.py
base/tests/views/education_groups/test_detail.py
base/tests/views/education_groups/test_publication_contact.py
base/tests/views/learning_units/test_search.py
base/tests/views/test_education_group.py
base/views/education_groups/achievement/detail.py
base/views/education_groups/detail.py
base/views/education_groups/search.py
base/views/learning_units/search/common.py
learning_unit/api/views/learning_achievement.py

Fix issues on osis 4203

---

base/static/css/osis.css
base/templates/learning_unit/blocks/titles.html
base/templates/learning_unit/identification.html

OSIS-4406 change indent to box

---

base/templatetags/navigation.py
base/tests/templatetags/test_navigation.py
base/tests/utils/test_db.py
base/tests/views/education_groups/test_publication_contact.py
base/tests/views/learning_units/test_search.py
base/tests/views/test_education_group.py
base/utils/db.py

Fix template with descending ordering

---

base/static/js/learning_unit_creation.js

OSIS-4213 : Find and remove all help-block block

---

base/templates/learning_unit/blocks/titles.html
base/templates/learning_unit/identification.html

OSIS-4406 last modif for template?

---

base/business/learning_units/edition.py

OSIS-4218 : Do not look to end_year proposal if not consolidated

---

assessments/templatetags/score_justification_disabled_status.py

OSIS-4373 : Correction pep08

---

base/scripts/generate_11_ba_from_1_ba.py
base/tests/scripts/test_generate_11_ba_from_1_ba.py

OSIS-4404 Script to create 11BA from 1BA.
