uclouvain/osis

backoffice/wsgi.py
=> IUFC-604 : Retrieve injection code

program_management/business/group_element_years/group_element_year_tree.py
=> OSIS-4177-pep8

assessments/templates/scores_encoding.html, assessments/tests/views/test_score_encoding.py
Pull request automatique de hotfix/OSIS-1716 vers QA
=> [hotfix/OSIS-1716 => QA] En tant que prof, encodage des notes > Tableaux de bord > perte du filtre sur la formation

education_group/schema.yml
=> OSIS-4419 : Fix schema

base/scripts/generate_11_ba_from_1_ba.py, base/tests/scripts/test_generate_11_ba_from_1_ba.py
=> OSIS-4320 Update titles content

base/templates/learning_unit/blocks/form/search_form_learning_unit.html, base/templatetags/navigation.py
Pull request automatique de hotfix/OSIS-4459 vers MASTER
=> [WIP] [hotfix/OSIS-4459 => MASTER] Bug recherche UE entité attribution manquante

program_management/ddd/business_types.py, program_management/ddd/domain/program_tree_version.py, program_management/tests/ddd/domain/test_program_tree.py, program_management/tests/ddd/domain/test_program_tree_version.py
=> OSIS-4358 add new ProgramTreeVersion domain object

.env.example, backoffice/settings/base.py, requirements.txt
=> Remove unused library on OSIS

osis_role/README.md
=> Writing documentation on OSIS Role module

base/templates/learning_unit/blocks/form/search_form_learning_unit.html, base/tests/views/learning_units/test_search.py, base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/search/common.py
=> OSIS-4460 fix display of borrowing faculty form field

program_management/ddd/domain/node.py, program_management/ddd/domain/prerequisite.py, program_management/ddd/repositories/load_node.py, program_management/ddd/repositories/load_prerequisite.py, program_management/ddd/validators/_attach_finality_end_date.py, program_management/ddd/validators/_attach_option.py, program_management/serializers/node_view.py, program_management/serializers/program_tree_view.py, program_management/tests/ddd/domain/test_link.py, program_management/tests/ddd/domain/test_node.py, program_management/tests/ddd/domain/test_prerequisite.py, program_management/tests/ddd/factories/node.py, program_management/tests/ddd/repositories/test_load_tree.py, program_management/tests/ddd/repositories/test_persist_tree.py, program_management/tests/ddd/validators/test_attach_finality_end_date.py, program_management/tests/ddd/validators/test_attach_option.py, program_management/tests/forms/tree/test_detach.py, program_management/tests/serializers/test_node_view.py, program_management/tests/serializers/test_program_tree_view.py, program_management/tests/views/tree/test_attach.py, program_management/tests/views/tree/test_detach.py
=> OSIS-4469 fixed Node representation in Tree and renamed Node.acronym to Node.code

base/fixtures/groups.json
A merger après :  https://github.com/uclouvain/osis-continuing-education/pull/401
IUFC-645 + 643 + 632
=> OSIS-4437 Rename permission of IUFC in  groups.json + Update Ref Continuing Education

base/templates/learning_unit/blocks/form/search_form_learning_unit.html, base/tests/views/learning_units/test_search.py, base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/search/common.py
Pull request automatique de hotfix/OSIS-4460 vers MASTER
=> [hotfix/OSIS-4460 => MASTER] La faculté emprunteuse a disparu de l_onglet « Cours emprunté »

education_group/schema.yml
=> OSIS-4398 : Fix schema.yml

base/models/group_element_year.py, base/tests/models/test_group_element_year.py, base/tests/views/test_education_group.py, education_group/api/views/learning_unit.py, education_group/tests/api/views/test_learning_unit.py, requirements.txt
=> OSIS-4310 : Filter finality and get root

base/templates/learning_unit/blocks/form/form_external.html, base/templates/learning_unit/identification.html, base/templates/learning_unit/learning_unit_layout.html, base/templates/learning_unit/simple/creation.html
=> OSIS-4487 : UE: Ajouter le champs "autre remarque" pour les UE externes

osis_role/contrib/models.py, osis_role/tests/contrib/test_models.py
=> OSIS-4449 create EntityRoleModel

education_group/contrib/models/education_group_role.py, education_group/tests/contrib/models/test_education_group_role.py
=> OSIS-4450 create EducationGroupRoleModel

base/templates/layout.html
- Empêcher de fermer les modals autrement qu'en cliquant sur annuler ou enregistrer
=> OSIS-4375 Empêcher de fermer les modals autrement qu'en cliquant sur annuler ou enregistrer

base/fixtures/groups.json, base/templates/learning_unit/blocks/form/form_external.html, base/templates/learning_unit/identification.html, base/templates/learning_unit/learning_unit_layout.html, base/templates/learning_unit/simple/creation.html
Pull request automatique de feature/OSIS-4222 vers DEV
=> [feature/OSIS-4222 => DEV] UE: Ajouter le champs _autre remarque_ pour les UE externes

.env.example, backoffice/settings/base.py, osis_role/README.md
=> OSIS-4451 Add AUTHENTICATION_BACKENDS .env variable

program_management/business/excel.py, program_management/ddd/domain/link.py, program_management/ddd/domain/node.py, program_management/ddd/domain/program_tree.py, program_management/ddd/repositories/load_node.py, program_management/ddd/repositories/load_tree.py, program_management/tests/business/test_excel.py, program_management/tests/business/test_excel_ue_in_of.py, program_management/tests/ddd/domain/test_link.py, program_management/tests/ddd/domain/test_node.py, program_management/tests/ddd/domain/test_program_tree.py, program_management/tests/ddd/factories/link.py, program_management/tests/ddd/factories/node.py, program_management/tests/ddd/repositories/test_load_tree.py
=> OSIS-4472 usage of 'ddd' to load excel 'is_prerequisite' file

base/forms/learning_unit/edition.py, base/tests/views/test_learning_unit_proposal.py
=> OSIS-4445 block proposal suppression date to year N-1 from LU + test

base/templates/layout.html
Pull request automatique de hotfix/OSIS-4375 vers QA
=> [hotfix/OSIS-4375 => QA] Modal qui se ferme lors d_un clique à l_extérieur de celui-ci

base/templatetags/education_group_pdf.py
- Ajouter le symbole lorsque l'UE a des pré-requis dans le PDF
=> OSIS-4444 Ajouter le symbole lorsque l'UE a des pré-requis dans le PDF

assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, base/fixtures/message_template.json, base/utils/send_mail.py
=> OSIS-4489 Erreurs de traduction + fautes d'orthographe

base/business/learning_units/xls_educational_information_and_specifications.py
Pull request automatique de hotfix/OSIS-4500 vers QA
=> [hotfix/OSIS-4500 => QA] Erreur inattendue génération liste UE avec fiche desc et cahier des charges

base/business/learning_units/xls_educational_information_and_specifications.py
Pull request automatique de hotfix/OSIS-4500 vers MASTER
=> [hotfix/OSIS-4500 => MASTER] Erreur inattendue génération liste UE avec fiche desc et cahier des charges

base/business/learning_units/xls_educational_information_and_specifications.py
Pull request automatique de hotfix/OSIS-4500 vers DEV
=> [hotfix/OSIS-4500 => DEV] Erreur inattendue génération liste UE avec fiche desc et cahier des charges

education_group/api/serializers/group_element_year.py, education_group/schema.yml, education_group/tests/api/serializers/test_group_element_year.py
=> OSIS-4399 : Add missing datas + adapt schemas

base/templates/education_group/blocks/form/training_certificate.html, base/templates/education_group/blocks/modal/modal_publication_contact_entity_edit_inner.html, base/templates/education_group/tab_edit_administrative_data.html, base/templates/learning_unit/blocks/form/volumes_management_form.html, base/templates/learning_unit/blocks/modal/modal_back_to_initial.html, base/templates/learning_unit/blocks/modal/modal_confirm_delete.html, base/templates/learning_unit/blocks/modal/modal_consolidate.html, base/templates/learning_unit/blocks/modal/modal_force_state.html, base/templates/learning_unit/blocks/modal/modal_pedagogy_edit.html, base/templates/learning_unit/teaching_material/modal_delete.html, base/templates/learning_unit/teaching_material/modal_edit.html, base/templates/organization/organization_address_form.html
OSIS-4415 Uniformisation des boutons principaux à droite
Référence Jira : OSIS-4415
=> OSIS-4415 Uniformisation des boutons principaux à droite

base/tests/views/test_education_group.py, program_management/ddd/domain/node.py, program_management/ddd/domain/program_tree.py, program_management/ddd/repositories/load_node.py, program_management/forms/prerequisite.py, program_management/tests/ddd/domain/test_program_tree.py, program_management/tests/ddd/factories/node.py, program_management/tests/forms/test_prerequisite.py, program_management/views/generic.py, program_management/views/prerequisite_update.py
=> OSIS-4486 ProgramTree to fetch permitted codes as prerequisite

education_group/tests/contrib/test_admin.py, education_group/tests/contrib/test_models.py, osis_role/tests/contrib/test_admin.py
=> OSIS-4503 Writing test on RoleAdmin interface

education_group/api/serializers/group.py, education_group/api/serializers/mini_training.py, education_group/api/serializers/training.py, education_group/api/serializers/utils.py, education_group/schema.yml, education_group/tests/api/serializers/test_group.py, education_group/tests/api/serializers/test_mini_training.py, education_group/tests/api/serializers/test_training.py, education_group/tests/api/views/test_group.py, education_group/tests/api/views/test_mini_training.py, education_group/tests/api/views/test_training.py
=> OSIS-4504 : Add faculty entity to serializers

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/identification.html, base/templatetags/learning_unit.py
- Modification d'interface pour les titres des UEs (Full et Partim)
Référence Jira : OSIS-4498
=> OSIS-4498 Modification d'interface pour les titres des UEs (Full et Partim)

base/templates/learning_unit/blocks/form/search_form_external_learning_unit.html, base/templates/learning_unit/blocks/form/search_form_learning_unit.html, base/templates/learning_unit/blocks/form/search_form_summary_list.html
- Aggrandissement des champs status et quadrimestre pour une cohérence visuelle sur petit ecran (1024X862)
Référence Jira : OSIS-3379
=> OSIS-3379 - Aggrandissement des champs status et quadrimestre pour une cohérence visuelle sur petit ecran (1024X862)

base/fixtures/groups.json
=> OP-342 Add partnership role in groups.json

base/business/learning_units/perms.py, base/forms/learning_unit_specifications.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/test_learning_unit_deletion.py, base/tests/business/test_perms.py
=> OSIS-4318 attribution -> appication

base/static/css/styles.css, base/templates/layout.html, base/templatetags/learning_unit.py, base/tests/templatetags/test_learning_unit.py, education_group/api/serializers/group_element_year.py, education_group/tests/api/serializers/test_group_element_year.py
=> [QA][WS] Quick fix

.env.example
=> Test Integ

.env.example
Reverts uclouvain/osis#7395 DEV-123
=> Revert "Test Integ"

base/tests/utils/test_send_mail.py, base/utils/send_mail.py
=> OSIS-4489 : Ajout de qq tests

base/tests/utils/test_send_mail.py
=> OSIS-4489 : ajout de tests

base/forms/learning_achievement.py, base/views/learning_achievement.py
=> OSIS-4402 resolve issue when save AA french and english shift

education_group/schema.yml
=> OSIS-4521 : Fix schema Tree

base/models/abstracts/abstract_achievement.py, base/models/learning_achievement.py
=> OSIS-4402-2 add pertinent info in admin list for AA

education_group/schema.yml
=> OSIS-4521 : Add spaces

program_management/ddd/repositories/load_tree.py, program_management/serializers/node_view.py, program_management/tests/ddd/repositories/test_load_tree.py
=> OSIS-4470 3*d : add program tree load performance and fixed case 2 nodes have same id

assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, base/tests/utils/test_send_mail.py, base/utils/send_mail.py
=> OSIS-4489 : les intitulés du tableau n'étaient pas traduit en anglais

base/tests/views/learning_units/proposals/test_consolidate.py
=> Osis 4378 correct unittest

base/tests/views/test_education_group.py, program_management/tests/views/test_groupelementyear_read.py
=> OSIS-4310 : resolve conflicts dev

base/templates/blocks/navbar_top.html
=> [TEST] Change partnership agreement url

base/templates/blocks/navbar_top.html
=> [DEV] Change partnership agreement url

education_group/api/views/group_element_year.py, program_management/ddd/domain/link.py, program_management/ddd/repositories/load_tree.py, program_management/serializers/node_view.py, program_management/tests/ddd/factories/link.py, program_management/tests/serializers/test_node_view.py
=> OSIS-4452 fixed urls and actions into NodeViewAttributeSerializer

program_management/ddd/business_types.py
=> [DEV] Fix reference iufc + Revert 'Removing imports'

education_group/api/views/group_element_year.py, program_management/ddd/domain/link.py, program_management/ddd/repositories/load_tree.py, program_management/serializers/node_view.py, program_management/tests/ddd/factories/link.py, program_management/tests/serializers/test_node_view.py
=> Revert "OSIS-4452 fixed urls and actions into NodeViewAttributeSerializer"

education_group/api/views/group_element_year.py, program_management/ddd/domain/link.py, program_management/ddd/repositories/load_tree.py, program_management/serializers/node_view.py, program_management/tests/ddd/factories/link.py, program_management/tests/serializers/test_node_view.py
=> Revert "Revert "OSIS-4452 fixed urls and actions into NodeViewAttributeSerializer""

webservices/api/serializers/general_information.py, webservices/tests/api/serializers/test_general_information.py
=> OSIS-4525 : Remove common from endpoint

base/forms/learning_unit/edition.py, base/tests/forms/test_learning_unit_edition.py
=> OSIS-4214 Fixed bug lors de changement des end_year pour les partims

base/templates/blocks/navbar_top.html, webservices/api/serializers/general_information.py, webservices/tests/api/serializers/test_general_information.py
Pull request automatique de hotfix/OSIS-4525 vers QA
=> [hotfix/OSIS-4525 => QA] [WS] Reddot : Retirer les _common_ du endpoint principal

base/tests/utils/test_send_mail.py, base/utils/send_mail.py
=> OSIS-4523 : La langue de l'email est bien la langue du receiver

base/tests/utils/test_send_mail.py, base/utils/send_mail.py
=> OSIS-4523-to-qa

base/views/education_groups/detail.py, program_management/serializers/node_view.py, program_management/serializers/program_tree_view.py, program_management/tests/serializers/test_node_view.py, program_management/tests/serializers/test_program_tree_view.py, program_management/views/generic.py
=> [Performance] Enhance performance for the serialization of ProgramTree by making custom Serializer

education_group/schema.yml
=> OSIS-4540 : Schema for program versions publication (proposition)

base/templates/learning_unit/blocks/form/form_external.html, base/templates/learning_unit/learning_unit_layout.html
- Uniformiser les templates de creation et edition des externe avec les UEs
Référence Jira : OSIS-4554
=> OSIS-4554 Uniformiser les templates de creation et edition des externe avec les UEs

base/templates/learning_unit/identification.html, base/templatetags/learning_unit.py
- Fixed régressions suite à refactoring
Référence Jira : OSIS-4555
=> OSIS-4555  Fixed régressions suite à refactoring sur le gris des title common des partims

base/templates/learning_unit/blocks/form/form_external.html, base/templates/learning_unit/identification.html, base/templates/learning_unit/learning_unit_layout.html
Pull request automatique de hotfix/OSIS-4554 vers QA
=> [hotfix/OSIS-4554 => QA] [ECHEC QA] UE: Ajouter le champs _autre remarque_ pour les UE externes

education_group/schema.yml
J'ai pas encore été voir comment gérer le 'logical_operator'
=> OSIS-4546 : Schema for offer prerequisites publication (proposition)

osis_role/contrib/views.py, osis_role/templatetags/osis_role.py, osis_role/tests/templatetags/test_osis_role.py
=> OSIS-4536 Add wrapper on templatetags + django rules

base/templates/learning_unit/blocks/save_cancel_buttons.html
- Mettre dans le bon ordre les boutons Save et Annuler pour les propositions
Référence Jira : OSIS-4557
=> OSIS-4557 Mettre dans le bon ordre les boutons Save et Annuler pour les propositions

base/forms/learning_unit_specifications.py, base/tests/views/education_groups/test_search.py, base/tests/views/test_learning_unit.py, base/utils/send_mail.py, base/views/education_groups/perms.py, program_management/forms/education_groups.py, program_management/tests/business/test_excel_ue_in_of.py, program_management/views/search.py
Pull request automatique de hotfix/OSIS-4434 vers QA
=> [hotfix/OSIS-4434 => QA] Le report du cahier des charges ne fonctionne pas

program_management/business/group_element_years/group_element_year_tree.py, program_management/tests/business/group_element_years/test_build_tree.py, program_management/tests/business/test_excel_ue_in_of.py
=> Osis 4520 Problème de visualisation dans l'arbre (repliage)

base/forms/learning_achievement.py, base/tests/views/test_learning_achievement.py
=> OSIS-4590 : Not postpone after proposal year..

base/business/learning_units/perms.py
modified:   base/business/learning_units/perms.py
=> OSIS-4520 pep8

base/templates/learning_unit/blocks/form/search_form_external_learning_unit.html, base/templates/learning_unit/blocks/form/search_form_learning_unit.html, base/templates/learning_unit/blocks/form/search_form_summary_list.html
- Rollback sur l'interface de recherche des UEs
Référence Jira : OSIS-4564
=> OSIS-4564 Rollback sur l'interface de recherche des UEs

base/templates/learning_unit/blocks/form/search_form_external_learning_unit.html, base/templates/learning_unit/blocks/form/search_form_learning_unit.html, base/templates/learning_unit/blocks/form/search_form_summary_list.html
=> Hotfix/osis 4564 to QA

osis_role/README.md
=> OSIS-4537 Update README of osis_role module

base/forms/learning_unit/learning_unit_partim.py, base/tests/forms/test_learning_unit_partim.py
=> OSIS-4532 prevent end_anac to be before start_anac when saving partim

base/templates/blocks/navbar_top.html
=> Release 2.9.1 Fix patnership url

base/forms/learning_unit/learning_unit_partim.py, base/tests/forms/test_learning_unit_partim.py
Pull request automatique de hotfix/OSIS-4532 vers QA
=> [hotfix/OSIS-4532 => QA] Quand on crée un partim sur une UE en proposition de fin d_enseignement, on a un AttributeError

base/static/js/spinner.js
=> [UX] hide spinner according to sync/async trigger

education_group/migrations/0006_centraladmissionmanager_centralmanager_facultymanager.py
=> Correct migration files

osis_role/contrib/backends.py
=> Add RemoteUserBackend to OSIS-Role module

program_management/templatetags/prerequisite.py, program_management/tests/templatetags/test_prerequisite.py
=> OSIS-4633 do not display title when prerequisite is not in tree

base/static/css/custom.css, base/static/js/ckeditor/custom_ckeditor.js, base/static/js/modal_form_submit.js, program_management/static/js/program_management/education_group_tree.js
=> OSIS-4023 fix achievement tab CMS to complete ajax request

education_group/api/views/training.py, education_group/tests/api/views/test_training.py
=> OSIS-4639 : Filter with lowercase acronym

education_group/api/views/mini_training.py, education_group/tests/api/views/test_mini_training.py
=> OSIS-4639 : Missing mini trainings

base/templates/education_group/blocks/modal/modal_pedagogy_edit_inner.html, base/templates/learning_unit/blocks/modal/modal_pedagogy_edit.html
=> OSIS-4023 add CKUpdate to education_group and learning_unit pedagogy modal

education_group/api/serializers/group_element_year.py, education_group/tests/api/serializers/test_group_element_year.py, program_management/ddd/domain/node.py, program_management/tests/ddd/domain/test_node.py
=> OSIS-4562 : Do not get direct child of reference link

education_group/schema.yml
=> OSIS-4641 : Fix schema tree

education_group/api/serializers/education_group_version.py, education_group/api/url_v1.py, education_group/api/views/education_group_version.py, education_group/tests/api/serializers/test_education_group_version.py, education_group/tests/api/views/test_education_group_version.py
=> OSIS-4541 : Get versions list of EducationGroupYear

base/models/enums/education_group_types.py, education_group/api/serializers/group_element_year.py, education_group/tests/api/serializers/test_group_element_year.py, program_management/ddd/domain/node.py, program_management/tests/ddd/domain/test_node.py
=> OSIS-4562 : Exception for minors

education_group/api/views/mini_training.py, education_group/api/views/training.py, education_group/tests/api/views/test_mini_training.py
=> OSIS-4542 : Missing version_name for mini_formation

program_management/api/url_v1.py, program_management/api/views/prerequisite.py
=> OSIS-4548 correct url + add get_serializer_context in get_queryset

program_management/api/serializers/prerequisite.py, program_management/api/views/prerequisite.py
=> OSIS-2945-correct-pep8 correct pep8

education_group/api/serializers/group_element_year.py, education_group/tests/api/serializers/test_group_element_year.py
=> OSIS-4642 : Only get common title if no specific one

learning_unit/api/views/learning_achievement.py, learning_unit/tests/api/views/test_learning_achievement.py
=> OSIS-4643 : Get achievements only if text

education_group/api/serializers/group_element_year.py, education_group/tests/api/serializers/test_group_element_year.py, program_management/ddd/domain/node.py, program_management/tests/ddd/domain/test_node.py
=> OSIS-4562 : Fix: Within minor list exception

base/models/entity_version.py, base/static/css/osis.css, base/utils/cte.py
=> Add CTESubquery and allow more control over CTE queries

education_group/api/url_v1.py, education_group/api/views/mini_training.py, education_group/schema.yml, education_group/tests/api/views/test_mini_training.py
=> OSIS-4560 : Concerned offers endpoint

program_management/ddd/validators/validators_by_business_action.py
=> OSIS-4647 add DetachOptionValidator into validator_by_business_Action

base/models/authorized_relationship.py, program_management/ddd/domain/node.py, program_management/ddd/repositories/load_authorized_relationship.py, program_management/ddd/validators/_authorized_relationship.py, program_management/tests/ddd/domain/test_authorized_relationship.py, program_management/tests/ddd/domain/test_prerequisite.py, program_management/tests/ddd/validators/test_authorized_relationship.py
=> OSIS-4648 fixed DetachAuthorizedRelationshipValidator with taking care of LearningUnit authorized relations and links with type=REFERENCE

learning_unit/api/views/learning_achievement.py, learning_unit/tests/api/views/test_learning_achievement.py
Pull request automatique de hotfix/OSIS-4643 vers QA
=> [hotfix/OSIS-4643 => QA] [Echec Qa] - Learning Achievement : problème d_affichage et de save

education_group/schema.yml
=> OSIS-4560 : Schema

education_group/api/serializers/training.py, education_group/tests/api/serializers/test_training.py
=> OSIS-4661 : Habilitation into serializer

education_group/api/serializers/hops.py, education_group/api/url_v1.py, education_group/api/views/hops.py, education_group/tests/api/serializers/test_hops.py, education_group/tests/api/views/test_hops.py
=>  OSIS-4659 : Get used hops for an given year

base/templates/learning_unit/blocks/titles.html, base/tests/views/test_learning_unit.py, base/views/learning_units/create.py
=> OSIS-4559 Change title (partim) on partim creation

education_group/api/views/training.py, education_group/schema.yml, education_group/tests/api/views/test_training.py
=> OSIS-4660 : Filter training by ares_ability + Schema

base/templates/learning_unit/blocks/titles.html, base/tests/views/test_learning_unit.py, base/views/learning_units/create.py
Pull request automatique de hotfix/OSIS-4599 vers QA
=> [hotfix/OSIS-4599 => QA] Quand on crée une partim, on doit voir _Complément spécifique à l_UE (partim)_

program_management/serializers/node_view.py, program_management/serializers/program_tree_view.py, program_management/tests/serializers/test_program_tree_view.py
=> Revert "[WIP] [hotfix/OSIS-4591 => DEV] (DDD) Problème de visualisation dans l_arbre (repliage)"

education_group/api/serializers/hops.py, education_group/api/views/hops.py, education_group/schema.yml, education_group/tests/api/serializers/test_hops.py, education_group/tests/api/views/test_hops.py
=> OSIS-4669 : Return only list of ares_abilities

program_management/serializers/program_tree_view.py, program_management/tests/serializers/test_program_tree_view.py
=> OSIS-4666 add url to root node

program_management/schema.yml
=> OSIS-4672 : Fix indentation schema

program_management/tests/views/tree/test_detach.py, program_management/views/tree/detach.py
=> OSIS-4384 - fixed 'detach' action with new model

program_management/api/serializers/prerequisite.py, program_management/tests/api/serializers/test_prerequisite.py
=> OSIS-4676 : Get only common_title if no specific

base/business/learning_units/perms.py, base/tests/business/test_learning_unit_deletion.py
=> OSIS-4593 Check applications on all years to delete luy + tests

base/templates/education_group/blocks/form/group.html, base/templates/education_group/blocks/form/minitraining.html, base/templates/education_group/blocks/form/training_tab_identification.html, base/templatetags/education_group.py, base/tests/templatetags/test_education_group.py, base/views/education_groups/update.py
=> OSIS-4674 hide update content tab when user has no perm to change link data

base/business/learning_units/perms.py, base/tests/business/test_learning_unit_deletion.py
Pull request automatique de hotfix/OSIS-4593 vers QA
=> [hotfix/OSIS-4593 => QA] Quand l_UE a des candidatures, l_action _supprimer définitivement_ devrait toujours être grisée

base/tests/templatetags/test_education_group.py, education_group/auth/predicates.py, education_group/auth/roles/faculty_manager.py, education_group/tests/auth/test_predicates.py, program_management/views/groupelementyear_create.py
=> OSIS-4675 check user has all scopes according to education group year management entity

attribution/ddd/domain/attribution.py, attribution/ddd/domain/teacher.py, attribution/ddd/repositories/load_attribution.py, attribution/tests/ddd/domain/test_attribution.py, attribution/tests/ddd/domain/test_teacher.py, attribution/tests/ddd/factories/attribution.py, attribution/tests/ddd/factories/teacher.py, attribution/tests/ddd/repositories/test_load_attribution.py
=> Osis 4671 : ajout ddd pour attributions

base/views/education_groups/update.py, education_group/auth/predicates.py, education_group/tests/auth/test_predicates.py
=> OSIS-3717 fix misused perm and resolve children in predicate

learning_unit/ddd/domain/achievement.py, learning_unit/ddd/domain/learning_unit_year.py, learning_unit/ddd/repository/load_achievement.py, learning_unit/ddd/repository/load_learning_unit_year.py, learning_unit/tests/ddd/domain/test_learning_unit_year.py, learning_unit/tests/ddd/factories/achievement.py, learning_unit/tests/ddd/factories/learning_unit_year.py, learning_unit/tests/ddd/repository/load_achievement.py, learning_unit/tests/ddd/repository/test_load_achievement.py, learning_unit/tests/ddd/repository/test_load_learning_unit_year.py
=> OSIS-4684 :  Ajout de la notion d'achievement dans le ddd

education_group/auth/roles/faculty_manager.py
=> OSIS-4693 enable faculty manager to change/delete education group even when period is closed

learning_unit/ddd/domain/learning_unit_year.py, learning_unit/ddd/repository/load_learning_unit_year.py, learning_unit/tests/ddd/repository/test_load_learning_unit_year.py
=> OSIS-4687 : Ajout de qq notion dans le ddd pour le volume

learning_unit/api/views/learning_unit.py, learning_unit/tests/api/views/test_learning_unit.py
=> OSIS-4697 : get only luy with container

base/business/learning_units/edition.py
=> OSIS-4699 Fix creation proposal consolidation

base/forms/education_group/common.py, base/tests/views/test_learning_unit_proposal.py
=> OSIS-4696 extract PermissionFieldEducationGroupYearMixin from PermissionFieldEducationGroupMixin

base/business/learning_units/edition.py
Pull request automatique de hotfix/OSIS-4699 vers MASTER
=> [hotfix/OSIS-4699 => MASTER] La consolidation des créations est impossible en PROD (utilisateur QOPA)

learning_unit/api/views/learning_unit.py, learning_unit/tests/api/views/test_learning_unit.py
Pull request automatique de hotfix/OSIS-4697 vers QA
=> [hotfix/OSIS-4697 => QA] [WS] FicheActivite : utiliser objects_with_container

base/business/learning_unit_proposal.py, base/tests/business/test_learning_unit_proposal.py
=> Osis 4592 Get detailed error message when action blocked on proposal

education_group/schema.yml, learning_unit/schema.yml
=> OSIS-4702 : Pagination in schemas

requirements.txt
pillow -> 6.2.2
bleach -> 3.1.4
=> update bleach and pillow requirements

base/templates/education_group/blocks/dropdown/identification_actions_bar.html
=> OSIS-4526 give path get parameter to paste url

base/templates/education_group/blocks/dropdown/identification_actions_bar.html
=> OSIS-4704 disable quick search action for faculty managers in other entity

osis_role/contrib/forms/fields.py, osis_role/tests/contrib/forms/test_fields.py
=> OSIS-4705 filter EntityRoleChoiceField by ALL scope for faculty managers

.github/CONTRIBUTING.md, program_management/ddd/business_types.py, program_management/ddd/command.py, program_management/ddd/domain/node.py, program_management/ddd/domain/program_tree.py, program_management/ddd/domain/program_tree_version.py, program_management/ddd/repositories/load_tree.py, program_management/ddd/repositories/node.py, program_management/ddd/repositories/persist_tree.py, program_management/ddd/repositories/program_tree.py, program_management/tests/ddd/domain/test_program_tree_version.py
=> Guidelines made with the team about DDD and its implementation

base/tests/models/test_group_element_year.py
The block validation has been moved to validators of the ddd.
=> remove block model test

education_group/auth/roles/faculty_manager.py, education_group/tests/auth/test_predicates.py
=> OSIS-4703 enable egy creation only for linked entity

learning_unit/api/views/learning_unit.py
=> OSIS-4712 : Fix luy without learning_container_year

learning_unit/api/views/learning_unit.py
Pull request automatique de hotfix/OSIS-4712 vers QA
=> [hotfix/OSIS-4712 => QA] [WS] FicheActivite: ajout d un filtre sur le container

base/templates/education_group/blocks/content_actions.html, program_management/templatetags/group_element_year.py
=> OSIS-3717 allow multiple params for action_with_permission template tag

education_group/ddd/domain/_diploma.py, education_group/ddd/domain/training.py, education_group/ddd/repository/training.py, education_group/templates/training/diplomas_certificates_read.html, education_group/views/training/diplomas_certificates_read.py
=> OSIS-4384 Refactored urls for 'Training certificates/diplomas' view

education_group/templates/training/content_read.html
=> OSIS-4384 Refactored urls for 'Training content' view

base/models/enums/mandate_type.py, education_group/ddd/domain/_academic_partner.py, education_group/ddd/domain/_diploma.py, education_group/ddd/domain/service/identity_search.py, education_group/templates/training/administrative_data.html, education_group/templatetags/dates_from_to.py, education_group/urls.py, education_group/views/serializers/training_administrative_dates.py, education_group/views/training/__init__.py, education_group/views/training/administrative_data.py, education_group/views/training/common_read.py, education_group/views/training/identification_read.py, program_management/ddd/domain/service/identity_search.py, program_management/ddd/repositories/program_tree_version.py
=> OSIS-4384 Refactored urls for 'Training administrative data' view

education_group/auth/predicates.py, education_group/auth/roles/central_manager.py, education_group/auth/roles/faculty_manager.py, education_group/locale/en/LC_MESSAGES/django.po, education_group/locale/fr_BE/LC_MESSAGES/django.po, osis_role/contrib/models.py
=> OSIS-3717 fix delete permanently

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4715 Translations

base/templates/education_group/blocks/header.html, base/templatetags/navigation.py, base/tests/templatetags/test_navigation.py, education_group/templates/general_information/layout_read.html, education_group/templates/group/layout_read.html, education_group/templates/mini_training/layout_read.html, education_group/templates/training/layout_read.html, program_management/ddd/domain/program_tree.py, program_management/views/search.py
=> Fix test navigation education group year

education_group/api/views/learning_unit.py, education_group/api/views/mini_training.py, education_group/tests/api/views/test_learning_unit.py, education_group/tests/api/views/test_mini_training.py
Classes de tests réparé:
- EducationGroupRootsListTestCase
- FilterEducationGroupRootsTestCase
- OfferRootsTestCase
=> Fix tests for OSIS-4384

education_group/api/url_v1.py, education_group/api/views/group_element_year.py
=> OSIS-4750 : Fix urls with whitespaces + /

base/static/css/osis.css, education_group/templates/education_group_app/blocks/layout_detail.html, education_group/templates/education_group_app/group/identification_read.html, education_group/templates/education_group_app/group/layout_read.html, education_group/templates/education_group_app/mini_training/identification_read.html, education_group/templates/education_group_app/mini_training/layout_read.html, education_group/templates/education_group_app/training/identification/panel_informations.html, education_group/templates/education_group_app/training/layout_read.html, education_group/views/proxy/read.py, program_management/ddd/repositories/load_node.py
- Il ne faut pas afficher la liste déroulante des versions s'il n'y en a qu'une seule
- Certains libellés dans l'onglet identification sont en minuscule (exemple : activités en anglais, domaine principal, domaines secondaires,commentaire (interne)...)
- La valeur du champ "Type de contrainte" apparaît en majuscules (exemple : CREDITS)
=> OSIS-4749 : Correction des problèmes suivants :

education_group/api/url_v1.py, education_group/api/views/group_element_year.py
Pull request automatique de hotfix/OSIS-4750 vers MASTER
=> [hotfix/OSIS-4750 => MASTER] [WS] trainings : erreur de calcul d_url pour certaines offres

base/tests/forms/test_edition_form.py, base/tests/views/test_learning_unit_edition.py, base/views/learning_units/update.py
Each commit will correspond to a test class that is speed up
=> Speed test

education_group/ddd/business_types.py, education_group/ddd/domain/_content_constraint.py, education_group/ddd/domain/_remark.py, education_group/ddd/domain/exception.py, education_group/ddd/domain/group.py, education_group/ddd/factories/group.py, education_group/ddd/repository/group.py, education_group/ddd/service/read/group_service.py, education_group/tests/ddd/domain/test_group.py, education_group/tests/ddd/repository/test_group.py, education_group/tests/ddd/service/read/test_group_service.py, education_group/tests/factories/group_year.py
=> OSIS-4754 Add Group DDD + Repository + Read Service

base/utils/send_mail.py
=> OSIS-4763 Do not replace 0 with empty str for final score

base/utils/send_mail.py, education_group/api/url_v1.py, education_group/api/views/group_element_year.py
Pull request automatique de hotfix/OSIS-4763 vers QA
=> [hotfix/OSIS-4763 => QA] Encodage de notes : zéro non affichés dans mail récap

program_management/templates/learning_unit/tab_prerequisite_training.html
=> OSIS-4760-1 fix link to modify prerequisite

base/utils/send_mail.py
=> OSIS-4763 Do not replace 0 with empty str for final score - bis

base/utils/send_mail.py, education_group/api/url_v1.py, education_group/api/views/group_element_year.py
Pull request automatique de hotfix/OSIS-4763 vers DEV
=> [hotfix/OSIS-4763 => DEV] Encodage de notes : zéro non affichés dans mail récap

base/utils/send_mail.py
Pull request automatique de hotfix/OSIS-4763 vers MASTER
=> Release 2.12.3

base/business/learning_unit_xls.py, base/templates/education_group/blocks/modal/custom_xls.html, base/tests/business/test_learning_unit_xls.py, education_group/templates/education_group_app/blocks/layout_detail.html, program_management/business/excel_ue_in_of.py
=> Osis 4725 new

base/locale/fr_BE/LC_MESSAGES/django.po, program_management/ddd/repositories/_persist_prerequisite.py, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/tests/ddd/repositories/test_persist_prerequisite.py, program_management/tests/ddd/service/write/test_paste_node_service.py, program_management/tests/ddd/validators/test_validate_end_date_and_option_finality.py
=> OSIS-4529 translations + fix couper

README.md, doc/technical-manual.adoc
=> update documentation with geodjango installation

base/models/enums/education_group_types.py, base/models/utils/utils.py, program_management/ddd/domain/program_tree.py, program_management/ddd/validators/_has_or_is_prerequisite.py, program_management/ddd/validators/validators_by_business_action.py, program_management/tests/ddd/validators/test_has_or_is_prerequisite.py, program_management/views/tree/detach.py, program_management/views/tree/paste.py
Fix following errors:
- error when detaching in english language
- can now cut an element that is prerequisite but present multiple times in the program tree
- clear clipboard after paste
=> OSIS-4723 fix issues with copy/cut/paste/detach

base/models/utils/utils.py, program_management/ddd/domain/program_tree.py, program_management/ddd/validators/_has_or_is_prerequisite.py, program_management/ddd/validators/validators_by_business_action.py, program_management/tests/ddd/validators/test_has_or_is_prerequisite.py, program_management/views/tree/detach.py, program_management/views/tree/paste.py
Pull request automatique de technical/OSIS-4723 vers DEV
=> [technical/OSIS-4723 => DEV] Adapter couper/copier/coller avec les nouvelles urls

education_group/ddd/command.py, education_group/ddd/domain/exception.py, education_group/ddd/domain/group.py, education_group/ddd/repository/group.py, education_group/ddd/service/write/group_service.py, education_group/tests/ddd/domain/test_group.py, education_group/tests/ddd/repository/test_group.py, education_group/tests/ddd/service/write/test_group_service.py
=> OSIS-4757 Write create repository method

base/migrations/0517_entityversionaddress.py, base/models/entity_version_address.py, base/tests/factories/entity_version_address.py, base/tests/models/test_entity_version_address.py
=> OSIS-4567 Add tests and fix english term (location)

base/admin.py
=> OSIS-4775 : admin.py

base/models/student_specific_profile.py
=> OSIS-4775 : edit filters

assessments/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4784-1 correct spelling in french

program_management/forms/education_groups.py, program_management/tests/views/test_search.py
=> OSIS-4788 : Search groups

program_management/forms/education_groups.py, program_management/tests/views/test_search.py
Pull request automatique de technical/OSIS-4787 vers DEV
=> [technical/OSIS-4787 => DEV] Adapter la recherche de groupements (actuellement aucun résultat)

education_group/templates/education_group_app/blocks/content_actions.html, education_group/templates/education_group_app/group/content_read.html, education_group/templates/education_group_app/mini_training/content_read.html, education_group/templates/education_group_app/training/content_read.html
=> OSIS-4730 disable up and down for first and last element

learning_unit/api/views/learning_unit.py, learning_unit/tests/api/views/test_learning_unit.py
=> OSIS-4800 : add campus filter to LUY endpoint

base/models/enums/education_group_types.py, education_group/api/views/mini_training.py, education_group/api/views/training.py, education_group/tests/api/views/test_mini_training.py, education_group/tests/api/views/test_training.py
=> OSIS-4799 : Filter by campus & special types ficheoffre

assessments/business/score_encoding_export.py, assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/tests/views/test_score_encoding.py
=> OSIS-4769 : Mettre un '-' quand il n'y a pas d'accompagnateur

attribution/templates/manage_my_courses/educational_information.html
=> OSIS-4806 disabled button when no permission

education_group/schema.yml, learning_unit/schema.yml
=> OSIS-4811 : Schémas

base/business/learning_unit_proposal.py, base/business/learning_units/edition.py, base/tests/business/test_learning_unit_edition.py, base/views/learning_units/proposal/consolidate.py
Implement the postponement of component years when consolidating modification proposal.
=> [OSIS-4797] postpone volumes on consolidate proposal

base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/blocks/navbar_top.html
=> Revamp partnership menu display

base/migrations/0520_update_entityversionaddress.py, base/models/entity_version_address.py, base/tests/factories/entity_version_address.py
=> OSIS-4781 Add state + fix admin search

education_group/templates/education_group_app/mini_training/identification_read.html
=> OSIS-4814 : Pour les mineures, on ne voit pas des champs communs grisés

base/models/entity_version_address.py, base/tests/models/test_entity_version_address.py
=> OSIS-4781 Fix address edition failing + add tests

education_group/templates/education_group_app/mini_training/identification_read.html
Pull request automatique de feature/OSIS-3483 vers DEV
=> [feature/OSIS-3483 => DEV] En tant que gestionnaire central du catalogue de formation, je veux visualiser une version des formations

education_group/api/views/mini_training.py, education_group/api/views/training.py, education_group/schema.yml, education_group/tests/api/views/test_mini_training.py, education_group/tests/api/views/test_training.py
=> OSIS-4811 : Remove useless filters

base/models/entity_version.py, education_group/ddd/command.py, education_group/ddd/domain/exception.py, education_group/ddd/domain/group.py, education_group/ddd/repository/group.py, education_group/ddd/service/write/copy_group_service.py, education_group/ddd/service/write/create_group_service.py, education_group/ddd/validators/_content_constraint.py, education_group/ddd/validators/validators_by_business_action.py, education_group/forms/group.py, education_group/locale/en/LC_MESSAGES/django.po, education_group/locale/fr_BE/LC_MESSAGES/django.po, education_group/templates/education_group_app/group/upsert/layout_group_form.html, education_group/tests/ddd/domain/test_group.py, education_group/tests/ddd/service/read/test_group_service.py, education_group/tests/ddd/service/write/test_group_service.py, education_group/tests/ddd/validators/test_content_constraint.py, education_group/tests/views/group/test_create.py, education_group/views/group/create.py, program_management/ddd/command.py, program_management/ddd/service/read/allowed_children_types_service.py, program_management/ddd/service/read/node_identity_service.py, program_management/ddd/service/write/create_group_and_attach_service.py, program_management/ddd/validators/_authorized_relationship.py, program_management/tests/ddd/service/read/test_allowed_children_types_service.py, program_management/tests/ddd/service/read/test_node_identity_service.py, program_management/tests/ddd/service/write/test_create_group_and_attach_service.py
=> Osis 4758 Split attach group service into two different

base/business/education_group.py, base/tests/business/test_education_group.py, base/views/education_groups/search.py, program_management/templates/search.html, program_management/views/search.py
Pull request automatique de technical/OSIS-4817 vers DEV
=> [technical/OSIS-4817 => DEV] Rétablir export liste des formations recherche OF

assessments/business/score_encoding_export.py, assessments/tests/views/test_score_encoding.py
=> OSIS-4769 : Ajout d'une traduction manquante

program_management/forms/education_groups.py
=> OSIS-4820 : Corriger pour que le tri sur la colonne du titre fonctionne

base/models/enums/education_group_types.py, education_group/api/views/mini_training.py
=> OSIS-4798 : Missing remove

base/models/enums/education_group_types.py, education_group/api/views/mini_training.py, education_group/api/views/training.py, education_group/tests/api/views/test_mini_training.py, education_group/tests/api/views/test_training.py
=> OSIS-4798 : Cherry pick 

base/tests/views/test_organization.py, base/views/organization.py
=> Make tests more precise, filter on ACADEMIC_PARTNER

attribution/tests/views/test_manage_my_courses.py, attribution/views/manage_my_courses.py, base/templates/learning_unit/specifications_all.html
Pull request automatique de hotfix/OSIS-4830 vers MASTER
=> Release 2.13.2

assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po
=> feature/OSIS-4769-qa-2 : Ajout de traductions manquantes

attribution/urls.py, attribution/views/attribution.py, base/templates/learning_unit/blocks/tabs.html, base/urls.py, base/views/learning_unit.py, base/views/learning_units/common.py, base/views/learning_units/pedagogy/read.py, base/views/learning_units/pedagogy/update.py, base/views/learning_units/update.py
Pull request automatique de technical/OSIS-4773 vers DEV
=> [technical/OSIS-4773 => DEV] Onglet Enseignants d_une UE HS

education_group/tests/views/group/test_content_read.py, education_group/tests/views/group/test_general_information_read.py, education_group/tests/views/group/test_identification_read.py, education_group/tests/views/group/test_utilization_read.py, education_group/views/group/common_read.py, education_group/views/mini_training/common_read.py, education_group/views/training/common_read.py, program_management/serializers/program_tree_version_view.py, program_management/serializers/program_tree_view.py, program_management/tests/views/test_element_utilization.py, program_management/tests/views/test_prerequisite_read.py, program_management/views/generic.py
=> OSIS-4832 : Ajouter le version_label à la racine de l'arbre s'il existe

base/static/css/osis.css, base/static/js/education_group/update_training_errors.js, education_group/templates/education_group_app/training/upsert/layout_training_form.html
=> OSIS-4728 highlight tab ul when tab contains errors

education_group/forms/training.py, education_group/tests/views/training/test_create.py, education_group/views/training/create.py
=> OSIS-4728 add tests on create training view

education_group/forms/fields.py
=> OSIS-4728 raise validation error when management entity is not filled

education_group/templates/education_group_app/training/upsert/layout_training_form.html, education_group/views/training/create.py
=> OSIS-4728 display confirmation modal on warnings

education_group/forms/training.py
=> OSIS-4728 fix falling tests

base/templates/education_group/blocks/admission_condition_text.html, education_group/templates/education_group_app/training/admission_condition_read.html
=> OSIS-4731 : Correction url

education_group/forms/training.py
=> OSIS-4728 enable certification aims and section

education_group/api/serializers/group_element_year.py, education_group/api/views/group_element_year.py, education_group/tests/api/views/test_group_element_year.py
=> OSIS-4841 : Concatenate version_info

base/static/js/education_group/modify-text-btn.js, base/templates/education_group/blocks/admission_condition_table_row.html, base/templates/education_group/blocks/admission_condition_text.html, base/tests/views/test_education_group.py, base/views/education_group.py, base/views/education_groups/perms.py, base/views/education_groups/urls.py, education_group/templates/education_group_app/mini_training/admission_condition_read.html, education_group/templates/education_group_app/training/admission_condition_read.html, education_group/tests/views/general_information/test_common.py, education_group/tests/views/group/test_general_information_read.py, education_group/tests/views/mini_training/test_general_information_read.py, education_group/tests/views/training/test_general_information_read.py, education_group/views/general_information/common.py, education_group/views/group/general_information_read.py, education_group/views/mini_training/general_information_read.py, education_group/views/training/admission_condition_read.py, education_group/views/training/general_information_read.py
=> Osis 4829 regler conflit avec dev

education_group/api/serializers/group_element_year.py
=> OSIS-4849 : Remove space in acronym and remove useless fields on nodes

education_group/api/serializers/group_element_year.py, education_group/tests/api/serializers/test_group_element_year.py
=> Fix group title

education_group/api/serializers/education_group_version.py, education_group/api/serializers/utils.py, education_group/api/url_v1.py, education_group/api/views/education_group_version.py, education_group/api/views/group_element_year.py, education_group/api/views/mini_training.py, education_group/models/group_year.py, education_group/schema.yml, education_group/tests/api/serializers/test_mini_training.py, education_group/tests/api/views/test_group_element_year.py, education_group/tests/api/views/test_mini_training.py
=> OSIS-4838 : Create endpoints

education_group/views/proxy/read.py, program_management/views/proxy/identification.py
=> OSIS-4722 : Chnager l'url en fonction de la page de laquelle on vient

base/tests/views/test_learning_unit_proposal.py, base/views/learning_units/proposal/update.py
=> OSIS-4600 Fix suppression proposal on UE with end date

program_management/ddd/domain/node.py, program_management/tests/ddd/domain/test_node.py
=> OSIS-4856 Ensure computation of order when add_child

program_management/ddd/domain/program_tree_version.py, program_management/ddd/repositories/load_tree.py, program_management/ddd/repositories/program_tree_version.py, program_management/ddd/service/tree_service.py, program_management/serializers/node_view.py, program_management/templates/blocks/table_element_utilizations.html, program_management/views/element_utilization.py
=> OSIS-4356 : Adapter l'onglet "Utilisation" dans UE avec des versions

education_group/templates/education_group_app/group/content_read.html, education_group/views/group/common_read.py
=> OSIS-4857 Adapt template on content read in order to show usefull fields

base/tests/views/test_learning_unit_proposal.py, base/views/learning_units/proposal/update.py
Pull request automatique de hotfix/OSIS-4600 vers QA
=> [hotfix/OSIS-4600 => QA] Quand je tente de mettre une UE en proposition de fin d_enseignement sur une UE qui a une date de fin, j_ai un TypeError

assessments/business/score_encoding_export.py
=> Osis 4854 Encodage des notes: fichier Excel > la colonne date d'échéance doit être grisée

education_group/tests/views/proxy/test_read.py, education_group/views/group/common_read.py, education_group/views/proxy/read.py, program_management/views/proxy/identification.py
=> OSIS-4729 : Fix after test failed (redirect on identification)

education_group/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4823 Adapt translation for group success message

education_group/api/serializers/group_element_year.py, education_group/api/url_v1.py, education_group/api/views/education_group_version.py, education_group/api/views/mini_training.py, education_group/tests/api/serializers/test_mini_training.py, education_group/tests/api/views/test_mini_training.py
=> OSIS-4838 : Fix official_partial_acronym

base/templates/learning_unit/blocks/titles.html
=> OSIS-4863 : Remove asterisk

education_group/schema.yml
=> OSIS-4872 : Adapt schema

education_group/tests/views/group/test_utilization_read.py, education_group/tests/views/mini_training/test_utilization_read.py, education_group/tests/views/training/test_utilization_read.py, education_group/views/group/common_read.py, education_group/views/group/utilization_read.py, education_group/views/mini_training/utilization_read.py, education_group/views/training/utilization_read.py, program_management/templates/blocks/table_element_utilizations.html
=> OSIS-4356 : Fix test failed : missing version_name

education_group/tests/api/views/test_group_element_year.py
=> OSIS-4872 : Fix test_group_element_year.py

base/business/learning_units/simple/deletion.py, base/models/learning_unit_year.py, base/tests/business/test_learning_unit_deletion.py
- Passer par child_element pour vérifier si une UE est attaché à un groupement
Référence Jira : OSIS-4876
=> OSIS-4876 En tant que tous, je voudrais qu'on tienne compte des versions de programmes lorsqu'on modifie la date de fin d'une UE

education_group/views/serializers/general_information.py
=> OSIS-4878 : Remplacement d'un dict en ordereddict pour conserver l'ordre

base/models/authorized_relationship.py, program_management/ddd/domain/program_tree.py, program_management/ddd/domain/service/generate_node_abbreviated_title.py, program_management/ddd/domain/service/validation_rule.py, program_management/tests/ddd/domain/service/test_validation_rule.py, program_management/tests/ddd/domain/test_authorized_relationship.py
=> OSIS-4728 fixes on mandatory children order and abbreviated title generation

education_group/locale/en/LC_MESSAGES/django.po, education_group/locale/fr_BE/LC_MESSAGES/django.po, education_group/templates/education_group_app/training/upsert/blocks/panel_remarks_form.html, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4728 add 'remarks' panel to training form + add translations

education_group/api/serializers/training.py, education_group/tests/api/views/test_training.py
=> OSIS-4898 : Fix domain name if no parent

base/tests/views/education_groups/test_publication_contact.py, base/views/education_groups/publication_contact.py, base/views/education_groups/urls.py, education_group/templates/education_group_app/blocks/general_information_section_contact_panel.html, education_group/templates/education_group_app/blocks/general_information_section_contact_ul.html
=> OSIS-4880 : simplification des ursl

education_group/api/serializers/training.py, education_group/tests/api/views/test_training.py
Pull request automatique de hotfix/OSIS-4898 vers QA
=> [hotfix/OSIS-4898 => QA] [WS] educationGroups et _domain_name_ manquants

education_group/api/serializers/training.py, education_group/tests/api/views/test_training.py
=> OSIS-4898 : DEV

education_group/api/views/mini_training.py
=> OSIS-4909: only non-transition

education_group/api/views/mini_training.py, education_group/api/views/training.py, education_group/tests/api/views/test_training.py
=> OSIS-4910 : only standard in lists

education_group/api/views/mini_training.py, education_group/api/views/training.py, education_group/schema.yml
=> OSIS-4910 : revert

base/forms/education_group/common.py
=> OSIS-4902-1 replace '.' by ',' in co_graduation_coefficient formfield

base/templates/education_group/blocks/form/create_cancel_buttons.html, education_group/forms/training.py, education_group/views/training/create.py, program_management/ddd/domain/service/element_id_search.py
=> OSIS-4728 : fix redirections and initial values in Training Form (when action is create + attach)

education_group/views/training/identification_read.py
=> OSIS-4717-1 adapt django reversion on new model

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4862 Add translation on business exception message

education_group/views/training/create.py
=> OSIS-4728 fixed initial values when post data

education_group/api/serializers/learning_unit.py, education_group/api/views/learning_unit.py, education_group/tests/api/serializers/test_learning_unit.py, education_group/tests/api/views/test_learning_unit.py, learning_unit/schema.yml
=> OSIS-4893 : get learning_unit_credit in EducationGroupRoots

base/business/education_groups/general_information_sections.py, base/templates/education_group/blocks/modal/modal_pedagogy_edit_inner.html, base/views/education_group.py, base/views/education_groups/perms.py, education_group/views/group/general_information_read.py, education_group/views/group/general_information_update.py, webservices/api/serializers/general_information.py
=> OSIS-4920 : Fix edit and add new section

base/views/education_groups/achievement/update.py
=> OSIS-4920 : Fix cms in skills & achievements

education_group/api/serializers/learning_unit.py, education_group/api/views/learning_unit.py, education_group/tests/api/serializers/test_learning_unit.py, education_group/tests/api/views/test_learning_unit.py
=> OSIS-4893 : Fixing get multiple object

education_group/templates/education_group_app/training/upsert/blocks/panel_academic_informations_form.html
=> OSIS-4905 : Suppression de saut de lignes inutiles à l'affichage

education_group/api/serializers/group_element_year.py, education_group/api/serializers/learning_unit.py, education_group/api/serializers/utils.py, education_group/api/url_v1.py, education_group/api/views/education_group_version.py, education_group/api/views/group_element_year.py, education_group/api/views/mini_training.py, education_group/converters.py, education_group/schema.yml, education_group/tests/api/serializers/test_mini_training.py, education_group/tests/api/views/test_group_element_year.py, education_group/tests/api/views/test_mini_training.py, education_group/views/training/utilization_read.py
=> OSIS-4924 : [WS] Adapt mini trainings url to use acronym

education_group/api/serializers/learning_unit.py, education_group/api/views/learning_unit.py
=> OSIS-4924 : Fix urls in Prerequisites

education_group/api/url_v1.py
=> OSIS-4929 : Accept actual special caracters

education_group/forms/mini_training.py, education_group/views/mini_training/create.py
=> OSIS-4727 take initial value from request cache

education_group/api/serializers/training.py, education_group/tests/api/serializers/test_training.py
=> OSIS-4928 : Manage case no domain

education_group/api/serializers/training.py, education_group/api/views/training.py, education_group/tests/api/serializers/test_training.py, education_group/tests/api/views/test_training.py
=> OSIS-4928 : Annotate & do same for domain_code

base/business/education_groups/general_information_sections.py
=> OSIS-4934 : Version section

education_group/api/url_v1.py
=> OSIS-4923 : Fix urls

education_group/api/serializers/training.py, education_group/api/views/training.py, education_group/tests/api/serializers/test_training.py, education_group/tests/api/views/test_training.py
Pull request automatique de hotfix/OSIS-4928 vers QA
=> [hotfix/OSIS-4928 => QA] [WS] Renvoyer None si pas de main_domain

education_group/api/serializers/training.py, education_group/api/views/training.py, education_group/tests/api/serializers/test_training.py, education_group/tests/api/views/test_training.py
=> [hotfix/OSIS-4928 => DEV] [WS] Renvoyer None si pas de main_domain

education_group/api/views/group_element_year.py, education_group/api/views/mini_training.py
=> OSIS-4937 : Accept version_name no sensitive

education_group/api/url_v1.py, education_group/api/views/mini_training.py
=> OSIS-4937 : Edit urls order

learning_unit/api/views/learning_unit.py, learning_unit/tests/api/views/test_learning_unit.py
=> OSIS-4941 : Filter external mobility

education_group/api/serializers/learning_unit.py, education_group/api/views/learning_unit.py, education_group/tests/api/serializers/test_learning_unit.py, education_group/tests/api/views/test_learning_unit.py, learning_unit/schema.yml
=> OSIS-4919 : Get relative credits in EducationGroupRoots

education_group/api/serializers/education_group_title.py, education_group/tests/api/views/test_learning_unit.py, education_group/tests/api/views/test_training.py
=> OSIS-4923 : Fix title

learning_unit/api/views/learning_unit.py, learning_unit/tests/api/views/test_learning_unit.py
=> Osis 4941 dev

base/templates/templatetags/navigation_education_group.html
=> OSIS-4943 : L'intitulé de la version n'est pas complet

education_group/api/serializers/education_group_title.py, education_group/api/views/group_element_year.py
=> OSIS-4923 : Fix version_name in acronym

base/templates/templatetags/navigation_education_group.html
Pull request automatique de technical/OSIS-4943 vers DEV
=> [technical/OSIS-4943 => DEV] L_intitulé de la version n_est pas complet

base/templates/learning_unit/formations.html
Pull request automatique de technical/OSIS-4940 vers DEV
=> [technical/OSIS-4940 => DEV] UE onglet Utilisation : le lien vers le groupe dans lequel l_UE est utilisée ne fonctionne plus

education_group/api/url_v1.py, education_group/api/views/mini_training.py
=> OSIS-4923 : Add offer_roots for versions

script_copy_program.py
=> Osis 4435 qa create qa-based branch for copy script

education_group/ddd/repository/training.py
=> OSIS-4809 suppress hops on update

education_group/views/training/update.py
=> OSIS-4809 fix messages

education_group/ddd/domain/training.py, education_group/views/training/update.py
=> OSIS-4809 fix some issues

education_group/ddd/domain/_funding.py, education_group/views/training/update.py
=> OSIS-4809 treat null cases in form

base/static/css/osis.css, base/static/js/education_group/update_training_errors.js, base/templates/blocks/modal/confirmation_modal.html, education_group/templates/education_group_app/training/upsert/update.html, education_group/views/training/update.py
=> OSIS-4809 display warnings on funding fields

base/templates/blocks/modal/confirmation_modal.html, education_group/templates/education_group_app/training/upsert/layout_training_form.html, education_group/templates/education_group_app/training/upsert/update.html
=> OSIS-4809 fix warning modal submit

education_group/templates/education_group_app/training/identification/panel_academic_informations.html, education_group/views/training/update.py, program_management/ddd/service/write/delete_standard_program_tree_version_service.py
=> OSIS-4809 fix some minor bugs

base/models/hops.py, base/static/js/education_group/update_training_errors.js, education_group/ddd/business_types.py, education_group/ddd/domain/_diploma.py, education_group/ddd/domain/_study_domain.py, education_group/ddd/domain/training.py, education_group/ddd/service/read/get_update_training_warning_messages.py, education_group/ddd/service/write/update_training_service.py, education_group/forms/fields.py, education_group/forms/training.py, education_group/locale/en/LC_MESSAGES/django.po, education_group/locale/fr_BE/LC_MESSAGES/django.po, education_group/templates/education_group_app/training/identification/panel_academic_informations.html, education_group/templates/education_group_app/training/identification/panel_hops.html, education_group/templates/education_group_app/training/upsert/blocks/panel_academic_informations_form.html, education_group/templates/education_group_app/training/upsert/blocks/panel_diplomas_certificates_form.html, education_group/views/training/common_read.py, education_group/views/training/identification_read.py, education_group/views/training/update.py
=> Fix issues with update training

base/models/hops.py, base/static/js/education_group/update_training_errors.js, education_group/ddd/business_types.py, education_group/ddd/domain/_diploma.py, education_group/ddd/domain/_study_domain.py, education_group/ddd/domain/training.py, education_group/ddd/service/read/get_update_training_warning_messages.py, education_group/ddd/service/write/update_training_service.py, education_group/forms/fields.py, education_group/forms/training.py, education_group/locale/en/LC_MESSAGES/django.po, education_group/locale/fr_BE/LC_MESSAGES/django.po, education_group/templates/education_group_app/training/identification/panel_academic_informations.html, education_group/templates/education_group_app/training/identification/panel_hops.html, education_group/templates/education_group_app/training/upsert/blocks/panel_academic_informations_form.html, education_group/templates/education_group_app/training/upsert/blocks/panel_diplomas_certificates_form.html, education_group/views/training/common_read.py, education_group/views/training/identification_read.py, education_group/views/training/update.py
Pull request automatique de technical/OSIS-4809 vers DEV
=> [WIP] [technical/OSIS-4809 => DEV] Adapter _Mise à jour_ formation avec nouvelles urls / view / service

base/models/education_group_type.py
=> OSIS-4925 Improve admin for education group type

education_group/api/views/group_element_year.py, education_group/models/group_year.py, program_management/models/education_group_version.py, program_management/models/element.py
=> Improve admin for element & education group version

education_group/converters.py, education_group/ddd/domain/training.py, education_group/ddd/service/read/get_update_training_warning_messages.py, education_group/urls.py
=> Fix some minor issues with update training

education_group/converters.py
=> OSIS-4809 update converters

education_group/locale/en/LC_MESSAGES/django.po, education_group/locale/fr_BE/LC_MESSAGES/django.po, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4810 traductions

education_group/urls.py
=> OSIS-4810 treat special case urls

education_group/urls.py
=> OSIS-4810 use acronym path converter for education group read proxy

backoffice/settings/base.py, base/forms/widgets.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/static/css/lat-lon-widget.css, base/static/js/lat-lon-widget.js, base/templates/address/widgets/lat-long-widget.html, base/tests/forms/test_widgets.py, base/tests/views/test_geocode.py, base/urls.py, base/views/geocoding.py
https://jira.sgsi.ucl.ac.be/browse/OSIS-4953
Ne pas oublier de rajouter dans les settings
- `GEOCODING_URL`
- `GEOCODING_TOKEN`
- `MAPBOX_ACCESS_TOKEN`
=> Add location widget

education_group/views/mini_training/update.py, education_group/views/training/update.py
=> Only show link success message on changed data

education_group/api/serializers/learning_unit.py, education_group/api/views/learning_unit.py, education_group/tests/api/serializers/test_learning_unit.py, education_group/tests/api/views/test_learning_unit.py
=> Release 2.16.2

education_group/api/url_v1.py, program_management/api/url_v1.py, program_management/api/views/prerequisite.py, program_management/ddd/domain/program_tree_version.py, program_management/tests/api/views/test_prerequisite.py
=> OSIS-4976 : Adapt prerequisites mini trainings urls

base/models/admission_condition.py, script_copy_program.py
=> OSIS-4435 fix issues with script

education_group/views/serializers/group_year.py, program_management/ddd/domain/exception.py, program_management/ddd/validators/_match_version.py, program_management/templates/quick_search_egy_inner.html, program_management/templates/tree/paste_inner.html, program_management/tests/ddd/validators/test_match_version.py, program_management/tests/views/tree/test_paste.py, program_management/views/tree/paste.py
Référence Jira : OSIS-4069 test reviews
=> OSIS-4069 display version info in popup, quick search and error msg

education_group/schema.yml
=> OSIS-4978 : Adapt schémas

education_group/schema.yml
=> OSIS-4980 : Fix schemas

program_management/tests/views/tree/test_paste.py, program_management/views/tree/paste.py
=> OSIS-4069 format title with version when available

base/models/entity_version.py, base/tests/models/test_entity_version.py
=> Add acronym path in CTE

education_group/schema.yml
=> OSIS-4975 : Fix schema

program_management/ddd/validators/_detach_option_2M.py, program_management/tests/ddd/validators/test_detach_option_2M.py, program_management/views/tree/detach.py
=> Fix detach finality

script_copy_program.py
=> Update group values 

base/templates/education_group/blocks/dropdown/identification_actions_bar.html
=> OSIS-4986 : Masquer le bouton action quand on est sur un noeud UE

base/templates/education_group/blocks/dropdown/identification_actions_bar.html, base/templatetags/education_group_pdf.py, program_management/serializers/node_view.py, program_management/tests/serializers/test_node_view.py, program_management/views/groupelementyear_read.py
=> OSIS-4984 : Corrections diverses pour le pdf

base/static/css/osis.css, education_group/templates/education_group_app/mini_training/identification_read.html, education_group/templates/education_group_app/training/identification/panel_informations.html
=> OSIS-4981 : Griser l'acronym quand on affiche une version particulière

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/views/tree/detach.py
=> OSIS-4867-3 correct when no group_year

requirements.txt
=> fix version setuptools

base/templates/education_group/blocks/dropdown/identification_actions_bar.html
- Ajout d'une séparation entre les action sur les version et le reste des action de l'OF
=> OSIS-1826 Issue-3

requirements.txt
=> freeze version setuptools

education_group/auth/predicates.py, education_group/tests/auth/test_predicates.py
=> OSIS-4681 extend check to root

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4912 translations

education_group/views/training/create.py
=> OSIS-4913 prefill management entity with parent one

education_group/locale/en/LC_MESSAGES/django.po, education_group/locale/fr_BE/LC_MESSAGES/django.po
=> Translations

education_group/templates/education_group_app/mini_training/identification_read.html, program_management/ddd/repositories/program_tree_version.py, program_management/ddd/validators/_copy_check_end_date_tree_version.py
=> Feature/OSIS-1826 Fix end year of ProgramTreeVersion

program_management/ddd/validators/_detach_option_2M.py, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/tests/ddd/validators/test_detach_option_2M.py
=> OSIS-4070 append version name to acronym in validation msg on detach

program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/templates/tree/paste_inner.html
=> OSIS-4875 remove access condition label next to form checkbox

education_group/templates/education_group_app/group/content_read.html, education_group/templatetags/version_details.py, education_group/views/serializers/group_year.py, program_management/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5016 :  Ajout de l'intitutlé de version dans la recherche

education_group/api/serializers/training.py, education_group/forms/training.py, program_management/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4988 : 4 decimals for co_graduation_coef

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/views/tree/move.py, program_management/views/tree/paste.py
=> Osis 4868 1 update confirmation messages

education_group/forms/fields.py, education_group/forms/group.py
=> OSIS-5021 : Fix issue with creation of a new group into a program

base/business/learning_units/perms.py, base/forms/learning_unit/edition.py, base/tests/business/test_perms.py
=> OSIS-4969 : Can edit end year if no application in future

program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/templates/tree_version/create_specific_version_inner.html
=> OSIS-5030 : Ajout du crochet manquant à l'écran de création de version

program_management/forms/version.py
Référence Jira : OSIS-1826  issue12
=> Osis 1826 issue12

education_group/forms/fields.py, education_group/forms/group.py
=> OSIS-4931 : Fix creation of group into other group

base/models/enums/education_group_types.py, program_management/ddd/domain/node.py, program_management/ddd/service/read/get_default_link_type_service.py, program_management/ddd/validators/_authorized_link_type.py, program_management/forms/tree/paste.py, program_management/tests/ddd/validators/test_authorized_link_type.py, program_management/tests/forms/tree/test_paste.py, program_management/views/tree/paste.py
=> OSIS-4875 dissociate OptionList from MajorMinorList to define link_type

education_group/forms/fields.py, education_group/forms/group.py
Pull request automatique de technical/OSIS-4931 vers DEV
=> [technical/OSIS-4931 => DEV] Formation > Nouveau groupement > création d_une liste au choix dans une liste au choix > Plantage

base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html
=> OSIS-5032 : Remove copy from action menu

program_management/forms/tree/paste.py
=> OSIS-4875 avoid too many returns

education_group/views/mini_training/common_read.py, education_group/views/training/common_read.py, program_management/ddd/command.py, program_management/ddd/service/read/get_program_tree_version_from_node_service.py, program_management/ddd/service/write/update_mini_training_version_service.py, program_management/ddd/service/write/update_training_version_service.py, program_management/forms/version.py, program_management/templates/tree_version/mini_training/blocks/identification.html, program_management/templates/tree_version/mini_training/update.html, program_management/templates/tree_version/training/blocks/diplomas_certificates.html, program_management/templates/tree_version/training/blocks/identification.html, program_management/templates/tree_version/training/blocks/panel_academic_informations_form.html, program_management/templates/tree_version/training/blocks/panel_entities_form.html, program_management/templates/tree_version/training/blocks/panel_funding_form.html, program_management/templates/tree_version/training/blocks/panel_hops_form.html, program_management/templates/tree_version/training/blocks/panel_informations_form.html, program_management/templates/tree_version/training/blocks/panel_remarks_form.html, program_management/templates/tree_version/training/update.html, program_management/templates/tree_version/training_version_update.html, program_management/tests/ddd/service/read/test_get_program_tree_version_from_node_service.py, program_management/tests/views/tree_version/test_update_mini_training.py, program_management/tests/views/tree_version/test_update_training.py, program_management/urls.py, program_management/views/tree_version/update_mini_training.py, program_management/views/tree_version/update_training.py
=>  Osis 4388 Add update_mini_training_version / update_training_version form

base/locale/fr_BE/LC_MESSAGES/django.po, education_group/views/mini_training/delete.py, education_group/views/training/delete.py, program_management/ddd/repositories/program_tree_version.py, program_management/forms/version.py, program_management/tests/ddd/factories/program_tree_version.py, program_management/tests/ddd/repositories/test_program_tree_version.py
=> OSIS-4064 Fix details to delete training / minitraining versions

program_management/forms/tree/paste.py, program_management/tests/forms/tree/test_paste.py, program_management/views/tree/paste.py
=> OSIS-4875 create PasteMinorMajorListToMinorMajorListChoiceForm

education_group/ddd/service/write/update_mini_training_service.py, education_group/ddd/service/write/update_training_service.py, education_group/tests/ddd/service/write/test_update_mini_training_service.py, education_group/tests/ddd/service/write/test_update_training_service.py, program_management/ddd/service/write/update_program_tree_version_service.py, program_management/ddd/service/write/update_training_version_service.py, program_management/tests/ddd/factories/commands/update_training_version_command.py, program_management/tests/ddd/service/write/test_update_training_version_service.py
=> OSIS-4388 DDD service to update training version

base/tests/views/test_education_group.py, base/views/education_groups/perms.py
=> OSIS-4745 Correct permission for admission_condition

program_management/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5039 translations

base/tests/business/test_learning_unit_edition.py
=> OSIS-5035 : test extending partim with no end year (limited by parent)

base/forms/learning_unit/learning_unit_partim.py, base/tests/views/test_learning_unit_edition.py
=> OSIS-4952 don't overwrite partim start year on update

program_management/ddd/domain/service/calculate_end_postponement.py, program_management/ddd/service/write/update_mini_training_version_service.py, program_management/ddd/service/write/update_program_tree_version_service.py, program_management/tests/ddd/factories/commands/update_mini_training_version_command.py, program_management/tests/ddd/factories/commands/update_program_tree_version.py, program_management/tests/ddd/service/write/test_update_mini_training_version_service.py, program_management/tests/ddd/service/write/test_update_program_tree_version_service.py
=> OSIS-1823 manage end_year and deletions when updating 'end year' of Training version

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/views/tree/detach.py
=> OSIS4867-4 forgot year in messages

attribution/urls.py, attribution/views/learning_unit/common.py
=> OSIS-5043 : Enable teacher tab (fixed bug)

education_group/templates/education_group_app/group/upsert/content_form.html
=> OSIS-5045 : content tab - hide credit for major/minor/option list

base/business/learning_units/perms.py, base/forms/learning_unit/edition.py, base/tests/business/test_perms.py
Pull request automatique de hotfix/OSIS-4969 vers MASTER
=> Release 2.16.5

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/templates/program_management/content/block/panel_content.html
=> OSIS-5027 do not display credits for minor major list choice parent

education_group/ddd/domain/_diploma.py, education_group/templates/education_group_app/training/identification/panel_informations.html, education_group/tests/ddd/domain/test_diploma.py, program_management/ddd/service/write/update_program_tree_version_service.py, program_management/forms/version.py, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/templates/tree_version/training/blocks/panel_entities_form.html, program_management/tests/forms/test_version.py, program_management/tests/views/tree_version/test_update_training.py, program_management/views/tree_version/update_training.py
=> Feature/OSIS-1823 bugfixes  on updat of training versions

education_group/locale/fr_BE/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5039 traductions

base/static/css/osis.css, education_group/templates/education_group_app/mini_training/identification_read.html, education_group/templates/education_group_app/training/identification/panel_informations.html, education_group/tests/ddd/domain/test_isced_domain.py, program_management/forms/version.py, program_management/views/tree_version/update_training.py
=> Feature/OSIS-1823 Fixed display of fields for update version form

education_group/ddd/domain/group.py, program_management/templates/program_management/content/update.html, program_management/views/content/update.py
=> OSIS-5027 display version name when modify content

education_group/templates/education_group_app/training/identification/panel_informations.html
=> OSIS-1823-fix use similar translation for title version fr/en

program_management/templates/program_management/content/update.html
=> OSIS-5027 display fix

base/views/learning_unit.py
=> OSIS-5049 : Case no campus

base/context_processors/user_manual.py, base/templates/layout.html
=> OSIS-5066 : Edit Help url to uclouvain.be/osis

base/models/academic_calendar.py
=> Fixed open_calendar change gt to gte

program_management/templates/tree_version/mini_training/update.html, program_management/templates/tree_version/training/update.html
=> OSIS-5070 : Add missing version label in update training/mini_training

base/models/academic_calendar.py, base/tests/templatetags/test_learning_unit_li.py, base/tests/views/test_institution.py, program_management/tests/ddd/domain/service/test_calculate_end_postponement.py
=> fixed test

program_management/templates/program_management/content/update.html
=> OSIS-5070 : Add correct title to content tab

assessments/templates/online_encoding_form.html
=> OSIS-5087 : remove coquille

education_group/templates/education_group_app/training/upsert/update.html
=> OSIS-5035 : Adapt title for finalities

base/business/learning_units/xls_comparison.py, base/tests/business/learning_units/test_xls_comparison.py, base/tests/business/test_education_group.py, base/tests/business/test_proposal_xls.py, base/tests/views/test_learning_unit.py
=> OSIS-5081 : Fix issue with keyError in xls production

base/views/user_list.py
=> OSIS-5076 : Fix import

base/views/user_list.py
Pull request automatique de technical/OSIS-5076 vers DEV
=> [technical/OSIS-5076 => DEV] Institutions > Liste des utilisateurs > ImportError > cannot import name _PartnershipEntityManager_

program_management/views/content/update.py
=> OSIS-5025 fix update content

education_group/ddd/domain/mini_training.py, education_group/ddd/domain/training.py, education_group/ddd/service/write/create_orphan_mini_training_service.py, education_group/ddd/service/write/create_orphan_training_service.py, education_group/ddd/service/write/postpone_group_modification_service.py, education_group/ddd/service/write/postpone_mini_training_and_group_modification_service.py, education_group/ddd/service/write/postpone_training_and_group_modification_service.py, education_group/ddd/service/write/update_mini_training_and_group_service.py, education_group/forms/fields.py, education_group/locale/fr_BE/LC_MESSAGES/django.po, education_group/tests/ddd/service/write/test_create_orphan_mini_training_service.py, education_group/tests/ddd/service/write/test_create_orphan_training_service.py, education_group/tests/ddd/service/write/test_postpone_group_modification_service.py, education_group/tests/ddd/service/write/test_postpone_mini_training_and_group_modification_service.py, education_group/tests/ddd/service/write/test_postpone_training_and_group_modification_service.py, education_group/views/training/create.py, program_management/ddd/domain/service/calculate_end_postponement.py, program_management/ddd/domain/service/identity_search.py, program_management/ddd/service/read/get_end_postponement_year_service.py, program_management/ddd/service/write/postpone_program_tree_service.py, program_management/ddd/service/write/postpone_program_tree_service_mini_training.py, program_management/ddd/service/write/postpone_tree_version_service.py, program_management/ddd/service/write/postpone_tree_version_service_mini_training.py, program_management/ddd/service/write/update_program_tree_version_service.py, program_management/ddd/validators/validators_by_business_action.py, program_management/tests/ddd/domain/service/test_calculate_end_postponement.py, program_management/tests/ddd/service/read/test_get_end_postponement_year_service.py
=> OSIS-4995 Fix create and paste version

base/fixtures/validation_rules.csv
=> OSIS-5095 : Fix tooltip for certificate of success

base/business/learning_unit_xls.py, base/models/learning_unit_year.py, base/tests/business/test_learning_unit_xls.py
=> OSIS-5094 : Fix xls (missing title + relative_credits)

education_group/templates/education_group_app/training/administrative_data.html
=> OSIS-5106 : Deliberation date

program_management/ddd/service/write/update_program_tree_version_service.py, program_management/tests/ddd/service/write/test_update_program_tree_version_service.py
=> OSIS-4995 Update call to delete tree version

base/templates/education_group/blocks/dropdown/identification_actions_bar.html, program_management/ddd/service/write/create_mini_training_with_program_tree.py
=> OSIS-5123 create ProgramTree and ProgramTreeVersion before postponement

base/business/learning_unit_xls.py
=> OSIS-5094 : Fix title of program

base/models/learning_container_year.py, base/templates/learning_unit/comparison.html, base/views/learning_unit.py
=> OSIS-5091 : Fix order of entities

program_management/ddd/validators/_detach_option_2M.py, program_management/tests/ddd/validators/test_detach_option_2M.py
=> OSIS-5102 validate detach option according to parent list

base/business/learning_units/xls_comparison.py
=> OSIS-5117 : Colonnes décalées dans l'xls de comparaison des ues

base/templates/learning_unit/blocks/summary_locked.html
=> OSIS-5118 Hide summary blocked info when flag is off 

base/business/learning_unit_year_with_context.py
=> OSIS-5117 : Le volume global était tj à 0

base/auth/roles/program_manager.py
=> OSIS-4954 fix too many return statements

program_management/tests/ddd/domain/test_program_tree.py
=> Fix test program tree builder for mandatory children

base/auth/predicates.py, base/auth/roles/program_manager.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/auth/test_predicates.py, education_group/locale/en/LC_MESSAGES/django.po, education_group/locale/fr_BE/LC_MESSAGES/django.po, education_group/views/training/update.py
=> OSIS-4954 consider GroupYear received in predicate is_linked_to_offer

base/models/learning_container_year.py
=> OSIS-5091 : Fix ordering

base/business/learning_unit_year_with_context.py, base/business/learning_units/xls_comparison.py, base/tests/business/learning_units/test_edition.py
=> OSIS-5117 : Merge with DEV

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/templates/program_management/templatetags/prerequisite/is_prerequisite.html
=> OSIS-5159 : Correction d'une traduction

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/manage_my_courses/blocks/list/learning_units_summary_editable.html, attribution/templates/manage_my_courses/blocks/submission_dates.html, attribution/templatetags/date_operations.py, attribution/tests/views/test_manage_my_courses.py, attribution/views/manage_my_courses.py, base/business/event_perms.py, base/templates/learning_unit/blocks/panel/educational_informations_force_majeure.html, base/templates/learning_unit/blocks/summary_locked.html
Pull request automatique de hotfix/OSIS-5118 vers MASTER
=> Release 2.17.3

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/templates/program_management/templatetags/prerequisite/is_prerequisite.html
Pull request automatique de technical/OSIS-5159 vers DEV
=> [technical/OSIS-5159 => DEV] OF > Arbre > Sélectionner un prérequis > Renommer acronyme en _Sigle_

education_group/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5148 : Correction d'une traduction

base/forms/learning_unit/learning_unit_create_2.py, base/forms/learning_unit/learning_unit_partim.py
=> OSIS-5157 display error when creating partim without title

education_group/locale/en/LC_MESSAGES/django.po, education_group/locale/fr_BE/LC_MESSAGES/django.po, education_group/templates/education_group_app/general_information/layout_read.html, education_group/tests/views/general_information/test_common.py, education_group/urls.py, education_group/views/general_information/__init__.py, education_group/views/general_information/common.py, education_group/views/serializers/general_information.py
=> Technical/osis 5164 

base/tests/forms/learning_unit/test_learningUnitYearModelForm.py, base/tests/views/learning_units/external/test_create.py, education_group/tests/views/mini_training/test_identification_read.py, education_group/tests/views/mini_training/test_skills_achievements_read.py, education_group/tests/views/training/test_general_information_read.py, education_group/tests/views/training/test_identification_read.py, webservices/tests/api/serializers/test_contacts.py
=> Fix current year in tests

base/tests/utils/test_operator.py, base/utils/operator.py, education_group/locale/en/LC_MESSAGES/django.po, education_group/locale/fr_BE/LC_MESSAGES/django.po, education_group/tests/views/training/test_update.py, education_group/views/mini_training/update.py, education_group/views/training/update.py, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/tests/views/tree_version/test_update_mini_training.py, program_management/tests/views/tree_version/test_update_training.py, program_management/views/tree_version/update_mini_training.py, program_management/views/tree_version/update_training.py
=> Osis 4995 uniform delete message for training and mini end date update

base/business/learning_units/perms.py, base/tests/forms/learning_unit/test_learningUnitYearModelForm.py, base/tests/views/learning_units/external/test_create.py
=> OSIS-5184 : No limitation 'in_past'

education_group/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5164 Correct bad traduction in french

base/static/css/osis.css, education_group/templates/education_group_app/training/identification/panel_informations.html
=> OSIS-5192 Add partial_title_fr/partial_title_en of unversioned field

education_group/api/serializers/group_element_year.py, education_group/schema.yml, education_group/tests/api/serializers/test_group_element_year.py
=> OSIS-5183 : add version_name to node into tree

base/auth/predicates.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, education_group/ddd/domain/exception.py
=> OSIS-4954 fix missing and erroneous translations

base/business/learning_units/perms.py, base/tests/forms/learning_unit/test_learningUnitYearModelForm.py, base/tests/views/learning_units/external/test_create.py
Pull request automatique de hotfix/OSIS-5184 vers QA
=> [hotfix/OSIS-5184 => QA] Problème de mettre fin des partims

base/business/education_group.py
=> OSIS-5185 : On tentait d'acquérir un acronym sur un objet None

backoffice/settings/base.py, base/tests/business/test_education_group.py, education_group/auth/predicates.py, education_group/tests/auth/test_predicates.py, osis_role/cache.py, osis_role/tests/test_cache.py
=> Implement cache for permission

rules_management/fixtures/field_reference.json
=> OSIS-4954 prevent faculty manager to edit keywords when editing period is closed

assessments/views/score_encoding.py
=> OSIS-4954 fix missing import

base/models/models_signals.py
=> Fix program_manager role import

base/business/education_group.py, base/tests/business/test_education_group.py
=> Remove unused can_user_edit_administrative_data

education_group/templates/education_group_app/training/identification/panel_academic_informations.html
Modifications qui seront validées :
modifié :         education_group/templates/education_group_app/training/identification/panel_academic_informations.html
Adaptation pour enlever le tiret en car de valeur None
Référence Jira : OSIS-5161
=> OSIS-5161 Adaptation pour enlever le tiret en car de valeur None (Catégorie de Décret pour OF)

program_management/ddd/domain/exception.py, program_management/ddd/domain/node.py, program_management/ddd/repositories/program_tree_version.py, program_management/ddd/validators/_match_version.py, program_management/ddd/validators/validators_by_business_action.py, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/tests/ddd/domain/test_link.py, program_management/tests/ddd/domain/test_node.py, program_management/tests/ddd/factories/repository/fake.py, program_management/tests/ddd/validators/test_match_version.py, program_management/tests/views/tree/test_paste.py
=> Osis 5199 Update version mismatch validator

program_management/ddd/domain/exception.py, program_management/ddd/domain/node.py, program_management/ddd/repositories/program_tree_version.py, program_management/ddd/validators/_match_version.py, program_management/ddd/validators/validators_by_business_action.py, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/tests/ddd/domain/test_link.py, program_management/tests/ddd/domain/test_node.py, program_management/tests/ddd/validators/test_match_version.py, program_management/tests/views/tree/test_paste.py
Pull request automatique de technical/OSIS-5199 vers DEV
=> [technical/OSIS-5199 => DEV] Finalité > Créer une formation > Impossible de la sauver _la version doit être la même _none__

education_group/tests/api/views/test_training.py
=> fix training list api test randomly failing

attribution/tests/ddd/domain/test_teacher.py, program_management/business/excel_ue_in_of.py, program_management/tests/business/test_excel_ue_in_of.py
Pull request automatique de technical/OSIS-5190 vers DEV
=> [technical/OSIS-5190 => DEV] Excel Liste des UE de la formation > Inclure sigle version

education_group/tests/views/serializers/test_admission_condition.py, education_group/views/serializers/admission_condition.py
=> OSIS-5172 Show common condition admission condition for 180-240/60

program_management/tests/views/tree_version/test_update_mini_training.py, program_management/tests/views/tree_version/test_update_training.py, program_management/views/tree_version/update_mini_training.py, program_management/views/tree_version/update_training.py
=> OSIS-5088 Keep path context after update training/minitraining version

education_group/forms/mini_training.py, education_group/forms/training.py
Pull request automatique de technical/OSIS-5213 vers DEV
=> [technical/OSIS-5213 => DEV] Mini-formation > Validité not set empêche d_enregistrer les changements

base/views/education_groups/achievement/update.py
=> OSIS-5216 Update skills&achievements modal get_root

program_management/forms/version.py
=> OSIS-5149 set initial management entity for versions

program_management/templates/learning_unit/tab_prerequisite_update.html, program_management/tests/views/test_prerequisite_read.py, program_management/views/element_utilization.py, program_management/views/generic.py, program_management/views/prerequisite_read.py, program_management/views/prerequisite_update.py
=>  OSIS-4987 Apply permission base.change_prerequisite

base/views/education_group.py
=> OSIS-5209 Fixed bug quand il n'y a pas de condition d'admission

base/views/education_groups/achievement/common.py
=> OSIS-5208 Fix issue when POST invalid data on form

program_management/forms/tree/paste.py, program_management/tests/forms/tree/test_paste.py
=> OSIS-5222 Set is_mandatory to True as initial on Paste Form

education_group/ddd/command.py, education_group/ddd/domain/training.py, education_group/ddd/service/write/create_orphan_training_service.py, education_group/ddd/service/write/postpone_training_and_group_modification_service.py, education_group/ddd/service/write/update_training_and_group_service.py, education_group/tests/ddd/factories/command/postpone_training_and_group_modification_command.py, education_group/tests/ddd/factories/command/update_training_and_group_factory.py, education_group/views/training/update.py, program_management/ddd/command.py, program_management/ddd/service/write/postpone_training_and_program_tree_modifications_service.py, program_management/tests/ddd/factories/commands/postpone_training_and_root_group_modification_with_program_tree.py
=> OSIS-5241 Add rate_code to update training/postpone command

program_management/forms/tree/paste.py, program_management/tests/forms/tree/test_paste.py
Pull request automatique de technical/OSIS-5222 vers DEV
=> [technical/OSIS-5222 => DEV] [TEST]Formation > Contenu > le lien doit être obligatoire par défaut

education_group/views/training/update.py, program_management/views/tree_version/update_training.py
=> OSIS-5242 Fix bad if conditional on training_update

education_group/views/training/update.py, program_management/views/tree_version/update_training.py
Pull request automatique de technical/OSIS-5242 vers DEV
=> [technical/OSIS-5242 => DEV] [TEST+DEV]Formation > Modification > AttributeError >_NoneType_ object has no attribute _name_

base/models/enums/constraint_type.py, education_group/forms/training.py
=> OSIS-5228 Update label name of form/enum

education_group/ddd/domain/training.py, education_group/tests/ddd/domain/test_training.py, education_group/tests/ddd/factories/academic_partner.py, education_group/tests/ddd/factories/co_organization.py
Pull request automatique de technical/OSIS-5233 vers DEV
=> [technical/OSIS-5233 => DEV] [TEST] Formation > Report > Supprimer les co-organisations du report et des contrôles de consistance

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/home.html
=> OSIS-4154 change carousel button trans

education_group/forms/training.py, program_management/forms/version.py
=> OSIS-5228 Capitalize secondary domain label for training form/version

base/fixtures/validation_rules.csv
=> OSIS-5239 Set NOT_REQUIRED rate_code field for certificate type

program_management/business/excel_ue_in_of.py, program_management/forms/custom_xls.py, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/tests/business/test_excel_ue_in_of.py
=> OSIS-4974 : Force majeure in xls (ues in training)

education_group/templates/education_group_app/blocks/layout_detail.html
Pull request automatique de technical/OSIS-5230 vers DEV
=> [technical/OSIS-5230 => DEV] [TEST]Formations > Modification > Ouverture inversée du menu Actions

education_group/views/mini_training/create.py, program_management/ddd/domain/program_tree_version.py, program_management/views/content/update.py
=> OSIS-5119 : Test fail : acronym instead of code

program_management/ddd/service/write/update_and_postpone_mini_training_version_service.py, program_management/ddd/service/write/update_and_postpone_training_version_service.py, program_management/tests/ddd/service/write/test_update_mini_training_version_service.py, program_management/tests/ddd/service/write/test_update_training_version_service.py
Pull request automatique de technical/OSIS-5259 vers DEV
=> [technical/OSIS-5259 => DEV] [DEV]Formation > Modifier une version particulière > prolonger la date de fin d_organisation > le squelette est vide

program_management/static/js/program_management/education_group_tree.js
=> Set tree data on local storage to improve performance

assessments/urls.py, backoffice/urls.py, base/locale/fr_BE/LC_MESSAGES/djangojs.po
=> OSIS-5198 fixed javascript translations

program_management/templates/learning_unit/tab_prerequisite_group.html, program_management/templates/learning_unit/tab_prerequisite_training.html, program_management/views/prerequisite_read.py
=> Osis-4987 Fixed template, add tooltip and add edition prerequisite pour mini formation

education_group/templates/education_group_app/mini_training/identification_read.html, program_management/ddd/command.py, program_management/ddd/domain/program_tree_version.py, program_management/ddd/repositories/program_tree_version.py, program_management/ddd/service/write/create_mini_training_with_program_tree.py, program_management/ddd/service/write/create_program_tree_version_service.py, program_management/ddd/service/write/create_standard_program_tree_service.py, program_management/ddd/service/write/create_training_with_program_tree.py, program_management/tests/ddd/factories/node.py, program_management/tests/ddd/factories/program_tree_version.py, program_management/tests/ddd/service/write/test_create_program_tree_version_service.py, program_management/tests/ddd/service/write/test_create_standard_program_tree_service.py, program_management/tests/ddd/service/write/test_create_standard_version_service.py, program_management/views/tree_version/create.py
=> OSIS-5269 add 'start year' into program tree version

base/models/academic_year.py, education_group/views/mini_training/create.py
=> OSIS-5249 take academic year from parent for create and paste mini training

base/tests/views/learning_units/search/test_educational_information.py, base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/search/educational_information.py
=> OSIS-5243 :  Ne travaillais que sur la 1 iere page affichée

program_management/business/excel_ue_in_of.py, program_management/tests/business/test_excel_ue_in_of.py
=> OSIS-5130 : Les infos crédits et bloc n'étaint pas tj correctes

base/tests/views/learning_units/search/test_educational_information.py, base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/search/educational_information.py
Pull request automatique de hotfix/OSIS-5237 vers QA
=> [hotfix/OSIS-5237 => QA] (234675) Unités d_enseignement > onglet fiches descriptives > Excel Liste des supports de cours obligatoires

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/views/quick_search.py
Pull request automatique de technical/OSIS-5272 vers DEV
=> [technical/OSIS-5272 => DEV] Formations > Arbre > Rechercher > Impossible de réordonner dans la modale

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/views/tree/update.py
=> OSIS-5282 : Fix if no change of links

base/templates/learning_unit/blocks/panel/educational_informations.html
=> OSIS-5280 : Décalage pour la mobility également

base/models/authorized_relationship.py, base/utils/constants.py, program_management/ddd/domain/node.py, program_management/ddd/domain/program_tree.py, program_management/ddd/validators/_attach_finality_end_date.py, program_management/ddd/validators/_authorized_relationship.py, program_management/ddd/validators/_check_finalities_end_date_lower_or_equal_to_2M.py, program_management/ddd/validators/_match_version.py, program_management/ddd/validators/validators_by_business_action.py, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/templates/program_management/content/block/content_form_table.html, program_management/tests/ddd/domain/test_authorized_relationship.py, program_management/tests/ddd/domain/test_program_tree.py, program_management/tests/ddd/factories/authorized_relationship.py, program_management/tests/ddd/factories/program_tree.py, program_management/tests/ddd/service/write/test_paste_node_service.py, program_management/tests/ddd/service/write/test_update_link_service.py, program_management/tests/ddd/validators/test_authorized_relationship.py, program_management/tests/ddd/validators/test_match_version.py, program_management/tests/views/tree_version/test_update_training.py
- relative credit validator not called on paste
- check max count authorized threw exception on relationship not authorized
- node full group title not computed correctly in case of finalities
- do not check versions on mini training
Référence Jira : OSIS-4951
=> OSIS-4951 fix link validators + fix title for node

base/templates/learning_unit/identification.html
=> OSIS-5279 : UE > Lieu d'enseignement est tronqué en consultation

education_group/templates/education_group_app/mini_training/identification_read.html
Pull request automatique de technical/OSIS-5268 vers DEV
=> [technical/OSIS-5268 => DEV] [DEV]Mini-formation > Consultation > Le lieu d_enseignement est tronqué

program_management/views/tree_version/update_training.py
=> OSIS-5254 : Erreur lors de la modification d'une version particulière

program_management/ddd/domain/program_tree.py, program_management/ddd/service/read/allowed_children_types_service.py, program_management/ddd/validators/_has_or_is_prerequisite.py
=> OSIS-5281 fix detach because of cached method descendents

program_management/ddd/domain/exception.py, program_management/ddd/validators/_authorized_relationship.py, program_management/ddd/validators/_detach_option_2M.py, program_management/ddd/validators/_detach_root.py, program_management/ddd/validators/_has_or_is_prerequisite.py, program_management/ddd/validators/validators_by_business_action.py, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/tests/ddd/validators/test_authorized_relationship.py, program_management/tests/ddd/validators/test_detach_option_2M.py, program_management/tests/ddd/validators/test_detach_root.py, program_management/tests/ddd/validators/test_has_or_is_prerequisite.py, program_management/views/tree/detach.py
=> OSIS-5281 handle detach errors when 'couper'

program_management/business/excel_ue_in_of.py
=> OSIS-4974 : Fix custom_xls_form

education_group/ddd/repository/mini_training.py
=> OSIS-5288 fixed queryset to get single EducationGroup from minitraining domain object

attribution/templates/manage_my_courses/educational_information.html
=> OSIS-5255 Enable button if force majeure is open

program_management/business/excel_ue_in_of.py
=> OSIS-4974 : Fix useless header

attribution/templates/manage_my_courses/educational_information.html
Pull request automatique de hotfix/OSIS-5255 vers QA
=> [hotfix/OSIS-5255 => QA] Fiches descriptives sur le portail: actualiser la publication disponible pour cas de force majeure

base/forms/learning_unit/learning_unit_create_2.py
=> OSIS-5298 Order component year qs for learning unit modify form

base/forms/learning_unit/learning_unit_create_2.py
=> [hotfix/OSIS-5298 => QA] Volumes PM et PP inversés lors de la modification d_une UE

base/forms/learning_unit/learning_unit_create_2.py
Pull request automatique de hotfix/OSIS-5298 vers MASTER
=> [hotfix/OSIS-5298 => MASTER] Volumes PM et PP inversés lors de la modification d_une UE

base/business/education_group.py
=> OSIS-5196 : Gestion de l'erreur si pas de management entity version

base/business/learning_units/xls_educational_information_and_specifications.py
=> FIxed format date

base/models/learning_unit_year.py
=> OSIS-5305 : Mot non traduit dans un warning UE

base/fixtures/validation_rules.csv
=> [WIP] [technical/OSIS-5108 => DEV] Problème de synchronisation pour les codes générés automatiquent dans Osis mais qui existent déjà côté EPC

learning_unit/ddd/domain/achievement.py
=> OSIS-5307 Set default value on Achievement as empty str

program_management/business/excel_ue_in_of.py
=> FIxed code climate

program_management/business/excel_ue_in_of.py
=> OSIS-4973 FIxed code climate

attribution/templates/manage_my_courses/educational_information.html
=> OSIS-5255-to-dev Enable button if force majeure is open

education_group/views/training/common_read.py
=> OSIS-5308 disable administrative data tab for program 2M

attribution/views/manage_my_courses.py, base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/pedagogy/update.py
=> Osis 5085 display success messages on pedagogy edit

program_management/static/js/program_management/education_group_tree.js, program_management/views/tree/paste.py
=> Osis 5281 small improvements on paste actions

base/templates/organization/organization.html, base/tests/views/test_organization.py, base/views/organization.py
=> OSIS-5303 Add addresses list on OrganizationRead View

base/fixtures/validation_rules.csv
=> OSIS-5263 update MC validation rule for rate code field

learning_unit/ddd/domain/description_fiche.py, learning_unit/ddd/domain/learning_unit_year.py, learning_unit/ddd/repository/load_learning_unit_year.py, learning_unit/tests/ddd/repository/test_load_learning_unit_year.py, program_management/business/excel_ue_in_of.py, program_management/forms/custom_xls.py, program_management/tests/business/test_excel_ue_in_of.py
=> OSIS-4974 : Adapt code for DEV

program_management/views/tree_version/create.py
=> OSIS-5257 Récupération des titles dans le cas où ceux-ci sont vides

base/business/education_groups/volume_strategy.py, base/forms/learning_unit/edition_volume.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5194 Fixed problème lors dencodage d'une donnée négative

base/business/learning_units/xls_educational_information_and_specifications.py
=> OSIS-4973 Prise en compte des teachning materials

base/business/education_groups/volume_strategy.py, base/forms/learning_unit/edition_volume.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de technical/OSIS-5194 vers DEV
=> [technical/OSIS-5194 => DEV] UE > Composants dans identification > Contrainte >=0

base/business/learning_units/xls_educational_information_and_specifications.py, base/tests/business/learning_units/test_xls_educational_information_and_specifications.py, program_management/business/excel_ue_in_of.py
Pull request automatique de hotfix/OSIS-4973 vers QA
=> [hotfix/OSIS-4973 => QA] UE > Liste des UE avec la fiche descriptive et le cahier des charges > ajouter les colonnes cas de force majeure

program_management/ddd/domain/program_tree.py, program_management/ddd/service/write/detach_node_service.py
=> OSIS-5281 remove prerequisites in tree containing link

education_group/views/training/admission_condition_read.py, education_group/views/training/common_read.py, education_group/views/training/content_read.py, education_group/views/training/general_information_read.py, education_group/views/training/skills_achievements_read.py, program_management/ddd/domain/exception.py, program_management/ddd/service/write/create_and_attach_mini_training_service.py, program_management/ddd/service/write/postpone_training_and_program_tree_modifications_service.py, program_management/ddd/validators/_end_date_between_finalities_and_masters.py, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/tests/views/tree_version/test_update_training.py
=>  OSIS-5248 fixed error messages translations and use cached_property instead of lru_cache

program_management/tests/views/tree/test_detach.py, program_management/views/tree/detach.py
=> OSIS-5277 Fix redirection after detach element on tree

program_management/templates/search.html
=> OSIS-5109 Add pagination (page size) to education group search

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/views/learning_units/create.py
=> OSIS-5314 Ajout du cas d'erreur et du messages d'erreur

base/templatetags/education_group_pdf.py
=> OSIS-5135 Add end icon in the same row line as text on pdf generation

education_group/ddd/domain/_co_graduation.py, education_group/ddd/domain/exception.py, education_group/ddd/domain/service/conflicted_fields.py, education_group/tests/ddd/domain/service/test_conflicted_fields.py
- did not show training fields and group fields at same time
- treat case for co graduation with none and empty value
Référence Jira : OSIS-5211
=> OSIS-5211 fix consistency not displaying fields well

base/static/js/osis_cache.js, base/templates/layout.html, program_management/static/js/program_management/education_group_tree.js
=> OSIS-5327 limit number of items in program tree cache

base/static/js/osis_cache.js, base/templates/layout.html, program_management/static/js/program_management/education_group_tree.js
Pull request automatique de technical/OSIS-5327 vers DEV
=> [technical/OSIS-5327 => DEV] Limiter le nombre d_arbres stockés en cache

program_management/tests/views/test_quicksearch.py, program_management/views/quick_search.py
=> OSIS-5328 Fix Quicksearch to take account of academic year

program_management/ddd/domain/link.py, program_management/ddd/domain/program_tree.py
=> OSIS-5267 default link values when creating specific program

program_management/formatter.py, program_management/tests/views/tree_version/test_delete.py
=> OSIS-5276 : Ajout d'un espace entre Intitulé & [Intitulé version]

base/templatetags/education_group_pdf.py, program_management/formatter.py
=> OSIS-5186 Ajout des version_name pour les options

assessments/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5336 correct translations

program_management/formatter.py
=> OSIS-5186 Eviter les double titre

assessments/business/score_encoding_export.py, assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/templates/online_encoding.html, assessments/tests/views/test_score_encoding.py, assessments/views/upload_xls_utils.py, base/business/learning_unit_xls.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templatetags/education_group_pdf.py, program_management/formatter.py
=> Osis 5337  Update header xls export for learning unit with program

program_management/ddd/domain/node.py, program_management/ddd/validators/_validate_end_date_and_option_finality.py, program_management/templates/program_management/content/block/content_form_table.html, program_management/tests/ddd/factories/program_tree.py
=> Osis 5338 set correct order value when paste

base/business/learning_units/perms.py, base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html, base/views/autocomplete.py, learning_unit/auth/predicates.py, learning_unit/auth/roles/central_manager.py, learning_unit/auth/roles/faculty_manager.py, learning_unit/locale/en/LC_MESSAGES/django.po, learning_unit/locale/fr_BE/LC_MESSAGES/django.po
- fix permission to update force majeure section
Référence Jira : OSIS-4652
=> OSIS-4652 fix permissions

assessments/views/score_encoding.py
=> Osis 4248 Add email of score_sheet_adress to cc 

base/templatetags/education_group_pdf.py, base/tests/templatetags/test_education_group_pdf.py, program_management/formatter.py, program_management/tests/ddd/factories/node.py
=> OSIS-5186 Fixed tiret inutile

assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/templates/scores_responsible/list.html
=> OSIS-5342 Change translation 'sigle' to 'code' on score responsible list

assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5065 : un message n'était pas défini

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/views/mixins.py
=> OSIS-5105-bis : Ajout de la traducation

base/templates/learning_unit/identification.html
=> OSIS-5343 Tronquer le campus

base/templates/learning_unit/pedagogy.html
=> OSIS-5141 Add refresh publication button in pedagogy tab

assessments/views/score_encoding.py
=> OSIS-4243 fix multiple same lines for tutor + correct progression

program_management/tests/ddd/domain/test_program_tree_version.py
=> Fix random failling test on program tree version copy to next year

education_group/forms/mini_training.py, education_group/views/mini_training/update.py, program_management/ddd/domain/exception.py, program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5252-1 correct message + translation

program_management/ddd/validators/_end_date_between_finalities_and_masters.py, program_management/ddd/validators/_paste_option.py, program_management/ddd/validators/_validate_end_date_and_option_finality.py, program_management/ddd/validators/validators_by_business_action.py, program_management/tests/ddd/validators/test_validate_end_date_and_option_finality.py
=> OSIS-5015 fix paste option validator

education_group/templates/education_group_app/group/utilization_read.html
=> OSIS-5348 Change redirection on group in utilization read

base/tests/business/test_perms.py, base/tests/views/test_learning_unit_proposal.py, learning_unit/auth/predicates.py, learning_unit/auth/roles/central_manager.py, learning_unit/auth/roles/faculty_manager.py
=> OSIS-4652 prevent predicates checking period open to raise exception

education_group/views/group/create.py, education_group/views/group/update.py, education_group/views/mini_training/create.py, education_group/views/mini_training/update.py, education_group/views/training/create.py, education_group/views/training/update.py, program_management/ddd/validators/validators_by_business_action.py, program_management/views/tree_version/update_training.py
=> OSIS-5015 fix regression on check finality end date

program_management/forms/tree/paste.py
=> OSIS-5341 display error when link_type field not present

assessments/templates/blocks/deadline_tutor_display.html, assessments/templatetags/tutor_deadline.py, base/static/css/osis.css
=> OSIS-4243 display all tutor deadlines

base/forms/learning_unit/learning_unit_postponement.py
=> OSIS-5256 : consistency of quadrimester

assessments/templates/blocks/deadline_tutor_display.html, assessments/templates/scores_encoding.html, assessments/templates/scores_encoding_by_learning_unit.html, base/static/css/osis.css
=> Osis 4243 align teacher deadline cell

program_management/templates/program_management/content/block/content_form_table.html
=> OSIS-5359 Update learning_unit url redirection on update link modal

education_group/api/serializers/group_element_year.py, education_group/schema.yml, education_group/tests/api/serializers/test_group_element_year.py
=> OSIS-5365 : Add english fields in tree

education_group/api/serializers/education_group_title.py, education_group/api/serializers/group.py, education_group/api/serializers/mini_training.py, education_group/api/serializers/training.py, education_group/schema.yml, education_group/tests/api/serializers/test_education_group_title.py, education_group/tests/api/serializers/test_group.py, education_group/tests/api/serializers/test_learning_unit.py, education_group/tests/api/serializers/test_mini_training.py, education_group/tests/api/serializers/test_training.py, learning_unit/schema.yml
=> OSIS-5366 : Add english fields into details

education_group/api/serializers/education_group_title.py, education_group/api/serializers/mini_training.py, education_group/api/serializers/training.py, education_group/tests/api/serializers/test_education_group_title.py, education_group/tests/api/serializers/test_learning_unit.py, learning_unit/schema.yml
=> OSIS-5371 : Remove title_en from some serializers

education_group/views/mini_training/create.py
=> OSIS-5357 correct academicyear to int based on change in OSIS-5252

base/ddd/utils/business_validator.py, education_group/ddd/domain/exception.py, education_group/ddd/service/write/create_orphan_mini_training_service.py, education_group/ddd/service/write/create_orphan_training_service.py, education_group/ddd/service/write/update_mini_training_and_group_service.py, education_group/ddd/service/write/update_training_and_group_service.py, education_group/tests/views/group/test_create.py, program_management/tests/ddd/service/write/test_update_link_service.py, program_management/tests/views/tree/test_paste.py
Pull request automatique de technical/OSIS-5361 vers DEV
=> [technical/OSIS-5361 => DEV] [DEV]Formation > Nouvelle mini-formation > erreur affichée en double

education_group/templates/education_group_app/training/upsert/update.html, program_management/templates/program_management/content/update.html, program_management/templates/tree_version/training/update.html, program_management/views/content/update.py
Pull request automatique de technical/OSIS-5262 vers DEV
=> [technical/OSIS-5262 => DEV] [DEV]Formation>Modification d_une finalité > ajuster l_en-tête avec l_intitulé

education_group/views/mini_training/create.py
Pull request automatique de technical/OSIS-5357 vers DEV
=> [technical/OSIS-5357 => DEV] [Dev] Arbre > Création approfondissement avec date fin < Bachelier > Traceback

program_management/templates/program_management/content/block/content_form_table.html
Pull request automatique de technical/OSIS-5359 vers DEV
=> [technical/OSIS-5359 => DEV] [DEV]Formation > Arbre > Modifier le lien > le lien sur le code d_une UE redirige vers une _Page not found_

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/proposal_learning_unit.py, base/templates/learning_unit/blocks/dropdown/identification_actions_bar.html, base/tests/models/test_proposal_learning_unit.py, base/tests/views/test_learning_unit.py, base/views/learning_units/create.py
=> Osis 5319 Block partim creation if LU in creation proposal

program_management/templates/blocks/table_element_utilizations.html
=> OSIS-5344 add no keep-tab for training column

base/fixtures/validation_rules.csv
=> OSIS-4900 : Correction coquille

education_group/api/serializers/education_group_title.py, education_group/api/serializers/group_element_year.py, education_group/api/serializers/utils.py
=> OSIS-5376 : Fix some titles

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/pedagogy.html, base/tests/views/test_learning_unit.py, base/views/learning_units/pedagogy/read.py
=> OSIS-5141 Enable publish button if permission ok and luy in current year

education_group/api/serializers/group_element_year.py, education_group/api/serializers/learning_unit.py, education_group/api/serializers/utils.py, education_group/api/url_v1.py
=> OSIS-5377 : disable /versions & /versions/

education_group/schema.yml
=> OSIS-5382 adapt schema to add the 3 ares codes

education_group/api/serializers/training.py, education_group/api/views/training.py, education_group/tests/api/serializers/test_training.py
=> OSIS-5383 add the 3 ares codes to endpoint + adapt test

education_group/api/serializers/training.py, education_group/schema.yml, education_group/tests/api/serializers/test_training.py
Pull request automatique de feature/OSIS-5380 vers DEV
=> [feature/OSIS-5380 => DEV] Il manque 3 codes Ares dans le endpoint /api/v1/education_group/training

program_management/templates/blocks/node_trees_utilizations_table.html
=> OSIS-5344-resolve-conflicts add ?keep-tab=to to url

education_group/api/serializers/education_group_title.py
=> OSIS-5331 : Get title from offer

education_group/tests/api/serializers/test_training.py
=> OSIS-5329 : missing coma

program_management/ddd/repositories/load_node.py
=> OSIS-5391 : get quadri enum

base/business/learning_unit.py
=> OSIS-5090 : Pep08

education_group/tests/api/serializers/test_training.py
=> OSIS-5330 : missing coma

attribution/tests/views/test_manage_my_courses.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/static/js/learning_unit_creation.js, base/templates/learning_unit/pedagogy.html, base/tests/views/test_learning_unit.py, base/views/learning_units/pedagogy/read.py, education_group/api/serializers/education_group_title.py, education_group/api/serializers/group.py, education_group/api/serializers/group_element_year.py, education_group/api/serializers/mini_training.py, education_group/api/serializers/training.py, education_group/api/serializers/utils.py, education_group/schema.yml, education_group/tests/api/serializers/test_group.py, education_group/tests/api/serializers/test_group_element_year.py, education_group/tests/api/serializers/test_learning_unit.py, education_group/tests/api/serializers/test_mini_training.py, education_group/tests/api/serializers/test_training.py
=> Osis 5330 conflict

education_group/ddd/domain/exception.py, education_group/ddd/validators/_start_year_end_year.py, education_group/models/group.py, education_group/views/training/create.py
- Fusion de validation identique avec un message différent
- Suppression du check remontant l'erreur dans la stack pour une exception génré et affiché dans le formulaire
Référence Jira : OSIS-5384
=> OSIS-5384 Correction exception validation et fusion de deux exception identique

education_group/converters.py
=> OSIS-5386 allow dot in acronym for URL + simplify regex

program_management/business/excel_ue_in_of.py, program_management/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5399 : Version title in XLS UE in Offer

program_management/ddd/domain/program_tree.py, program_management/ddd/repositories/program_tree.py, program_management/ddd/validators/_infinite_recursivity.py, program_management/ddd/validators/validators_by_business_action.py, program_management/tests/ddd/validators/test_inifinite_recursivity.py
=> OSIS-5363 fixed infinite loop validator by taking care of chlidren of node to attach

base/api/serializers/student.py, base/tests/api/serializers/test_student.py, webservices/urls.py
Référence Jira : INTERNSHIP-210
=> INTERNSHIP-210 enable API url for internship

education_group/converters.py
because of too many special char used in acronyms
will be reduce in OSIS-4831
=> OSIS-5386-issue1 reuse regex from StringConverter

program_management/templates/tree/link_update_inner.html
=> OSIS-5312 add osis form validation on link update

program_management/ddd/service/write/paste_element_service.py
=> OSIS-5368 save tree after paste and before detach

program_management/locale/en/LC_MESSAGES/django.po, program_management/locale/fr_BE/LC_MESSAGES/django.po, program_management/templates/tree_version/create_specific_version_inner.html, program_management/views/tree_version/check_version_name.py
=> OSIS-5312 specify that a prolong will be done with past version

base/forms/learning_unit/learning_unit_postponement.py, base/tests/forms/test_learning_unit_postponement.py
Pull request automatique de hotfix/OSIS-5395 vers QA
=> [hotfix/OSIS-5395 => QA] Traduction manquante dans le message de report: biennial_even

base/templates/learning_unit/blocks/modal/modal_modification_ask_to_report.html, base/templates/learning_unit/identification.html
=> Hotfix/osis 5390 Bug quand on essaie de sauvegarder la modification d'une UE

base/forms/learning_unit/search/simple.py
Pull request automatique de hotfix/OSIS-4401 vers QA
=> [hotfix/OSIS-4401 => QA] Recherche sur les UE > Tri sur les types incorrecte

program_management/business/excel_ue_in_of.py
=> OSIS-5399 : remove bracket if no version title

base/forms/learning_unit/search/quick_search.py, program_management/views/quick_search.py
=> OSIS-5397 adapt queryset to not show result when filter empty

assessments/templates/blocks/deadline_tutor_display.html, assessments/templates/scores_encoding.html, assessments/templates/scores_encoding_by_learning_unit.html
=> OSIS-5396 Fix cell display (spaces instead of row+col)

base/context_processors/user_manual.py
=> OSIS-5408 : edit url

program_management/business/excel.py, program_management/formatter.py
=> OSIS-5400 : Missing version title

assessments/business/score_encoding_list.py, assessments/views/score_encoding.py
=> OSIS-4197 do not allow tutor to submit scores if deadline is reached or in past

program_management/ddd/domain/exception.py, program_management/ddd/domain/node.py, program_management/ddd/domain/program_tree.py, program_management/ddd/repositories/_persist_prerequisite.py, program_management/ddd/repositories/load_tree.py, program_management/ddd/validators/_has_or_is_prerequisite.py, program_management/ddd/validators/_prerequisites_items.py, program_management/templates/program_management/templatetags/prerequisite/is_prerequisite.html, program_management/tests/ddd/domain/test_program_tree.py, program_management/tests/ddd/validators/test_has_or_is_prerequisite.py, program_management/tests/ddd/validators/test_prerequisite_items.py, program_management/views/prerequisite_update.py
=> OSIS-5372 Fixes on prerequisites validators for "detach" and "update prerequisites" actions

program_management/business/excel_ue_in_of.py
=> OSIS-5399 : translate main gathering node title

base/templatetags/navigation.py
=> OSIS-5379 Fixed soucis lorsqu'on passait d'un training à un autre type

program_management/ddd/domain/program_tree.py, program_management/ddd/validators/_prerequisites_items.py, program_management/tests/ddd/domain/test_program_tree.py, program_management/tests/ddd/validators/test_prerequisite_items.py
=> OSIS-5372 Fixes on prerequisites usage in bachelor and minors

base/context_processors/user_manual.py
Pull request automatique de hotfix/OSIS-5408 vers QA
=> [hotfix/OSIS-5408 => QA] [Echec Qa] - Suppression ? vert et remplacement du lien ? gris

program_management/business/excel_ue_in_of.py, program_management/tests/business/test_excel_ue_in_of.py
=> OSIS-5399 : get group or offer title

assessments/business/score_encoding_list.py
Pull request automatique de hotfix/OSIS-4197 vers QA
=> [hotfix/OSIS-4197 => QA] Empêcher un professeur de soumettre ses notes si la date d_échéance est atteinte

program_management/business/excel.py, program_management/tests/business/test_excel.py
=> OSIS-5400 : Get group or offer title

program_management/ddd/service/write/update_and_postpone_training_version_service.py, program_management/tests/ddd/service/write/test_update_training_version_service.py
=> OSIS-5403 : Do not edit GroupYear title if update version title

attribution/templates/attribution/attributions.html, attribution/views/attribution.py, base/urls.py
Pull request automatique de technical/OSIS-5421 vers DEV
=> [technical/OSIS-5421 => DEV] UE_s > Flèche _suivante_ sur onglet Enseignant.e.s

program_management/business/excel_ue_in_of.py
Pull request automatique de hotfix/OSIS-5427 vers QA
=> [hotfix/OSIS-5427 => QA] Formations > Excel Liste des UE_s traceback lorsque pas d_UE_s

education_group/tests/forms/test_group.py, education_group/tests/views/mini_training/test_update.py, education_group/views/mini_training/update.py
=> OSIS-5418 Fixed save du formulaire quand end_year est indéterminé

education_group/tests/forms/test_group.py, education_group/tests/views/mini_training/test_update.py, education_group/views/mini_training/update.py
Pull request automatique de technical/OSIS-5418 vers DEV
=> [technical/OSIS-5418 => DEV] [DEV][QA] Impossible d_éditer une mini-formation

education_group/api/serializers/learning_unit.py
=> OSIS-5435 : Get correct url for standard version

assessments/templates/scores_encoding.html, assessments/templates/scores_encoding_by_learning_unit.html
Pull request automatique de hotfix/OSIS-5414 vers QA
=> [hotfix/OSIS-5414 => QA] Encodage de notes > mise en page tooltips

base/templates/offers.html
=> OSIS-5437 : Adresses > Remplacer 'Acronyme' par 'Sigle/Inititulé abrégé'

base/views/learning_units/search/common.py
=> OSIS-5146-corriger-pour-travis

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/base/person_list.html, base/views/user_list.py
=> Osis 5440 Adapt user-list based on osis-role refactoring

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/base/person_list.html, base/views/user_list.py
Pull request automatique de hotfix/OSIS-5440 vers QA
=> [hotfix/OSIS-5440 => QA] Institution > Liste des Utilisateurs > Traceback

assessments/templates/scores_encoding.html, assessments/templates/scores_encoding_by_learning_unit.html, education_group/views/mini_training/skills_achievements_read.py, education_group/views/training/skills_achievements_read.py
Pull request automatique de hotfix/OSIS-5234 vers DEV
=> [hotfix/OSIS-5234 => DEV] Candidature en ligne > permission manquante

base/templatetags/navigation.py, base/tests/templatetags/test_navigation.py
=> OSIS-5379 Correctif sur les fleches de navigation UE et OF

learning_unit/auth/roles/central_manager.py, learning_unit/auth/roles/faculty_manager.py
Pull request automatique de hotfix/OSIS-5444 vers QA
=> [hotfix/OSIS-5444 => QA] Faulty_manager_for_ue: pas d_accès au catalogue

learning_unit/auth/roles/central_manager.py, learning_unit/auth/roles/faculty_manager.py
Pull request automatique de hotfix/OSIS-5444 vers MASTER
=> Release 3.0.4

learning_unit/auth/roles/central_manager.py, learning_unit/auth/roles/faculty_manager.py
Pull request automatique de hotfix/OSIS-5444 vers DEV
=> [hotfix/OSIS-5444 => DEV] Faulty_manager_for_ue: pas d_accès au catalogue

base/templates/learning_unit/search/external.html
=> OSIS-5163 fix blank insitutiion for external search

cms/models/translated_text.py, learning_unit/ddd/repository/load_description_fiche.py, learning_unit/ddd/repository/load_description_fiche_force_majeure.py, learning_unit/ddd/repository/load_learning_unit_cms.py, learning_unit/ddd/repository/load_specification.py
=> OSIS-5321 refactor code

learning_unit/ddd/repository/load_specification.py
=> OSIS-5321 no revisions loading for specification

base/business/learning_units/edition.py
Pull request automatique de hotfix/OSIS-5419 vers MASTER
=> [hotfix/OSIS-5419 => MASTER] [DEV] Impossible de consolider une proposition de suppression

base/auth/roles/entity_manager.py
=> OSIS-5456 Ajout de dissertation.change_offerproposition

base/templates/learning_unit/search/external.html
Pull request automatique de hotfix/OSIS-5163 vers QA
=> [hotfix/OSIS-5163 => QA] Affichage de l_institution erroné dans la recherche d_UE externe

backoffice/triggers/update_group_years_unversioned_fields.sql
=> OSIS-5403 : Using NEW : if INSERT old does not exist

education_group/templates/education_group_app/training/identification_read.html
=> OSIS-5312 collapse warning barrier by default

education_group/api/url_v1.py, education_group/converters.py, education_group/urls.py, program_management/urls.py
=> OSIS-5464 : Remise l'ancienne mode des url_v1

base/forms/learning_unit/search/simple.py, base/tests/forms/learning_unit/test_search_form.py
Pull request automatique de hotfix/OSIS-5463 vers QA
=> [hotfix/OSIS-5463 => QA] Message d_erreur quand on fait une recherche d_UE avec un enseignant qui a un nom composé

program_management/ddd/service/write/publish_program_trees_using_node_service.py
=> OSIS-5466 call publish on himself when node is root

program_management/ddd/service/write/publish_program_trees_using_node_service.py
Pull request automatique de hotfix/OSIS-5466 vers MASTER
=> Release 3.0.11

education_group/ddd/service/write/update_training_and_group_service.py
=> OSIS-5403 : Update training before group

assessments/business/score_encoding_export.py
=> OSIS-5473 : PEPS > Type PEPS > Remplacer "Non défini" par "-"

assessments/business/score_encoding_export.py
Pull request automatique de hotfix/OSIS-5473 vers MASTER
=> Release 3.0.12

assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/tests/views/test_upload_xls_utils.py, assessments/views/upload_xls_utils.py
=> [QA] Hotfix/osis 5086

attribution/business/application_json.py
=> OSIS-4251 modify tutor application json field

education_group/schema.yml, learning_unit/schema.yml, program_management/schema.yml
=> OSIS-5476 : quotes and version in schema

education_group/api/serializers/group_element_year.py, education_group/api/views/group_element_year.py, education_group/tests/api/serializers/test_group_element_year.py
=> OSIS-5430 : Get not children of minor list choice within bachelor

education_group/api/serializers/group_element_year.py, education_group/api/views/group_element_year.py, education_group/tests/api/serializers/test_group_element_year.py
=> OSIS-5430 : Fix : Hide mini_training content instead of minor/major list

base/migrations/0551_remarks_annualized.py
=> OSIS-4142 : rename migration

education_group/api/views/mini_training.py, education_group/api/views/training.py, education_group/api/views/utils.py, education_group/tests/api/views/test_training.py
=> OSIS-5487 : fix filter version_type

base/fixtures/groups.json
Pull request automatique de hotfix/OSIS-5488 vers QA
=> [hotfix/OSIS-5488 => QA] Fiches descriptives: modifiables par les profs alors que périodes fermées

base/fixtures/groups.json
Pull request automatique de hotfix/OSIS-5488 vers MASTER
=> Release 3.0.14

base/migrations/0551_remarks_annualized.py
=> OSIS-4142 : Fix migration script

assessments/templates/online_encoding.html
=> OSIS-5442 : Ajustement du look d'un tooltip sur un bouton

base/migrations/0552_remarks_annualized.py, base/migrations/0553_auto_20210108_1118.py
=> Fix migrations dependencies

learning_unit/api/serializers/component.py
=> OSIS-5492 : Not display trailing zero from decimal

backoffice/triggers/update_group_years_unversioned_fields.sql, base/management/commands/load_triggers.py, base/tests/utils/test_load_sql_scripts.py, base/utils/load_sql_scripts.py, education_group/ddd/service/write/update_training_and_group_service.py, education_group/tests/models/test_group_year.py
@edd19 Prévoir l'appel à load_triggers à chaque déploiement ???
=> [QA]hotfix/osis-5403 : trigger for group year

base/migrations/0552_remarks_annualized.py
=> OSIS-4604 : update changed

learning_unit/api/serializers/component.py
=> OSIS-5492 : Fix volume if none

learning_unit/api/serializers/component.py, learning_unit/tests/api/serializers/test_component.py
=> OSIS-5492 : Fix test and normalize

attribution/business/attribution_json.py, attribution/tests/business/test_attribution_json.py
=> OSIS-4220 : Ajout d'un critère pour le recompute

education_group/api/serializers/group_element_year.py, education_group/tests/api/serializers/test_group_element_year.py
Pull request automatique de hotfix/OSIS-5494 vers QA
=> [hotfix/OSIS-5494 => QA] Le type de proposition d_une UE n est pas bien envoyé dans le WS /tree

base/tests/utils/test_load_sql_scripts.py, education_group/ddd/service/write/update_training_and_group_service.py, education_group/tests/api/serializers/test_group_element_year.py
=> Pull qa into dev

learning_unit/api/views/attribution.py, learning_unit/tests/api/views/test_attribution.py
=> OSIS-5493 : remove coordinator without volume

base/migrations/0554_remove_in_charge.py
=> technical/OSIS-5499 : Vérification de la présence d'in_charge

program_management/ddd/repositories/load_tree.py, program_management/tests/ddd/repositories/test_load_tree.py
=> OSIS-5372 fixed case when try to  load multiple roots when one root is contained inside the other root
