internship/forms.py, internship/models.py, internship/templates/internship_detail.html, internship/templates/internship_modification.html, internship/templates/internships.html, internship/templates/internships_create.html, internship/templates/internships_home.html, internship/templates/internships_stud.html, internship/templates/period_create.html, internship/templates/periods.html, internship/templates/place_detail.html, internship/templates/place_form.html, internship/templates/places.html, internship/templates/places_stud.html, internship/templates/student_resume.html, internship/templates/student_search.html, internship/urls.py, internship/views/home.py, internship/views/internship.py, internship/views/period.py, internship/views/place.py, internship/views/student_resume.py
=> Travail sur l'interface globale des écrans de stages (Issue#742)

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/learning_unit_enrollment.py, base/templates/learning_unit.html, base/views/learning_unit.py
=> #786 display enrollment to the teaching unit

internship/templates/place_form.html, internship/templates/places.html, internship/urls.py, internship/views/place.py
=> Possibilité de modifier les hôpitaux existants (Issue#789)

backoffice/settings.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/logged_out.html, base/urls.py, base/views/common.py, louvain/views/common.py
Inform the ticket you are solving in this pull request: #821 
Comment: @htmfilho Il faut que je teste sur dev les modif de configurtation.
=> #821 logout local + server

base/templates/assessments/online_encoding.html, base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #820 
Comment: 
=> #820 updated progression's display

base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #845
Comment: 
=> #845 fixed print of '0' in PDF

backoffice/urls.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/server_error.html, base/views/common.py
=> #839 ajout values dans render

base/static/css/custom.css, base/templates/assessments/online_encoding.html, base/templates/assessments/scores_encoding.html, base/templates/assessments/scores_encoding_by_learning_unit.html, base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #820
Comment: 
=> #820 changed progress bar's display

base/utils/upload_xls_utils.py
Inform the ticket you are solving in this pull request: #851
Comment: 
=> #851 added try-except in case of KeyError

base/templates/academic_calendar.html, base/templates/academic_calendar_form.html, base/templates/organization_address_form.html, base/templates/organization_form.html, base/templatetags/full_width.py, base/templatetags/get_at_index.py, base/views/score_encoding.py
Simple test refactorings for readability
=> Simple test refactorings for readability

base/templates/layout.html
Inform the ticket you are solving in this pull request: #820
Comment: 
=> #820 updated cache custom.css

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/utils/upload_xls_utils.py
Inform the ticket you are solving in this pull request: #871
Comment: 
=> #871 error message in case 'session' column is empty

base/models/exam_enrollment.py, base/templates/assessments/scores_encoding_by_specific_criteria.html, base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #877
Comment: 
=> #877 list's sort in 'by specific criteria' tab

base/templates/offer_year_calendar.html
Inform the ticket you are solving in this pull request: #885
Comment: 
=> #885 'edit' button only if academicCalendar.start_date/end_date is set

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/utils/export_utils.py, base/utils/send_mail.py
Inform the ticket you are solving in this pull request: #859 
Comment: 
=> #859 modif session vers sessionn

base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #917
Comment: 
=> #917 admin : permissions for examEnrollmentHistory + search_fields

base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #917 
Comment: 
=> #917 get_actions() to hide the dropdownlist with the 'delete' option

base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #917
Comment: 
=> #917 readonly fields

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/academic_year.py, base/utils/upload_xls_utils.py
Inform the ticket you are solving in this pull request: #929 
Comment: 
=> #929 error message in case of wrong academic year

backoffice/queue/queue.py, base/apps.py
Inform the ticket you are solving in this pull request: #934
=> Treated the exception when connecting to message queue

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/utils/upload_xls_utils.py, base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #940
Comment: 
=> #940 correction of excel file injection

base/static/js/osis.js, base/templates/layout.html
Inform the ticket you are solving in this pull request: #945
=> #945 Removed Javascript test

base/templates/layout.html
Inform the ticket you are solving in this pull request: #945
Comment: 
=> #945 Removed latest trace of the divs

base/utils/upload_xls_utils.py
Inform the ticket you are solving in this pull request: #962
=> #962 correction of indentation to inject draft scores

internship/views/home.py
=> index out of range if no interships home page (issue#905)

internship/views/home.py
=> check if the user is a student, if not the noma is 0 (issue#921)

base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #810
Comment: 
=> #810 correction of message text 'scores' --> 'notes'

base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #967
Comment: 
=> #967 correct deadline displayed in scores' sheets

internship/templates/internship_modification.html, internship/templates/internships.html, internship/templates/internships_create.html, internship/templates/internships_stud.html, internship/templates/student_search.html, internship/views/internship.py
Inform the ticket you are solving in this pull request: #895 
Comment: 
=> Sélection de l'hôpital sauvegardé (Issue#895)

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #918
Comment: 
=> Fichiers traduction Assistants - incomplet

internship/views/internship.py
=> Problème pour l'appel de la page /internships/internships/std/ (issue#973)

internship/templates/interships_masters.html
Inform the ticket you are solving in this pull request: #952 
Comment: 
=> #952 Cacher bouton upload master si pas gestionnaire de stage

assistant/templates/assistant_mandates.html, assistant/urls.py, assistant/views/assistant.py, assistant/views/home.py
Inform the ticket you are solving in this pull request: #980 
Comment: 
=> Tableau de bord assistants

internship/locale/en/LC_MESSAGES/django.po, internship/locale/fr_BE/LC_MESSAGES/django.po
=> Mettre en place les fichier de traductions (issue#976)

internship/models.py, internship/views/internship.py
=> Internships are display in alphabetical order of the speciality (issue#992)

base/migrations/0058_add_initial_users_to_groups.py
Inform the ticket you are solving in this pull request: #865 
Comment: 
=> #865 correction init migration users perm

base/models/models_signals.py, base/models/program_manager.py, base/models/student.py, base/models/tutor.py
=> #865 ajout dans group si creation student,pgm_manager,tutor via signals

internship/locale/en/LC_MESSAGES/django.po, internship/locale/fr_BE/LC_MESSAGES/django.po, internship/templates/internships.html, internship/templates/interships_masters.html, internship/templates/places.html
=> Add new translation lines (Issue#976)

base/templates/studies.html, louvain/authentication/shibboleth_auth.py
Inform the ticket you are solving in this pull request: #865 
Comment: @htmfilo contient les modif dues aux tests, je mergerai quand j'aurais fini de tester en dev
=> #865 modif alignement template

louvain/authentication/shibboleth_auth.py
=> #865 modif config user shibb

internship/locale/en/LC_MESSAGES/django.po, internship/locale/fr_BE/LC_MESSAGES/django.po, internship/templates/internship_modification_student.html, internship/templates/internships_stud.html, internship/templates/student_resume.html, internship/views/internship.py
=> Corrections suite aux tests en Dev (Issue#1008)

internship/admin.py
=> #admin model

internship/views/student.py
=> #1007 modif import

internship/templates/student_information_modification.html, internship/templates/student_resume.html, internship/urls.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1013 
Comment: 
… edition. Add the method to edit datas. Edit them, then go back in the student sumup
=> Modification des informations des étudiants (dans la partie stage) (Issue#1013)

internship/views/student.py
=> #1007 modif ordre colonne import

internship/models.py, internship/templates/student_information_modification.html, internship/templates/student_resume.html, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1018
Comment: 
=> #1018 corrections

internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1018 
Comment: Creation info si innexistante
=> #1018 creation info si non existante

internship/locale/en/LC_MESSAGES/django.po, internship/locale/fr_BE/LC_MESSAGES/django.po, internship/templates/internships_stud.html, internship/views/home.py, internship/views/internship.py, internship/views/master.py, internship/views/place.py
=> [Internship] Correction après tests (Issue#1018)

internship/admin.py
Inform the ticket you are solving in this pull request: #1030 
Comment: 
=> #1030 modif site admin pour InternshipStudentInformations

internship/admin.py
=> #1030 erreur list search field

internship/admin.py, internship/locale/fr_BE/LC_MESSAGES/django.po, internship/models.py, internship/templates/internship_modification_student.html, internship/templates/internships.html, internship/templates/internships_home.html, internship/templates/internships_stud.html, internship/templates/interships_masters.html, internship/templates/place_form.html, internship/templates/places.html, internship/templates/student_search.html, internship/templates/students.html, internship/upload_xls.py, internship/urls.py, internship/views/internship.py, internship/views/master.py, internship/views/place.py, internship/views/student.py, internship/views/student_resume.py
=> Issue#1032

internship/models.py, internship/templates/student_resume.html, internship/templates/student_search.html, internship/templates/students.html, internship/views/speciality.py, internship/views/student.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1038
Comment: 
=> Ajustements d'interface et de créations de spécialité (Issue#1038)

internship/templates/internships_stud.html
Inform the ticket you are solving in this pull request: #1047
Comment: 
=> Désactivation du tri des offres de stage par hopital

internship/templates/internships_stud.html
Inform the ticket you are solving in this pull request: #1047
=> Issue#1047

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1053 
Comment: Le check n'était pas fait sur le bon objet, ce qui entraînait l'erreur
=> Correction d'un AttributeError (Issue#1053)

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1053
=> Issue #1053

internship/templates/student_search.html, internship/views/internship.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1056 
Comment: 
=> Corrections d'erreurs (Issue#1056)

internship/templates/student_search.html, internship/views/internship.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1056
=> Issue #1056

internship/views/internship.py, internship/views/master.py, internship/views/period.py, internship/views/place.py, internship/views/speciality.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1063 
Comment: la requête request.POST[...] entraîne des erreurs de multivaluekeydicterror, remplacement de toutes ces requêtes par la méthode request.POST.get(...) qui elle ne provoque pas cette erreur et retourne la bonne valeur
=> correction des request.POST (Issue#1063)

internship/views/internship.py, internship/views/master.py, internship/views/period.py, internship/views/place.py, internship/views/speciality.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1063
=> Issue#1063

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1067 
Comment: 
…s avant init
=> Correction sur des listes utilisées avant référencement (issue#1067)

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1067
=> Issue #1067

louvain/authentication/shibboleth_auth.py
=> #1071 modif si email pas formé comme d'ahb

internship/admin.py, internship/models.py, internship/templates/internship_modification_student.html, internship/templates/students.html, internship/views/internship.py, internship/views/student.py
Inform the ticket you are solving in this pull request: #1076 
Comment: Suite au commencement de la modification des stages par STAC, plusieurs erreurs ont été relevées
=> Ajustement dans la modification des stages par l'administration (Issue#1076)

internship/admin.py, internship/models.py, internship/templates/internship_modification_student.html, internship/templates/students.html, internship/views/internship.py, internship/views/student.py
Inform the ticket you are solving in this pull request: #1076
=> Issue #1076

internship/templates/internship_modification_student.html, internship/views/internship.py
Inform the ticket you are solving in this pull request: #1076
=> Variable init avant d'être utilisée

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1088
=> Init list before use

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/utils/pdf_utils.py
Inform the ticket you are solving in this pull request: #872
Comment: 
=> #872 Today's date in the scores' sheet

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1088 
Comment: Report du patch 16.7.1.8 en Dev
=> #1088 (report patch en dev)

internship/upload_xls.py
Inform the ticket you are solving in this pull request: #1085 
Comment: 
=> Déplacement du check_internship qui pose soucis si plusieurs spec

internship/admin.py
Inform the ticket you are solving in this pull request: #1043
=> Utilisation d'une FK pour n'afficher que l'ID dans la page d'admin

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1093
=> Correction IndexError

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1093
=> Issue #1093

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1095
=> Calcul de distance entre 2 adresses (Issue#1095)

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/utils/export_utils.py
Inform the ticket you are solving in this pull request: #872
Comment: 
=> #872 production date in excel file

dissertation/models/adviser.py, dissertation/templates/manager_informations_list.html
=> Issue#1141

dissertation/locale/en/LC_MESSAGES/django.po, dissertation/locale/fr_BE/LC_MESSAGES/django.po
=> ajout des texts messages en lien avec 1114 et 1141

dissertation/views/dissertation.py
Inform the ticket you are solving in this pull request: #1154 
=> Issue#1154 bugfix 

base/models/exam_enrollment.py, base/models/offer_year.py, base/models/offer_year_calendar.py, base/views/academic_calendar.py
Inform the ticket you are solving in this pull request: #1152
=> #1152 tests & preparation of the third session exam

assistant/templates/assistant_form_part1.html, assistant/templates/assistant_mandates.html
Inform the ticket you are solving in this pull request: #1099 
Comment: 
=> Modifications tableau de bord assistant

base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1180
=> #1180 correction of get_score_encoded() (branch from QA)

base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1184 
=> #1184 corection of last scores encodings date display

base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1197 
=> #1197 bugfix filter object is not recognized as a list

base/templates/assessments/scores_encoding_by_specific_criteria.html
Inform the ticket you are solving in this pull request: #1199
=> #1199 bugfix possibility to encode scores < 0

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #1164 
=> Continuation of the translation

internship/forms.py, internship/models.py, internship/templates/period_create.html, internship/templates/periods.html, internship/templates/specialities.html, internship/templates/speciality_create.html, internship/urls.py, internship/views/period.py, internship/views/speciality.py
Inform the ticket you are solving in this pull request: #1104
=> Modification des périodes et spécialités

assistant/forms.py, assistant/templates/mandate_form.html
Inform the ticket you are solving in this pull request: #1170 
=> Mandate form look and feel

base/models/person.py, base/models/student.py, base/models/tutor.py
Inform the ticket you are solving in this pull request: #1230 
=> #1230 modification envoie dans queue

base/models/models_signals.py, base/models/person.py
Inform the ticket you are solving in this pull request: #1230 
=> #1230 modification envoi dans queue ajout tutor student

assistant/templates/mandates_list.html, assistant/views/assistant_form.py
Inform the ticket you are solving in this pull request: #1166 
=> afficher les reviews dans tableau de bord manager

backoffice/portal_migration.py, base/models/student.py, base/models/tutor.py
Inform the ticket you are solving in this pull request: #1230 
=> #1230 envoi message un par un

base/views/institution.py
Inform the ticket you are solving in this pull request: #1240
=> #1240 suppression des test de droits pour accès structure (Merge into Qa)

base/views/offer.py
Inform the ticket you are solving in this pull request: #1240 
=> #1240 correction acces methode

dissertation/templates/manager_proposition_dissertation_detail.html, dissertation/templates/proposition_dissertation_detail.html, dissertation/views/proposition_dissertation.py
Inform the ticket you are solving in this pull request: #1246 
=> issue#1246 neutralisation jury proposition_dissertation

internship/forms.py, internship/models.py, internship/templates/place_form.html, internship/upload_xls.py, internship/views/place.py
Inform the ticket you are solving in this pull request: #1252
=> Rectification des bugs dans internship après mise en prod release 16.8.2.0 (Issue#1252)

internship/forms.py, internship/models.py, internship/templates/place_form.html, internship/upload_xls.py, internship/views/place.py
Inform the ticket you are solving in this pull request: #1252 
=> Issue#1252

internship/models.py
Inform the ticket you are solving in this pull request: #1252 
=> #1252 modif encodage url

dissertation/models/faculty_adviser.py, dissertation/models/offer_proposition.py
Inform the ticket you are solving in this pull request: #1264
=> issue#1264 champ offer en raw_id_field

internship/models.py
Inform the ticket you are solving in this pull request: #1270
=> Ajustement calcul latitude longitude (issue#1270)

internship/models.py
Inform the ticket you are solving in this pull request: #1270 
=> Issue#1270

base/models/offer_year.py, base/models/student.py, dissertation/models/dissertation.py, dissertation/models/dissertation_role.py, dissertation/models/faculty_adviser.py, dissertation/models/offer_proposition.py, dissertation/models/proposition_dissertation.py, dissertation/templates/manager_dissertations_list.html, dissertation/templates/manager_dissertations_wait_commission_list.html, dissertation/templates/manager_dissertations_wait_eval_list.html, dissertation/templates/manager_dissertations_wait_list.html, dissertation/templates/manager_dissertations_wait_recep_list.html, dissertation/templates/manager_informations_detail_list.html, dissertation/templates/manager_informations_list_request.html, dissertation/views/dissertation.py, dissertation/views/information.py, dissertation/views/offer_proposition.py, dissertation/views/proposition_dissertation.py
Inform the ticket you are solving in this pull request: #1248
=> Issue#1248 Accept multiples faculty_adviser for adviser

base/static/js/osis.js
Inform the ticket you are solving in this pull request: #1207 
=> #1207 Algorithm corrigé.

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1306
=> Correction sur le calcul des distances (Issue#1306)

dissertation/templates/informations_detail_stats.html, dissertation/templates/manager_informations_detail_stats.html
=> ajout des chart JS en remplacement des google Charts

dissertation/templates/manager_offer_parameters_edit.html
Inform the ticket you are solving in this pull request: #1205 
=> issue#1205 correction bug champs dates

assistant/forms.py
Inform the ticket you are solving in this pull request: #1334 
=> resolve osis installation error when DB not initialized

internship/templates/student_search.html, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1284
=> Adapter la fonction de recherche dans le bilan des étudiants (Issue#1284)

internship/views/internship.py
Inform the ticket you are solving in this pull request: #1297 
of speciality and no more by juste the name
=> Compute the number of choice by the acronym (issue#1297)

internship/models.py, internship/views/place.py
Inform the ticket you are solving in this pull request: #1323
=> Correction lors de la création d'un nouvel hôpital (issue#1323)

internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1284
=> Add partial research (Issue#1284)

base/templates/layout.html
Inform the ticket you are solving in this pull request: #1346 
=> issue#1346 correction lien source code

internship/templates/internship_affectation_statics.html
Inform the ticket you are solving in this pull request: #1362 
=> #1362 correextion trad

internship/views/affectation_statistics.py
Inform the ticket you are solving in this pull request: #1364 
=> #1364 test

internship/views/affectation_statistics.py
=> Revert "#1364 test"

dissertation/locale/en/LC_MESSAGES/django.po, dissertation/locale/fr_BE/LC_MESSAGES/django.po, dissertation/templates/informations_add.html, dissertation/views/information.py
Inform the ticket you are solving in this pull request: #1341 
=> issue#1341 bugfix

backoffice/portal_migration.py, backoffice/queue/queue_actions.py
Inform the ticket you are solving in this pull request: #1368 
=> #1368 except rabbit not launched

internship/views/affectation_statistics.py
Inform the ticket you are solving in this pull request: #1373
=> Comment a function

internship/models.py, internship/templates/internship_affectation_statics.html, internship/templates/student_search.html, internship/utils/upload_xls.py, internship/views/affectation_statistics.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1376
=> Corrections après démonstrations (Issue#1376)

internship/models.py, internship/templates/internship_affectation_statics.html, internship/templates/student_search.html, internship/utils/upload_xls.py, internship/views/affectation_statistics.py, internship/views/student_resume.py
=> Issue#1376

dissertation/views/dissertation.py
Inform the ticket you are solving in this pull request: #1382 
Attention : patch à merger en `qa`
=> issue#3182 correction page accueil pour user qui est student + tutor

dissertation/views/dissertation.py
Inform the ticket you are solving in this pull request: #1382 
=> Issue#1382

internship/templates/internships_home.html, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1407 
=> Suppression temporaire accès

internship/templates/internship_affectation_sumup.html, internship/templates/student_affectation_modification.html, internship/templates/student_resume.html, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1411
=> Corrections après test en QA avec les utilisateurs (Issue#1411)

internship/templates/internship_affectation_sumup.html, internship/templates/student_affectation_modification.html, internship/templates/student_resume.html, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1411
=> Issue#1411

internship/templates/internships_home.html
Inform the ticket you are solving in this pull request: #1414 
=> #1414 affichage des liens pour les gestionnaires de stages

internship/templates/internship_affectation_sumup.html, internship/templates/place_detail_affectation.html, internship/views/affectation_statistics.py, internship/views/place.py
Inform the ticket you are solving in this pull request: #1419
=> Modification d'interface pour grouper 3 tableaux en 1 (Issue#1419)

internship/templates/internship_affectation_sumup.html, internship/templates/place_detail_affectation.html, internship/views/affectation_statistics.py, internship/views/place.py
Inform the ticket you are solving in this pull request: #1419 
=> Issue#1419

dissertation/templates/dissertations_jury_edit.html, dissertation/templates/manager_dissertations_jury_edit.html, dissertation/templates/manager_proposition_dissertations_jury_edit.html, dissertation/templates/proposition_dissertations_jury_edit.html, dissertation/views/dissertation.py, dissertation/views/proposition_dissertation.py
Inform the ticket you are solving in this pull request: #1422
=> #1422 Correction des balises Required

base/migrations/0070_scoresencoding.py, base/models/scores_encoding.py
Inform the ticket you are solving in this pull request: #1278
=> #1278 Correction of 'scoresEncoding' view

internship/views/affectation_statistics.py
Inform the ticket you are solving in this pull request: #1442 
=> Fix bug - assignation des stages (Swap only normal internships)

internship/views/affectation_statistics.py
Inform the ticket you are solving in this pull request: #1442
=> Issue#1442

internship/templates/internship_affectation_statics.html, internship/views/affectation_statistics.py
Inform the ticket you are solving in this pull request: #1448 
=> correction Bug sur la page "Affection des stages"

internship/templates/internship_affectation_statics.html, internship/views/affectation_statistics.py
Inform the ticket you are solving in this pull request: #1448
=> Issue#1448

internship/admin.py
Inform the ticket you are solving in this pull request: #1461 
=> #1461 modif admin

internship/templates/internship_affectation_statics.html
Inform the ticket you are solving in this pull request: #1461 
=> #1461 modif template

internship/admin.py, internship/templates/internship_affectation_statics.html
Inform the ticket you are solving in this pull request: #1461 
=> #1461 format date time

internship/templates/internship_affectation_statics.html
Inform the ticket you are solving in this pull request: #1476 
=> #1476 cahcer le bouton

base/models/student.py, internship/locale/en/LC_MESSAGES/django.po, internship/locale/fr_BE/LC_MESSAGES/django.po, internship/templates/student_resume.html, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1482
=> Bugfix/1482 (To Dev)

internship/templates/internships_home.html
Inform the ticket you are solving in this pull request: #1482
=> #1482 affichage du lien pour les étudiants (To Dev)

internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1482 
=> #1482 raise forbidden exception instead of simple acces denied page

backoffice/settings.py, base/templates/layout.html, requirements.txt
Inform the ticket you are solving in this pull request: #1490
=> Ajout analytical to QA

backoffice/settings.py, base/templates/layout.html, requirements.txt
=> Bugfix/1490 to Dev

base/models/student.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1500
=> Bugfix/1500 => Dev

base/models/student.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1500 
=> #1500 modif get internshipChoice

assistant/models/assistant_mandate.py, assistant/views/assistant.py
Inform the ticket you are solving in this pull request: #1324 
=> bug correction

dissertation/views/proposition_dissertation.py
Inform the ticket you are solving in this pull request: #1511 
Attention : Patch donc ce PR est en QA, je fais aussi le PR en dev à côté.
=> Patch -> QA : issue#1511 amélioration export XLS

dissertation/models/dissertation.py, dissertation/models/dissertation_role.py, dissertation/models/dissertation_update.py, dissertation/models/faculty_adviser.py, dissertation/models/proposition_dissertation.py, dissertation/models/proposition_role.py
Inform the ticket you are solving in this pull request: #1514 
=> issue#1514 raw_id_fields pour les ForeignKey

dissertation/models/dissertation.py
Inform the ticket you are solving in this pull request: #1441  correction bug, non envoi de mail après refus du promoteur
=> Dissertation: Correction bug non envoi de mail après refus du promoteur

dissertation/models/dissertation.py
Inform the ticket you are solving in this pull request: #1441
modification bug non envoi de mail après refus du promoteur
=> Dissertation: modification bug non envoi de mail après refu du promoteur

internship/models.py
Inform the ticket you are solving in this pull request: #1517 
=> #1517 cannot make select_related on none

internship/models.py
Inform the ticket you are solving in this pull request: #1571
=> Bugfix/1517 To Dev

dissertation/views/proposition_dissertation.py
Inform the ticket you are solving in this pull request: #1528 
=> issue#1528 gestion du cas division par zéro

backoffice/settings.py
Inform the ticket you are solving in this pull request: #1544 
=> #1544 osis_common 0.6.1

base/models/academic_calendar.py, base/templates/academic_calendar_form.html, base/tests/models/test_academic_calendar.py, base/views/academic_calendar.py, base/views/offer.py
Inform the ticket you are solving in this pull request: #1509 
=> #1509 correction of algorithm to get academic calendar form

dissertation/templates/dissertations_detail.html
Inform the ticket you are solving in this pull request: #1446 
=> #1446 Correction

assistant/admin.py, assistant/models/settings.py, assistant/views/manager_settings.py
Inform the ticket you are solving in this pull request: #1556 
=> Add settings model in admin + form correction

doc/technical-manual.adoc
=> removed unecessary comma + init git submodule

requirements.txt
=> #1563 maj psycopg2 (Merge to Dev)

base/models/scores_encoding.py, base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #899 
=> #899 added  field scores_not_yet_submitted in admin

base/templates/layout.html, base/views/common.py
Inform the ticket you are solving in this pull request: #1474 
=> Bugfix/1474 (to Dev)

base/templates/layout.html, base/views/common.py
Inform the ticket you are solving in this pull request: #1474 
=> Bugfix/1474 (To Qa)

base/views/common.py
Inform the ticket you are solving in this pull request: #1474 (To Dev)
=> ajout dns publique sentry

base/views/common.py
Inform the ticket you are solving in this pull request: #1474
=> ajout dns publique sentry (To Qa)

base/templates/layout.html
Inform the ticket you are solving in this pull request: #1474 
=> #1474 supression du js de retour utilisateur (Merge to Qa)

base/models/models_signals.py
Inform the ticket you are solving in this pull request: #1594 
=> Bugfix/1594 (Merge to Dev)

base/models/models_signals.py
Inform the ticket you are solving in this pull request: #1594 
=> #1594 appel de save person si utilisateur créé, sinon appel super save (Merge to Qa)

base/tests/views/test_score_encoding.py, base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #862 
**It's a correction of an error.**
=> feature/862 (correction of original pull request) corrected sending on email when using only justifications when encoding

base/templates/assessments/scores_encoding_by_specific_criteria.html
Inform the ticket you are solving in this pull request: #909 
=> (correction) truncate whole learning unit title

dissertation/admin.py, dissertation/models/adviser.py, dissertation/models/dissertation.py, dissertation/models/dissertation_role.py, dissertation/models/dissertation_update.py, dissertation/models/faculty_adviser.py, dissertation/models/proposition_dissertation.py, dissertation/models/proposition_offer.py, dissertation/models/proposition_role.py, dissertation/templates/manager_proposition_dissertation_edit.html, dissertation/templates/manager_proposition_dissertation_new.html, dissertation/views/proposition_dissertation.py
Inform the ticket you are solving in this pull request: #1579 #1580 #1581 
=> Patch dissertation bugs #1579 #1580 #1581 to qa

dissertation/admin.py, dissertation/models/adviser.py, dissertation/models/dissertation.py, dissertation/models/dissertation_role.py, dissertation/models/dissertation_update.py, dissertation/models/faculty_adviser.py, dissertation/models/proposition_dissertation.py, dissertation/models/proposition_offer.py, dissertation/models/proposition_role.py, dissertation/templates/manager_proposition_dissertation_edit.html, dissertation/templates/manager_proposition_dissertation_new.html, dissertation/views/proposition_dissertation.py
Inform the ticket you are solving in this pull request: #1579 #1580 #1581 
=> Patch dissertation bugs #1579 #1580 #1581 to dev

base/migrations/0080_scoresencoding.py, base/templates/assessments/scores_encoding_by_learning_unit.html
Inform the ticket you are solving in this pull request: #899 
=> #899 updated SQL view + scores draft display

base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1599 
=> correctio bug

base/templates/assessments/scores_encoding_by_specific_criteria.html
Inform the ticket you are solving in this pull request: #909 
=> ajout nombre de caracteres pour learning unit dans specific criteria

dissertation/models/offer_proposition.py, dissertation/templates/proposition_dissertation_edit.html, dissertation/templates/proposition_dissertation_new.html, dissertation/views/proposition_dissertation.py
Inform the ticket you are solving in this pull request: #1601 
=> feature/1601 Trier la liste des programmes à la création/modif d'un sujet

dissertation/models/proposition_dissertation.py
Inform the ticket you are solving in this pull request: #1646
=> bugfix/1646 Correction bug nom fonction (to qa)

dissertation/admin.py, dissertation/models/adviser.py, dissertation/models/dissertation.py, dissertation/models/dissertation_document_file.py, dissertation/models/dissertation_group.py, dissertation/models/dissertation_location.py, dissertation/models/dissertation_role.py, dissertation/models/dissertation_update.py, dissertation/models/faculty_adviser.py, dissertation/models/offer_proposition.py, dissertation/models/proposition_dissertation.py, dissertation/models/proposition_document_file.py, dissertation/models/proposition_offer.py, dissertation/models/proposition_role.py
Inform the ticket you are solving in this pull request: #1662
=>  #1662 Modifications d'administration To QA

dissertation/models/dissertation_document_file.py, dissertation/models/dissertation_group.py, dissertation/models/dissertation_update.py, dissertation/models/faculty_adviser.py, dissertation/models/offer_proposition.py, dissertation/models/proposition_document_file.py
Inform the ticket you are solving in this pull request: #1662
=> #1662 Modification d'administration To QA 

base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #1669
=> #1669 updated information text for score sheet address

base/static/js/osis.js
Inform the ticket you are solving in this pull request: #1624
=> #1624 center the screen on the encoding scor/justificatione

base/models/exam_enrollment.py, base/templates/assessments/online_double_encoding_validation.html, base/templates/assessments/online_encoding.html, base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1655
=> #1655 display of 'absent' justification for tutors

base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #1655
=> #1655 display justifications case None

attribution/models/attribution.py
Inform the ticket you are solving in this pull request: #1678
=> #1678 Changement des start_date/end_date en start_year/end_year

base/models/synchronization.py, base/templates/assessments/scores_encoding_by_learning_unit.html, base/tests/models/test_synchronization.py
Inform the ticket you are solving in this pull request: #1708
=> #1708 case empty table + unit tests

backoffice/settings.py
Inform the ticket you are solving in this pull request: #1722
=> Bugfix#1722 (Merge to Dev)

backoffice/settings.py
Inform the ticket you are solving in this pull request: #1722
=> #1722 ajout logger queue dans settings + maj osis-common ref (Merge to Qa)

assistant/models/assistant_document_file.py, assistant/views/upload_assistant_file.py
Inform the ticket you are solving in this pull request: #1717
=> Issue#1717

assistant/templates/load_mandates.html, assistant/utils/import_xls_file_data.py
Inform the ticket you are solving in this pull request: #1715
=> Issue#1715

assistant/views/upload_assistant_file.py
Inform the ticket you are solving in this pull request: #1717
=> correction recherche documentfile

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #1702
=> Feature/1702 Il manquait qq tradutions

base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1747
=> Bugfix#1747 (Merge to Dev)

base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1747
=> #1747 ref osis-common + gestion queue et log (Merge to Qa)

base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1751
=> Bugfix#1751 (Merge to Dev)

base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1751
=> #1751 modif ref osis-common + gestion des Exception generique (Merge to Qa)

base/fixtures/learning_unit.json, internship/fixtures/internship.json, internship/models/organization_address.py
Inform the ticket you are solving in this pull request: #1743 
Correction des bugs du pull request précédent.
=> Feature/1743 (correction bug)

assistant/forms.py, assistant/views/reviewers_management.py
Corrige une erreur lors de l'ajout d'un reviewer. Le champ 'person' doit être supprimé du formulaire. 
Inform the ticket you are solving in this pull request: #1777
=>  Correction bug ajout reviewer

internship/views/affectation_statistics.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1743
=> corrected view affectation_statistics

base/models/learning_unit_component.py
Inform the ticket you are solving in this pull request: #1781
=> #1781 Amelioration de l'affichage de l'entité dans l'admin

assistant/templates/assistant_form_part5.html, assistant/templates/assistant_form_part6.html
Inform the ticket you are solving in this pull request: #1786 
refactoring templates du formulaire de l'assistant (parties 5 et 6).
=> templates refactoring

assistant/templates/manager_add_reviewer.html, assistant/templates/manager_home.html, assistant/templates/mandate_form.html, assistant/templates/reviewers_list.html, assistant/views/home.py
Inform the ticket you are solving in this pull request: #1780 
Finalisation de la page d'accueil pour les managers et du menu de navigation.
=> manager menu + nav

base/models/models_signals.py
Inform the ticket you are solving in this pull request: #1801
=> corrected bug when add person to group

base/models/models_signals.py
Inform the ticket you are solving in this pull request: #1801
=> corrected bug 

dissertation/models/dissertation_update.py
Inform the ticket you are solving in this pull request: #1804
=> feature/1804 add search criteria for dissertation_update

doc/technical-manual.adoc
=> added git revert doc

.codeclimate.yml
Refine the configuration of codeclimate
=> Exclude paths from codeclimate config

base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1853
=> #1853 Correct function call for pdf generation

internship/templates/internship_modification_student.html, internship/templates/student_resume.html, internship/views/internship.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1844
=> Feature/1844 (correction)

internship/views/home.py, internship/views/internship.py, internship/views/master.py, internship/views/place.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1767
=> only internship manager can have access to module internship

internship/templates/student_resume.html
Inform the ticket you are solving in this pull request: #1874
=> display speciality

internship/models/internship_choice.py, internship/models/internship_offer.py, internship/models/internship_student_affectation_stat.py, internship/models/organization.py, internship/models/organization_address.py, internship/models/period_internship_places.py, internship/templates/internship_affectation_statics.html
Inform the ticket you are solving in this pull request: #1882
=> added search fields for admin page

internship/templates/internship_affectation_statics.html
Inform the ticket you are solving in this pull request: #1876
=> corrected error for no displaying search bar

base/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1883
=> #1883 Remove cyclic dep between osis and osis-common

internship/models/internship_choice.py, internship/tests/models/test_internship_choice.py, internship/views/student_resume.py
Inform the ticket you are solving in this pull request: #1912
=> corrected numbers

internship/models/internship_offer.py, internship/views/home.py, internship/views/internship.py
Inform the ticket you are solving in this pull request: #1909
=> corrected disabling of offers

assistant/utils/import_xls_file_data.py
Inform the ticket you are solving in this pull request: #1917
=> Add link between mandates and sectors when the data file is imported.

assistant/admin.py, assistant/models/academic_assistant.py
Inform the ticket you are solving in this pull request: #1932 
Add raw_id_fields in academic_assistant model
=> Issue#1932 : Add raw_id_fields in academic_assistant model

base/models/academic_year.py
Inform the ticket you are solving in this pull request: #1952
=> #1952 Set affectation to filter

base/tests/models/test_academic_year.py
Inform the ticket you are solving in this pull request: #1954
=> #1954 Correct tests academic year

base/models/academic_year.py, base/tests/models/test_academic_year.py
Inform the ticket you are solving in this pull request: #1952
=> #1952 Patch error queryset

__init__.py, assistant/admin.py, assistant/models/assistant_mandate.py
Inform the ticket you are solving in this pull request: #1943 
Add AssistantMandateAdmin class
=> Issue#1943 : Add AssistantMandateAdmin class

base/templates/my_osis/profile.html
Inform the ticket you are solving in this pull request: #1929
=> #1929 Prevent None display for middle name when not exist

assessments/templates/scores_encoding.html, assessments/templates/scores_encoding_by_learning_unit.html
Inform the ticket you are solving in this pull request: #1626
=> #1626 add link to via excel/via paper

internship/utils/student_assignment/solver.py, internship/utils/student_assignment/student_wrapper.py
Inform the ticket you are solving in this pull request: #1968
=> corrected classification of students by priority and contest

assessments/templates/online_double_encoding_form.html, assessments/templates/online_double_encoding_validation.html, assessments/templates/online_encoding.html, assessments/templates/online_encoding_form.html, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #900
=> #900 Change 'Enseignant' to 'Autres Enseignants'

assessments/templates/online_encoding.html
Inform the ticket you are solving in this pull request: #1975
=> #1975 Change </button> to </a> tag

assistant/forms.py, assistant/models/enums/review_advice_choices.py, assistant/models/enums/review_status.py, assistant/models/review.py, assistant/templates/phd_supervisor_assistants_list.html, assistant/templates/pst_form_view.html, assistant/templates/review_form.html, assistant/templates/review_view.html, assistant/templates/reviewer_structures_list.html, assistant/urls.py, assistant/views/phd_supervisor_assistants_list.py, assistant/views/phd_supervisor_review.py, assistant/views/reviewer_delegation.py, assistant/views/reviewer_mandates_list.py, assistant/views/reviewer_review.py
Add PhD Supervisor dashboard and PhDSupervisor reviews management. 
These changes have resulted in changes in reviewers reviews management
Inform the ticket you are solving in this pull request: #1899
=> Add PhD Supervisor dashboard and PhDSupervisor reviews management.

assessments/templates/scores_encoding_by_learning_unit.html
Inform the ticket you are solving in this pull request: #1980
=> #1980 Correct show last_name and first_name of a tutor

assistant/templates/load_mandates.html, assistant/templates/manager_home.html
Inform the ticket you are solving in this pull request: #1988
=> add import data item to manager home page

assessments/templates/online_double_encoding_form.html, assessments/templates/online_encoding_form.html, assessments/views/score_encoding.py
Inform the ticket you are solving in this pull request: #1978
=> #1978 Correct simple form encoding

base/tests/models/test_academic_year.py
Inform the ticket you are solving in this pull request: #2008
=> #2008 Correct academic year test

backoffice/settings.py, base/management/__init__.py, base/management/commands/__init__.py, base/management/commands/runserver.py
Inform the ticket you are solving in this pull request: #2016
=> #2016 Settings validation runserver

base/management/commands/runserver.py
Inform the ticket you are solving in this pull request: #2016
=> #2016 Resolve problem with static files

dissertation/templates/manager_dissertations_detail.html, dissertation/templates/manager_proposition_dissertation_detail.html, dissertation/templates/proposition_dissertation_detail.html
Inform the ticket you are solving in this pull request: #1867
=> #1867 Suppression du code JS qui n'étaient pas utilisé dans Dissertation

assistant/views/reviewer_review.py
Inform the ticket you are solving in this pull request: #1996
=> add case to assign value to review_is_done var

internship/models/period_internship_places.py, internship/templates/student_affectation_modification.html, internship/utils/upload_xls.py, internship/views/student_resume.py
Fixes a few bugs that appeared when we started using the new internship with real data.
#2038
=> Internship hotfix

base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #1995
=> #1995 Correct My Osis html page

internship/utils/upload_xls.py, internship/views/affectation_statistics.py
=> Scope affectation stats by cohort through periods

internship/utils/upload_xls.py
=> Handle both mandatory and non mandatory imports

internship/utils/upload_xls.py
=> Fix upload xls

dissertation/views/dissertation.py
Inform the ticket you are solving in this pull request: #1850
=> feature/1850 Add desc + defend_year in dissertations xls export

internship/views/affectation_statistics.py
=> Scope affectation-stats by cohort

internship/views/affectation_statistics.py
=> Fix affectation stats

dissertation/models/dissertation_role.py, dissertation/views/dissertation.py
Inform the ticket you are solving in this pull request: #2085
=> #2085 Correct data in xls export

base/models/session_exam_deadline.py
Inform the ticket you are solving in this pull request: #2013
=> #2013 Correct admin session exam deadline

internship/forms/form_select_speciality.py, internship/models/internship_student_information.py, internship/templates/internship_modification_student.html, internship/templates/specialities.html, internship/views/internship.py, internship/views/place.py
=> Fix internship bugs

internship/views/internship.py
=> Fix internship period bug

assessments/models/scores_encoding.py, attribution/models/attribution.py, base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #2109
=> #2109 Adding select_related for performance improvment

assessments/templates/online_encoding.html, assessments/templates/online_encoding_form.html
Inform the ticket you are solving in this pull request: #1937
=> #1937 Correct CSS style

assessments/tests/business/__init__.py, assessments/tests/business/test_score_encoding_progress.py
Inform the ticket you are solving in this pull request: #2125
=> #2125 Addin test for score encoding progress

assessments/views/upload_xls_utils.py
Inform the ticket you are solving in this pull request: #1470
=> #1470 Correct Message when justification invalid

assessments/views/upload_xls_utils.py
Inform the ticket you are solving in this pull request: #1470
=> #1470 Support t,a as T,A

assessments/business/score_encoding_progress.py
Inform the ticket you are solving in this pull request: #2160
=> #2160 Correct tutor list ordering

assistant/templates/assistant_mandates.html, assistant/templates/mandate_reviews_view.html, assistant/urls.py, assistant/views/assistant_mandate_reviews.py
Inform the ticket you are solving in this pull request: #2015
=> Issue#2015 : Assistants should seen their file at the end of the workflow

assistant/templates/review_form.html, assistant/urls.py
Inform the ticket you are solving in this pull request: #2166
=> solve error when phd supervisor saves form

base/tests/views/test_learning_unit.py
Inform the ticket you are solving in this pull request: #2168
=> add tests for the learning_units views

assessments/views/upload_xls_utils.py
Inform the ticket you are solving in this pull request: #2173
=> #2173 Group error message by type

assessments/views/upload_xls_utils.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #2178
=> #2178 Warn user if try to change M to A

base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #2187
=> #2187 Correct draft display

assessments/business/score_encoding_export.py, assessments/business/score_encoding_list.py, assessments/templates/online_double_encoding_form.html, assessments/templates/online_encoding.html, assessments/templates/online_encoding_form.html, assessments/views/score_encoding.py, base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #2193
=> #2193 Adding deadline on all row in all form

base/models/offer_year_calendar.py, base/models/session_exam_calendar.py, base/tests/factories/user.py, base/tests/models/test_session_exam_calendar.py
Inform the ticket you are solving in this pull request: #2193
=> #2193 Correct deliberation date

assessments/views/score_encoding.py
Inform the ticket you are solving in this pull request: #2200
=> #2200 Correct variable

assessments/templates/scores_encoding_by_specific_criteria.html, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #2225
=> feature/2225 Justification --> Etat

assessments/tests/views/test_score_encoding.py, internship/tests/factories/offer.py
=> Fix tests for offer and encoding

assessments/business/score_encoding_list.py
Inform the ticket you are solving in this pull request: #2242
=> #2242 Correct export XLS accept zero value

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #2243
=> #2243 Correction du lien RGEE sur feuille de notes

base/templates/my_osis/profile.html
Inform the ticket you are solving in this pull request: #2215
=> #2215 Correct template url

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, dissertation/locale/en/LC_MESSAGES/django.po, dissertation/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #2259
=> #2259 Move translation between osis/osis-common

assistant/templates/assistant_form_part3.html, assistant/templates/assistant_form_part4.html, assistant/views/assistant_form.py
Inform the ticket you are solving in this pull request: #2229
=> prevent loss of unsaved data when click on a link in the assistant form

assistant/templates/pst_form_view.html
Inform the ticket you are solving in this pull request: #2231
=> remove duplicate content

assistant/templates/assistant_form_part1.html, assistant/views/assistant_form.py
Inform the ticket you are solving in this pull request: #2246
=> remove address from assistant form

assistant/forms.py, assistant/templates/review_form.html, assistant/views/phd_supervisor_review.py, assistant/views/reviewer_review.py
Inform the ticket you are solving in this pull request: #2248
=> justification required if advice is negative in the review form

attribution/models/attribution.py
Inform the ticket you are solving in this pull request: #2198
=> #2198 Debug du calcule du nombre de tutor par learning_unit_year

assessments/templates/scores_responsible_edit.html
Inform the ticket you are solving in this pull request: #2198
=> #2198 Correction template

base/templates/learning_unit/tabs.html
Inform the ticket you are solving in this pull request: #2139
=> #2139 Remove Href to tabs to prevent click

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #2275
=> #2275 Correct text translation

base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #2276
=> #2276 Correct find score responsibles method

assessments/views/scores_responsible.py, attribution/models/attribution.py, attribution/tests/models/test_attribution.py, base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #2276
=> #2276 Revert to previous + correct attribution

base/models/learning_container.py, base/models/learning_unit_year.py
Inform the ticket you are solving in this pull request: #2299
=> #2299 Add str and searchfield in admin

assessments/templates/online_double_encoding_form.html, assessments/templates/online_double_encoding_validation.html, assessments/templates/online_encoding.html, assessments/templates/online_encoding_form.html, assessments/templates/scores_encoding_by_specific_criteria.html
Inform the ticket you are solving in this pull request: #2276
=> #2276 Prevent 'None' displayed when no last_name/first_name student

assistant/urls.py
Inform the ticket you are solving in this pull request: #2303
=> simplify urls

assessments/views/score_encoding.py
Inform the ticket you are solving in this pull request: #2324
=> #2324 renvoi json vide au lieu de None si erreur dans paper_sheet (Merge to Qa)

assessments/views/score_encoding.py
Inform the ticket you are solving in this pull request: #2324
=> #2324 gestion dews erreur de queue (Merge to Dev)

assessments/views/score_encoding.py
=> #2324 gestion dews erreur de queue (Merge to Qa)

assessments/views/score_encoding.py
Inform the ticket you are solving in this pull request: #2331
=> #2331 fixed function return + time sleep to reinitilize the closed connection (to QA)

assistant/views/reviewer_review.py
Inform the ticket you are solving in this pull request: #2313
=> reviewer menu simplification

internship/utils/sync_internship_choices.py, internship/views/affectation_statistics.py
=> Algorithm fixes

assessments/views/score_encoding.py
Inform the ticket you are solving in this pull request: #2331
=> #2331 fixed function return + time sleep to reinitilize the closed connection (to Dev)

assistant/urls.py, assistant/views/reviewer_review.py
Inform the ticket you are solving in this pull request: #2342
=> correct url and reviewer menu generation

dissertation/models/dissertation.py, dissertation/models/offer_proposition.py, dissertation/views/dissertation.py
Inform the ticket you are solving in this pull request: #2262
=> #2262 Safe get on offer_proposition

dissertation/views/dissertation.py
Inform the ticket you are solving in this pull request: #2345
=> #2345 Manage IllegalCharacterError

assessments/views/score_encoding.py, base/tests/models/test_learning_unit_year.py
Inform the ticket you are solving in this pull request: #2339
=> #2339 not display error msg case no receivers found or no html template found to send email

dissertation/models/faculty_adviser.py
Inform the ticket you are solving in this pull request: #2351 
Test failed -> correction.
=> #2351 Be safe if no offer_year for offer

base/models/academic_year.py, base/models/tutor.py
Inform the ticket you are solving in this pull request: #2373
=> Added action in the admin to add selected tutors in the group tutors

assessments/templates/admin/pgm_manager.html, assessments/views/pgm_manager_administration.py
Inform the ticket you are solving in this pull request: #2280
=> #2280 Correct bug fixes asked by Hang

assistant/forms.py, assistant/templates/manager_replace_reviewer.html, assistant/templates/reviewers_list.html, assistant/urls.py, assistant/views/reviewers_management.py
Inform the ticket you are solving in this pull request: #2269
=> Issue#2269 : add reviewer replacement

assistant/templates/pst_form_view.html
Inform the ticket you are solving in this pull request: #2361
=> add tutoring learning units details

.env.example, backoffice/settings/base.py
Inform the ticket you are solving in this pull request: #2384
=> #2384 added new logger 'send_mail'

base/forms/learning_unit_pedagogy.py, base/forms/learning_unit_specifications.py
Inform the ticket you are solving in this pull request: #2234
=> #2234 Correct 'None' value displayed

base/views/entity.py
=> Update the copyright

assessments/templates/scores_responsible.html, assessments/templates/scores_responsible_edit.html, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/academic_actors.html
Inform the ticket you are solving in this pull request: #2316
=> #2316 Modification traduction

assessments/utils/remove_offers_2M_2MS.py
Inform the ticket you are solving in this pull request: #2425.
=> #2425 script to remove offers with acronym like '%2M'/'%2MS'

dev-settings.py
=> Import the default settings

base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #2411
=> #2411 Correct django.po for missing translation

assessments/tests/views/test_score_encoding.py, assessments/views/score_encoding.py
Inform the ticket you are solving in this pull request: #2443
=> #2443 fixed problem of data removed case form was submitted  without any changes

base/models/exam_enrollment.py
=> Admin enrollment history

base/models/exam_enrollment.py
=> Fixed reference to search field

base/models/student.py
Inform the ticket you are solving in this pull request: #2450
=> Feature/2450 Order students by name in find_by_offer return

base/serializers.py
Inform the ticket you are solving in this pull request: #2476
=> feature/2476 EntityVersionSerializer accepts external_id field

assistant/templates/assistant_form_part1.html, assistant/templates/assistant_form_part4.html, assistant/templates/assistant_form_part5.html, assistant/templates/assistant_form_part6.html, assistant/templates/mandate_learning_unit_list.html
Inform the ticket you are solving in this pull request: #2486
=> hide research in the assistant form for teaching assistants

backoffice/settings/base.py, base/views/layout.py, requirements.txt
Inform the ticket you are solving in this pull request: #2501
=> Bugfix#2501 (Merge to Dev)

base/models/entity_version.py
Inform the ticket you are solving in this pull request: #2487
=> #2487 Manage in creation object (start_date and end_date are None)

assistant/templates/mandates_list.html, assistant/templates/phd_supervisor_assistants_list.html, assistant/templates/reviewer_mandates_list.html, assistant/utils/import_xls_file_data.py
Inform the ticket you are solving in this pull request: #2508
=> change de sorting order of the mandates structures

assistant/templates/pst_form_view.html
Inform the ticket you are solving in this pull request: #2510
=> Remove assistant degrees in the reviewer assistant form

assistant/templates/mandate_reviews_view.html, assistant/templates/review_view.html
Inform the ticket you are solving in this pull request: #2512
=> Add justification in the reviews summary if the advice in unfavorable

backoffice/settings/base.py, base/forms/learning_unit_pedagogy.py, base/templates/learning_unit/pedagogy_edit.html, base/views/learning_unit.py
Inform the ticket you are solving in this pull request: #2422
=> #2422 Correct remarks and adapt HTML

base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/breadcrumb.html, base/templates/learning_units.html, base/templates/offer.html, base/templates/offer_year_calendar.html
Inform the ticket you are solving in this pull request: #2524
=> #2524 Correct Misspelling

base/templates/learning_unit/identification.html
Inform the ticket you are solving in this pull request: #2142
=> #2142 Remove duplicate HTML line due to auto merge git

assistant/templates/assistant_form_part3.html
Inform the ticket you are solving in this pull request: #2538
=> Hide phd inscription date if the inscription is in progress

assistant/models/reviewer.py, assistant/tests/factories/mandate_structure.py, assistant/tests/models/test_mandate_structure.py, assistant/views/assistant.py
Inform the ticket you are solving in this pull request: #2540
=> send email to dean when assistant decline

assistant/views/reviewer_review.py
Inform the ticket you are solving in this pull request: #2558
=> hide vice-rector review to previous reviewers

assistant/templates/assistant_form_part1.html
Inform the ticket you are solving in this pull request: #2567
=> Sort structures by id in the assistant form

assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/templates/reviewer_mandates_list.html
Inform the ticket you are solving in this pull request: #2570 
- remove global_id
- add full-time equivalent
- add renewal_type
=> reviewers dashboard improvement

base/models/learning_component_year.py, base/templates/learning_unit/components.html, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
Inform the ticket you are solving in this pull request: #2585
=> #2585 Add Description + improve query to get classes

assistant/forms.py, assistant/locale/en/LC_MESSAGES/django.po, assistant/templates/assistant_form_part1.html, assistant/templates/assistant_form_part3.html, assistant/templates/assistant_form_part4.html, assistant/templates/assistant_form_part5.html, assistant/templates/assistant_form_part6.html, assistant/templates/assistants.html, assistant/templates/load_mandates.html, assistant/templates/manager_add_reviewer.html, assistant/templates/manager_home.html, assistant/templates/manager_replace_reviewer.html, assistant/templates/mandate_form.html, assistant/templates/mandates_list.html, assistant/templates/messages.html, assistant/templates/phd_supervisor_assistants_list.html, assistant/templates/pst_form_view.html, assistant/templates/review_form.html, assistant/templates/review_view.html, assistant/templates/reviewer_mandates_list.html, assistant/templates/reviewer_structures_list.html, assistant/templates/reviewers_list.html, assistant/templates/settings.html
Inform the ticket you are solving in this pull request: #2582
=> Interface improvements

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/templates/pst_form_view.html, assistant/templates/review_form.html, assistant/templates/review_view.html, assistant/templates/reviewer_add_reviewer.html, assistant/templates/reviewer_mandates_list.html, assistant/templates/reviewer_structures_list.html, assistant/views/reviewer_delegation.py, assistant/views/reviewer_review.py
Inform the ticket you are solving in this pull request: #2599
=> add current reviewer role as information

assistant/utils/import_xls_file_data.py
Inform the ticket you are solving in this pull request: #2608
=> Solve mandate renewal type error when importing data from xlsx

dissertation/views/dissertation.py
Hello,
La fonction n'affichait pas correctement ce qu'elle devait afficher.
Le filtrer va permettre de mieux visualiser les mémoires par l'offer_proposition. 
cordialement
LD
Inform the ticket you are solving in this pull request: issue#2621
=> dissertation : adaptation de la fonction manager_dissertation_search bugée

.env.example, backoffice/settings/base.py, doc/technical-manual.adoc
Inform the ticket you are solving in this pull request: #1468
=> #1468 Modification du nom de la DB et de son utilisateur

dissertation/models/dissertation.py, dissertation/tests/views/test_dissertation.py, dissertation/views/dissertation.py
Inform the ticket you are solving in this pull request: #2615
=> Issue#2615

assessments/utils/update_ext_id_ac_calendar.py
(replaced 'title' by 'reference' and 'number_session' in ext id value)
Inform the ticket you are solving in this pull request: #2647
=> #2647 script to update external_id of AcademicCalendar & OfferYearCalendar

base/models/models_signals.py
Inform the ticket you are solving in this pull request: #2653
=> #2653 correction ajout groupe creation ou update user

assistant/models/review.py, assistant/views/mandate.py
Inform the ticket you are solving in this pull request: #2646
=> Solve data exportation to xls file problem

dissertation/models/dissertation.py
L' erreur dans le workflow a été corrigée
=> Issue#2615 Sécurité sur le workflow, correction bug Pullrequest précédent

dissertation/tests/views/test_dissertation.py
Inform the ticket you are solving in this pull request: #2668
=> #2668 Fix academic_year for test_adviser_can_manage_dissertation

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/static/css/custom.css, base/static/css/osis.css, base/templates/learning_unit/component_edit.html, base/templates/learning_unit/components.html, base/templatetags/components_classes.py, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
Inform the ticket you are solving in this pull request: #2652
=> Feature/2652 Update "components" page

base/forms/learning_class.py, base/templates/learning_unit/class_edit.html
Inform the ticket you are solving in this pull request: #2293
=> #2293 Add field description for update

base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #2679
=> #2679 Add missing translation --> QA

assessments/templates/online_double_encoding_form.html, assessments/templates/online_double_encoding_validation.html, assessments/templates/online_encoding.html, assessments/templates/online_encoding_form.html
Inform the ticket you are solving in this pull request: #2687
=> Bugfix/2687 --> qa

assessments/templates/online_encoding.html, assessments/templates/online_encoding_form.html, assessments/templates/scores_encoding_by_specific_criteria.html
Inform the ticket you are solving in this pull request: #2686
=> Feature/2686 ---> QA

assessments/business/score_encoding_progress.py
Inform the ticket you are solving in this pull request: #2692
=> #2692 > QA

base/models/exam_enrollment.py
Inform the ticket you are solving in this pull request: #2684
=> #2684 Correct bug treat empty list not as null value

assistant/templates/mandate_form.html, assistant/templates/mandates_list.html, assistant/tests/views/test_messages.py, assistant/urls.py, assistant/views/mandate.py, assistant/views/messages.py
Inform the ticket you are solving in this pull request: #2709
=> remove ids from urls and add @user_passes_test decorator

assistant/forms.py, assistant/templates/phd_supervisor_assistants_list.html, assistant/templates/pst_form_view.html, assistant/templates/review_form.html, assistant/templates/review_view.html, assistant/templates/reviewer_add_reviewer.html, assistant/templates/reviewer_mandates_list.html, assistant/templates/reviewer_structures_list.html, assistant/urls.py, assistant/views/phd_supervisor_assistants_list.py, assistant/views/phd_supervisor_review.py, assistant/views/reviewer_delegation.py, assistant/views/reviewer_review.py
Inform the ticket you are solving in this pull request: #2714
=> Add @user_passes_test decorator and remove id from urls for reviewer role

base/views/student.py
Inform the ticket you are solving in this pull request: #2666
=> #2666 Correct views parameters

dissertation/templates/manager_dissertations_list.html, dissertation/tests/views/test_dissertation.py, dissertation/views/dissertation.py
Inform the ticket you are solving in this pull request: #2661
=> In DEV the title of the offer was not displayed as desired

dissertation/templates/manager_dissertations_list.html
Inform the ticket you are solving in this pull request: #2661
=> dissertation: improved advanced search menu

base/forms/learning_units.py, base/templates/learning_units.html
Inform the ticket you are solving in this pull request: #2725
=> #2725 Reorganize search button + Remove search limit

base/templates/learning_unit/components.html, base/views/learning_unit.py
Inform the ticket you are solving in this pull request: #2742
=> #2742 Correct order of user by learning units

base/templates/learning_units.html
Inform the ticket you are solving in this pull request: #2725
=> #2725 Support search by status

base/templates/learning_units.html
Inform the ticket you are solving in this pull request: #2725
=> #2725 Allow sorting on subtype column - remove settings

base/models/learning_unit.py
Inform the ticket you are solving in this pull request: #2756
=> #2756 Add search capabilities on learning unit model

base/models/learning_unit_year.py
Inform the ticket you are solving in this pull request: #2756
=> #2756 Add external_id search on learning unit year

base/migrations/0152_auto_20170905_1317.py
Inform the ticket you are solving in this pull request: #982
=> #982 added the missing runSQL migration step (fixed bug due to alterField 'country')

base/static/js/diacritics-sort.js, base/templates/layout.html, base/templates/learning_units.html
Inform the ticket you are solving in this pull request: #2750
=> Ajout de js pour régler le problème de tri

assistant/templates/review_view.html
Inform the ticket you are solving in this pull request: #2784
=> Add reviewer details in the review

assessments/business/score_encoding_sheet.py, assessments/tests/business/test_score_encoding_sheet.py
Inform the ticket you are solving in this pull request: #982
=> fixed serialization of Country object (score sheet to JSON for Osis-portal) + unit test

base/forms/learning_units.py
Inform the ticket you are solving in this pull request: #2788
=> Modification du nombre de row dans les Textarea des remarques

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/templates/assistant_form_part1.html, assistant/templates/assistant_mandates.html, assistant/templates/pst_form_view.html, assistant/templates/reviewer_mandates_list.html, assistant/views/reviewer_delegation.py
Inform the ticket you are solving in this pull request: #2796
=> add a few traductions

base/templates/learning_unit/learning_unit_form.html
Inform the ticket you are solving in this pull request: #2786
=> Correction de la traduction dans le formulaire

base/views/learning_unit.py
Inform the ticket you are solving in this pull request: #2775
=> Correction des cas où l'utilisateur ne choisit pas d'entité additional

base/urls.py
Inform the ticket you are solving in this pull request: #2789 
Je en sais pas si j'ai compris ce que tu voulais que je fasse.
Tu peux me confirmer que c'est oki pour toi maintenant ?
=> Modification url

base/templates/learning_unit/learning_unit_form.html
Inform the ticket you are solving in this pull request: #2802
=> Test de la valeur du sigle avec une regex

base/forms/learning_units.py, base/templates/learning_unit/learning_unit_form.html
La validation de l'acronym accepte aussi des lowercases & Le message d'erreur required est aussi disponible en francais
Inform the ticket you are solving in this pull request: #2719
=> Correction mineure sur le form UE

base/templates/layout.html
Inform the ticket you are solving in this pull request: #2604
=> do not display version if set to None

base/views/learning_unit.py
Inform the ticket you are solving in this pull request: #JIRA 20
=> Remplace les volumes horaires non definis par un blanc a la place d'un '?'

base/forms/learning_units.py, base/views/learning_unit.py
CF. https://uclouvain-sips.atlassian.net/browse/OSIS-18
=> #18 Improve performance and reduce memory footprint of method get

assessments/tests/views/test_score_encoding.py, base/tests/models/test_academic_year.py
Inform the ticket you are solving in this pull request: 
VOIR https://uclouvain-sips.atlassian.net/browse/OSIS-81
=> #OSIS-81 Correct score encoding test

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #OSIS-164
=> OSIS-164 improve translation

assistant/templates/pst_form_view.html, assistant/views/phd_supervisor_review.py, assistant/views/reviewer_review.py
Inform the ticket you are solving in this pull request: #OSIS-38
=> OSIS-38 add link to pdf files + research section in pst_form_view

base/forms/education_groups.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> #OSIS-14 Adding translation for of categories

.gitignore, base/tests/views/test_academic_calendar.py, base/tests/views/test_learning_unit.py, base/urls.py
Creation of unit tests to improve the code coverage.
=> Test assessments

base/templates/home.html
Inform the ticket you are solving in this pull request: #2767
=> reduce sliding interval to 3 seconds for carousel on home page

base/forms/education_groups.py
Inform the ticket you are solving in this pull request: #6
=> #OSIS-6 Remove 'all' on categories + to upper entity management

dissertation/utils/request.py, dissertation/views/dissertation.py, dissertation/views/information.py, dissertation/views/offer_proposition.py, dissertation/views/proposition_dissertation.py
Inform the ticket you are solving in this pull request: issue#2544
=> dissertation: delete function redirect and keep if X is None:

base/forms/learning_units.py
Inform the ticket you are solving in this pull request:  #OSIS-5
=> #OSIS-5 Correction

base/forms/learning_units.py, base/tests/forms/test_learning_units.py
Inform the ticket you are solving in this pull request: OSIS-5
=> #OSIS-5 Correction de la recherche avec dpt requirement/allocation

dissertation/models/offer_proposition.py
Inform the ticket you are solving in this pull request: # PATCH-160
=> Dissertation patch-160 to QA : add blank=True to offerproposition

doc/technical-manual.adoc
Removed phantomjs instructions
Added the step to compile messages
Adapted the text to consider the new fixtures files
=> Updated instalation instructions after installing on Mac

base/forms/learning_units.py, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
=> Revert "OSIS-209 verify access permission for views to create a new learning…"

assistant/utils/send_email.py, assistant/views/reviewer_delegation.py
Inform the ticket you are solving in this pull request: #OSIS-219
=> send email to the reviewer delegate when he is added by a reviewer

attribution/tests/models/test_attribution.py
=> updated reference to osis-common

base/models/entity_version.py, base/models/organization.py
Inform the ticket you are solving in this pull request: #OSIS-231
=> Replacing iexact by icontains in filter

base/models/learning_unit_year.py
Inform the ticket you are solving in this pull request: #2897
=> #OSIS-163 Change regex to iregex

base/templates/education_group/tab_identification_details.html
=> #OSIS-13 Utilisation du template Tag

base/templates/education_group/tab_identification_details.html, base/templatetags/format.py
Inform the ticket you are solving in this pull request: #OSIS-13
=> #OSIS-13 Gestion du cas ou il n'y a pas de Comparateur

base/tests/models/test_education_group_year.py, base/tests/views/test_student.py, base/views/student.py
Inform the ticket you are solving in this pull request: #OSIS-235
=> Replace finally by except in student_picture method and unittests

base/views/student.py
Inform the ticket you are solving in this pull request: #OSIS-235
=> Add ValueError in the try/except of student_picture

base/business/learning_unit.py, base/views/learning_unit.py
Inform the ticket you are solving in this pull request: #OSIS-39
=> #OSIS-39 Rajout du code supprimé par erreur par d'autre ticket

cms/models/text_label.py, cms/models/translated_text.py, cms/models/translated_text_label.py
Inform the ticket you are solving in this pull request: OSIS-241
=> OSIS-241 Added search/filters for admin of "cms" django app app

base/forms/common.py, base/forms/learning_units.py, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/learning_unit_year.py, base/templates/learning_unit/by_activity.html, base/tests/forms/test_learning_units.py, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
Inform the ticket you are solving in this pull request: OSIS-262
=> OSIS-262 fixed search case too many results + set focus on 'acronym' search

base/models/learning_component_year.py
=> forgot comma

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/views/mandate.py, base/models/person.py, base/tests/models/test_person.py
Inform the ticket you are solving in this pull request: #OSIS-300
=> [OSIS-300] remove unnecessary data from export

assistant/views/phd_supervisor_assistants_list.py
Inform the ticket you are solving in this pull request: #OSIS-306
=> OSIS-306 considered academic_year must be the current

assistant/utils/send_email.py, assistant/views/assistant.py
Inform the ticket you are solving in this pull request: #OSIS-316
=> solve bogues

assistant/views/mandate.py
Inform the ticket you are solving in this pull request: #OSIS-304
=> Osis 304 : inclusion of the logistic entities in the exportation

base/tests/models/test_tutor.py
=> Unit tests for tutor model

attribution/business/attribution_json.py
=> #OSIS-319 Add end_year to attribution

dissertation/models/dissertation.py
Inform the ticket you are solving in this pull request: # OSIS-25
=> Dissertation modification :  manager_accept() with defended

base/migrations/0183_mandate_offer_calendar_date.py
=> correction migrations

base/migrations/0186_message_templates_learning_unit_deletion.py
=> #OSIS-242 Correct migration conflict

base/business/learning_unit_deletion.py, base/tests/business/test_learning_unit_deletion.py
Inform the ticket you are solving in this pull request: #OSIS-242
=> #OSIS-242 Fix bug: multiple messages for check_learning_unit_deletion

base/templates/education_group/tab_administrative_data.html
Inform the ticket you are solving in this pull request: #OSIS-301
=> #OSIS-301 Correction du template

base/business/learning_unit_deletion.py, base/models/learning_unit_year.py, base/templates/learning_unit/deletion.html, base/tests/business/test_learning_unit_deletion.py, base/views/learning_unit_deletion.py
Inform the ticket you are solving in this pull request: #OSIS-242
=> Fix bugs for #OSIS-242

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #OSIS-242
=> #OSIS-242 Change the text for the confirmation button

base/business/learning_unit_deletion.py, base/tests/business/test_learning_unit_deletion.py
Inform the ticket you are solving in this pull request: #OSIS-242
=> #OSIS-242 Add unit tests for the deletion and fix bugs

base/business/learning_unit_deletion.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/deletion.html, base/tests/views/test_learning_unit_deletion.py, base/views/learning_unit_deletion.py
Inform the ticket you are solving in this pull request: OSIS-242
=> OSIS-242 fixed problem of container deletion in case of classe deletion

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/templates/mandate_form.html, assistant/templates/mandates_list.html, assistant/views/mandate.py, assistant/views/mandates_list.py
Inform the ticket you are solving in this pull request: #OSIS-315
=> Osis 315 Ajout des promoteurs de thèse dans tableau de bord manager

base/models/learning_unit_year.py, base/tests/factories/learning_unit_year.py, base/tests/models/test_exam_enrollment.py, base/tests/models/test_learning_unit_year.py, base/tests/utils/test_send_mail.py, base/views/learning_unit_deletion.py
Inform the ticket you are solving in this pull request: OSIS-242
=> OSIS-242 create new method to find gte_learning_units_year

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/templates/assistant_form_part3.html, assistant/templates/assistant_form_part4.html, assistant/templates/mandate_learning_unit_list.html, assistant/views/upload_assistant_file.py
Inform the ticket you are solving in this pull request: #OSIS-326
=> Osis 326 Improve PDF file upload 

assistant/models/tutoring_learning_unit_year.py, base/business/learning_unit_deletion.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/test_learning_unit_deletion.py
Inform the ticket you are solving in this pull request: #OSIS-336 #OSIS-337
=>  Add check_deletion for assistants and internship_speciality

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/models/academic_assistant.py, assistant/models/assistant_mandate.py, assistant/templates/assistant_form_part1.html, assistant/templates/assistant_form_part3.html, assistant/templates/assistant_form_part5.html, assistant/templates/assistant_form_part6.html, assistant/tests/views/test_assistant_form.py, assistant/utils/assistant_access.py, assistant/views/assistant.py, assistant/views/assistant_form.py, assistant/views/home.py
Inform the ticket you are solving in this pull request: #OSIS-346
=> solve object matching query does not exist errors

assistant/views/mandate.py
Inform the ticket you are solving in this pull request: #OSIS-361
=> add assistants email in exportation file

assessments/templates/scores_encoding_by_specific_criteria.html
=> OSIS-363 Correct enter click on input in encoding by specific criteria

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/templates/phd_supervisor_assistants_list.html, assistant/templates/reviewer_mandates_list.html, assistant/templates/reviewer_structures_list.html, assistant/urls.py, assistant/views/home.py, assistant/views/phd_supervisor_review.py, assistant/views/reviewer_mandates_list.py, assistant/views/reviewer_review.py
Inform the ticket you are solving in this pull request: #OSIS-358
=> OSIS-358 : add reviewer todo tab

base/business/learning_unit_deletion.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #OSIS-337
=> #OSIS-337 Modify the check message for the UE deletion with internship

base/models/education_group_year.py
Inform the ticket you are solving in this pull request: #OSIS-236
=> #OSIS-236 Replace getattrs by if.

base/models/education_group_year.py
Inform the ticket you are solving in this pull request: #OSIS-236
=> #OSIS-236 Change _exact to _icontains for the search on partial_acronym

base/templates/education_group/identification_group_details.html, base/templates/education_group/identification_mini_training_details.html, base/templates/education_group/identification_training_details.html, base/templates/education_group/tab_administrative_data.html, base/templates/education_group/tab_content.html, base/templates/education_group/tab_diplomas.html, base/templates/education_group/tab_general_informations.html, base/templates/education_group/tab_identification.html, base/templates/education_group/tabs.html, base/tests/views/test_education_group.py, base/views/education_group.py
Inform the ticket you are solving in this pull request: #OSIS-238
=> OSIS-238 Ajout de l'arborescence dans les onglets

base/templates/education_group/tab_administrative_data.html, base/templates/education_group/tab_content.html, base/templates/education_group/tab_diplomas.html, base/templates/education_group/tab_general_informations.html
Inform the ticket you are solving in this pull request: #OSIS-238
=> OSIS-238 Ajout de l'arborescense dans l'onglet content

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/enums/education_group_categories.py, base/templates/education_groups.html, base/views/education_group.py
…elect field
Inform the ticket you are solving in this pull request: #OSIS-105
=> #OSIS-105 Change textboxes title + traduction on categories

assistant/tests/views/test_phd_supervisor_review.py, assistant/views/phd_supervisor_review.py
Inform the ticket you are solving in this pull request: #OSIS-374
=> Osis 374 : simplify generate_phd_supervisor_menu_tabs func

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-69 Correct mispelling translation

assessments/templates/scores_encoding_by_specific_criteria.html
=> OSIS-363 Correct score encoding bug enter focus on next field

base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: OSIS-69
=> OSIS-69 correction orthographe

base/templates/learning_unit/footer.html, base/templates/learning_unit/identification.html, base/views/learning_unit.py
=> LearningUnit identification display type of proposal

base/templates/education_groups.html
Inform the ticket you are solving in this pull request: OSIS-105
=> OSIS-105 invert size of cols

base/templates/education_groups.html
Inform the ticket you are solving in this pull request: OSIS-105
=> OSIS-105 Layout

base/models/learning_unit_enrollment.py
=> OSIS-397 Add enrollment_state field to admin

base/models/learning_unit_enrollment.py
=> OSIS-397 Addin enrollment_state in fieldsets

base/templates/learning_unit/footer.html
=> OSIS-419 Refactor footer in order to better enhencement

base/templates/layout.html
=> Documentation OSIS url corrected

base/templates/layout.html
=> Revert link url of documentation

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> Modified traduction of end_date for score_encoding

assessments/templates/online_double_encoding_form.html, assessments/templates/online_encoding.html, assessments/templates/online_encoding_form.html, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> Added new translations for end_date for score encoding (qa)

base/models/session_exam_calendar.py, base/tests/factories/academic_year.py, base/tests/models/test_session_exam_calendar.py
=> [ PATCH ] OSIS-455 fixed funciton to find deliberation date (ignoring global academic date)

base/models/session_exam_calendar.py, base/tests/factories/academic_year.py, base/tests/models/test_session_exam_calendar.py
=> [ merge to dev ] OSIS-455 fixed funciton to find deliberation date (ignoring global academic date)

.travis.yml, requirements.txt, travis-requirements.txt
=> Test travis

.github/CONTRIBUTING.md
=> New contributing rules (CONTRIBUTING.md)

.travis.yml, travis-requirements.txt
A correction has been made on the seriable model class so as to
enable the suppression of data.
Référence Jira : OSIS-467
=> PATCH OSIS-467 Updated ref osis_common for correction of serializable model (qa)

base/forms/education_groups_administrative_data.py
=> #OSIS-375 Fix bug, wrong import of the date coonverters

base/business/offer_year_calendar.py, base/forms/utils/datefield.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/education_group/breadcrumb.html, base/templates/education_group/tab_administrative_data.html, base/templates/education_group/tab_edit_administrative_data.html
=> Fix date widget wrong format 

.codeclimate.yml, .coveragerc, .travis.yml, setup.cfg
=> Codeclimate

attribution/models/attribution_new.py
=> OSIS-478 Add function field to fieldsets of admin view

base/forms/bootstrap.py, base/forms/education_groups_administrative_data.py, base/forms/utils/datefield.py, base/templates/education_group/tab_edit_administrative_data.html, base/tests/forms/test_education_grous_administrative_data.py
=> #OSIS-91 Use a splitdatetime widget in administrative data form

attribution/business/attribution_json.py, attribution/tests/business/test_attribution_json.py
=> OSIS-509 Manage Delete attribution case, empty list

attribution/business/attribution_json.py, attribution/tests/business/test_attribution_json.py
=> dev to test

attribution/business/application_json.py, attribution/tests/business/test_application_json.py
=> OSIS-509 Consider None as 0.0 for json computation

assistant/views/mandate.py, dissertation/views/dissertation.py, dissertation/views/proposition_dissertation.py
=> #OSIS-504 Modification du mimetype

base/business/learning_unit_year_with_context.py, base/models/entity_version.py, base/tests/forms/test_learning_units.py
=> Osis 463 - Do not search service course by sector

base/business/scores_encodings_deadline.py, base/models/offer_year_calendar.py, base/models/session_exam_calendar.py, base/tests/business/test_scores_encodings_deadline.py, base/tests/models/test_session_exam_calendar.py
=> Change queryset to get OfferYearCalendar

base/models/education_group.py, base/models/entity.py, base/tests/models/test_education_group.py, base/tests/models/test_entity.py
=> added admin search on acronym for Entity and EducationGroup

base/models/learning_container_year.py, base/models/learning_unit.py, base/models/learning_unit_year.py
=> OSIS-533 Add fieldset to admin for learning unit (year)/containeryear

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templatetags/learning_unit.py, base/tests/models/test_learning_unit.py
=> OSIS-493 Ajout de la phrase en cas de date de fin non prévue

base/business/education_group.py, base/models/person_entity.py, base/tests/business/test_education_group.py, base/tests/models/test_person_entity.py, base/tests/views/test_education_group.py, base/views/education_group.py
=> OSIS-407 Correct permission for edit education group administrative data

base/business/learning_unit_deletion.py, base/tests/business/test_learning_unit_deletion.py
=> Internship 0.4.0

base/forms/learning_unit_create.py, base/static/js/learning_unit_creation.js, base/views/learning_unit.py
=> OSIS-184 fixed READONLY fields (type, internship_subtype and entities)

base/forms/learning_unit_create.py, base/static/js/learning_unit_creation.js, base/templates/learning_unit/learning_unit_form.html, base/templates/learning_unit/partim_form.html, base/tests/models/test_entity_version.py, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
=> OSIS-184 fixed JS error message for acronym

base/forms/learning_unit_create.py
=> OSIS-540 Fix bug when creating partim with faculty_manager

base/templates/education_group/identification_mini_training_details.html
=> OSIS-590 Corrected template for mini training

base/business/learning_units/edition.py, base/tests/business/test_learning_unit_edition.py
Fix bug: the container year was not saved during the duplication
Référence Jira : OSIS-591
=> OSIS-591 :  Correction of the story 67

base/templates/learning_unit/learning_unit_form.html, base/templates/learning_unit/partim_form.html
=> OSIS-599 Correct HTML bug + Enhence col-md for first_letter dropdown

base/business/learning_units/edition.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/test_learning_unit_edition.py, base/views/learning_units/edition.py
Modify parent_greater_than_partim msg and get learning_container_year if it already exists
Référence Jira : OSIS-591
=> OSIS-591Correction of the US-67

base/business/learning_unit.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/template_messages.html, base/views/learning_unit.py
=> OSIS-598 Add UE created link to success message

base/business/learning_units/perms.py, base/tests/views/test_learning_unit.py
=> OSIS-68 Faculty manager can modify LU end date of partim

assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/models/assistant_mandate.py, assistant/templates/manager_home.html, assistant/tests/factories/reviewer.py, assistant/tests/models/test_assistant_mandate.py, assistant/tests/utils/test_export_utils_pdf.py, assistant/urls.py, assistant/utils/export_utils_pdf.py
=> [MERGE TO QA] Osis 171

base/models/entity_version.py
=> OSIS-621 Extend entity_type for entity_version selected

base/business/learning_units/edition.py, base/business/learning_units/perms.py, base/tests/business/test_learning_unit_edition.py, base/tests/factories/business/learning_units.py
…(without learning_unit_year for the partims)
Référence Jira : OSIS-631
=> Exception raised when the partim end date is shorter than its parent 

base/tests/factories/academic_year.py, base/tests/views/test_my_osis.py
=>  Resolve instability for the test : MyOsisViewTestCase.test_profile_attributions

base/business/learning_units/edition.py, base/tests/business/test_learning_unit_edition.py
=>  Differentiation of the maximum value and the None value for academic years

base/business/learning_unit.py, base/tests/business/test_learning_unit_creation.py
=> Ajout de test #OSIS-654

assessments/templates/online_encoding.html
=> Osis 653 To QA

assessments/templates/online_encoding.html, assessments/templates/scores_encoding.html, assessments/templates/scores_encoding_by_learning_unit.html
=> OSIS-653 To QA

base/business/learning_units/perms.py, base/models/learning_unit_year.py, base/templates/learning_unit/by_activity.html, base/templates/learning_unit/by_service_course.html, base/tests/business/test_perms.py, base/tests/models/test_learning_unit_year.py
=> Correction pour l'affichage du titre des classes #OSIS-608

assessments/templates/online_encoding.html, assessments/templates/scores_encoding.html, assessments/templates/scores_encoding_by_learning_unit.html
=> [MERGE TO DEV] Osis 653

base/forms/learning_unit/edition.py, base/tests/forms/test_learning_unit_edition.py, base/views/learning_units/edition.py
=> OSIS-636 Queryset for requirement entity LearningUnitModificationForm

base/forms/learning_unit_create.py, base/forms/utils/choice_field.py, base/tests/forms/test_learning_unit_proposal.py, base/tests/views/test_learning_unit.py
=> Rewrite add_blank with None and Optimize imports

base/tests/forms/utils/test_add_blank.py
=> Add unit test for add_blank

base/forms/learning_unit_create.py
=> Osis 671 internship_subtype

base/models/learning_unit_year.py, base/tests/business/test_learning_unit_edition.py
=> Add unit tests when partim end_year is None

base/business/learning_unit_deletion.py, base/business/learning_units/edition.py, base/models/learning_component_year.py, base/models/learning_container_year.py, base/tests/business/test_learning_unit_deletion.py
=> Check attribution instead of attribution_charge during deletion

attribution/models/attribution.py, attribution/tests/factories/attribution.py, base/business/learning_unit_deletion.py, base/models/learning_component_year.py
=> OSIS-681 Reactivation of the proctection on the attribution_charge

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/static/js/learning_unit_creation.js, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
=> OSIS-683 Correction acronym_existing message form

base/templates/learning_unit/footer.html
=> OSIS-684 Adapt disable button behaviour

base/business/learning_unit_deletion.py, base/views/learning_unit_deletion.py
=> OSIS-681 Add check on attributionNew

base/business/learning_unit.py, base/business/learning_unit_deletion.py, base/tests/business/test_learning_unit_deletion.py, base/views/learning_unit.py
=> OSIS-687 Remove CMS data when LUY removal

base/business/learning_unit_deletion.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/test_learning_unit_deletion.py
=> Add check on learning unit in proposal during deletion

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-67 Change translation key

cms/models/text_label.py, cms/models/translated_text.py, cms/models/translated_text_label.py
=> OSIS-690 Disallowed the rigth to remove CMS data via AdminInterface

cms/models/text_label.py, cms/models/translated_text.py, cms/models/translated_text_label.py
=> OSIS-690 Remove delete button on admin interface detail

cms/models/text_label.py, cms/models/translated_text.py, cms/models/translated_text_label.py
=> OSIS-690 Remove deleted in fieldset on admin interface

base/business/learning_unit_year_volumes.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/test_learning_unit_year_volumes.py, base/tests/views/test_learning_unit.py, base/views/common.py, base/views/learning_unit.py
=> Validation de modifications d'une UE / volumes

base/static/js/learning_unit_creation.js
=> OSIS-642 Corrected js for display of entities

base/views/learning_unit.py
=> OSIS-730 Bugfix

base/forms/learning_units.py, base/tests/forms/test_learning_units.py
=> OSIS-731 Move results quantity check to right place + update test

base/forms/learning_unit/edition.py, base/forms/learning_unit/edition_volume.py, base/templates/learning_unit/volumes_management.html, base/tests/forms/test_edition_form.py, base/tests/views/test_learning_unit_edition.py, base/views/learning_units/edition.py
=> Reactivation of ajax request

base/business/learning_units/edition.py, base/tests/business/test_learning_unit_edition.py
=> Create learning_units for all academic_years when the end_date of learning_unit biennal is changed

base/business/learning_unit_year_with_context.py, base/forms/learning_unit/edition_volume.py, base/templates/learning_unit/components/modal_modification_ask_to_report.html, base/templates/learning_unit/components/volumes_management_form.html, base/tests/forms/test_edition_form.py, base/urls.py, base/views/learning_units/edition.py
=> OSIS-726 Use modal to ask postponement

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/footer.html, base/templates/learning_unit/identification.html
=> #OSIS-709 Add the 'action' button right under the header.

base/business/learning_unit.py, base/tests/business/test_learning_unit_creation.py
=> OSIS-736 Correct link additional entities

base/migrations/0234_auto_20180222_1649.py
=> fix migration files

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/proposal_learning_unit.py, base/templates/learning_unit/footer.html
=> OSIS-708 Add translation and remove empty choice in modelform

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/views/learning_unit_proposal.py
=> OSIS-708 Add translation

base/templates/learning_unit/components.html
=> OSIS-743 Remove ability to edit component/class

base/templates/learning_unit/identification.html
=> OSIS-744 Add 1 & 2 in labels additional_requirement_entities

base/business/learning_unit_proposal.py, base/models/entity.py, base/tests/views/test_learning_unit_proposal.py
=> #OIS-710 Correction pour l'affichage des anciens sigle

base/forms/learning_unit_create.py
=> OSIS-741 Correction field form credit

base/business/learning_unit_proposal.py, base/templates/learning_unit/identification.html, base/tests/views/test_learning_unit_proposal.py
=> #OSIS-710 Modification affichage des anciennes valeurs dans le templates

base/forms/learning_unit_create.py, base/templates/learning_unit/learning_unit_layout.html
=> OSIS-746 Refactoring regex learning_unit heritage

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/proposal/edition_proposal_state.html, base/templates/learning_unit/proposal/modal_warning_state_modification.html
=> OSIS-745 Show warning message if inconsistent status changed

base/forms/learning_unit_create.py
=> OSIS-746 Remove codeclimate warnings

base/templates/learning_unit/blocks/save_cancel_buttons_with_modal.html, base/templates/learning_unit/modification.html
=> OSIS-642 Display modal to choose report or no

base/forms/learning_unit_search.py
=> OSIS-751 Correct acronym label to code

base/templates/learning_units.html
=> OSIS-752 Write same actions button list than detail

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/blocks/modal/generic_modal.html, base/templates/learning_unit/blocks/modal/modal_force_state.html, base/templates/learning_unit/proposal/edition_proposal_state.html
=> OSIS-750 Add warning messages when user selects Inconsistent State

base/forms/learning_unit/edition.py, base/models/learning_unit_year.py, base/tests/forms/test_learning_unit_edition.py, base/tests/models/test_learning_unit_year.py
=> OSIS-642 Get max partims credits and not min

base/business/education_group.py, base/business/learning_unit_deletion.py, base/business/learning_units/perms.py, base/forms/learning_unit/edition.py, base/forms/learning_unit_create.py, base/models/entity_version.py, base/models/person.py, base/models/person_entity.py, base/models/utils/person_entity_filter.py, base/templates/learning_unit/end_year_edit.html, base/templates/learning_unit/footer.html, base/tests/business/test_education_group.py, base/tests/business/test_learning_unit_deletion.py, base/tests/business/test_perms.py, base/tests/forms/test_learning_unit_edition.py, base/tests/models/test_entity_version.py, base/tests/models/test_person_entity.py, base/views/education_group.py, base/views/learning_unit.py, base/views/learning_unit_deletion.py, base/views/learning_units/perms.py
=> Optimizations of perms and entity_version

assessments/business/scores_encodings_deadline.py, assessments/tests/business/test_scores_encodings_deadline.py
=> #453 fixed recompute of all session exam deadlines from academicCalendar

base/business/learning_units/perms.py, base/forms/learning_unit/edition.py, base/models/learning_unit.py, base/models/learning_unit_year.py, base/models/person.py, base/models/proposal_learning_unit.py, base/tests/business/test_perms.py, base/tests/models/test_proposal_learning_unit.py, base/tests/views/test_learning_unit_edition.py, base/urls.py, base/views/learning_unit.py, base/views/learning_units/edition.py, base/views/learning_units/perms.py
=> OSIS-714 Implement perms to edit luy with a faculty manager

assessments/tests/views/test_score_sheet.py, base/tests/business/test_learning_unit_year_with_context.py, base/tests/models/test_learning_unit_year.py, base/tests/models/test_person.py, base/tests/models/test_program_manager.py, base/tests/models/test_synchronization.py, base/tests/templatetags/test_offer_year_calendar_display.py, base/tests/views/test_education_group.py, base/tests/views/test_learning_unit.py
=> Remove deprecated methods in tests

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/my_osis/profile.html
=> OSIS-785 Remove edit link in list of attributions

base/business/learning_units/perms.py, base/views/learning_units/edition.py
=> OSIS-790 Redirect even if an error occurs

base/business/learning_unit_deletion.py, base/tests/business/test_learning_unit_deletion.py
=> OSIS-809 Correct acronym to code scs in group error message

base/business/learning_unit_deletion.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/test_learning_unit_deletion.py
=> Correct message when included in educationgroup for deletion

base/models/person.py, base/views/learning_unit.py
=> OSIS-815 Correction soucis de permissions

base/business/learning_unit_deletion.py, base/business/learning_units/edition.py, base/business/learning_units/perms.py, base/forms/learning_unit/edition_volume.py, base/models/learning_unit_year.py, base/tests/business/test_learning_unit_edition.py, base/tests/forms/test_edition_form.py, base/tests/views/test_learning_unit_deletion.py, base/views/learning_unit.py
=> OSIS-817 Disable fields only for full luy

dissertation/templates/manager_informations_list.html
=> Osis-353 : filter and sort on the list of teachers

assessments/business/score_encoding_progress.py, assessments/business/score_encoding_sheet.py, assessments/templates/scores_encoding_by_specific_criteria.html, assistant/templates/mandate_learning_unit_list.html, assistant/templates/pst_form_view.html, assistant/tests/utils/test_export_utils_pdf.py, assistant/utils/export_utils_pdf.py, assistant/views/assistant_form.py, attribution/business/attribution.py, attribution/business/attribution_json.py, base/business/learning_unit.py, base/models/exam_enrollment.py, base/models/learning_unit_year.py, base/templates/my_osis/profile.html, base/tests/models/test_learning_unit_year.py, base/tests/views/test_learning_unit.py
=> Osis 802 (QA)

base/forms/learning_unit_search.py, base/models/learning_unit_year.py, base/models/proposal_learning_unit.py, base/templates/learning_unit/blocks/search_form_learning_unit.html, base/templates/learning_unit/components/search_form_proposal.html, base/tests/forms/test_learning_units.py, base/tests/views/test_learning_unit_proposal.py
=> OSIS-763 Ajout de Tutor dans la recherche d'UE et des propositions

attribution/templates/manage_my_courses/blocks/list/learning_units_summary_editable.html, attribution/templates/manage_my_courses/list_my_courses_summary_editable.html
=> OSIS-829 Can now sort summary editable courses

base/business/learning_units/edition.py
=> OSIS-833 Extract code to function in order to improve lisibility

base/business/learning_units/edition.py, base/tests/business/learning_units/test_edition.py
=> OSIS-833 Correct consistency check

base/models/proposal_learning_unit.py
=> OSIS-848 remove entity in search_field

base/tests/views/test_learning_unit_proposal.py, base/views/learning_units/proposal/create.py, base/views/learning_units/proposal/update.py
=> OSIS-841 Corrections : pour la proposition de création + redirection après suppression

base/business/learning_units/edition.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/blocks/create_form_learning_unit.html, base/templates/learning_unit/blocks/institution.html, base/templates/learning_unit/identification.html, base/templates/learning_unit/partim_form.html, base/tests/business/learning_units/test_edition.py
=> OSIS-833 Correct translation of message in conflict case

base/business/learning_units/proposal/common.py, base/forms/learning_unit_proposal.py, base/views/learning_units/proposal/create.py
=> #OSIS-852 Correction d'un bug

base/views/institution.py
modified:   base/views/institution.py
Référence Jira : OSIS-856
=> OSIS-856 Renamed variable for template

base/tests/views/test_learning_unit_deletion.py, base/urls.py, base/views/learning_units/delete.py
=> OSIS-805 Clean old code

base/static/js/locales/moment-fr.js, base/templates/education_group/blocks/datetimepicker_js.html
=> OSIS-854 Added french translation for moment.js (dates widget)

base/forms/learning_unit/edition_volume.py, base/tests/forms/test_edition_form.py
=> OSIS-766 Resolve bug 0 < 0

base/business/learning_units/edition.py
=> OSIS-836 Add NT for component type null

base/forms/learning_unit/edition_volume.py
=> OSIS-766 Check null value before compare

base/business/learning_units/edition.py, base/forms/learning_unit/edition_volume.py, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/tests/business/learning_units/test_edition.py, base/tests/views/test_learning_unit_edition.py, base/tests/views/test_learning_unit_proposal.py, base/views/learning_units/update.py
=> OSIS-836 Correct translation + add message + enhance error message

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/manage_my_courses/educational_information.html, attribution/templates/manage_my_courses/list_my_courses_summary_editable.html
modifié :         attribution/locale/en/LC_MESSAGES/django.po
modifié :         attribution/locale/fr_BE/LC_MESSAGES/django.po
modifié :         attribution/templates/manage_my_courses/educational_information.html
modifié :         attribution/templates/manage_my_courses/list_my_courses_summary_editable.html
Référence Jira : OSIS-839
=> OSIS-839 Modification de la traduction gerer mes cours

base/business/learning_unit_proposal.py, base/business/learning_units/edition.py, base/business/learning_units/simple/deletion.py, base/tests/business/test_learning_unit_deletion.py, base/tests/views/test_learning_unit_proposal.py, base/views/learning_units/delete.py, base/views/learning_units/proposal/create.py, base/views/learning_units/proposal/delete.py, base/views/learning_units/proposal/update.py
=> OSIS-868 Redirect proposal modification and delete + refactoring

base/templates/learning_unit/blocks/acronym.html
=> #OSIS-858 Increase the size of the col for the first letter of the code.

base/tests/views/test_learning_unit_deletion.py, base/views/learning_units/delete.py
=> OSIS-824 Catch integrityError

base/templates/learning_unit/partim_form.html
modifié :         base/templates/learning_unit/partim_form.html
Référence Jira : OSIS-667
=> OSIS-667 Correction du ? flottant pour les partim

base/business/learning_unit_proposal.py, base/tests/views/test_learning_unit_proposal.py
=> #OSIS-859 TRANSFORMATION if first-letter OR acronym are updated.

base/tests/views/test_learning_unit_edition.py, base/views/learning_units/update.py
=> OSIS-833 Correct message when report conflict

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/learning_unit.py, base/views/learning_unit.py
=> OSIS-824 Add translation for error

base/business/learning_unit_proposal.py, base/forms/learning_unit/edition.py, base/views/learning_unit.py, base/views/learning_units/proposal/update.py
=> OSIS 782 Workaround for proposition type (ugly way)

base/business/learning_units/perms.py, base/tests/business/test_perms.py
=> OSIS-874 Create test central_manager change end_date + adapt perm

base/business/learning_unit_proposal.py
=> Osis 872 intial data can be empty

base/business/learning_units/perms.py, base/models/proposal_learning_unit.py, base/tests/business/test_perms.py
=> Osis 877 Limit modification proposal according to entity for faculty manager

attribution/templates/manage_my_courses/blocks/submission_dates.html, attribution/templates/manage_my_courses/educational_information.html, attribution/templates/manage_my_courses/list_my_courses_summary_editable.html, attribution/tests/views/test_manage_my_courses.py, attribution/views/manage_my_courses.py, base/models/academic_calendar.py, base/tests/models/test_academic_calendar.py
=> OSIS-867 Display submission dates of educational information

base/business/learning_unit_proposal.py
=> #OSIS-879 Bug : titre vide reste vide -> indiqué en vert comme modifié

base/business/learning_unit.py
=> Pour enlever les doublons

base/templates/learning_unit/blocks/proposal_folder.html
modifié :         base/templates/learning_unit/blocks/proposal_folder.html
Référence Jira : OSIS-880
=> OSIS-880 Modification de focus pour un scroll complet en bout de page

base/forms/proposal/learning_unit_proposal.py, base/templates/learning_unit/by_activity.html, base/templates/learning_unit/by_proposal.html, base/tests/business/test_perms.py
=> OSIS-888 Translate type in proposals list

base/fixtures/groups.json, base/templates/learning_units.html
=> OSIS-845 Administrive_manager can access catalog

base/forms/learning_unit_proposal.py
=> OSIS-872 Added field to ignore for data changed on proposal

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/views/learning_unit.py
=> OSIS-878 Use a generic success message

base/forms/learning_unit_proposal.py, base/tests/forms/test_learning_unit_proposal.py
=> OSIS-872 Lower dict keys for form initial data

base/forms/learning_unit_pedagogy.py, base/templates/learning_unit/pedagogy.html, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
=> OSIS-906 Check permissions for educational information

base/templates/learning_units.html
fix permission menu actions learning_units
=> fix permission menu actions learning_units

attribution/templates/manage_my_courses/educational_information.html, attribution/views/manage_my_courses.py, base/templates/layout.html, base/templates/learning_unit/blocks/panel/educational_informations.html, base/templates/learning_unit/pedagogy.html, base/tests/views/test_learning_unit.py, base/urls.py, base/views/learning_unit.py, base/views/learning_units/update.py
=> OSIS-908 Same view for attribution and update_learning_unit_pedagogy

base/fixtures/groups.json
add perm for central_manager in fixture
=> add perm for central_manager in fixture

base/forms/learning_unit_proposal.py, base/templates/learning_unit/blocks/proposal_folder.html, base/tests/views/test_learning_unit_proposal.py, base/views/learning_units/proposal/update.py
modifié :         base/templates/learning_unit/blocks/proposal_folder.html
Référence Jira : OSIS-911
=> OSIS-911 Ajout du field state dans le formulaire

dissertation/utils/emails_dissert.py
Référence Jira : OSIS-352 dissertation: add subject variable
=> OSIS-352 dissertation: add subject variable

assessments/business/score_encoding_export.py
modifié :         assessments/business/score_encoding_export.py
Référence Jira : OSIS-658
=> OSIS-658 Ajout du field email et suppression de l'ID

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/learning_unit/summary_list.html, base/views/learning_units/educational_information.py
=> #OSIS-883 Disabled du bouton s'il n'y a aucun rappel à envoyer

base/locale/fr_BE/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/djangojs.po, base/templates/learning_unit/proposal/creation.html
=> OSIS-792 Correct translation + add asterics

base/business/learning_units/edition.py
=> OSIS-589 Correct return empty list when no short/extends

assistant/models/reviewer.py, base/forms/entity.py, base/forms/learning_units.py, base/models/entity_version.py, base/templates/entities.html, base/tests/views/test_institution.py, base/urls.py, base/views/institution.py
=> Add pagination for entity_search_form

base/forms/learning_units.py, base/models/learning_unit_year.py, base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/educational_information.py
=> OSIS-953 Use only one queryset to filter the requirement entities

base/models/learning_unit_year.py
=> OSIS-956 Filter by first and last name for summary_responsible

base/forms/learning_unit_search.py, base/forms/learning_units.py, base/templates/learning_unit/blocks/form/search_form_summary_list.html, base/tests/views/test_learning_unit_pedagogy.py, base/views/learning_units/educational_information.py
=> OSIS-955 Add requirement entity in search form

base/templates/learning_unit/summary_list.html
=> OSIS-842 Add break line in template

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
modifié :         base/locale/en/LC_MESSAGES/django.po
modifié :         base/locale/fr_BE/LC_MESSAGES/django.po
Référence Jira : OSIS-974
=> OSIS-974 Correction d'une clé de traduction erronée

base/templates/learning_unit/achievements.html, base/templatetags/index.py, base/tests/templatetags/test_index.py
=> OSIS-982 Correct + Allow user to hide a part of accordeon

base/templates/learning_unit/achievements.html
=> OSIS-982 Correct JS + write in a better way

base/models/offer_enrollment.py, base/models/offer_year.py, base/models/student.py, base/tests/models/test_offer_enrollment.py, base/tests/models/test_offer_year.py, base/tests/models/test_student.py, dissertation/static/css/dissertation_style.css, dissertation/templates/manager_students_list.html, dissertation/views/dissertation.py
Référence Jira : OSIS-354 dissertation: add the list of managed students and if they have a current dissertation or not.
=> Osis 354 dissertation: add the list of managed students and if they have a current dissertation or not.

base/forms/learning_unit/learning_unit_create_2.py, base/forms/learning_unit_proposal.py, base/tests/forms/test_learning_unit_create_2.py
=> OSIS-1033 Disable postponement for proposals

base/models/group_element_year.py, base/tests/models/test_group_element_year.py, base/tests/views/test_learning_unit.py, base/views/learning_unit.py
=> OSIS-1036 ordered formations and group elements years by acronym

base/models/education_group_year.py, base/models/group_element_year.py, base/tests/models/test_education_group_year.py, base/tests/models/test_group_element_year.py, base/views/learning_unit.py
=> OSIS-1037 fixed child appear twice for same parent + fixed enrollments count

base/locale/en/LC_MESSAGES/djangojs.po, base/locale/fr_BE/LC_MESSAGES/djangojs.po, base/templates/learning_unit/achievements.html
=> #OSIS-983 Ajout d'un message de confirmation

base/forms/learning_unit/learning_unit_create.py, base/forms/utils/acronym_field.py, base/tests/forms/test_learning_unit_partim.py
=> OSIS-1042 Use split-acronym for initial data

base/business/learning_units/edition.py, base/forms/learning_unit/learning_unit_create_2.py, base/tests/forms/test_learning_unit_partim.py
=> OSIS-1044 Updating a partim does not change its container

base/tests/forms/test_learning_unit_proposal.py, base/tests/views/test_learning_unit_proposal.py, base/views/learning_units/proposal/update.py
=> OSIS_1057 Initial state for proposal with central_manager

base/business/entity.py
=> #OSIS-1062 Add condition on all_descendants in _get_distinct_entity_ids.

base/forms/learning_achievement.py, base/templates/learning_unit/achievement_edit.html, base/templates/learning_unit/achievements.html, base/views/learning_achievement.py
=> Osis 984  OSIS-984 Automatically create an english entry for each french achievements

base/business/learning_unit_proposal.py
=> #OSIS-950 Refactor cancel_proposal to show ERROR to user.

base/business/learning_units/perms.py, base/templates/learning_unit/achievements.html, base/tests/views/test_learning_achievement.py, base/views/learning_achievement.py, base/views/learning_unit.py, base/views/learning_units/perms.py
=> OSIS-993 Add permissions to update learning_achievements

base/models/learning_unit.py, base/tests/model_forms/learning_unit/test_learning_unit_year.py, base/tests/models/test_learning_unit.py
modifié :         base/models/learning_unit.py
Référence Jira : OSIS-1070
=> Correction de l'admin de LearningUnit

base/forms/learning_unit_proposal.py
=> OSIS-1076 Change default value for proposal_type in ProposalBaseForm

assistant/business/assistant_mandate.py, assistant/locale/en/LC_MESSAGES/django.po, assistant/locale/fr_BE/LC_MESSAGES/django.po, assistant/models/review.py, assistant/templates/manager_assistant_form_view.html, assistant/templates/manager_reviews_view.html, assistant/templates/mandate_form.html, assistant/templates/mandates_list.html, assistant/tests/business/test_assistant_mandate.py, assistant/tests/models/test_review.py, assistant/tests/test_urls.py, assistant/urls.py, assistant/views/manager_reviews_view.py, assistant/views/mandates_list.py, assistant/views/phd_supervisor_review.py
=> Osis 1020 : Add mandates step backward

base/templates/learning_unit/achievements.html
=> #OSIS-1077 Ajout de permission sur le bouton ajouter

base/templates/learning_unit/achievements.html
=> #OSIS-1077 Modification disposition écran

base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-1089 Add translation for program managers

backoffice/settings/base.py, base/tests/views/learning_units/proposals/test_consolidate.py, base/tests/views/learning_units/proposals/test_creation.py, base/tests/views/test_learning_unit_proposal.py, base/views/learning_units/proposal/consolidate.py, base/views/learning_units/proposal/create.py, base/views/learning_units/proposal/delete.py, base/views/learning_units/proposal/update.py, requirements.txt, travis-requirements.txt
=> OSIS_Waffle : install django_waffle and test it on proposals

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/models/learning_unit_year.py, base/templates/learning_unit/identification.html, base/templatetags/learning_unit.py
modifié :         base/locale/en/LC_MESSAGES/django.po
modifié :         base/locale/fr_BE/LC_MESSAGES/django.po
modifié :         base/models/learning_unit_year.py
modifié :         base/templates/learning_unit/identification.html
Référence Jira : OSIS-614
=> OSIS-614 Gestion du cas des Internship sans sous-type de stage
