- base/migrations/0555_copy_reddot_information.py
> OSIS-3719 : migration test script

- base/migrations/0555_copy_reddot_information.py
> Fix migration

- base/migrations/0555_copy_reddot_information.py
> fix missing args

- base/migrations/0555_copy_reddot_information.py
> OSIS-3719 : publication_contact_entity

- education_group/api/serializers/group_element_year.py
- program_management/tests/ddd/factories/node.py
> OSIS-5512 : Fix constraint_type

- attribution/views/manage_my_courses.py
- base/models/learning_unit_year.py
- base/tests/models/test_learning_unit_year.py
- learning_unit/calendar/learning_unit_force_majeur_summary_edition.py
- learning_unit/migrations/0006_auto_20210112_1041.py
- learning_unit/tests/calendar/test_learning_unit_force_majeur_summary_edition.py
> Osis 5507 Fix migration file + rename variable 

- attribution/business/attribution_json.py
- base/models/proposal_learning_unit.py
- base/tests/models/test_proposal_learning_unit.py
> OSIS-5532 Add is_in_suppression_proposal bool to luy data sent to portal

- program_management/ddd/business_types.py
- program_management/ddd/domain/program_tree.py
- program_management/ddd/repositories/load_tree.py
- program_management/ddd/repositories/program_tree.py
- program_management/ddd/repositories/tree_prerequisites.py
- program_management/ddd/service/write/detach_node_service.py
- program_management/ddd/service/write/paste_element_service.py
- program_management/ddd/validators/_has_or_is_prerequisite.py
- program_management/ddd/validators/validators_by_business_action.py
- program_management/tests/ddd/domain/test_program_tree.py
- program_management/tests/ddd/factories/domain/program_tree/LADRT100I_MINADROI.py
- program_management/tests/ddd/factories/domain/program_tree/LDROI100B_DROI1BA.py
- program_management/tests/ddd/factories/domain/program_tree/LSPED200M_SPED2M.py
- program_management/tests/ddd/repositories/test_persist_tree.py
- program_management/tests/ddd/validators/test_has_or_is_prerequisite.py
> OSIS-5372 Create and use PrerequisiteRepository to manage specific tests cases in prerequisites validation

- education_group/api/serializers/group_element_year.py
> OSIS-5519 : Remove trailing zeros in volume

- education_group/templates/education_group_app/publication_contact/edit_inner.html
> OSIS-3839 check form valid before submit for contact form

- base/tests/business/test_perms.py
- learning_unit/auth/predicates.py
- learning_unit/auth/roles/central_manager.py
- learning_unit/auth/roles/faculty_manager.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-5521 block lu end date modification if attributions in future

- cms/templates/cms/modal/modal_cms_edit_inner.html
- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/templates/education_group_app/achievement/delete_inner.html
- education_group/templates/education_group_app/achievement/edit_inner.html
- education_group/templates/education_group_app/achievement/order_inner.html
- education_group/templates/education_group_app/admission_condition/edit_inner.html
- education_group/templates/education_group_app/admission_condition/line_delete_inner.html
- education_group/templates/education_group_app/admission_condition/line_edit_inner.html
- education_group/templates/education_group_app/admission_condition/line_order_inner.html
- education_group/templates/education_group_app/blocks/achievements_panel.html
- education_group/templates/education_group_app/publication_contact/delete_inner.html
- education_group/templates/education_group_app/publication_contact/edit_inner.html
- education_group/templates/education_group_app/publication_contact/entity_edit_inner.html
> OSIS-3839 adapt text

- base/tests/business/test_perms.py
- learning_unit/auth/predicates.py
- learning_unit/auth/roles/central_manager.py
- learning_unit/auth/roles/faculty_manager.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-5521 vers QA
> [hotfix/OSIS-5521 => QA] Unités d_enseignement > Modifier la date de fin indisponible pour un facultaire

- base/business/event_perms.py
- education_group/calendar/dissertation_submission_calendar.py
- education_group/tasks/check_academic_calendar.py
- education_group/tests/calendar/test_dissertation_submission_calendar.py
- education_group/tests/tasks/test_check_academic_calendar.py
> Osis 5543 Create Dissertation Submission Calendar

- education_group/views/training/common_read.py
> OSIS-5260 : Suppression de print

- base/business/event_perms.py
- education_group/calendar/dissertation_submission_calendar.py
- education_group/tasks/check_academic_calendar.py
- education_group/tests/calendar/test_dissertation_submission_calendar.py
- education_group/tests/tasks/test_check_academic_calendar.py
Pull request automatique de technical/OSIS-5543 vers DEV
> [technical/OSIS-5543 => DEV] [Remise du mémoire] Adapter les événements académiques

- backoffice/settings/base.py
Référence Jira : INTERNSHIP-208
> INTERNSHIP-208 update ref internship

- program_management/ddd/domain/prerequisite.py
> OSIS-5530 : Do not translate secondary operator

- cms/contrib/views.py
- cms/templates/cms/modal/modal_cms_edit_inner.html
- education_group/forms/admission_condition.py
- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/templates/education_group_app/achievement/delete_inner.html
- education_group/templates/education_group_app/achievement/edit_inner.html
- education_group/templates/education_group_app/achievement/order_inner.html
- education_group/templates/education_group_app/admission_condition/line_delete_inner.html
- education_group/templates/education_group_app/admission_condition/line_order_inner.html
- education_group/templates/education_group_app/mini_training/admission_condition_read.html
- education_group/tests/views/mini_training/test_general_information_update.py
- education_group/tests/views/training/test_general_information_update.py
- education_group/views/admission_condition/common.py
- education_group/views/admission_condition/create.py
- education_group/views/admission_condition/update.py
- education_group/views/mini_training/general_information_update.py
- education_group/views/training/general_information_update.py
> Osis 3839 minor corrections

- base/business/learning_units/simple/deletion.py
- base/tests/views/test_learning_unit_deletion.py
Pull request automatique de hotfix/OSIS-4524 vers QA
> [hotfix/OSIS-4524 => QA] Rapport de consolidation : infos en double

- program_management/ddd/validators/_authorized_relationship.py
- program_management/ddd/validators/_authorized_relationship_for_all_trees.py
- program_management/ddd/validators/validators_by_business_action.py
> OSIS-5221 transmit link type when pasting

- education_group/auth/predicates.py
- education_group/views/mini_training/common_read.py
- education_group/views/training/common_read.py
- education_group/views/training/identification_read.py
- program_management/business/excel_ue_in_of.py
- program_management/ddd/domain/exception.py
- program_management/ddd/domain/program_tree_version.py
- program_management/forms/version.py
- program_management/templates/tree_version/mini_training/blocks/identification.html
- program_management/templates/tree_version/training/blocks/panel_informations_form.html
- program_management/templatetags/version_label.py
- program_management/templatetags/version_name_suffix.py
- program_management/tests/ddd/factories/program_tree_version.py
- program_management/tests/templatetags/test_version_label.py
- program_management/tests/views/tree_version/test_update_mini_training.py
- program_management/views/proxy/identification.py
- program_management/views/tree_version/update_mini_training.py
- program_management/views/tree_version/update_training.py
> OSIS-5529 : Edit transition version (mostly display)

- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/views/publication_contact/create.py
- education_group/views/publication_contact/delete.py
- education_group/views/publication_contact/update.py
> OSIS-3839 traductions

- base/tests/business/test_perms.py
- education_group/api/serializers/group_element_year.py
- learning_unit/auth/predicates.py
- learning_unit/auth/roles/central_manager.py
- learning_unit/auth/roles/faculty_manager.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-5479 vers DEV
> [hotfix/OSIS-5479 => DEV] [QA] UE > Actualiser et visualiser la publication doit utiliser qacours

- program_management/ddd/domain/program_tree.py
- program_management/ddd/validators/_authorized_relationship_for_all_trees.py
- program_management/tests/ddd/domain/test_program_tree.py
> OSIS-5221 fix check authorized relationship on all trees

- education_group/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-3839 typo

- education_group/auth/roles/faculty_manager.py
> OSIS-5547 change check calendar for skills and conditions tabs

- program_management/ddd/domain/program_tree.py
- program_management/ddd/validators/_authorized_relationship_for_all_trees.py
- program_management/ddd/validators/validators_by_business_action.py
- program_management/tests/ddd/factories/node.py
> Osis 5221 fix double error message displaying

- webservices/api/serializers/admission_condition_line.py
> OSIS-5549 : use enum for access in admission condition

- education_group/auth/roles/faculty_manager.py
Pull request automatique de hotfix/OSIS-5547 vers MASTER
> Release 3.1.2

- education_group/templates/education_group_app/group/content_read.html
- education_group/templates/education_group_app/mini_training/content_read.html
- education_group/templates/education_group_app/training/content_read.html
> OSIS-4490 : le nom des div/a n'était pas bien construit

- learning_unit/calendar/learning_unit_enrollment_calendar.py
- learning_unit/tasks/check_academic_calendar.py
- learning_unit/tests/calendar/test_learning_unit_enrollment_calendar.py
- learning_unit/tests/tasks/test_check_academic_calendar.py
> OSIS-5544 Create LearningUnitEnrollmentCalendar on learning_unit app

- assessments/calendar/scores_exam_diffusion_calendar.py
- assessments/tasks/__init__.py
- assessments/tasks/check_academic_calendar.py
- assessments/tests/calendar/test_scores_exam_diffusion_calendar.py
- assessments/tests/tasks/test_check_academic_calendar.py
> OSIS-5568 Add ScoreExamDiffusionCalendar on assessments calendar

- base/templates/education_group/blocks/modal/modal_pedagogy_edit_inner.html
- base/templates/learning_unit/blocks/modal/modal_pedagogy_edit.html
> OSIS-5491 : Fix Osis-Inception

- education_group/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-4379 : Accès personnalisé => Accès sur dossier

- base/business/education_groups/general_information_sections.py
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/templates/education_group_app/general_information/common_master.html
- education_group/templates/education_group_app/training/admission_condition_read.html
> OSIS-5548 : Add common-2m (general conditions)

- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/templates/education_group_app/general_information/common_master.html
- education_group/templates/education_group_app/training/admission_condition_read.html
- education_group/tests/views/serializers/test_admission_condition.py
- education_group/views/serializers/admission_condition.py
> OSIS-5548 : English translation

- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/templates/education_group_app/training/admission_condition_read.html
> OSIS-5548 : Move general_condition down

- base/templates/learning_unit/search/base.html
Pull request automatique de hotfix/OSIS-5551 vers QA
> [hotfix/OSIS-5551 => QA] UE_s > Onglet propositions > Modification de la recherche après changement d_état

- assessments/business/scores_encodings_deadline.py
- assessments/tests/business/test_scores_encodings_deadline.py
- base/models/offer_year_calendar.py
> OSIS-5562 refactored signals to compute scores encodings deadlines (using EducationGroupyear)

- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/templates/education_group_app/general_information/common_master.html
- education_group/templates/education_group_app/training/admission_condition_read.html
- education_group/tests/views/serializers/test_admission_condition.py
- education_group/views/serializers/admission_condition.py
> OSIS-4379 : English translation

- base/migrations/0558_auto_20210202_1700.py
> OSIS-5522 : Fix script in migration

- base/templates/base/person_list.html
- base/views/user_list.py
- osis_role/contrib/helper.py
> OSIS-5573 create helper to get entity roles from multiple persons

- base/migrations/0558_auto_20210202_1700.py
> OSIS-5522 : fix migration

- education_group/migrations/0018_default_titles_and_credits.py
- program_management/ddd/domain/node.py
- program_management/ddd/domain/service/generate_node_abbreviated_title.py
- program_management/ddd/domain/service/validation_rule.py
- program_management/tests/ddd/domain/service/test_generate_node_abbreviated_title.py
> OSIS-5526 : Adapt query and fix generated title

- base/templatetags/messages.py
- base/views/learning_units/common.py
- base/views/learning_units/detail.py
- base/views/learning_units/proposal/update.py
- base/views/learning_units/update.py
- program_management/ddd/domain/node.py
- program_management/formatter.py
> Osis 3822 bis

- program_management/ddd/domain/node.py
> OSIS-5526 : default credit in version creation

- base/business/learning_unit_proposal.py
- learning_unit/auth/predicates.py
- learning_unit/auth/roles/central_manager.py
- learning_unit/auth/roles/faculty_manager.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
s'il tente d'annuler ou réfuser une proposition de création qui a des attributions
s'il tente de consolider une proposition de suppression qui a des attributions
> OSIS-5554-bis : bloquer l'utilisateur :

- program_management/ddd/domain/node.py
- program_management/tests/ddd/domain/test_node.py
- program_management/tests/ddd/validators/test_authorized_relationship.py
> OSIS-5527 : Fix order when delete link

- program_management/ddd/domain/program_tree_version.py
> OSIS-5580 change return for is_transition property

- education_group/templates/education_group_app/training/identification/panel_entities.html
> OSIS-5582 : Display correct end year if transition

- base/templates/template_messages.html
> fix template tag load

- program_management/ddd/domain/node.py
- program_management/ddd/domain/program_tree.py
- program_management/ddd/repositories/program_tree.py
- program_management/ddd/service/write/bulk_copy_program_tree_version_content_service.py
- program_management/ddd/service/write/copy_program_tree_content_service.py
- program_management/locale/en/LC_MESSAGES/django.po
- program_management/locale/fr_BE/LC_MESSAGES/django.po
- program_management/models/education_group_version.py
- program_management/tests/ddd/service/write/test_bulk_copy_program_tree_version_content_service.py
> OSIS-5352 copy program tree content to next year

- base/migrations/0566_fix_link_orders.py
> OSIS-5527 : fix migration

- base/forms/learning_unit/search/borrowed.py
> OSIS-4205 omit learning unit without element in borrowed search

- base/api/serializers/person.py
- base/tests/api/serializers/test_person.py
> Add birth_date to person serializer

- education_group/schema.yml
> OSIS-5585 : Add title_en into schema

- program_management/ddd/validators/_authorized_relationship.py
- program_management/forms/content.py
- program_management/tests/ddd/service/write/test_paste_node_service.py
> OSIS-5586 fix permit paste list minor major inside list minor major

- program_management/schema.yml
> OSIS-5585 : Add title_en into schema (program_management)

- backoffice/settings/rest_framework/common_views.py
> Fallback to default lang when requested lang is not supported

- education_group/schema.yml
- program_management/ddd/validators/_authorized_relationship.py
- program_management/forms/content.py
- program_management/schema.yml
- program_management/tests/ddd/service/write/test_paste_node_service.py
> Rc.3.2.1 Hotfix

- education_group/schema.yml
- program_management/schema.yml
Pull request automatique de hotfix/OSIS-5585 vers MASTER
> [hotfix/OSIS-5585 => MASTER] Champ _title_en_ pour les prérequis d_une offre pas repris dans le schéma yml

- program_management/ddd/validators/_authorized_relationship.py
- program_management/forms/content.py
- program_management/tests/ddd/service/write/test_paste_node_service.py
Pull request automatique de hotfix/OSIS-5586 vers MASTER
> [hotfix/OSIS-5586 => MASTER] (245344) Formation > Arbre > impossible d_ajouter une liste aux choix de mineures dans une liste au choix

- education_group/forms/group.py
- education_group/forms/mini_training.py
- education_group/forms/training.py
- program_management/forms/content.py
- program_management/forms/version.py
**NE PAS MERGER**
Référence Jira : OSIS-5588
> OSIS-5588 convert to richtext remark fields for versions

- education_group/migrations/0021_default_titles_bis.py
> OSIS-5593 : Fix common core queryset

- learning_unit/auth/predicates.py
- learning_unit/auth/roles/central_manager.py
- learning_unit/auth/roles/faculty_manager.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-5554-bis : Correction d'un message d'erreur dans un predicate

- base/templates/education_group/blocks/dropdown/identification_actions_bar.html
> OSIS-5601 menu séparé pour créer la version de transition

- education_group/migrations/0021_default_titles_bis.py
> OSIS-5593 : remove space

- program_management/formatter.py
- program_management/locale/en/LC_MESSAGES/django.po
- program_management/locale/fr_BE/LC_MESSAGES/django.po
- program_management/views/tree_version/delete.py
> Osis 5591 confirmation message delete

- program_management/ddd/command.py
- program_management/ddd/domain/exception.py
- program_management/ddd/service/read/check_transition_name_service.py
- program_management/ddd/validators/_transition_name_pattern.py
- program_management/ddd/validators/validators_by_business_action.py
- program_management/forms/version.py
- program_management/locale/en/LC_MESSAGES/django.po
- program_management/locale/fr_BE/LC_MESSAGES/django.po
- program_management/urls.py
- program_management/views/tree_version/check_transition_name.py
> Fixed Issue1, Issue6, Issue7

- education_group/templates/education_group_app/general_information/common_master.html
> OSIS-5604 : Add missing code !?

- base/business/education_groups/general_information_sections.py
- education_group/templates/education_group_app/general_information/common_bachelor.html
- education_group/templates/education_group_app/training/admission_condition_read.html
- education_group/tests/views/serializers/test_admission_condition.py
- education_group/views/serializers/admission_condition.py
> OSIS-5605 : add common section for bachelors

- program_management/ddd/validators/_transition_name_pattern.py
- FIxed validator patern transition_name
Référence Jira : OSIS-5599
> OSIS-5599 Fixed validator

- base/fixtures/validation_rules.csv
> OSIS-5333 : Valider 'Bachelier ???' au lieu de 'Bachelier en ???'

- program_management/views/groupelementyear_read.py
> OSIS-5600 : Le pdf ne s'imprimait plus

- program_management/ddd/domain/link.py
- program_management/ddd/domain/node.py
- program_management/ddd/domain/program_tree.py
- program_management/ddd/validators/_authorized_relationship.py
**NE PAS MERGER**
Référence Jira : OSIS-5592
> OSIS-5592 copy tree performance up

- base/fixtures/validation_rules.csv
Pull request automatique de feature/OSIS-5333 vers DEV
> [feature/OSIS-5333 => DEV] Formations > Modification expression régulière acceptée 1BA

- base/business/education_groups/general_information_sections.py
- education_group/templates/education_group_app/general_information/common_bachelor.html
- education_group/templates/education_group_app/training/admission_condition_read.html
- education_group/tests/views/serializers/test_admission_condition.py
- education_group/views/serializers/admission_condition.py
Pull request automatique de hotfix/OSIS-5605 vers QA
> [hotfix/OSIS-5605 => QA] Formations > Conditions > Ajout d_une section dans Common-1ba pour les bacheliers

- base/templates/education_group/blocks/dropdown/identification_actions_bar.html
> OSIS-5609 : action menu format

- education_group/views/mini_training/common_read.py
- education_group/views/training/common_read.py
- program_management/locale/en/LC_MESSAGES/django.po
- program_management/locale/fr_BE/LC_MESSAGES/django.po
- program_management/templates/tree_version/create_specific_version_inner.html
- program_management/views/tree_version/create.py
> OSIS-5606 : Display error in modal instead of hiding button

- education_group/views/mini_training/common_read.py
> OSIS-5610: disable url if has other transition (mini_training)

- assessments/business/enrollment_state.py
- assessments/views/score_encoding.py
- base/business/event_perms.py
- base/models/session_exam_calendar.py
- base/tests/forms/test_education_groups_administrative_data.py
- base/tests/mixin/session_exam_calendar.py
- base/tests/models/test_session_exam_calendar.py
> OSIS-3458 use new PermissionCalendar for scores encodings period opening

- program_management/ddd/domain/program_tree.py
- program_management/forms/content.py
- program_management/forms/tree/paste.py
- program_management/tests/ddd/service/write/test_paste_node_service.py
When attaching a node to a parent which is list minor major or
option choice, the link should not be mandatory.
> OSIS-5557 mandatory false when parent is list minor major option

- requirements.txt
> update celery libraries

- base/views/offer.py
> OSIS-5617  OSIS-5617 include subordinated entities when searching offers by entity's acronym

- base/fixtures/validation_rules.csv
- base/templates/templatetags/navigation_education_group.html
- base/templatetags/navigation.py
- base/tests/templatetags/test_navigation.py
- education_group/templates/education_group_app/group/layout_read.html
- education_group/templates/education_group_app/mini_training/identification_read.html
- education_group/templates/education_group_app/mini_training/layout_read.html
- education_group/templates/education_group_app/training/identification/panel_informations.html
- education_group/templates/education_group_app/training/layout_read.html
- education_group/templatetags/version_details.py
- education_group/views/mini_training/common_read.py
- education_group/views/training/common_read.py
- program_management/ddd/domain/service/get_next_version_if_exists.py
- program_management/ddd/validators/_match_transition.py
- program_management/ddd/validators/_update_check_existence_of_transition.py
- program_management/ddd/validators/validators_by_business_action.py
- program_management/forms/education_groups.py
- program_management/forms/transition.py
- program_management/templates/program_management/content/update.html
- program_management/templates/tree_version/mini_training/blocks/identification.html
- program_management/templates/tree_version/mini_training/update.html
- program_management/templates/tree_version/training/blocks/panel_informations_form.html
- program_management/templates/tree_version/training/update.html
- program_management/tests/ddd/validators/test_match_transition.py
- program_management/tests/ddd/validators/test_update_check_existence_of_transition.py
- program_management/views/content/update.py
- program_management/views/tree/move.py
- program_management/views/tree_version/update_mini_training.py
- program_management/views/tree_version/update_training.py
> OSIS-5332 : retour de tests

- program_management/forms/education_groups.py
> OSIS-5332 : Fix label in search view

- program_management/forms/education_groups.py
> OSIS-5629 : Fix missing groups if with_transition disabled

- base/templates/education_group/blocks/modal/modal_xls_trainings_list_with_parameters.html
> OSIS-4558 : Mettre le select all en gras

- education_group/tests/views/admission_condition/test_common.py
- education_group/views/admission_condition/common.py
- education_group/views/admission_condition/create.py
- education_group/views/admission_condition/delete.py
- education_group/views/admission_condition/order.py
- education_group/views/admission_condition/update.py
Pull request automatique de hotfix/OSIS-5634 vers MASTER
> RELEASE 3.3.2

- base/static/js/osis-form.js
On error, we need to remove the warning message that was present.
> fix remote validation warning message suppression

- program_management/forms/tree/paste.py
> OSIS-5557 populate clean data even if no data changed

- base/tasks/__init__.py
> Add import calendar_reminder_notice on __init__ of tasks

- program_management/templates/tree_version/create_transition_version_inner.html
> OSIS-5606 : Fix style of modal and add cancel button if error

- base/tasks/__init__.py
> Change Calendar Reminder Notice to 8 hours instead of 9 hours

- attribution/tests/api/serializers/test_calendar.py
- attribution/tests/views/test_manage_my_courses.py
- base/tests/models/test_entity_version_address.py
- osis_role/tests/contrib/forms/test_fields.py
> assertEquals to assertEqual

- education_group/views/mini_training/common_read.py
> OSIS-5606 : Fix overrided change

- base/business/learning_units/comparison.py
- base/templates/learning_unit/comparison.html
- base/templates/learning_unit/remarks_comparison.html
> OSIS-5495 : Ajouter les champs remarques dans la fiche comparative

- base/migrations/0569_update_is_mandatory_field_when_empty_skeleton.py
> OSIS-4492-issue1 fix migration to update minitraining too

- base/business/list/ue_utilizations.py
> OSIS-4174 : Certaines bordures top n'était pas settées

- base/business/learning_units/perms.py
> OSIS-5644 Fix conditions to edit learning units pedagogy

- attribution/views/manage_my_courses.py
- base/tests/views/test_learning_unit_pedagogy.py
- base/views/learning_units/pedagogy/update.py
> OSIS-5644 Restore redirections after posts

- .github/CONTRIBUTING.md
> reorganized sections and add table of content

- attribution/views/manage_my_courses.py
- base/templates/learning_unit/blocks/modal/modal_pedagogy_edit.html
- base/tests/views/test_learning_unit_pedagogy.py
- base/views/learning_units/pedagogy/update.py
Pull request automatique de hotfix/OSIS-5644 vers MASTER
> Release 3.3.5

- education_group/views/mixin.py
> OSIS-5639 : label in popup for copy/cut

- education_group/templates/education_group_app/mini_training/utilization_read.html
- education_group/templates/education_group_app/training/utilization_read.html
> OSIS-5594 : Label in some views

- base/business/education_group.py
- base/tests/business/test_education_group.py
- education_group/views/serializers/group_year.py
- program_management/models/education_group_version.py
- program_management/templates/quick_search_egy_inner.html
- program_management/tests/models/test_education_group_version.py
> OSIS-5596 : label in search and xls

- base/forms/learning_unit/edition.py
- base/tests/forms/test_learning_unit_edition.py
> OSIS-5350 fix Modifier la date de fin d_une UE dans le passe impossible

- base/migrations/0569_update_is_mandatory_field_when_empty_skeleton.py
> OSIS-4492-issue2 fix skeleton after update of excel file

- .env.example
- attribution/api/serializers/attribution.py
- attribution/api/views/attribution.py
- attribution/schema.yml
- attribution/tests/api/serializers/test_attribution.py
- attribution/tests/api/views/test_attribution.py
- backoffice/settings/base.py
> OSIS-5633 Update endpoint attribution to take account of charge in epc

- education_group/views/general_information/common.py
- education_group/views/general_information/common_aggregate.py
- education_group/views/general_information/common_bachelor.py
- education_group/views/general_information/common_master.py
- education_group/views/general_information/common_master_specialized.py
> OSIS-5656 : le bouton "refresh" des commons avait disparu

- education_group/api/views/training.py
- education_group/schema.yml
- reference/api/serializers/study_domain.py
- reference/api/views/study_domain.py
- reference/models/enums/decree_type.py
- reference/schema.yml
- reference/tests/api/serializers/test_study_domain.py
- reference/tests/api/views/test_study_domain.py
Pull request automatique de technical/OSIS-5662 vers DEV
> [technical/OSIS-5662 => DEV] Ajouter API/filtre pour la recherche d_une formation

- program_management/ddd/domain/program_tree.py
- program_management/ddd/domain/service/identity_search.py
- program_management/tests/ddd/domain/test_program_tree.py
- program_management/tests/views/test_prerequisite_update.py
- program_management/views/generic.py
- program_management/views/prerequisite_update.py
> OSIS-5650 : deprecated get_node_by_id_and_type

- learning_unit/migrations/0010_auto_20210115_1314.py
> OSIS-5469-update_date correct start_date for daily management + remove old calendars

- base/models/enums/academic_calendar_type.py
> OSIS-5469-calendar_view add new calendars and remove old ones

- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/templates/education_group_app/general_information/common_aggregate.html
- education_group/templates/education_group_app/general_information/common_bachelor.html
- education_group/templates/education_group_app/general_information/common_master.html
- education_group/templates/education_group_app/general_information/common_master_specialized.html
- education_group/templates/education_group_app/mini_training/admission_condition_read.html
- education_group/templates/education_group_app/training/admission_condition_read.html
- education_group/tests/views/serializers/test_admission_condition.py
- education_group/views/serializers/admission_condition.py
> OSIS-5655 : Edit translations of admission condition

- education_group/ddd/service/write/update_mini_training_and_group_service.py
- program_management/ddd/service/write/update_and_postpone_mini_training_version_service.py
> OSIS-5658 : Fix blocked report caused by consistency error

- base/business/learning_unit_proposal.py
Pull request automatique de hotfix/OSIS-5537 vers QA
> [hotfix/OSIS-5537 => QA] Unités d_enseignement > Propositions > Annuler > Erreur

- base/migrations/0568_auto_20210304_1442.py
> OSIS-4991 : fix group too

- education_group/ddd/validators/_hops_validator.py
> OSIS-5636 : J'avais oublié d'utiliser la variable ares_fields_needed

- base/migrations/0568_auto_20210304_1442.py
> OSIS-4991 : Fix migration

- base/migrations/0568_auto_20210304_1442.py
> OSIS-4991 : Fix Groups 2015

- program_management/ddd/command.py
- program_management/ddd/domain/program_tree.py
- program_management/ddd/service/write/copy_program_tree_prerequisites_from_program_tree_service.py
- program_management/ddd/service/write/fill_program_tree_version_content_from_program_tree_version_service.py
> OSIS-5352 fix prerequisites copy

- base/forms/learning_unit/entity_form.py
> OSIS-5670 : Eviter la keyerror

- base/forms/learning_unit/entity_form.py
Pull request automatique de hotfix/OSIS-5670 vers QA
> [hotfix/OSIS-5670 => QA] [Echec Qa] - Proposition de création d_UE en état accepté > Ne jamais bloquer la consolidation

- program_management/migrations/0009_auto_20210305_1506.py
> OSIS-5664 : Create missing childs and element

- learning_unit/auth/predicates.py
- learning_unit/tests/auth/test_predicates.py
> OSIS-5669 : Je dois pouvoir supprimer un partim peu importe son type

- education_group/auth/predicates.py
- education_group/auth/roles/faculty_manager.py
> OSIS-4805 : faculty permissions

- education_group/forms/group.py
- education_group/tests/forms/test_group.py
- program_management/forms/transition.py
> OSIS-4805 : Fix fields permissions

- base/tests/business/test_learning_unit_deletion.py
- base/tests/business/test_learning_unit_proposal.py
- base/tests/business/test_perms.py
- learning_unit/auth/predicates.py
- learning_unit/auth/roles/central_manager.py
- learning_unit/auth/roles/faculty_manager.py
> OSIS-5678 allow delete on partim even attribution on parent

- base/business/learning_unit_proposal.py
- base/forms/learning_unit/entity_form.py
Pull request automatique de hotfix/OSIS-5670 vers DEV
> [hotfix/OSIS-5670 => DEV] [Echec Qa] - Proposition de création d_UE en état accepté > Ne jamais bloquer la consolidation

- base/static/css/osis.css
- base/static/js/education_group/element-focus.js
- education_group/templates/education_group_app/blocks/admission_condition_table_row.html
- education_group/templates/education_group_app/blocks/admission_condition_text.html
- education_group/templates/education_group_app/training/layout_read.html
> OSIS-5673 : Focus sur l'élément modifié/crée/supprimé

- program_management/ddd/service/write/publish_program_trees_using_node_service.py
> OSIS-5682 : Publish minor with its bachelors

- education_group/auth/roles/faculty_manager.py
Pull request automatique de hotfix/OSIS-5546 vers QA
> [hotfix/OSIS-5546 => QA] Formations > Facultaire en gestion journalière doit pouvoir éditer certains champs

- attribution/api/views/attribution.py
- attribution/schema.yml
Pull request automatique de hotfix/OSIS-5693 vers QA
> [WIP] [hotfix/OSIS-5693 => QA] Ma charge d’enseignement ne fonctionne pas si la date de début est null

- attribution/tests/views/test_attribution.py
- attribution/views/attribution.py
- base/models/person.py
- base/templates/my_osis/profile.html
- base/tests/models/test_person.py
> OSIS-5696 : Suppression du middle_name dans les affichages

- program_management/ddd/domain/service/get_node_publish_url.py
- program_management/tests/ddd/domain/service/test_get_node_publish_url.py
> OSIS-5682 : Fix url to publish

- program_management/views/groupelementyear_read.py
Pull request automatique de hotfix/OSIS-5704 vers QA
> [hotfix/OSIS-5704 => QA] Génération PDF depuis Formation racine --> erreur

- base/migrations/0578_studentspecificprofile_translation.py
> OSIS-5695 : fix migration for dev

- education_group/auth/roles/faculty_manager.py
> OSIS-4805 : Fix some faculty perms

- webservices/api/serializers/achievement.py
> OSIS-5703 : AA in english (caused by missing context)

- webservices/api/serializers/achievement.py
Pull request automatique de hotfix/OSIS-5703 vers QA
> [hotfix/OSIS-5703 => QA] WS Reddot > Les AA ne sont pas envoyés en anglais

- program_management/business/excel.py
- program_management/formatter.py
> OSIS-5595 : Format version_label for xls 65c8431

- education_group/api/serializers/education_group_version.py
- education_group/api/serializers/mini_training.py
- education_group/api/serializers/training.py
- education_group/schema.yml
- education_group/tests/api/serializers/test_education_group_version.py
> OSIS-5715 : add is_transition field

- education_group/auth/predicates.py
- education_group/auth/roles/faculty_manager.py
- education_group/tests/auth/test_predicates.py
> OSIS-4805 : fix perms : cannot edit if parent not a transition too

- rules_management/fixtures/field_reference.json
> OSIS-4805 : Field reference

- education_group/api/serializers/education_group_version.py
- education_group/api/serializers/mini_training.py
- education_group/api/serializers/training.py
- education_group/schema.yml
- education_group/tests/api/serializers/test_education_group_version.py
Pull request automatique de hotfix/OSIS-5715 vers MASTER
> Release 3.5.1

- education_group/auth/predicates.py
> OSIS-4805 : check all parents

- program_management/ddd/domain/program_tree.py
- program_management/ddd/domain/report_events.py
- program_management/ddd/repositories/report.py
- program_management/locale/en/LC_MESSAGES/django.po
- program_management/locale/fr_BE/LC_MESSAGES/django.po
- program_management/templates/tree_version/fill_content_inner.html
- program_management/urls.py
- program_management/views/tree_version/fill_content.py
> OSIS-1104 small corrections

- base/templatetags/education_group_pdf.py
> OSIS-5713 : Fix pdf with multiple blocks

- base/templatetags/education_group_pdf.py
Pull request automatique de hotfix/OSIS-5713 vers QA
> [hotfix/OSIS-5713 => QA] PDF Formation : croix absentes si bloc = 12

- base/forms/learning_unit/search/external.py
Pull request automatique de hotfix/OSIS-5712 vers QA
> [hotfix/OSIS-5712 => QA] Les UE externes s_affichent plusieurs fois dans les résultats de recherche

- program_management/ddd/domain/service/generate_node_code.py
- program_management/tests/ddd/domain/service/test_generate_node_code.py
> OSIS-1104 fix transition code generation

- program_management/ddd/validators/_delete_check_versions_end_date.py
> OSIS-5709 fix delete check version validator with transition

- base/auth/roles/program_manager.py
Pull request automatique de technical/OSIS-5731 vers DEV
> [technical/OSIS-5731 => DEV] DEV / Gest parcours pas accès à modif adresse feuilles de notes

- base/static/js/osis-form.js
> OSIS-5608 fix modal load when transition already exists

- base/static/js/osis-form.js
> OSIS-5608 keep error messages

- base/forms/learning_unit/search/simple.py
> OSIS-5718 : Décoché par défaut la case 'Uniquement propositions'

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/education_group/blocks/modal/modal_xls_trainings_list_with_parameters.html
- program_management/business/xls_customized.py
- program_management/tests/business/test_xls_customized.py
* retrait du paramètre "code osis"
* ajout du code dans les données par défaut après la colonne des crédits
> OSIS-5723 : Liste des formations > Adaptations

- program_management/ddd/repositories/program_tree_version.py
- program_management/tests/ddd/repositories/test_program_tree_version.py
> OSIS-5733 : fix clause to get start_year

- assessments/forms/score_sheet_address.py
- assessments/locale/en/LC_MESSAGES/django.po
- assessments/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-5732 : Modification libellé 'Localité' en 'Rue et numéro'

- assessments/forms/score_sheet_address.py
- assessments/locale/en/LC_MESSAGES/django.po
- assessments/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de technical/OSIS-5732 vers DEV
> [technical/OSIS-5732 => DEV] DEV / Label modification adresse feuille de notes

- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/templates/education_group_app/configuration/home.html
> OSIS-5701 : missing translation

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/education_group/blocks/modal/modal_xls_trainings_list_with_parameters.html
> OSIS-5723 : Correction intitulé modale

- base/templates/education_group/blocks/modal/modal_xls_trainings_list_with_parameters.html
> OSIS-5723 : Ajout des titles sur les textes aussi

- assessments/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-5739 : Correction coquille

- program_management/ddd/domain/node.py
- program_management/ddd/repositories/program_tree.py
- program_management/ddd/service/write/fill_program_tree_version_content_from_program_tree_version_service.py
> OSIS-1104 copy option in case of transition

- .gitmodules
- backoffice/urls.py
> Add admission app into osis project

- education_group/auth/predicates.py
- education_group/auth/roles/faculty_manager.py
- program_management/ddd/domain/node.py
- program_management/ddd/repositories/program_tree.py
- program_management/ddd/service/write/fill_program_tree_version_content_from_program_tree_version_service.py
> Osis 4066 permit faculty manager to fill transition version

- webservices/api/serializers/utils.py
> OSIS-5681 : fix ws ca_allegement field

- education_group/api/views/mini_training.py
- education_group/api/views/training.py
- education_group/schema.yml
> OSIS-5741 : filter by active status

- education_group/auth/predicates.py
- education_group/auth/roles/faculty_manager.py
> OSIS-4066 faculty manager can always fill transition version

- backoffice/urls.py
> Add API urls from admission app

- program_management/ddd/domain/exception.py
- program_management/ddd/service/read/allowed_children_types_service.py
- program_management/forms/select_type.py
> OSIS-5734 : Fix issue : cannot add more than one minor/major into list

- program_management/ddd/domain/exception.py
- program_management/ddd/service/read/allowed_children_types_service.py
- program_management/forms/select_type.py
- webservices/api/serializers/utils.py
Pull request automatique de technical/OSIS-5734 vers DEV
> [technical/OSIS-5734 => DEV] Formation: Impossible de créer plus d une mini-formation dans la boîte liste au choix de mineures

- backoffice/triggers/repercute_educationgroupyear_unversioned_fields_to_groupyears.sql
> OSIS-5667 : trigger on base_educationgroupyear

- education_group/forms/academic_year_choices.py
- education_group/tests/views/training/test_identification_read.py
- education_group/views/group/common_read.py
- education_group/views/mini_training/common_read.py
- education_group/views/training/common_read.py
- program_management/ddd/domain/service/node_identities_search.py
- program_management/forms/education_groups.py
> OSIS-5716 fix academic years choices dropdown in training and mini_training

- education_group/templates/education_group_app/training/access_requirements_read.html
> OSIS-5763 : Fix editable access requirement

- education_group/templates/education_group_app/training/access_requirements_read.html
> OSIS-5763 : open to adult = common and not editable

- base/forms/learning_unit/search/simple.py
- base/forms/proposal/learning_unit_proposal.py
- base/locale/en/LC_MESSAGES/djangojs.po
- base/locale/fr_BE/LC_MESSAGES/djangojs.po
- base/models/learning_unit_year.py
- base/templates/learning_unit/search/base.html
- base/templates/learning_unit/search/proposal.html
- base/views/learning_units/search/borrowed.py
- base/views/learning_units/search/proposal.py
- base/views/learning_units/search/service_course.py
- base/views/learning_units/search/simple.py
- learning_unit/api/serializers/learning_unit.py
> OSIS-5767 : Gérer la recherche des entités inactives

- .github/CONTRIBUTING.md
- doc/application_service_vs_domain_service.md
- doc/messages_bus.md
- doc/readme.md
> fixed dead links (404 not found) in documentation and guidelines

- assessments/views/score_sheet.py
> OSIS-5779 offer score sheet year base on current academic year

- assessments/views/score_encoding.py
> OSIS-5776 : Eviter un envoi multiple pour une même of

- assessments/views/pgm_manager_administration.py
- base/auth/roles/program_manager.py
> Osis 5779 fixes

- base/api/serializers/person.py
- base/tests/api/serializers/test_person.py
- base/tests/api/views/test_person.py
> OSIS-5790 Fix bad CDN access for scope manager IUFC

- assessments/views/score_encoding.py
> OSIS-5776-to-dev

- base/templates/offer/header.html
- base/templates/offers.html
- base/tests/views/test_offer.py
- base/views/offer.py
> OSIS-5785 : Parcours > Adresses > retirer la notion d'anac

- education_group/auth/predicates.py
- education_group/auth/roles/central_manager.py
- education_group/tests/auth/test_predicates.py
- program_management/forms/select_type.py
- program_management/tests/forms/test_select_type.py
- program_management/views/create_element.py
> OSIS-3718 Add permission for IUFC central manager role

- education_group/api/url_v1.py
- education_group/api/views/mini_training.py
- education_group/api/views/training.py
- education_group/schema.yml
- education_group/tests/api/views/test_mini_training.py
- education_group/tests/api/views/test_training.py
> OSIS-5778 : TrainingOfferRoots endpoint

- program_management/ddd/service/write/fill_program_tree_content_from_last_year_service.py
> OSIS-5680 copy prerequisites

- base/fixtures/validation_rules.csv
Pull request automatique de feature/OSIS-5796 vers DEV
> [feature/OSIS-5796 => DEV] Autoriser _Certificat_ pour les 1FC

- assessments/templates/admin/pgm_manager.html
- assessments/views/pgm_manager_administration.py
Pull request automatique de hotfix/OSIS-3771 vers QA
> [hotfix/OSIS-3771 => QA] Acteurs académiques > Désignation des gestionnaires de parcours > il ne faut plus mentionner l_anac

- education_group/views/group/update.py
> OSIS-5325-2 correct show acronym when inactive for message

- base/utils/send_mail.py
> OSIS-5776 : Si plusieurs receivers envoi d'un mail par receiver

- assessments/templates/admin/pgm_manager.html
> OSIS-5803 Fix type and entity display

- base/tests/utils/test_send_mail.py
- base/utils/send_mail.py
> OSIS-5776 : Si plusieurs receivers. Envoyer un mail par receiver

- assessments/tests/views/test_pgm_manager_administration.py
- assessments/views/pgm_manager_administration.py
> OSIS-5810 : Get only trainings in program managers screen

- base/forms/learning_unit/entity_form.py
- base/forms/learning_unit/learning_unit_create.py
- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/models/entity_version.py
- base/tests/forms/test_learning_unit_create_2.py
- base/tests/views/test_learning_unit_edition.py
- base/views/autocomplete.py
> OSIS-5769-bis : en modif indiquer si une entity est inactive

- requirements.txt
> Update django-autocomplete-light to 3.5.1 to fix jquery dual load

- requirements.txt
> [TEST] Update django-autocomplete-light to 3.5.1 to fix jquery dual load

- base/business/education_group.py
- base/business/xls.py
- base/models/entity_version.py
- base/tests/business/test_xls.py
- base/tests/models/test_entity_version.py
- education_group/views/group/identification_read.py
- education_group/views/mini_training/identification_read.py
- education_group/views/training/identification_read.py
- program_management/business/excel_ue_in_of.py
- program_management/business/xls_customized.py
- program_management/tests/business/test_excel_ue_in_of.py
- program_management/tests/business/test_xls_customized.py
> OSIS-5802 get strikethrough entity acronym when inactive on xls export

- education_group/ddd/domain/exception.py
- education_group/ddd/domain/service/postpone_group.py
- education_group/ddd/service/write/update_group_service.py
- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/tests/ddd/service/write/test_update_group_service.py
- program_management/ddd/domain/service/postpone_link.py
- program_management/ddd/service/write/bulk_update_link_service.py
- program_management/tests/ddd/service/write/test_bulk_update_and_postpone_link_service.py
- program_management/tests/ddd/service/write/test_create_program_tree_specific_version_service.py
> OSIS-3755 do not postpone if group or link is in past

- .gitmodules
- .idea/vcs.xml
> Add history app on osis project

- .gitmodules
- .idea/vcs.xml
- backoffice/urls.py
- requirements.txt
Refs  https://github.com/uclouvain/osis-mail-template/pull/4
> Add osis_mail_template to osis

- requirements.txt
> [QA] Release Partnership 1.1

- base/tests/views/test_learning_unit_pedagogy.py
- base/views/learning_units/pedagogy/read.py
> OSIS-5817 enable pedagogy info retrieval with luy code and year

- requirements.txt
> Release Partnership 1.1

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/studies.html
- base/tests/views/test_common.py
- base/views/common.py
> OSIS-5813 : Add link to Dissertation in student's path

- base/fixtures/groups.json
> Remove Partnership Viewer in groups.json

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/learning_unit/blocks/modal/modal_xls_with_parameters.html
- program_management/business/excel_ue_in_of.py
- program_management/locale/en/LC_MESSAGES/django.po
- program_management/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-5795 fix and rename gathering terms and trans

- program_management/ddd/domain/program_tree.py
> OSIS-5816 : fix duplicates nodes that have prerequisites

- base/business/education_group.py
> OSIS-5802 fix get egy management entity acronym

- base/templates/blocks/navbar_top.html
> OSIS-5813 : Add dissertation link in top menu

- education_group/forms/fields.py
> OSIS-5325-4 correct issue 2

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/blocks/navbar_top.html
- base/templates/studies.html
> OSIS-5813 : Add dissertation link in top menu and student's path page

- base/tests/views/test_common.py
- education_group/views/group/update.py
- education_group/views/mini_training/update.py
- education_group/views/training/update.py
- program_management/views/content/update.py
- program_management/views/tree_version/update_mini_training.py
- program_management/views/tree_version/update_training.py
> OSIS-5720 remove warning message for usage OF side

- infrastructure/messages_bus.py
- program_management/ddd/service/write/postpone_mini_training_and_program_tree_modifications_service.py
- program_management/ddd/service/write/postpone_training_and_program_tree_modifications_service.py
- program_management/tests/ddd/service/write/test_postpone_mini_training_and_program_tree_modifications_service.py
- program_management/tests/ddd/service/write/test_postpone_training_and_program_tree_modifications_service.py
> OSIS-3752 : Not blocking report if extending standard version

- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/templates/education_group_app/blocks/contact_actions.html
- education_group/templates/education_group_app/blocks/general_information_section_contact_ul.html
- education_group/templates/education_group_app/publication_contact/move_inner.html
- education_group/tests/views/publication_contact/test_move.py
- education_group/urls.py
- education_group/views/publication_contact/__init__.py
- education_group/views/publication_contact/move.py
> OSIS-4029 : Move contacts

- education_group/locale/en/LC_MESSAGES/django.po
- education_group/locale/fr_BE/LC_MESSAGES/django.po
- education_group/templates/education_group_app/publication_contact/move_inner.html
> OSIS-4029 : Fix translations

- base/fixtures/message_template.json
> OSIS-5823 : Modification dans un message template

- education_group/templates/education_group_app/blocks/access_requirements_table_row.html
> OSIS-5826 make diploma_text safe on admission conditions tab

- education_group/templates/education_group_app/blocks/access_requirements_table_row.html
> OSIS-5826 break lines with p in tab conditions for diplomas section

- program_management/ddd/domain/service/get_node_publish_url.py
- program_management/tests/ddd/domain/service/test_get_node_publish_url.py
> OSIS-5818 Revert change for endpoint computation publish url

- base/tests/views/test_common.py
- education_group/views/group/update.py
- education_group/views/mini_training/update.py
- education_group/views/training/update.py
- program_management/views/content/update.py
- program_management/views/tree_version/update_mini_training.py
- program_management/views/tree_version/update_training.py
Pull request automatique de feature/OSIS-5720 vers DEV
> [feature/OSIS-5720 => DEV] Suppression du message d_avertissement concernant les utilisations côté OF

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/learning_unit/blocks/modal/modal_xls_with_parameters.html
- program_management/business/excel_ue_in_of.py
- program_management/locale/en/LC_MESSAGES/django.po
- program_management/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de feature/OSIS-5795 vers DEV
> [feature/OSIS-5795 => DEV] Excels des UE > Changer le terme regroupement

- program_management/ddd/domain/program_tree.py
Pull request automatique de hotfix/OSIS-5816 vers QA
> [hotfix/OSIS-5816 => QA] Cours en triple dans liste prérequis catalogue: ws + excel des prérequis

- base/tests/views/test_learning_unit_pedagogy.py
- base/views/learning_units/pedagogy/read.py
Pull request automatique de hotfix/OSIS-5817 vers QA
> [hotfix/OSIS-5817 => QA] Statut fiches descriptives : pages vides avec navigation flèches

- assessments/forms/scores_responsible.py
- assessments/templates/admin/pgm_manager.html
- assessments/views/pgm_manager_administration.py
- base/models/education_group_year.py
- base/templates/offers.html
- base/views/offer.py
> Osis 5335 some fixes

- education_group/views/mini_training/general_information_read.py
> OSIS-5836 : fix perms to edit minitraining pedagogyinformation

- base/fixtures/message_template.json
- base/tests/utils/test_send_mail.py
- base/utils/send_mail.py
> hotfix/OSIS-5823-to-qa : Depuis branche qa, réinjection des modifs

- program_management/ddd/service/write/publish_program_trees_using_node_service.py
- program_management/tests/ddd/domain/service/test_get_node_publish_url.py
> Release 3.9.1

- assessments/business/score_encoding_list.py
- assessments/views/score_encoding.py
- base/tests/utils/test_send_mail.py
- base/utils/send_mail.py
> OSIS-5839 filter 'complete encoding' by education group year (and not by course)

- learning_unit/auth/predicates.py
> OSIS-5821 : fix queryset

- attribution/api/views/attribution.py
- attribution/schema.yml
* OSIS-5834 add classes to attributions according to query param
* OSIS-5834 default charge to None
Référence Jira : OSIS-5834
> [To QA] OSIS-5834 add classes to attribution api endpoint with filter

- attribution/api/views/attribution.py
- attribution/schema.yml
* OSIS-5834 add classes to attributions according to query param
* OSIS-5834 default charge to None
Référence Jira : OSIS-5834
> [To Dev] OSIS-5834 add classes to attribution api endpoint with filter 

- education_group/forms/fields.py
- education_group/forms/training.py
- program_management/forms/transition.py
- program_management/forms/version.py
- program_management/templates/search.html
> OSIS-5325-fix fixing issue from test

- attribution/api/views/attribution.py
- attribution/schema.yml
> Release 3.9.2

- program_management/ddd/domain/link.py
> Fix breaking import

- base/business/education_groups/access_requirements.py
- base/business/education_groups/achievement.py
- base/business/education_groups/publication_contact.py
- cms/contrib/utils.py
- education_group/cms/__init__.py
- education_group/cms/postponement.py
- program_management/ddd/service/write/postpone_program_trees_until_n_plus_6_service.py
- program_management/tasks/postpone_programs_until_n_plus_6.py
- program_management/tests/ddd/service/write/test_postpone_program_trees_until_n_plus_6_service.py
> Osis 5471 postpone cms

- base/static/js/ckeditor/custom_ckeditor.js
> OSIS-5856 remove break lines after br

- program_management/ddd/domain/program_tree.py
>  OSIS-5864 : sorted set

- base/static/js/ckeditor/custom_ckeditor.js
Pull request automatique de hotfix/OSIS-5865 vers QA
> [hotfix/OSIS-5865 => QA] [Echec Qa] - OF -> Conditions : affichage incorrect des caractères spéciaux

- base/static/js/ckeditor/custom_ckeditor.js
> OSIS-5856 no break lines after p

- .gitmodules
> Add notification app into osis project

- base/templates/learning_unit/components.html
> OSIS-5869 : Gérer un None à l'affichage sous l'onglet composants

- ddd/logic/learning_unit/commands.py
- ddd/logic/learning_unit/use_case/read/get_learning_unit_service.py
- infrastructure/messages_bus.py
> OSIS-5879 : Create service to get learning_unit

- education_group/ddd/repository/training.py
> OSIS-5885 delete 11ba when delete 1ba

- infrastructure/tests/learning_unit/repository/test_effective_class.py
> OSIS-5846 test get all identities

- ddd/logic/learning_unit/builder/learning_unit_builder.py
- ddd/logic/learning_unit/test/factory/ucl_entity.py
- ddd/logic/learning_unit/test/use_case/write/test_create_learning_unit_service.py
- ddd/logic/learning_unit/use_case/write/create_learning_unit_service.py
- infrastructure/learning_unit/repository/in_memory/ucl_entity.py
- infrastructure/learning_unit/repository/learning_unit.py
- infrastructure/tests/learning_unit/repository/test_learning_unit.py
> OSIS-5846 add unit tests

- program_management/ddd/domain/program_tree.py
- program_management/ddd/domain/program_tree_version.py
- program_management/ddd/domain/service/get_next_year_node.py
- program_management/ddd/repositories/node.py
- program_management/ddd/service/write/fill_program_tree_content_from_last_year_service.py
- program_management/ddd/service/write/fill_program_tree_version_content_from_program_tree_version_service.py
- program_management/tests/ddd/factories/repository/fake.py
> OSIS-5872 fix fill when learning unit is in transformation

- education_group/ddd/repository/mini_training.py
- program_management/tasks/postpone_programs_until_n_plus_6.py
> Osis 5471 small fixes

- program_management/ddd/service/write/fill_program_tree_version_content_from_program_tree_version_service.py
> OSIS-5873 fix load transitions when fil non official standard

- program_management/tasks/postpone_programs_until_n_plus_6.py
> OSIS-5471 fix non defined variable

- program_management/ddd/service/write/fill_program_tree_version_content_from_program_tree_version_service.py
Pull request automatique de hotfix/OSIS-5873 vers MASTER
> Release 3.10.1

- backoffice/urls.py
> Add API urls from osis_notification app

- education_group/migrations/0023_copy_11ba_in_new_model.py
> OSIS-5894 fix migration file

- learning_unit/forms/classes/create.py
- learning_unit/templates/class/creation.html
- learning_unit/templates/class/simplified_class_volumes_management_form.html
> OSIS-5846-additional-entity fixed display of additional entities

- attribution/views/attribution.py
> OSIS-4279 : Traitement d'un None

- learning_unit/auth/roles/central_manager.py
> OSIS-4270 only enable faculty_managers_for_ue to create classes

- ddd/logic/learning_unit/test/use_case/read/test_check_can_create_class_service.py
> OSIS-5846 remove mocks in TestCheckCanCreateEffectiveClass

- education_group/cms/postpone_commons.py
- education_group/ddd/repository/training.py
- program_management/tasks/postpone_programs_until_n_plus_6.py
> Osis 5471 fixes

- ddd/logic/learning_unit/test/use_case/read/test_get_learning_unit_service.py
> OSIS-4270 : Test get_learning_unit_service

- education_group/auth/roles/faculty_manager.py
> OSIS-5915 enable faculty manager to create transition version in extended calendar

- assessments/tests/views/test_score_sheet.py
- base/tests/factories/person.py
- base/tests/models/test_education_group_year.py
- base/tests/views/test_learning_unit_pedagogy.py
- base/views/learning_units/pedagogy/read.py
- program_management/tests/ddd/repositories/test_load_tree.py
> fix unstable tests

- education_group/auth/roles/faculty_manager.py
Pull request automatique de hotfix/OSIS-5915 vers MASTER
> Release 3.10.2

- ddd/logic/learning_unit/domain/validator/exceptions.py
- infrastructure/learning_unit/repository/learning_unit.py
- learning_unit/forms/classes/create.py
> OSIS-4270 multiple fixes

- base/business/learning_unit.py
- base/models/learning_unit_year.py
- base/templates/learning_unit/components.html
> OSIS-4279 : Issues

- base/forms/learning_unit/learning_unit_create.py
- base/forms/learning_unit/learning_unit_create_2.py
- base/forms/learning_unit/learning_unit_partim.py
> OSIS-5912 save add an end_year when cannot

- base/forms/learning_unit/learning_unit_create.py
- base/forms/learning_unit/learning_unit_create_2.py
- base/forms/learning_unit/learning_unit_partim.py
Pull request automatique de hotfix/OSIS-5912 vers QA
> [hotfix/OSIS-5912 => QA] (254992) Problème pour modifier une UE une 2è fois (+ partims)

- base/templates/learning_unit/layout_detail.html
- ddd/logic/learning_unit/builder/effective_class_builder.py
- infrastructure/messages_bus.py
- infrastructure/tests/learning_unit/repository/test_effective_class.py
- learning_unit/forms/classes/update.py
- learning_unit/views/learning_unit_class/update.py
> OSIS-4289-mise-en-commun

- base/auth/roles/program_manager.py
- base/fixtures/groups.json
- base/templates/learning_unit/components.html
- learning_unit/auth/roles/central_manager.py
- learning_unit/auth/roles/faculty_manager.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
- learning_unit/templates/class/identification_tab.html
> OSIS-5882 use can_access_class perm to authorize/prevent class identification access view

- backoffice/settings/base.py
- backoffice/settings/local.py
- base/models/learning_unit_year.py
- ddd/locale/en/LC_MESSAGES/django.po
- ddd/locale/fr_BE/LC_MESSAGES/django.po
> add ddd to installed apps

- ddd/logic/learning_unit/domain/model/effective_class.py
- ddd/logic/learning_unit/tests/factory/effective_class.py
- ddd/logic/learning_unit/tests/factory/learning_unit.py
- ddd/logic/learning_unit/tests/use_case/write/test_create_class_service.py
- ddd/logic/learning_unit/tests/use_case/write/test_update_class_service.py
- infrastructure/learning_unit/repository/in_memory/effective_class.py
- learning_unit/forms/classes/update.py
- program_management/tests/ddd/factories/node.py
> OSIS-5896 do not autorize update of 'class code' of an Effective class

- base/templates/learning_unit/components.html
> OSIS-5882 fix a_tag_has_perm

- ddd/logic/formation_catalogue/builder/training_builder.py
- script.py
> OSIS-5866 script to test

- ddd/logic/learning_unit/domain/model/effective_class.py
> OSIS-4289 fixed bad assignation to derogation quadrimester of effective class

- ddd/logic/formation_catalogue/builder/training_builder.py
> OSIS-5939 fixed typo

- assessments/locale/en/LC_MESSAGES/django.po
> OSIS-5938 Date format for english version of XLS

- ddd/logic/formation_catalogue/builder/training_builder.py
> [hotfix/OSIS-5939 => QA] (255822) Erreur inattendue quand on ouvre la page de certaines formations

- assessments/locale/en/LC_MESSAGES/django.po
> [hotfix/OSIS-5938 => QA] Date format for english version of XLS

- ddd/logic/formation_catalogue/builder/training_builder.py
Pull request automatique de hotfix/OSIS-5939 vers MASTER
> Release 3.11.1

- attribution/tests/views/charge_repartition/common.py
- attribution/tests/views/charge_repartition/test_create.py
- attribution/tests/views/test_attribution.py
- attribution/views/charge_repartition/create.py
- ddd/logic/attribution/tests/factory/tutor.py
- ddd/logic/learning_unit/tests/factory/effective_class.py
- ddd/logic/learning_unit/tests/factory/learning_unit.py
- infrastructure/tests/attribution/repository/test_tutor.py
> OSIS-5942 : Factories

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/models/learning_unit_year.py
- base/tests/models/test_learning_unit_year.py
- ddd/locale/en/LC_MESSAGES/django.po
- ddd/locale/fr_BE/LC_MESSAGES/django.po
- ddd/logic/learning_unit/commands.py
- ddd/logic/learning_unit/domain/model/_volumes_repartition.py
- ddd/logic/learning_unit/domain/model/effective_class.py
- ddd/logic/learning_unit/domain/service/get_effective_class_warnings.py
- ddd/logic/learning_unit/tests/factory/effective_class.py
- ddd/logic/learning_unit/tests/factory/learning_unit.py
- ddd/logic/learning_unit/tests/use_case/read/test_get_effective_class_warnings_service.py
- ddd/logic/learning_unit/tests/use_case/read/test_get_learning_unit_service.py
- ddd/logic/learning_unit/use_case/read/get_effective_class_warnings_service.py
- infrastructure/learning_unit/repository/in_memory/learning_unit.py
- infrastructure/messages_bus.py
- learning_unit/models/learning_class_year.py
- learning_unit/templates/class/identification_tab.html
- learning_unit/views/learning_unit_class/create.py
- learning_unit/views/learning_unit_class/identification_read.py
> Osis 4274 tuning v2

- program_management/tests/ddd/factories/node.py
> fix failling test

- learning_unit/templates/class/identification_tab.html
- learning_unit/templates/class_detail_layout.html
> OSIS-4274 : fix renaming of property

- base/templates/learning_unit/components.html
> OSIS-4274 : fix template

- ddd/logic/effective_class_repartition/use_case/read/has_class_repartition_service.py
- ddd/logic/learning_unit/builder/effective_class_identity_builder.py
- ddd/logic/learning_unit/commands.py
- ddd/logic/learning_unit/domain/service/can_effective_class_be_deleted.py
- ddd/logic/learning_unit/domain/service/i_tutor_distributed_to_class.py
- ddd/logic/learning_unit/tests/use_case/write/test_delete_effective_class_service.py
- ddd/logic/learning_unit/use_case/read/check_can_delete_class_service.py
- ddd/logic/learning_unit/use_case/write/delete_effective_class_service.py
- infrastructure/learning_unit/domain/service/tutor_distributed_to_class.py
- infrastructure/messages_bus.py
> OSIS-5947-anticorruption-layer-distributed_to_class

- ddd/logic/effective_class_repartition/use_case/read/has_enrollments_to_class_service.py
- ddd/logic/learning_unit/commands.py
- ddd/logic/learning_unit/domain/service/can_effective_class_be_deleted.py
- ddd/logic/learning_unit/domain/service/can_save_effective_class.py
- ddd/logic/learning_unit/domain/service/i_student_enrollments_to_effective_class.py
- ddd/logic/learning_unit/tests/use_case/write/test_create_class_service.py
- ddd/logic/learning_unit/tests/use_case/write/test_delete_effective_class_service.py
- infrastructure/learning_unit/domain/service/student_enrollments_to_effective_class.py
- infrastructure/messages_bus.py
> OSIS-5947-corruption-layer-has_enrollments :

- ddd/logic/learning_unit/domain/model/_volumes_repartition.py
- learning_unit/forms/classes/update.py
- learning_unit/views/learning_unit_class/create.py
> OSIS-4274 : Fix defautl 0.0 to accept empty value

- ddd/logic/learning_unit/use_case/read/check_can_delete_class_service.py
- infrastructure/messages_bus.py
> OSIS-4295 : Adapt parameters of DomainService

- learning_unit/views/learning_unit_class/delete.py
> feature/OSIS-4295 : correction complete_code en complete_acronym

- learning_unit/forms/classes/tutor_repartition.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
- learning_unit/templates/class/remove_charge_repartition.html
- learning_unit/templates/class/tutors_tab.html
- learning_unit/urls.py
- learning_unit/views/learning_unit_class/learning_unit_tutors.py
- learning_unit/views/learning_unit_class/tutor_repartition.py
- learning_unit/views/learning_unit_class/tutors.py
> OSIS-5905 : Enlever répartition : ajouter bouton (icone poubelle)

- education_group/auth/roles/faculty_manager.py
> OSIS-4461-issue1 block creation of transition version in past

- education_group/tests/api/serializers/test_group_element_year.py
- education_group/tests/ddd/repository/test_training.py
> fix tests randomly failling

- ddd/logic/learning_unit/domain/service/can_effective_class_be_deleted.py
- ddd/logic/learning_unit/domain/validator/exceptions.py
> OSIS-4295-formatage-message : Correction d'un message mal formaté

- ddd/logic/attribution/builder/tutor_builder.py
- learning_unit/views/learning_unit_class/learning_unit_tutors.py
> OSIS-4287-fix-distribute

- education_group/templates/education_group_app/training/access_requirements_read.html
> OSIS-5663 remove specific admission access requirement for bachelor

- ddd/logic/attribution/domain/model/tutor.py
- ddd/logic/attribution/tests/factory/tutor.py
- ddd/logic/attribution/tests/write/test_distribute_class_to_tutor_service.py
- ddd/logic/attribution/tests/write/test_unassign_tutor_class_service.py
- ddd/logic/attribution/use_case/write/distribute_class_to_tutor_service.py
- ddd/logic/effective_class_repartition/domain/validator/_should_be_numeric_validator.py
- ddd/logic/learning_unit/domain/model/_volumes_repartition.py
- ddd/logic/learning_unit/tests/factory/effective_class.py
- infrastructure/attribution/repository/in_memory/tutor.py
- infrastructure/messages_bus.py
- learning_unit/forms/classes/tutor_repartition.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
- learning_unit/views/learning_unit_class/tutor_repartition.py
> OSIS-5906 : Unassign tutor class service

- learning_unit/templates/class/breadcrumb.html
- learning_unit/templates/class/lu_tutors.html
- learning_unit/templates/class/tutors_tab.html
- learning_unit/views/learning_unit_class/tutors.py
> OSIS-4287 : some display fixes

- ddd/logic/attribution/domain/service/class_distribution_with_attribution.py
- ddd/logic/attribution/dtos.py
- learning_unit/forms/classes/tutor_repartition.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
- learning_unit/templates/class/tutors_tab.html
- learning_unit/urls.py
- learning_unit/views/learning_unit_class/common.py
- learning_unit/views/learning_unit_class/identification_read.py
- learning_unit/views/learning_unit_class/learning_unit_tutors.py
- learning_unit/views/learning_unit_class/tutor_repartition.py
- learning_unit/views/learning_unit_class/tutors.py
- learning_unit/views/learning_unit_class/update.py
> OSIS-4287 : Update View & Form

- learning_unit/views/learning_unit_class/identification_read.py
> Update view form

- learning_unit/postponement/postpone_learning_units.py
> OSIS-4125 exclude proposal creation for postpone

- base/forms/learning_unit/learning_unit_postponement.py
- base/tests/views/test_learning_unit_pedagogy.py
Pull request automatique de hotfix/OSIS-5931 vers QA
> [hotfix/OSIS-5931 => QA] UE > Traductions manquantes pour les types de stage dans les messages d_avertissement

- education_group/templates/education_group_app/training/access_requirements_read.html
Pull request automatique de feature/OSIS-5663 vers DEV
> [feature/OSIS-5663 => DEV] Formation > Conditions > Conditions spécifiques d_admission (free) à retirer pour les bacheliers

- base/forms/learning_unit/external_learning_unit.py
- base/forms/learning_unit/learning_unit_create.py
- base/static/js/learning_unit_creation.js
- base/templates/learning_unit/blocks/learning_unit_identification.html
- base/templates/learning_unit/simple/creation.html
- base/tests/views/test_learning_unit_edition.py
> OSIS-5964 add stage-dimona in CrU forms

- education_group/auth/roles/faculty_manager.py
- learning_unit/auth/roles/faculty_manager.py
- learning_unit/views/learning_unit_class/learning_unit_tutors.py
- learning_unit/views/learning_unit_class/tutor_repartition.py
> OSIS-4287 : Permissions

- learning_unit/postponement/postpone_learning_units.py
> OSIS-4125 fix eclude mobility and proposal creation

- learning_unit/postponement/postpone_learning_units.py
- learning_unit/tasks/postpone_learning_units_until_n_plus_6.py
> OSIS-4125 postpone partims that are not aligned with full

- learning_unit/views/learning_unit_class/learning_unit_tutors.py
> OSIS-4287 : Fix missing title

- base/business/learning_unit_xls.py
- base/views/learning_units/search/common.py
> OSIS-5967 : try to prefetch

- base/fixtures/validation_rules.csv
- base/forms/common.py
- education_group/forms/group.py
> OSIS-5297 first digit of code cannot be 0

- base/business/learning_unit_proposal.py
- base/static/js/learning_unit_creation.js
- base/tests/forms/test_learning_unit_proposal.py
- base/tests/views/test_learning_unit_proposal.py
- rules_management/fixtures/field_reference.json
> OSIS-5965 adapt field_reference.json for central and faculty + fix issue with proposal

- base/business/learning_units/comparison.py
- base/views/learning_unit.py
> OSIS-5972 fix comparison view with new stage_dimona field

- attribution/models/__init__.py
- attribution/tests/factories/attribution_class.py
- base/business/learning_units/simple/deletion.py
- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/tests/business/test_learning_unit_deletion.py
- base/tests/views/test_learning_unit_deletion.py
> OSIS-5980 : Check if attribution on class

- learning_unit/schema.yml
> OSIS-5979 : Update schema

- base/business/learning_units/edition.py
- base/forms/learning_unit/learning_unit_postponement.py
- base/static/js/learning_unit_creation.js
> Osis 5927 issues

- .gitmodules
- backoffice/urls.py
> Add osis_signature

- learning_unit/schema.yml
>  OSIS-5979 : Update schema

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/base/person_list.html
- base/tests/views/test_user_list.py
- base/urls.py
- base/views/user_list.py
- osis_role/contrib/helper.py
> Osis 5672 : Ajout du scope dans l'écran de la liste des utilisateurs + xls

- program_management/ddd/domain/service/generate_node_code.py
- program_management/tests/ddd/domain/service/test_generate_node_code.py
> OSIS-5297 ensure good code generated in case of transition

- base/migrations/0591_remove_organization_code.py
> fix-dev-migrations

- assessments/locale/en/LC_MESSAGES/django.po
- assessments/locale/fr_BE/LC_MESSAGES/django.po
- assessments/tests/views/test_score_encoding.py
- assessments/views/score_encoding.py
- base/business/academic_calendar.py
- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-5801 fix warning message score encoding

- .env.example
- backoffice/settings/base.py
- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/server_error.html
- base/views/common.py
> OSIS-5988 change error messages

- learning_unit/api/views/learning_unit.py
- learning_unit/schema.yml
> OSIS-5933 add filter stage_dimona + schema

- assessments/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-5801-qa fix message

- learning_unit/api/views/learning_unit.py
- learning_unit/schema.yml
Pull request automatique de feature/OSIS-5944 vers DEV
> [feature/OSIS-5944 => DEV] Création le WS qui envoie la liste des UEs qui concerne stage dimona

- base/templatetags/education_group_pdf.py
> OSIS-5991 : Fix pdf picto

- attribution/business/attribution_class.py
- base/business/learning_unit_xls.py
> OSIS-5970 : Remove some parent values in xls

- base/business/learning_unit_xls.py
- base/business/list/ue_utilizations.py
- base/tests/business/list/test_ue_utilizations.py
- base/tests/business/test_learning_unit_xls.py
- base/tests/factories/learning_unit_year.py
Pull request automatique de feature/OSIS-5929 vers DEV
> [feature/OSIS-5929 => DEV] En tant que gestionnaire central ou facultaire, je dois pouvoir visualiser Stage-Dimona dans les excels

- ddd/logic/learning_unit/builder/effective_class_builder.py
> OSIS-4287 : Fix issue

- base/business/learning_unit_xls.py
- base/tests/business/test_learning_unit_xls.py
> OSIS-5970 : Dont display 0 if no volume

- learning_unit/auth/predicates.py
Pull request automatique de hotfix/OSIS-5989 vers QA
> [hotfix/OSIS-5989 => QA] Partim impossible à supprimer

- assessments/locale/fr_BE/LC_MESSAGES/django.po
- base/templatetags/education_group_pdf.py
Pull request automatique de hotfix/OSIS-5991 vers QA
> [hotfix/OSIS-5991 => QA] Erreur pictogramme UE PDF

- base/migrations/0591_remove_organization_code.py
- base/models/organization.py
> Revert organization code field deleted

- ddd/logic/effective_class_repartition/builder/tutor_builder.py
- ddd/logic/effective_class_repartition/commands.py
- ddd/logic/effective_class_repartition/domain/model/tutor.py
- ddd/logic/effective_class_repartition/tests/write/test_edit_class_volume_repartition_to_tutor_service.py
- ddd/logic/effective_class_repartition/use_case/write/edit_class_volume_repartition_to_tutor_service.py
- ddd/logic/learning_unit/builder/effective_class_identity_builder.py
- infrastructure/messages_bus.py
- learning_unit/forms/classes/tutor_repartition.py
- learning_unit/templates/class/lu_tutors.html
- learning_unit/views/learning_unit_class/learning_unit_tutors.py
- learning_unit/views/learning_unit_class/tutor_repartition.py
> OSIS-4287 : Fix editon of tutor repartition

- backoffice/settings/base.py
- ddd/logic/learning_unit/tests/use_case/read/test_check_can_create_class_service.py
- ddd/logic/learning_unit/tests/use_case/read/test_get_effective_class_warnings_service.py
- ddd/logic/learning_unit/tests/use_case/read/test_get_learning_unit_service.py
- ddd/logic/learning_unit/tests/use_case/write/test_create_learning_unit_service.py
- ddd/logic/learning_unit/tests/use_case/write/test_delete_effective_class_service.py
- infrastructure/tests/learning_unit/repository/test_effective_class.py
> execute ddd + infrastructe tests + fix tests

- base/business/learning_units/simple/deletion.py
- base/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-4297 modify messages displayed

- education_group/forms/mini_training.py
- education_group/forms/training.py
- program_management/forms/transition.py
- program_management/forms/version.py
> Fixed Issue 2

- base/forms/learning_unit/edition.py
- base/templates/learning_unit/layout_detail.html
- base/tests/forms/test_learning_unit_edition.py
- base/views/learning_units/detail.py
- education_group/templates/education_group_app/training/layout_read.html
- education_group/views/configuration/common_list.py
- program_management/ddd/domain/service/node_identities_search.py
> Fixed issues test failed

- base/business/learning_unit_xls.py
- base/templates/base/person_list.html
- base/views/user_list.py
> OSIS-5672 display scope for central manager of of

- base/management/commands/clearcache.py
> add clear cache command

- learning_unit/api/serializers/learning_unit.py
- learning_unit/schema.yml
- learning_unit/tests/api/serializers/test_learning_unit.py
> Prepare OSIS-5977: Create Field + Update Schema

- ddd/logic/learning_unit/tests/use_case/write/test_create_class_service.py
> fix random test create class service failling

- learning_unit/api/serializers/learning_unit.py
- learning_unit/schema.yml
- learning_unit/tests/api/serializers/test_learning_unit.py
> [TEST] Pre osis 5977 test

- .gitmodules
- backoffice/urls.py
> Add osis_async app url

- attribution/schema.yml
- education_group/schema.yml
- learning_unit/schema.yml
- program_management/schema.yml
- reference/schema.yml
- webservices/api/views/auth_token.py
- webservices/schema.yml
- webservices/tests/api/views/test_auth_token.py
> Add X-USER-XXX custom header for integration with ESB

- base/fixtures/groups.json
> remove structure from groups fixture

- base/fixtures/groups.json
> remove internship group members from groups fixture

- base/fixtures/groups.json
> fix groups.json with deleted models

- reference/schema.yml
> OSIS-6011 : Schéma language

- attribution/views/attribution.py
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
- learning_unit/templates/class/lu_tutors.html
> OSIS-4287 : Fix issues

- reference/api/serializers/language.py
- reference/api/views/language.py
- reference/schema.yml
- reference/tests/api/serializers/test_language.py
- reference/tests/api/views/test_language.py
> OSIS-6012 : API language

- assessments/forms/score_encoding.py
- assessments/templates/assessments/tutor/learning_unit_score_encoding.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding_form.html
- assessments/tests/views/tutor/test_learning_unit_score_encoding_form.py
- assessments/urls.py
- assessments/views/serializers/score_sheet.py
- assessments/views/tutor/learning_unit_score_encoding.py
- assessments/views/tutor/learning_unit_score_encoding_form.py
- ddd/logic/encodage_des_notes/soumission/domain/service/feuille_de_notes_enseignant.py
- ddd/logic/encodage_des_notes/soumission/test/use_case/read/test_get_feuille_de_notes_service.py
- infrastructure/encodage_de_notes/soumission/domain/service/in_memory/inscription_examen.py
- infrastructure/encodage_de_notes/soumission/domain/service/in_memory/signaletique_etudiant.py
> Create score encoding form view

- ddd/logic/encodage_des_notes/encodage/domain/model/note_etudiant.py
> add 'nom_cohorte' to NoteEtudiant

- assessments/forms/score_file.py
- assessments/locale/fr_BE/LC_MESSAGES/django.po
- assessments/templates/assessments/common/xls_import_modal_inner.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding.html
- assessments/tests/views/serializers/test_score_sheet_xls_import.py
- assessments/tests/views/tutor/test_score_sheet_xls_import.py
- assessments/urls.py
- assessments/views/serializers/score_sheet_xls_import.py
- assessments/views/tutor/learning_unit_score_encoding.py
- assessments/views/tutor/score_sheet_xls_import.py
- base/static/js/modal_form_submit.js
> Upload XLS file view + serializer

- manage_submodules.py
> use argument branch when cloning submodule

- base/templates/learning_unit/components.html
> OSIS-5994 : Fix component tab

- reference/admin.py
> OSIS-6006 : Add to admin

- base/business/learning_unit_proposal.py
- base/business/learning_units/comparison.py
- base/business/learning_units/edition.py
- base/forms/learning_unit/external_learning_unit.py
- base/forms/learning_unit/learning_unit_create.py
- base/forms/learning_unit/learning_unit_postponement.py
- base/templates/learning_unit/blocks/learning_unit_identification.html
- base/tests/forms/test_learning_unit_proposal.py
- base/tests/views/test_learning_unit_edition.py
- base/tests/views/test_learning_unit_proposal.py
- base/views/learning_unit.py
> OSIS-6019 : Edition forms + proposal + Postponement

- ddd/logic/encodage_des_notes/soumission/domain/service/donnees_administratives.py
- ddd/logic/encodage_des_notes/soumission/domain/service/i_contact_feuille_de_notes.py
- ddd/logic/encodage_des_notes/soumission/domain/service/i_deliberation.py
- ddd/logic/encodage_des_notes/soumission/domain/service/i_inscription_examen.py
- ddd/logic/encodage_des_notes/soumission/domain/service/i_signaletique_personne.py
- ddd/logic/encodage_des_notes/soumission/dtos.py
- ddd/logic/encodage_des_notes/soumission/repository/i_responsable_de_notes.py
- ddd/logic/encodage_des_notes/soumission/test/use_case/read/test_search_donnees_administratives_feuille_de_notes_service.py
- ddd/logic/encodage_des_notes/soumission/use_case/read/search_donnees_administratives_feuille_de_notes_service.py
- infrastructure/encodage_de_notes/soumission/domain/service/adresse_feuille_de_notes.py
- infrastructure/encodage_de_notes/soumission/domain/service/contact_feuille_de_notes.py
- infrastructure/encodage_de_notes/soumission/domain/service/deliberation.py
- infrastructure/encodage_de_notes/soumission/domain/service/in_memory/adresse_feuille_de_notes.py
- infrastructure/encodage_de_notes/soumission/domain/service/in_memory/contact_feuille_de_notes.py
- infrastructure/encodage_de_notes/soumission/domain/service/in_memory/deliberation.py
- infrastructure/encodage_de_notes/soumission/domain/service/in_memory/inscription_examen.py
- infrastructure/encodage_de_notes/soumission/domain/service/in_memory/signaletique_personne.py
- infrastructure/encodage_de_notes/soumission/domain/service/inscription_examen.py
- infrastructure/encodage_de_notes/soumission/domain/service/signaletique_personne.py
- infrastructure/encodage_de_notes/soumission/repository/feuille_de_notes.py
- infrastructure/encodage_de_notes/soumission/repository/in_memory/responsable_de_notes.py
- infrastructure/encodage_de_notes/soumission/repository/responsable_de_notes.py
- infrastructure/messages_bus.py
- infrastructure/tests/encodage_des_notes/domain/service/test_adresse_feuille_de_notes.py
- infrastructure/tests/encodage_des_notes/domain/service/test_deliberation.py
- infrastructure/tests/encodage_des_notes/domain/service/test_signaletique_personne.py
> use case with DomainService 'DonneesAdministratives.search'

- infrastructure/application/serializer/application.py
- infrastructure/application/test/serializer/test_application.py
> Online application add global_id to message send to EPC

- base/templates/learning_unit/blocks/learning_unit_identification.html
- base/templates/learning_unit/simple/creation.html
> OSIS-5974 : fix templates

- assessments/templates/assessments/program_manager/learning_unit_score_encoding.html
- assessments/templates/assessments/program_manager/learning_unit_score_encoding_form.html
- assessments/tests/views/program_manager/test_learning_unit_score_encoding.py
- assessments/tests/views/program_manager/test_learning_unit_score_encoding_form.py
- assessments/tests/views/serializers/test_score_sheet_xls.py
- assessments/urls.py
- assessments/views/common/learning_unit_score_encoding.py
- assessments/views/common/learning_unit_score_encoding_form.py
- assessments/views/program_manager/learning_unit_score_encoding.py
- assessments/views/program_manager/learning_unit_score_encoding_form.py
- assessments/views/score_encoding.py
- osis_role/contrib/helper.py
> Program manager view

- assessments/templates/assessments/program_manager/learning_unit_score_encoding.html
- assessments/tests/views/program_manager/test_score_sheet_xls_import.py
- assessments/urls.py
- assessments/views/common/score_sheet_pdf_export.py
- assessments/views/common/score_sheet_xls_export.py
- assessments/views/common/score_sheet_xls_import.py
- assessments/views/program_manager/score_sheet_pdf_export.py
- assessments/views/program_manager/score_sheet_xls_export.py
- assessments/views/program_manager/score_sheet_xls_import.py
- assessments/views/score_encoding.py
- assessments/views/serializers/score_sheet_xls.py
- assessments/views/tutor/learning_unit_score_encoding.py
- assessments/views/tutor/score_sheet_xls_export.py
- assessments/views/tutor/score_sheet_xls_import.py
> Add Program Manager view for XLS/PDF export & XLS import

- base/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-3445 : Modification d'une traduction

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/learning_unit/blocks/modal/modal_confirm_delete_achievement.html
- base/templates/learning_unit/specifications_all.html
Pull request automatique de feature/OSIS-3445 vers DEV
> [feature/OSIS-3445 => DEV] Suppression d_un AA : mettre une modale bootstrap

- base/templates/learning_unit/blocks/learning_unit_identification.html
> OSIS-6029 move language and individual_loan in form to respect the visualisation part

- base/views/user_list.py
> OSIS-6026 : Ajout du scope

- base/templates/learning_unit/blocks/form/volumes_management_form.html
- base/templates/learning_unit/blocks/modal/modal_modification_ask_to_report.html
- base/templates/learning_unit/learning_unit_layout.html
> fix bad interaction with modal postponement learning and ddt

- base/templates/blocks/navbar_top.html
Pull request automatique de feature/OSIS-6032 vers DEV
> [feature/OSIS-6032 => DEV] Ouvrir le lien FARE dans une nouvelle fenêtre

- ddd/logic/encodage_des_notes/soumission/use_case/read/get_progression_generale_encodage_service.py
- ddd/logic/learning_unit/commands.py
- ddd/logic/learning_unit/dtos.py
- ddd/logic/learning_unit/repository/i_effective_class.py
- ddd/logic/learning_unit/tests/use_case/read/test_search_detail_classes_effectives.py
- ddd/logic/learning_unit/use_case/read/search_detail_classes_effectives.py
- infrastructure/encodage_de_notes/shared_kernel/service/unite_enseignement.py
- infrastructure/learning_unit/repository/effective_class.py
- infrastructure/learning_unit/repository/in_memory/effective_class.py
- infrastructure/messages_bus.py
- infrastructure/tests/encodage_des_notes/domain/service/test_unite_enseignement.py
- infrastructure/tests/learning_unit/repository/test_effective_class.py
> OSIS-6038 Add 'intitule complet classe' in search learning units (context 'soumission')

- assessments/views/program_manager/score_encoding_progress_overview.py
- base/models/offer_enrollment.py
- ddd/logic/encodage_des_notes/encodage/repository/note_etudiant.py
- infrastructure/encodage_de_notes/encodage/repository/note_etudiant.py
> increase performances of 'progression generale encodage'

- base/templates/learning_unit/blocks/form/search_form_learning_unit.html
> OSIS-6067 Make acronym field bigger and subtype field smaller

- base/templates/learning_unit/blocks/form/search_form_learning_unit.html
Pull request automatique de hotfix/OSIS-6067 vers QA
> [hotfix/OSIS-6067 => QA] UE > Recherche > agrandir le filtre sur le code et diminuer le filtre sur le sous-type

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/learning_unit/formations.html
Pull request automatique de feature/OSIS-6062 vers DEV
> [feature/OSIS-6062 => DEV] Gestion des classes > Utilisations des UE > ajouter un warning au niveau du pavé Utilisations

- learning_unit/templates/class/blocks/dropdown/identification_actions_bar.html
- learning_unit/templates/class/tutors_tab.html
Pull request automatique de feature/OSIS-6061 vers DEV
> [feature/OSIS-6061 => DEV] Gestion des classes > bloquer toute action sur les classes si le flag learning_class_create est désactivé

- base/migrations/0593_auto_20210820_1140.py
> OSIS-6002 : Fix migration script : sex = ''

- assessments/api/url_v1.py
- assessments/api/views/score_sheet_xls_export.py
- assessments/api/views/score_sheets_pdf_export.py
- assessments/schema.yml
- assessments/tests/api/views/test_score_sheet_xls_export.py
- assessments/tests/api/views/test_score_sheets_pdf_export.py
- webservices/urls.py
> Add PDF/XLS endpoint for generate file

- assessments/export/score_sheet_xls.py
- assessments/templates/assessments/program_manager/learning_unit_score_encoding.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding.html
- assessments/tests/views/serializers/test_score_sheet_xls.py
- assessments/views/common/score_sheet_xls_export.py
- assessments/views/serializers/score_sheet_xls.py
- ddd/logic/encodage_des_notes/shared_kernel/dtos.py
- infrastructure/encodage_de_notes/shared_kernel/service/in_memory/signaletique_etudiant.py
- infrastructure/encodage_de_notes/shared_kernel/service/signaletique_etudiant.py
- infrastructure/tests/encodage_des_notes/domain/service/test_signaletique_etudiant.py
> Add subtype on PEPS student data + format XLS value

- infrastructure/encodage_de_notes/soumission/repository/responsable_de_notes.py
> Fix get_for_unite_enseignement method on infrastructre respository

- base/views/common.py
> Fix redirect url for score encoding

- ddd/logic/encodage_des_notes/soumission/domain/model/_note.py
> Fix zero as NoteChiffree str function

- assessments/migrations/0006_populate_entity_cohort_of_score_sheet_address.py
> migration fill score sheet address from entity

- base/forms/learning_unit/comparison.py
> OSIS-6103 fix academic_year string in comparison modal

- assessments/templates/assessments/address/first_year_bachelor_score_sheet.html
- assessments/templates/assessments/address/score_sheet.html
- base/templates/blocks/navbar_top.html
- base/templates/studies.html
> point links to new score sheet address views

- attribution/api/serializers/attribution.py
- attribution/api/views/attribution.py
- attribution/schema.yml
- attribution/tests/api/views/test_attribution.py
> OSIS-6073 : add is_partim to serializer and schema..

- program_management/business/excel_ue_in_of.py
> OSIS-6031 fix header of excel in wrong language

- assessments/api/views/score_sheet_xls_export.py
- assessments/tests/views/serializers/test_score_sheet_xls.py
- assessments/views/common/score_sheet_xls_export.py
- assessments/views/serializers/score_sheet_xls.py
- assessments/views/tutor/score_sheet_xls_export.py
> Hide note value on XLS export

- program_management/business/excel_ue_in_of.py
Pull request automatique de hotfix/OSIS-6031 vers QA
> [hotfix/OSIS-6031 => QA] Liste des UE de la formation : langue des titres des colonnes

- attribution/api/views/attribution.py
> OSIS-3830 : Fix issue if no attributionClass

- education_group/tests/calendar/test_education_group_extended_daily_management.py
- education_group/tests/calendar/test_education_group_limited_daily_management.py
- education_group/tests/calendar/test_education_group_preparation_calendar.py
> OSIS-6105 fix fixed date with change academic year

- education_group/tests/calendar/test_education_group_extended_daily_management.py
- education_group/tests/calendar/test_education_group_limited_daily_management.py
- education_group/tests/calendar/test_education_group_preparation_calendar.py
Pull request automatique de hotfix/OSIS-6105 vers QA
> [WIP] [hotfix/OSIS-6105 => QA] Problème de tests unitaire lié au basculement de l_année academique

- education_group/tests/calendar/test_education_group_extended_daily_management.py
- education_group/tests/calendar/test_education_group_limited_daily_management.py
- education_group/tests/calendar/test_education_group_preparation_calendar.py
Pull request automatique de hotfix/OSIS-6105 vers DEV
> [WIP] [hotfix/OSIS-6105 => DEV] Problème de tests unitaire lié au basculement de l_année academique

- assessments/business/scores_responsible.py
- assessments/forms/scores_responsible.py
- assessments/views/scores_responsible.py
- attribution/business/score_responsible.py
- attribution/tests/business/test_score_responsible.py
- base/auth/roles/program_manager.py
Pull request automatique de hotfix/OSIS-6112 vers QA
> [hotfix/OSIS-6112 => QA] Problèmes désignation responsable de notes

- assessments/business/score_encoding_progress.py
- base/forms/learning_unit/comparison.py
- base/models/exam_enrollment.py
Pull request automatique de hotfix/OSIS-6113 vers DEV
> [WIP] [hotfix/OSIS-6113 => DEV] Encodage de notes > Recherche > la liste des enseignants est vide

- ddd/logic/learning_unit/domain/service/get_effective_class_warnings.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de technical/OSIS-6085 vers DEV
> [technical/OSIS-6085 => DEV] Gestion des classes > impossible de consulter une classe avec quadrimestre sur une UE qui n_a pas de quadrimestre

- ddd/logic/application/domain/service/vacant_course_searcher.py
- infrastructure/application/repository/vacant_course.py
> (Candidature en ligne) Fix search with allocation_entity_children

- base/templates/learning_unit/formations.html
> OSIS-4306 : Qq corrections pour l'affichage

- offer_enrollment/api/url_v1.py
- offer_enrollment/api/views/enrollment.py
- offer_enrollment/schema.yml
- offer_enrollment/tests/api/views/test_enrollment.py
> OSIS-6116 : API to get offer enrollments of specific year

- assessments/business/score_encoding_progress.py
> to QA - OSIS-6113 fix not showing list of tutors in search

- assessments/business/score_encoding_progress.py
> to DEV - OSIS-6113 fix not showing list of tutors in search

- infrastructure/application/repository/applicant.py
- infrastructure/application/services/learning_unit_service.py
- infrastructure/application/test/repository/test_applicant.py
- infrastructure/application/test/services/test_learning_unit_service.py
> OSIS-6050 Prevent showing partim attribution

- base/business/learning_unit_xls.py
- base/business/list/ue_utilizations.py
- base/tests/business/list/test_ue_utilizations.py
- base/tests/business/test_learning_unit_xls.py
> OSIS-6083 : Ajout des champs "Autre remarque" dans les xls des UE

- assessments/tests/factories/score_responsible.py
- base/models/learning_unit_enrollment.py
- base/tests/factories/learning_component_year.py
- ddd/logic/effective_class_repartition/domain/service/class_distribution_with_attribution.py
- ddd/logic/effective_class_repartition/tests/use_case/read/test_search_classes_enseignant.py
- ddd/logic/effective_class_repartition/tests/use_case/read/test_search_effective_classes_distributed_service.py
- ddd/logic/effective_class_repartition/use_case/read/search_classes_enseignant_service.py
- ddd/logic/effective_class_repartition/use_case/read/search_effective_classes_distributed_service.py
- ddd/logic/encodage_des_notes/encodage/test/factory/note_etudiant.py
- ddd/logic/encodage_des_notes/soumission/test/factory/note_etudiant.py
- ddd/logic/encodage_des_notes/soumission/test/factory/responsable_de_notes.py
- ddd/logic/learning_unit/builder/effective_class_builder.py
- ddd/logic/learning_unit/builder/effective_class_identity_builder.py
- ddd/logic/learning_unit/dtos.py
- infrastructure/encodage_de_notes/encodage/repository/note_etudiant.py
- infrastructure/encodage_de_notes/shared_kernel/service/attribution_enseignant.py
- infrastructure/encodage_de_notes/shared_kernel/service/inscription_examen.py
- infrastructure/encodage_de_notes/soumission/repository/note_etudiant.py
- infrastructure/encodage_de_notes/soumission/repository/responsable_de_notes.py
- infrastructure/learning_unit/repository/effective_class.py
- infrastructure/learning_unit/repository/in_memory/effective_class.py
- infrastructure/messages_bus.py
- infrastructure/tests/encodage_des_notes/domain/service/test_inscription_examen.py
- infrastructure/tests/encodage_des_notes/encodage/repository/test_note_etudiant.py
- infrastructure/tests/encodage_des_notes/soumission/repository/test_note_etudiant.py
- infrastructure/tests/encodage_des_notes/soumission/repository/test_responsable_de_notes.py
- infrastructure/tests/learning_unit/repository/test_effective_class.py
- learning_unit/models/learning_class_year.py
> Encodage classes code

- base/business/learning_unit_xls.py
- base/business/list/ue_utilizations.py
- base/tests/business/list/test_ue_utilizations.py
- base/tests/business/test_learning_unit_xls.py
Pull request automatique de feature/OSIS-6083 vers DEV
> [feature/OSIS-6083 => DEV] En tant que personne ayant accès au catalogue des UE, je veux voir les champs _Autre remarque_ dans les XLS des UE

- assessments/forms/score_encoding.py
- assessments/templates/assessments/program_manager/learning_unit_score_encoding_form.html
- assessments/templates/assessments/program_manager/score_search_form.html
- assessments/views/program_manager/score_search.py
- base/models/enums/exam_enrollment_justification_type.py
- ddd/logic/encodage_des_notes/shared_kernel/domain/service/progression_generale.py
- ddd/logic/encodage_des_notes/shared_kernel/dtos.py
- ddd/logic/encodage_des_notes/soumission/dtos.py
- infrastructure/encodage_de_notes/soumission/repository/in_memory/note_etudiant.py
- infrastructure/encodage_de_notes/soumission/repository/note_etudiant.py
- infrastructure/tests/encodage_des_notes/soumission/repository/test_note_etudiant.py
> fix some issues with rechercher of encodage

- assessments/templates/assessments/program_manager/score_encoding_progress_overview.html
- infrastructure/encodage_de_notes/encodage/repository/note_etudiant.py
> Encodage recherche

- program_management/templates/quick_search_egy_inner.html
- program_management/templates/quick_search_luy_inner.html
> OSIS-5946 Drop url

- learning_unit/schema.yml
- learning_unit_enrollment/api/serializers/enrollment.py
- learning_unit_enrollment/api/views/enrollment.py
- learning_unit_enrollment/schema.yml
>  OSIS-6076 make student specific profile guide nullable

- attribution/api/views/attribution.py
- attribution/tests/api/views/test_attribution.py
> OSIS-3830 : Get global volume

- learning_unit_enrollment/api/views/enrollment.py
- learning_unit_enrollment/schema.yml
> OSIS-3830 enable ordering in schema and api for enrollments

- assessments/templates/assessments/program_manager/learning_unit_score_encoding.html
- assessments/views/program_manager/learning_unit_score_encoding_form.py
- ddd/logic/encodage_des_notes/encodage/domain/service/progression_generale_encodage.py
- ddd/logic/encodage_des_notes/encodage/use_case/read/get_progression_generale_encodage_service.py
- ddd/logic/encodage_des_notes/shared_kernel/domain/service/progression_generale.py
- ddd/logic/encodage_des_notes/shared_kernel/dtos.py
- ddd/logic/encodage_des_notes/soumission/domain/service/progression_generale_encodage.py
- ddd/logic/encodage_des_notes/soumission/test/use_case/read/test_get_progression_generale_encodage_service.py
- ddd/logic/encodage_des_notes/soumission/use_case/read/get_progression_generale_encodage_service.py
- infrastructure/encodage_de_notes/soumission/repository/in_memory/note_etudiant.py
- infrastructure/messages_bus.py
> Encodage gestionnaire fixes

- assessments/templates/assessments/address/first_year_bachelor_score_sheet.html
> OSIS-6130 Ajout required_field

- learning_unit_enrollment/api/views/enrollment.py
- learning_unit_enrollment/schema.yml
> OSIS-3830 add enrolled students count

- assessments/tests/views/tutor/test_score_encoding_progress_overview.py
- assessments/views/tutor/score_sheet_xls_import.py
- ddd/logic/encodage_des_notes/soumission/builder/note_etudiant_builder.py
- ddd/logic/encodage_des_notes/soumission/domain/service/encoder_notes_en_lot.py
- ddd/logic/encodage_des_notes/soumission/domain/validator/_should_note_etre_choix_valide.py
- ddd/logic/encodage_des_notes/soumission/domain/validator/exceptions.py
- ddd/logic/encodage_des_notes/soumission/test/use_case/write/test_encoder_notes_etudiant_service.py
- ddd/logic/encodage_des_notes/soumission/use_case/write/encoder_notes_etudiant_service.py
- infrastructure/messages_bus.py
> Osis 6124 Testing analyste > prof > excel

- ddd/logic/effective_class_repartition/domain/service/class_distribution_with_attribution.py
- infrastructure/effective_class_repartition/domain/service/tutor_attribution.py
- infrastructure/tests/attribution/domain/service/test_tutor_attribution.py
> OSIS-6121 Issue 5: Afficher l'encodage pour les partims

- base/templates/learning_unit/components.html
- learning_unit/templates/class/update.html
Pull request automatique de technical/OSIS-6119 vers DEV
> [technical/OSIS-6119 => DEV] Gestion des classes > en-tête avec None

- base/models/enums/learning_unit_year_periodicity.py
- ddd/logic/learning_unit/domain/validator/exceptions.py
- learning_unit/forms/classes/update.py
- learning_unit/templates/class/identification_tab.html
Pull request automatique de technical/OSIS-6084 vers DEV
> [technical/OSIS-6084 => DEV] Gestion des classes > ajustement formulaire de création/visualisation

- doc/technical-manual.adoc
> Remove submodules configuration doc

- ddd/logic/learning_unit/repository/i_effective_class.py
- ddd/logic/learning_unit/use_case/read/get_learning_unit_effective_classes_service.py
- infrastructure/learning_unit/repository/effective_class.py
- infrastructure/learning_unit/repository/in_memory/effective_class.py
- learning_unit_enrollment/api/url_v1.py
- webservices/urls.py
> fix tests for refactoring bureau virtuel

- base/models/learning_unit_enrollment.py
- learning_unit_enrollment/api/views/enrollment.py
> OSIS-3830 optimize queries for learning_unit_enrollment api

- assessments/tests/views/serializers/test_score_sheet_xls_import.py
- assessments/views/program_manager/score_sheet_xls_import.py
- assessments/views/serializers/score_sheet_xls_import.py
- assessments/views/tutor/score_sheet_xls_import.py
- ddd/logic/encodage_des_notes/encodage/domain/service/encoder_notes_en_lot.py
- ddd/logic/encodage_des_notes/encodage/test/use_case/write/test_encoder_notes_service.py
- ddd/logic/encodage_des_notes/encodage/use_case/write/encoder_notes_service.py
- ddd/logic/encodage_des_notes/shared_kernel/commands.py
- ddd/logic/encodage_des_notes/shared_kernel/domain/builder/encoder_notes_rapport_builder.py
- ddd/logic/encodage_des_notes/shared_kernel/domain/builder/report_builder.py
- ddd/logic/encodage_des_notes/shared_kernel/domain/model/encoder_notes_rapport.py
- ddd/logic/encodage_des_notes/shared_kernel/domain/model/report.py
- ddd/logic/encodage_des_notes/shared_kernel/domain/model/report_events.py
- ddd/logic/encodage_des_notes/shared_kernel/repository/i_encoder_notes_rapport.py
- ddd/logic/encodage_des_notes/shared_kernel/repository/i_report.py
- ddd/logic/encodage_des_notes/shared_kernel/use_case/read/get_encoder_notes_rapport_service.py
- ddd/logic/encodage_des_notes/shared_kernel/use_case/read/get_encoder_notes_report_service.py
- ddd/logic/encodage_des_notes/soumission/domain/service/encoder_notes_en_lot.py
- ddd/logic/encodage_des_notes/soumission/test/use_case/write/test_encoder_notes_etudiant_service.py
- ddd/logic/encodage_des_notes/soumission/use_case/write/encoder_notes_etudiant_service.py
- infrastructure/encodage_de_notes/shared_kernel/repository/encoder_notes_rapport.py
- infrastructure/encodage_de_notes/shared_kernel/repository/in_memory/encoder_notes_rapport.py
- infrastructure/encodage_de_notes/shared_kernel/repository/report.py
- infrastructure/messages_bus.py
- infrastructure/tests/encodage_des_notes/shared_kernel/repository/test_encoder_notes_rapport.py
> [OSIS-6137] Testing analyste > Gestionnaire/Prof > Injection fichier XLS

- education_group/tests/views/training/test_administrative_data_read.py
- education_group/views/training/administrative_data_read.py
> OSIS-6147 Prevent showing program manager of 11BA

- program_management/business/excel.py
- program_management/ddd/domain/program_tree.py
- program_management/tests/business/test_excel.py
> OSIS-5956 : Ne plus se limiter au premier lien

- ddd/logic/learning_unit/domain/service/save_effective_class.py
- learning_unit/forms/classes/update.py
> OSIS-6091 : Mieux gérer quand ni volumes pratique, ni magistral

- learning_unit/auth/roles/central_manager.py
- osis_role/templatetags/osis_role.py
- osis_role/tests/templatetags/test_osis_role.py
> OSIS-6154 fix perm for central manager + modal when not authorized

- learning_unit/auth/roles/central_manager.py
- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-6154-1 add deny message

- base/business/learning_units/edition.py
- base/models/learning_component_year.py
- base/tests/business/test_learning_unit_edition.py
Pull request automatique de technical/OSIS-6033 vers DEV
> [technical/OSIS-6033 => DEV] Gestion des classes > les classes sont reportées sur 6 ans quand on modifie la date de fin de l_UE

- ddd/logic/encodage_des_notes/encodage/domain/service/i_notifier_encodage_notes.py
- ddd/logic/encodage_des_notes/encodage/use_case/write/encoder_notes_service.py
- infrastructure/encodage_de_notes/encodage/domain/service/in_memory/notifier_encodage_notes.py
- infrastructure/encodage_de_notes/encodage/domain/service/notifier_encodage_notes.py
- infrastructure/tests/encodage_des_notes/domain/service/test_notifier_encodage_notes.py
> OSIS-6141 fixed case mail not sent when student is not enrolled and score is missing

- learning_unit/schema.yml
- offer_enrollment/api/views/enrollment.py
> OSIS-3830 order offer enrollments api results by academic year

- attribution/templates/attribution/attributions.html
> OSIS-3446 : Ajout du tooltip pour le bouton "Gérer la répartition"

- program_management/business/excel.py
- program_management/tests/business/test_excel.py
> OSIS-5956 : Amélioration de l'affichage des blocks + mandatory

- assessments/templates/assessments/common/clear_filter.html
- assessments/templates/assessments/program_manager/score_encoding_progress_overview.html
- assessments/views/common/score_encoding_progress_overview.py
Pull request automatique de technical/OSIS-6142 vers DEV
> [technical/OSIS-6142 => DEV] Testing analyste > Gestionnaire > Recherche

- ddd/logic/encodage_des_notes/soumission/domain/service/i_notifier_soumission_notes.py
- ddd/logic/encodage_des_notes/soumission/test/factory/note_etudiant.py
- ddd/logic/encodage_des_notes/soumission/use_case/write/soumettre_notes_etudiant_service.py
- infrastructure/encodage_de_notes/encodage/domain/service/notifier_encodage_notes.py
- infrastructure/encodage_de_notes/soumission/domain/service/in_memory/notifier_soumission_notes.py
- infrastructure/encodage_de_notes/soumission/domain/service/notifier_soumission_notes.py
- infrastructure/messages_bus.py
- infrastructure/tests/encodage_des_notes/soumission/domain/service/test_notifier_soumission_notes.py
> OSIS-6146 fixed status in email when scores are not all submitted

- assessments/tests/views/serializers/test_score_sheet_xls_import.py
- assessments/views/serializers/score_sheet_xls_import.py
> (Encodage des notes) OSIS-6144 Issue 1: XLS import convert commat to dot

- learning_unit/schema.yml
- learning_unit_enrollment/api/views/enrollment.py
- learning_unit_enrollment/tests/api/views/test_enrollment.py
> OSIS-3830 optimize enrollments api perf

- infrastructure/encodage_de_notes/soumission/repository/note_etudiant.py
> OSIS-6139 Chunck queryparams for notes identites

- ddd/logic/encodage_des_notes/soumission/domain/model/note_etudiant.py
- infrastructure/encodage_de_notes/soumission/repository/note_etudiant.py
> OSIS-6139 Refactor to use minus queryparams

- attribution/schema.yml
> OSIS-3830 : Fix nullable total_learning_unit_charge

- assessments/templates/assessments/tutor/learning_unit_score_encoding.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding_submit_inner.html
Pull request automatique de technical/OSIS-6153 vers DEV
> [technical/OSIS-6153 => DEV] Testing analyste > prof > Encodage v2

- learning_unit_enrollment/api/views/enrollment.py
- learning_unit_enrollment/tests/api/views/test_enrollment.py
> OSIS-3830 filter enrollments by offer enrollment state

- ddd/logic/effective_class_repartition/tests/factory/tutor.py
> Fix random test fail

- requirements.txt
> upgrade packages

- assessments/templates/assessments/program_manager/learning_unit_score_encoding_form.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding_form.html
> OSIS-6213 focus on next input when keypress 'enter'

- assessments/tests/views/serializers/test_score_sheet_xls_import.py
- assessments/views/serializers/score_sheet_xls_import.py
Pull request automatique de technical/OSIS-6216 vers DEV
> [technical/OSIS-6216 => DEV] Testing analyste > XLS > impossible d_injecter un fichier > Décalage des colonnes

- base/fixtures/groups.json
> read administration can access catalog permission

- assessments/templates/assessments/program_manager/score_search_form.html
> OSIS-6200 : Add PEPS badge

- backoffice/settings/base.py
> Osis-document: settings

- assessments/tests/views/program_manager/test_score_sheet_xls_import.py
- assessments/tests/views/tutor/test_score_sheet_xls_import.py
- assessments/views/common/score_sheet_xls_import.py
- assessments/views/program_manager/score_sheet_xls_import.py
- assessments/views/tutor/score_sheet_xls_import.py
> OSIS-6220 xls injection : fixed case when score is erased by null or empty score

- base/fixtures/countries.csv
Pull request automatique de technical/OSIS-6204 vers DEV
> [technical/OSIS-6204 => DEV] Country _France Métropolitaine_ FX à supprimer ?

- base/fixtures/countries.csv
> [TEST] Technical/osis 6204 qa Remove FX (France métropolitaine) country in countries.csv

- base/fixtures/countries.csv
> [QA] OSIS-6204 Remove FX (France métropolitaine) country in countries.csv

- offer_enrollment/api/views/enrollment.py
> OSIS-5753 : Fix qs : use distinct nomas

- base/auth/predicates.py
- base/templates/education_group/blocks/dropdown/identification_actions_bar.html
- education_group/contrib/models.py
> Cache duplicate call + template cache for menu

- ddd/logic/encodage_des_notes/encodage/domain/service/encoder_notes_en_lot.py
- ddd/logic/encodage_des_notes/encodage/use_case/write/encoder_notes_service.py
> OSIS-4911 send email even if encoding errors

- backoffice/settings/local.py
- organisation/api/serializers/entities.py
- organisation/api/url_v1.py
- organisation/api/views/entities.py
- organisation/schema.yml
- organisation/tests/api/serializers/test_entities.py
- organisation/tests/api/views/test_entities.py
- organisations/api/serializers/entites.py
- organisations/api/url_v1.py
- organisations/api/views/entites.py
- organisations/schema.yml
- organisations/tests/api/serializers/test_entites.py
- organisations/tests/api/views/test_entites.py
- webservices/urls.py
> OS-73 : API to get entities

- reference/schema.yml
> OSIS-6167 : reference api 1.15

- reference/schema.yml
> OSIS-6167 : PaginatedResponse

- organisation/api/serializers/addresses.py
- organisation/api/views/addresses.py
- organisation/schema.yml
- organisation/tests/api/serializers/test_addresses.py
- organisation/tests/api/views/test_addresses.py
> OS-73 : EntitiesAddresses API

- assessments/api/serializers/progress_overview.py
- assessments/api/url_v1.py
- assessments/api/views/progress_overview.py
- assessments/schema.yml
- assessments/tests/api/views/test_progress_overview.py
- backoffice/settings/base.py
> OSIS-6219 create progress overview api endpoint

- reference/schema.yml
> OSIS-6167 : end_date nullable

- assessments/api/serializers/progress_overview.py
> OSIS-6219 fix missing change in serializer

- assessments/views/serializers/score_sheet_xls_import.py
> OSIS-6228 : Ajout de validation si trop peu de colonne de header

- base/business/learning_unit_xls.py
- base/tests/business/list/test_ue_utilizations.py
- base/tests/business/test_learning_unit_xls.py
> OSIS-6244 : ajout du champ 'Gestion par équipe' dans les xls des UE

- assessments/templates/assessments/program_manager/learning_unit_score_encoding.html
- assessments/templates/assessments/program_manager/learning_unit_score_encoding_form.html
- assessments/templates/assessments/program_manager/score_search_form.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding_form.html
> OSIS-6226 : tooltip + translation

- attribution/tests/views/manage_my_courses/test_manage_my_courses.py
- attribution/tests/views/manage_my_courses/test_my_attributions_summary_editable.py
- attribution/tests/views/test_manage_my_courses.py
- attribution/urls.py
- attribution/views/manage_my_courses.py
- attribution/views/manage_my_courses/manage_my_courses.py
- attribution/views/manage_my_courses/my_attributions_summary_editable.py
> OSIS-6245 : MyAttributionsSummaryEditable

- base/fixtures/countries.csv
- base/static/css/custom.css
Pull request automatique de feature/OSIS-6215 vers DEV
> [feature/OSIS-6215 => DEV] Améliorer la visibilité de l_icone de tri

- learning_unit/templates/class/identification_tab.html
Pull request automatique de technical/OSIS-6227 vers DEV
> [technical/OSIS-6227 => DEV] Gestion des classes > problème au niveau de l_affichage du quadrimestre en consultation

- assessments/templates/assessments/program_manager/learning_unit_score_encoding.html
- assessments/templates/assessments/program_manager/learning_unit_score_encoding_form.html
- assessments/templates/assessments/program_manager/score_search_form.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding_form.html
Pull request automatique de technical/OSIS-6226 vers DEV
> [technical/OSIS-6226 => DEV] Testing analyste > Gestionnaire + prof >intitulés et tooltips

- base/business/learning_unit_xls.py
- base/tests/business/list/test_ue_utilizations.py
- base/tests/business/test_learning_unit_xls.py
Pull request automatique de feature/OSIS-6244 vers DEV
> [feature/OSIS-6244 => DEV] En tant que personne ayant accès au catalogue des UE, je veux voir le champs Gestion par équipe dans les xls des UE

- base/api/serializers/student.py
- base/forms/student.py
- base/templates/student/students.html
- base/tests/views/test_student.py
- base/urls.py
- base/views/student.py
- base/views/student/detail.py
- base/views/student/list.py
> OSIS-6249 : Modification la vue students.py en class-based-views

- attribution/tests/views/manage_my_courses/test_educational_information.py
- attribution/tests/views/manage_my_courses/test_manage_my_courses.py
- attribution/urls.py
- attribution/views/manage_my_courses/educational_information.py
- attribution/views/manage_my_courses/manage_my_courses.py
- base/models/person.py
- base/views/learning_units/common.py
- base/views/learning_units/pedagogy/read.py
> OSIS-6247 : EducationalInformation

- program_management/api/serializers/education_group.py
- program_management/forms/education_groups.py
> (Program Management) Improve performance list

- education_group/views/serializers/achievement.py
- education_group/views/training/administrative_data_read.py
> Add select_related to improve performance on multiple view

- base/views/learning_units/common.py
- learning_unit/views/learning_unit/edit_educational_information.py
> OSIS-6245 : Refactor a little

- attribution/tests/views/test_attribution.py
- attribution/urls.py
- attribution/views/attribution.py
- attribution/views/manage_my_courses/my_educational_information.py
- base/tests/views/test_learning_unit.py
- base/tests/views/test_learning_unit_edition.py
- base/tests/views/test_learning_unit_pedagogy.py
- base/urls.py
- base/views/learning_unit.py
- base/views/learning_units/detail.py
- base/views/learning_units/pedagogy/read.py
- base/views/learning_units/update.py
> OSIS-6255 : LearningUnitAttributions + remove useless in context

- reference/api/views/city.py
> OSIS-6258 : remove lookup_expr to act as a filter not a search

- reference/api/views/language.py
- reference/schema.yml
> OSIS-6264 : Filter by code

- osis_role/contrib/views.py
- osis_role/tests/contrib/test_views.py
> Add an api required permission mixin

- assessments/views/program_manager/score_search.py
> [QA] Hotfix/osis 6261 Encodage de notes > Critères spécifiques > ajout d'un .0 après chaque note qui bloque la sauvegarde

- assessments/forms/score_encoding.py
- assessments/views/program_manager/score_search.py
> Hotfix/osis 6265 Encodage de notes > Critères spécifiques > impossible d'enregistrer avec la virgule pour les UE avec des crédits >= 15

- assessments/templates/assessments/program_manager/learning_unit_score_encoding.html
- assessments/templates/assessments/program_manager/learning_unit_score_encoding_form.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding_form.html
> OSIS-6268 Switcher colonnes PEPS et noma

- assessments/export/score_sheet_xls.py
- assessments/templates/assessments/common/row-background-color.html
- assessments/templates/assessments/program_manager/learning_unit_score_encoding.html
- assessments/templates/assessments/program_manager/learning_unit_score_encoding_form.html
- assessments/templates/assessments/program_manager/score_search_form.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding.html
- assessments/templates/assessments/tutor/learning_unit_score_encoding_form.html
- assessments/tests/views/serializers/test_score_sheet_xls.py
- assessments/views/program_manager/learning_unit_score_encoding_form.py
- assessments/views/serializers/score_sheet.py
- assessments/views/serializers/score_sheet_xls.py
- assessments/views/tutor/learning_unit_score_encoding.py
- assessments/views/tutor/learning_unit_score_encoding_form.py
- ddd/logic/encodage_des_notes/shared_kernel/dtos.py
> OSIS-6267 fix consistency in encoding deadlines in views and pdf/xls

- reference/api/views/city.py
Pull request automatique de technical/OSIS-6258 vers DEV
> [technical/OSIS-6258 => DEV] City API : les filtres ne devraient pas faire une recherche

- assessments/locale/en/LC_MESSAGES/django.po
- assessments/locale/fr_BE/LC_MESSAGES/django.po
- assessments/templates/assessments/program_manager/learning_unit_score_encoding_form.html
> OSIS-6270 : tooltip for program manager

- assessments/templates/assessments/program_manager/score_search_form.html
> OSIS-6268: Reverse PEPS column with Name

- assessments/views/program_manager/score_sheet_xls_import.py
> OSIS-6276 display each error in 1 line (scores injection by xls)

- assessments/forms/score_encoding.py
- assessments/templates/assessments/program_manager/score_encoding_progress_overview.html
- assessments/templates/assessments/program_manager/score_search_form.html
- assessments/urls.py
- assessments/views/program_manager/score_encoding_progress_overview.py
- assessments/views/program_manager/score_search.py
- base/static/css/osis.css
- ddd/logic/encodage_des_notes/encodage/builder/gestionnaire_parcours_builder.py
- ddd/logic/encodage_des_notes/encodage/commands.py
- ddd/logic/encodage_des_notes/encodage/domain/model/gestionnaire_parcours.py
- ddd/logic/encodage_des_notes/encodage/domain/service/progression_generale_encodage.py
- ddd/logic/encodage_des_notes/encodage/domain/service/rechercher_notes_etudiant.py
- ddd/logic/encodage_des_notes/encodage/test/use_case/read/test_rechercher_notes_service.py
- ddd/logic/encodage_des_notes/encodage/use_case/read/get_progression_generale_encodage_service.py
- ddd/logic/encodage_des_notes/encodage/use_case/read/rechercher_notes_service.py
> OSIS-4244 update ChoiceField to MultipleChoiceField to search 'formations' in score encoding

- ddd/logic/encodage_des_notes/encodage/builder/gestionnaire_parcours_builder.py
- ddd/logic/encodage_des_notes/encodage/domain/service/feuille_de_notes_par_cohorte.py
- ddd/logic/encodage_des_notes/encodage/domain/service/i_cohortes_du_gestionnaire.py
- ddd/logic/encodage_des_notes/encodage/use_case/read/get_cohortes_gestionnaire.py
- ddd/logic/encodage_des_notes/encodage/use_case/read/get_feuille_de_notes_service.py
- ddd/logic/encodage_des_notes/encodage/use_case/read/get_progression_generale_encodage_service.py
- ddd/logic/encodage_des_notes/encodage/use_case/read/rechercher_notes_service.py
- ddd/logic/encodage_des_notes/encodage/use_case/write/encoder_notes_service.py
- infrastructure/encodage_de_notes/encodage/domain/service/cohortes_du_gestionnaire.py
- infrastructure/encodage_de_notes/encodage/domain/service/in_memory/cohortes_du_gestionnaire.py
- infrastructure/tests/encodage_des_notes/domain/service/test_cohortes_du_gestionnaire.py
> OSIS-6273-bis

- assessments/views/serializers/score_sheet_xls_import.py
- base/utils/string.py
> OSIS-6284 fix header comparison for excel injection

- assessments/forms/scores_responsible.py
- assessments/locale/en/LC_MESSAGES/django.po
- assessments/locale/fr_BE/LC_MESSAGES/django.po
- assessments/templates/assessments/score_responsible/score_responsibles.html
Pull request automatique de hotfix/OSIS-6281 vers QA
> [hotfix/OSIS-6281 => QA] Désignation du responsable de notes > ajustements visuels au niveau du moteur de recherche

- assessments/export/score_sheet_xls.py
- assessments/views/serializers/score_sheet_xls_import.py
> OSIS-6284 check only mandatory header part present when injecting

- backoffice/settings/base.py
> commented 'transversal apps' in INSTALLED_APPS

- backoffice/settings/base.py
> Revert "commented 'transversal apps' in INSTALLED_APPS"

- requirements.txt
> [To Master] downgrade pillow version

- requirements.txt
> [To Master] downgrade pyyaml version

- assessments/forms/score_encoding.py
- assessments/templates/assessments/program_manager/score_encoding_progress_overview.html
- assessments/templates/assessments/program_manager/score_search_form.html
- assessments/views/program_manager/score_encoding_progress_overview.py
- base/static/css/osis.css
> OSIS-4244 fixed issues 2 to 4

- requirements.txt
> [MASTER] update requirements to python3.7

- assessments/templates/assessments/program_manager/score_encoding_progress_overview.html
> OSIS-6280 : remove tooltips

- requirements.txt
> [DEV] update requirements to python3.7

- assessments/templates/assessments/program_manager/score_encoding_progress_overview.html
> OSIS-6280 : Refactor

- learning_unit_enrollment/tests/api/views/test_enrollment.py
> fix random test

- ddd/logic/encodage_des_notes/shared_kernel/domain/service/i_periode_encodage_notes.py
- ddd/logic/encodage_des_notes/soumission/domain/service/encoder_adresse_feuille_de_notes.py
- ddd/logic/encodage_des_notes/soumission/domain/service/entites_adresse_feuille_de_notes.py
- ddd/logic/encodage_des_notes/soumission/domain/service/get_adresse_feuille_de_notes_dto.py
- ddd/logic/encodage_des_notes/soumission/test/use_case/read/test_get_adresse_feuille_de_notes_service.py
- ddd/logic/encodage_des_notes/soumission/test/use_case/write/test_encoder_addresse_feuille_de_notes_specifique_service.py
- ddd/logic/encodage_des_notes/soumission/test/use_case/write/test_encoder_adresse_entite_comme_addresse_feuille_de_notes_service.py
- ddd/logic/encodage_des_notes/soumission/test/use_case/write/test_supprimer_adresse_feuille_de_note_premiere_annee_du_bachelier_service.py
- infrastructure/encodage_de_notes/shared_kernel/service/in_memory/periode_encodage_notes.py
- infrastructure/encodage_de_notes/shared_kernel/service/periode_encodage_notes.py
- infrastructure/tests/encodage_des_notes/domain/service/test_periode_soumission_notes.py
Pull request automatique de hotfix/OSIS-6292 vers QA
> [hotfix/OSIS-6292 => QA] Impossible d_accéder à la gestion des adresses des feuilles de notes si la période est fermée

- learning_unit/schema.yml
> [DEV] Fix schema learning_unit.yml

- learning_unit/schema.yml
> [MASTER] Fix schema learning unit 

- base/templates/education_group/blocks/dropdown/identification_actions_bar.html
- education_group/views/group/common_read.py
- education_group/views/mini_training/common_read.py
- education_group/views/training/common_read.py
> OSIS-6299 : Ajout de l'active_tab dans l'utilisation de  cache

- requirements.txt
> [QA] update requirements to python3.7

- base/utils/serializers.py
- osis_role/contrib/views.py
- osis_role/tests/contrib/test_views.py
- Refactorization of the api permission required mixin to allow the use of the utility method.
- Update the DTOSerializer to keep the fields that are defined on the serializer class level but not on the DTO.
> Refactorization of the api permission required mixin

- base/templates/education_group/blocks/dropdown/identification_actions_bar.html
- education_group/views/group/common_read.py
- education_group/views/mini_training/common_read.py
- education_group/views/training/common_read.py
Pull request automatique de hotfix/OSIS-6299 vers MASTER
> [hotfix/OSIS-6299 => MASTER] La modification des OFs ne fonctionne plus correctement

- assessments/locale/en/LC_MESSAGES/django.po
- assessments/locale/fr_BE/LC_MESSAGES/django.po
- assessments/templates/assessments/tutor/learning_unit_score_encoding_form.html
> OSIS-6310 display error message client side when score is invalid

- assessments/locale/en/LC_MESSAGES/django.po
- assessments/locale/fr_BE/LC_MESSAGES/django.po
- assessments/templates/assessments/program_manager/score_encoding_progress_overview.html
- assessments/templates/assessments/score_responsible/score_responsibles.html
- assessments/templates/assessments/score_responsible/select_score_responsible.html
Pull request automatique de hotfix/OSIS-6309 vers QA
> [hotfix/OSIS-6309 => QA] Désignation du responsable de notes > ajustements visuels

- assessments/export/score_sheet_xls.py
> [hotfix/OSIS-6290 => QA] Encodage de notes > XLS > afficher sur fond blanc les données PEPS

- assessments/export/score_sheet_xls.py
Pull request automatique de hotfix/OSIS-6290 vers DEV
> [hotfix/OSIS-6290 => DEV] Encodage de notes > XLS > afficher sur fond blanc les données PEPS

- assessments/templates/assessments/program_manager_administration/list.html
- assessments/views/program_manager/pgm_manager_administration.py
> Osis 6303 some fixes for program manager administration

- .behaverc
> remove behaverc

- assessments/views/address/search.py
Pull request automatique de hotfix/OSIS-6293 vers QA
> [hotfix/OSIS-6293 => QA] Les formations 2M ne doivent pas être reprises dans la liste des adresses

- assessments/views/address/search.py
Pull request automatique de hotfix/OSIS-6293 vers DEV
> [hotfix/OSIS-6293 => DEV] Les formations 2M ne doivent pas être reprises dans la liste des adresses

- assessments/locale/en/LC_MESSAGES/django.po
- assessments/locale/fr_BE/LC_MESSAGES/django.po
- assessments/templates/assessments/tutor/learning_unit_score_encoding_form.html
Pull request automatique de hotfix/OSIS-6310 vers QA
> [hotfix/OSIS-6310 => QA] Encodage des notes > Prof > Encodage en ligne > reprendre le message d_erreur en dessous de la zone

- assessments/templates/assessments/program_manager/score_encoding_progress_overview.html
- base/models/student_specific_profile.py
Pull request automatique de technical/OSIS-6298 vers DEV
> [technical/OSIS-6298 => DEV] Module d_administration > impossible d_éditer les PEPS (Student Specific Profile)

- base/auth/roles/program_manager.py
> OSIS-6327 : Renommage permission

- base/fixtures/countries.csv
> Fix missing Georgie

- base/fixtures/countries.csv
> Fix georgie

- organisation/api/serializers/entities.py
- organisation/api/url_v1.py
- organisation/api/views/entities.py
- organisation/schema.yml
- organisation/tests/api/views/test_entities.py
> OS-103 : get detail of entity and add search_fields

- infrastructure/application/repository/vacant_course.py
- infrastructure/application/services/learning_unit_service.py
- infrastructure/application/test/repository/test_vacant_course.py
- infrastructure/application/test/services/test_learning_unit_service.py
> OSIS-6402 : Issue if empty list entity_ids passed in methods

- base/forms/learning_unit/external_learning_unit.py
- base/forms/learning_unit/learning_unit_create_2.py
- base/tests/views/test_learning_unit_deletion.py
- base/tests/views/test_learning_unit_proposal.py
> OSIS-6182 Fixed multi learning_container

- organisation/schema.yml
> Missing parameter in schema (organisation_code)

- ddd/locale/fr_BE/LC_MESSAGES/django.po
> OSIS-6057 Adapt translation for 'activité vacante' to 'cours vacant'

- osis_role/contrib/views.py
- osis_role/tests/contrib/test_views.py
Raising an exception make ActionLinkSerializer fail on rendering
> Fix check_method_permissions should return str or None

- base/tests/forms/test_learning_unit_postponement.py
- learning_unit/models/learning_class_year.py
- learning_unit/tests/models/test_learning_class_year.py
> OSIS-6425 : post_delete signal on classes

- base/fixtures/validation_rules.csv
> OSIS-6379 : Allow 3 digits into code

- manage_submodules.py
> [QA] fix manage submodule when declaring more than one submodule

- learning_unit/locale/en/LC_MESSAGES/django.po
- learning_unit/locale/fr_BE/LC_MESSAGES/django.po
- learning_unit/views/learning_unit_class/create.py
- learning_unit/views/learning_unit_class/update.py
> hotfix/OSIS-6331 (Gestion des classes) Afficher Erreur(s) dans le formulaire

- attribution/tasks/send_attribution_end_date_reached_summary.py
- ddd/logic/application/use_case/write/send_attribution_end_date_reached_summary.py
- infrastructure/application/services/attribution_end_date_reached_summary.py
> OSIS-6373 : Ajout de logs

- requirements.txt
> [QA]update django celery beat

- infrastructure/application/services/attribution_end_date_reached_summary.py
> OSIS-6373 : Véfification pour voir si un mail a déjà été envoyé

- base/migrations/0619_remove_tutors_without_attribution.py
- osis_role/contrib/models.py
> OSIS-6419 : Fix script and osis-role if no user

- attribution/tasks/send_attribution_end_date_reached_summary.py
- ddd/logic/application/use_case/write/send_attribution_end_date_reached_summary.py
- infrastructure/application/services/attribution_end_date_reached_summary.py
> Osis 6373 Enyoyer un mail aux profs à l’ouverture du module pour rappeler leurs attributions échues

- mockup/templates/mockup/ajouter_unites_enseignement.html
- mockup/templates/mockup/blocks/tab_contenu.html
- mockup/templates/mockup/blocks/tab_formulaire_inscription.html
- mockup/templates/mockup/formulaire_inscription.html
- mockup/templates/mockup/modification_unites_enseignement.html
- mockup/templates/mockup/supprimer_unites_enseignements.html
- mockup/templates/mockup/tabs.html
- mockup/views/event_modeling.py
- mockup/views/formulaire_inscription.py
> event-modeling-ajout-formulaire-inscription

- mockup/templates/mockup/ajouter_unites_enseignement.html
- mockup/templates/mockup/blocks/tab_contenu.html
- mockup/templates/mockup/blocks/tab_formulaire_inscription.html
- mockup/templates/mockup/modification_unites_enseignement.html
- mockup/templates/mockup/supprimer_unites_enseignements.html
- mockup/templates/mockup/tabs.html
> usage of bootstrap tabs + fixed bad hx-target of actions (infinite include)

- infrastructure/application/services/attribution_end_date_reached_summary.py
> [QA] Osis 6373 qa

- mockup/templates/mockup/blocks/tab_formulaire_inscription.html
> Hardcode form view template

- base/static/css/custom.css
- mockup/templates/mockup/ajouter_unites_enseignement.html
- mockup/templates/mockup/blocks/tab_contenu.html
- mockup/templates/mockup/blocks/tab_formulaire_inscription.html
- mockup/templates/mockup/modification_unites_enseignement.html
- mockup/templates/mockup/supprimer_unites_enseignements.html
- mockup/templates/mockup/tabs.html
- preparation_inscription/templates/preparation_inscription/ajouter_unites_enseignement.html
- preparation_inscription/templates/preparation_inscription/blocks/tab_contenu.html
- preparation_inscription/templates/preparation_inscription/blocks/tab_formulaire_inscription.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_recursif.html
- preparation_inscription/templates/preparation_inscription/consulter_contenu_groupement.html
- preparation_inscription/templates/preparation_inscription/formulaire_inscription.html
- preparation_inscription/templates/preparation_inscription/modification_unites_enseignement.html
- preparation_inscription/templates/preparation_inscription/preparation_inscription.html
- preparation_inscription/templates/preparation_inscription/supprimer_unites_enseignements.html
- preparation_inscription/templates/preparation_inscription/tabs.html
- preparation_inscription/urls.py
- preparation_inscription/views/consulter_contenu_groupement.py
- preparation_inscription/views/formulaire_inscription.py
- preparation_inscription/views/modification_contenu_groupement.py
- preparation_inscription/views/supprimer_unites_enseignement.py
> integrate form view in preparation_inscription

- ddd/logic/preparation_programme_annuel_etudiant/domain/service/get_formulaire_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/dtos.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/catalogue_formations.py
- preparation_inscription/templates/ligne_formulaire_inscription_pour_ue.html
- preparation_inscription/templatetags/formatage_credits.py
- preparation_inscription/views/formulaire_inscription_cours.py
- program_management/ddd/dtos.py
- program_management/ddd/repositories/program_tree_version.py
> OSIS-6313-corrections-isssues : corrections diverses pour l'affichage

- reference/migrations/0010_highschool.py
- reference/models/high_school.py
> OSIS-6458:  Fix ordering by organization name

- base/forms/learning_unit/external_learning_unit.py
- base/forms/learning_unit/learning_unit_create_2.py
> OSIS-6478 quick fix learning_container from first_ue missing

- mockup/templates/mockup/blocks/btn_annuler_ajout.html
- mockup/templates/mockup/blocks/btn_annuler_modification.html
- mockup/templates/mockup/blocks/btn_annuler_suppression.html
- mockup/templates/mockup/blocks/btn_deplacer_bas.html
- mockup/templates/mockup/blocks/btn_deplacer_haut.html
- mockup/templates/mockup/blocks/consulter_contenu_groupement.html
- mockup/templates/mockup/tabs.html
- mockup/urls.py
- mockup/views/deplacer_unite_enseignement.py
- mockup/views/event_modeling.py
> add view and update html to move an element in the list (up / down) with htmx

- ddd/logic/application/use_case/read/get_attributions_about_to_expire_service.py
- ddd/logic/application/use_case/write/renew_multiple_attributions_service.py
> [QA] (Candidature en ligne) Fix already applied error

- base/forms/learning_unit/external_learning_unit.py
- base/forms/learning_unit/learning_unit_create_2.py
> OSIS-6478 : Fix multiple container

- organisation/api/serializers/addresses.py
- organisation/api/views/addresses.py
- organisation/schema.yml
- organisation/tests/api/serializers/test_addresses.py
- organisation/tests/api/views/test_addresses.py
> Fix entity api : get address from Entity model

- ddd/logic/preparation_programme_annuel_etudiant/use_case/read/get_formulaire_inscription_cours_service.py
- preparation_inscription/templates/preparation_inscription/ajouter_unites_enseignement.html
- preparation_inscription/templates/preparation_inscription/blocks/tab_contenu.html
- preparation_inscription/templates/preparation_inscription/blocks/tab_formulaire_inscription.html
- preparation_inscription/templates/preparation_inscription/consulter_contenu_groupement.html
- preparation_inscription/templates/preparation_inscription/modification_unites_enseignement.html
- preparation_inscription/templates/preparation_inscription/supprimer_unites_enseignements.html
- preparation_inscription/templates/preparation_inscription/tabs.html
- preparation_inscription/urls.py
- preparation_inscription/views/ajouter_unites_enseignement.py
- preparation_inscription/views/modification_contenu_groupement.py
> include pae urls into path starting with year and acronym

- base/auth/roles/program_manager.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/read/test_get_formulaire_inscription_cours_service.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/in_memory/catalogue_formations.py
- infrastructure/preparation_programme_annuel_etudiant/tests/domain/service/test_catalogue_formations.py
- preparation_inscription/__init__.py
- preparation_inscription/tests/views/test_formulaire_inscription_cours.py
- preparation_inscription/views/formulaire_inscription_cours.py
- program_management/tests/ddd/repositories/test_program_tree_version.py
> OSIS-6313 :  Ajout de test pour la vue.

- ddd/logic/preparation_programme_annuel_etudiant/domain/service/get_formulaire_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/dtos.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/read/test_get_formulaire_inscription_cours_service.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/catalogue_formations.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/in_memory/catalogue_formations.py
- infrastructure/preparation_programme_annuel_etudiant/tests/domain/service/test_catalogue_formations.py
- preparation_inscription/tests/views/test_formulaire_inscription_cours.py
- preparation_inscription/views/formulaire_inscription_cours.py
- program_management/ddd/dtos.py
- program_management/ddd/repositories/program_tree_version.py
- program_management/tests/ddd/repositories/test_program_tree_version.py
> OSIS-6313-issue6 : correction affichage intitulé de programme

- preparation_inscription/templates/preparation_inscription/consulter_contenu_groupement.html
- preparation_inscription/views/ajouter_unites_enseignement.py
- preparation_inscription/views/consulter_contenu_groupement.py
- preparation_inscription/views/program_tree.py
> OSIS-6317 refresh automatically tree when new UE is added to the program

- base/forms/learning_unit/external_learning_unit.py
- base/forms/learning_unit/learning_unit_create_2.py
Pull request automatique de hotfix/OSIS-6478 vers MASTER
> Release 4.1.5

- mockup/templates/mockup/blocks/tree_recursif.html
> Fix tree icons

- ddd/logic/preparation_programme_annuel_etudiant/domain/service/get_programme_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/read/test_get_programme_inscription_cours_service.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/in_memory/catalogue_formations.py
- preparation_inscription/tests/views/test_formulaire_inscription_cours.py
- preparation_inscription/views/formulaire_inscription_cours.py
> feature/OSIS-6313 : Amélioration correction tests

- ddd/logic/preparation_programme_annuel_etudiant/commands.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/builder/groupement_ajuste_inscription_cours_builder.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/model/groupement_ajuste_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/service/get_formulaire_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/service/get_programme_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/service/i_catalogue_formations.py
- ddd/logic/preparation_programme_annuel_etudiant/dtos.py
- ddd/logic/preparation_programme_annuel_etudiant/repository/i_groupement_ajuste_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/read/test_get_programme_inscription_cours_service.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/write/test_ajouter_UE_au_programme_service.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/catalogue_formations.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/in_memory/catalogue_formations.py
- infrastructure/preparation_programme_annuel_etudiant/repository/in_memory/groupement_ajuste_inscription_cours.py
- preparation_inscription/templates/preparation_inscription/ajouter_unites_enseignement.html
- preparation_inscription/templates/preparation_inscription/consulter_contenu_groupement.html
- preparation_inscription/templates/preparation_inscription/modification_unites_enseignement.html
- preparation_inscription/templates/preparation_inscription/supprimer_unites_enseignements.html
- preparation_inscription/templates/preparation_inscription/tabs.html
- preparation_inscription/urls.py
- preparation_inscription/views/ajouter_unites_enseignement.py
- preparation_inscription/views/detail.py
- preparation_inscription/views/formulaire_inscription_cours.py
- preparation_inscription/views/modification_contenu_groupement.py
- preparation_inscription/views/program_tree.py
- preparation_inscription/views/supprimer_unites_enseignement.py
- program_management/ddd/dtos.py
- program_management/ddd/repositories/program_tree_version.py
- program_management/ddd/service/read/get_program_tree_version_service.py
> Use annee & code_programme for urls

- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/read/test_get_formulaire_inscription_cours_service.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/read/test_get_programme_inscription_cours_service.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/in_memory/catalogue_formations.py
> base-pae-ajout-cas-de-test : Ajout de cas de base pour les tests

- preparation_inscription/templates/preparation_inscription/blocks/tree_panel.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_recursif.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_sous_programme.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_unites_enseignements.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_unites_enseignements_ajoutees.html
> (Preparation PAE) Correction bloc column on tree

- ddd/logic/preparation_programme_annuel_etudiant/domain/service/get_programme_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/read/test_get_programme_inscription_cours_service.py
> OSIS-6314 : Issue 2 : missing level

- preparation_inscription/templates/preparation_inscription/blocks/tree_sous_programme.html
> OSIS-6314 : Fix missing level

- preparation_inscription/templates/preparation_inscription/blocks/tree_recursif.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_sous_programme.html
> OSIS-6314 : Fix

- base/auth/roles/program_manager.py
- preparation_inscription/tests/views/test_consulter_contenu_groupement.py
- preparation_inscription/tests/views/test_detail.py
- preparation_inscription/tests/views/test_program_tree.py
- preparation_inscription/views/consulter_contenu_groupement.py
- preparation_inscription/views/detail.py
- preparation_inscription/views/program_tree.py
> Osis 6314 issue 6 Gestion des permissions

- preparation_inscription/templates/preparation_inscription/blocks/tree_panel.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_recursif.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_sous_programme.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_unites_enseignements.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_unites_enseignements_ajoutees.html
- preparation_inscription/templates/preparation_inscription/preparation_inscription.html
- preparation_inscription/tests/views/test_detail.py
- preparation_inscription/views/detail.py
> Osis 6314 issue 7

- reference/api/serializers/country.py
- reference/api/views/country.py
- reference/schema.yml
- reference/tests/api/serializers/test_country.py
> OSIS-6463 : Add dialing_code to country api

- ddd/logic/preparation_programme_annuel_etudiant/domain/service/get_formulaire_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/service/get_programme_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/service/i_catalogue_formations.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/validator/exceptions.py
- ddd/logic/preparation_programme_annuel_etudiant/dtos.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/read/test_get_formulaire_inscription_cours_service.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/read/test_get_programme_inscription_cours_service.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/catalogue_formations.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/in_memory/catalogue_formations.py
- infrastructure/preparation_programme_annuel_etudiant/tests/domain/service/test_catalogue_formations.py
- preparation_inscription/templates/preparation_inscription/blocks/ligne_formulaire_inscription.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_recursif.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_sous_programme.html
- preparation_inscription/tests/views/test_formulaire_inscription_cours.py
- preparation_inscription/tests/views/test_program_tree.py
- preparation_inscription/views/detail.py
- program_management/ddd/dtos.py
- program_management/ddd/repositories/program_tree_version.py
- program_management/tests/ddd/repositories/test_program_tree_version.py
> Refactor catalogue

- ddd/logic/preparation_programme_annuel_etudiant/commands.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/builder/groupement_ajuste_inscription_cours_builder.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/builder/programme_inscription_cours_identity_builder.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/model/groupement_ajuste_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/model/unite_enseignement_supprimee.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/validator/_should_unite_enseignement_pas_deja_supprimee.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/validator/exceptions.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/validator/validators_by_business_action.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/write/test_supprimer_UE_du_programme_service.py
- ddd/logic/preparation_programme_annuel_etudiant/use_case/write/ajouter_UE_au_programme_service.py
- infrastructure/messages_bus.py
- preparation_inscription/locale/en/LC_MESSAGES/django.po
- preparation_inscription/locale/fr_BE/LC_MESSAGES/django.po
- preparation_inscription/templates/preparation_inscription/consulter_contenu_groupement.html
- preparation_inscription/templates/preparation_inscription/formulaire_inscription.html
- preparation_inscription/templates/preparation_inscription/modal_confirmer_annuler_ajout.html
- preparation_inscription/templates/preparation_inscription/modal_confirmer_annuler_modification.html
- preparation_inscription/templates/preparation_inscription/modal_confirmer_annuler_suppression.html
- preparation_inscription/templates/preparation_inscription/modification_unites_enseignement.html
- preparation_inscription/templates/preparation_inscription/preparation_inscription.html
- preparation_inscription/templates/preparation_inscription/supprimer_unites_enseignement.html
- preparation_inscription/views/consulter_contenu_groupement.py
- preparation_inscription/views/supprimer_unites_enseignement.py
> OSIS-6346 implement supprimer_UE_du_programme_service

- preparation_inscription/templates/preparation_inscription/blocks/tree_panel.html
> OSIS-6314 - Open/Close all limited to node selected

- ddd/logic/preparation_programme_annuel_etudiant/domain/service/get_programme_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/dtos.py
- preparation_inscription/templates/preparation_inscription/blocks/tree_recursif.html
- preparation_inscription/tests/views/test_program_tree.py
> OSIS-6314 Issue 10: Sigle (+sigle version) insead of code

- reference/api/serializers/country.py
- reference/api/views/country.py
- reference/schema.yml
- reference/tests/api/serializers/test_country.py
> OSIS-6461 : resolve conflicts

- ddd/logic/preparation_programme_annuel_etudiant/domain/service/get_programme_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/dtos.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/catalogue_formations.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/in_memory/catalogue_formations.py
- infrastructure/preparation_programme_annuel_etudiant/tests/domain/service/test_catalogue_formations.py
- preparation_inscription/templates/preparation_inscription/blocks/tree_panel.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_recursif.html
- preparation_inscription/tests/views/test_detail.py
- preparation_inscription/tests/views/test_program_tree.py
- preparation_inscription/views/detail.py
- program_management/ddd/dtos.py
- program_management/ddd/repositories/program_tree_version.py
> OSIS-6314 Display transition name

- ddd/logic/preparation_programme_annuel_etudiant/commands.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/service/i_catalogue_formations.py
- ddd/logic/preparation_programme_annuel_etudiant/dtos.py
- ddd/logic/preparation_programme_annuel_etudiant/use_case/read/get_contenu_groupement_service.py
- infrastructure/messages_bus.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/catalogue_formations.py
- infrastructure/preparation_programme_annuel_etudiant/domain/service/in_memory/catalogue_formations.py
- preparation_inscription/templates/preparation_inscription/ajouter_unites_enseignement.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_panel.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_recursif.html
- preparation_inscription/templates/preparation_inscription/blocks/tree_sous_programme.html
- preparation_inscription/templates/preparation_inscription/consulter_contenu_groupement.html
- preparation_inscription/templates/preparation_inscription/modification_unites_enseignement.html
- preparation_inscription/templates/preparation_inscription/supprimer_unites_enseignements.html
- preparation_inscription/templates/preparation_inscription/tabs.html
- preparation_inscription/templatetags/formatage_credits.py
- preparation_inscription/tests/views/test_consulter_contenu_groupement.py
- preparation_inscription/urls.py
- preparation_inscription/utils/chiffres_significatifs_de_decimal.py
- preparation_inscription/views/consulter_contenu_groupement.py
- preparation_inscription/views/detail.py
- program_management/ddd/command.py
- program_management/ddd/service/read/get_content_service.py
> OSIS-6340-depuis-base-pae : refait à partir de base-pae

- reference/schema.yml
> Fix bad tag

- infrastructure/preparation_programme_annuel_etudiant/domain/service/catalogue_formations.py
- preparation_inscription/templates/preparation_inscription/consulter_contenu_groupement.html
- program_management/ddd/domain/node.py
- program_management/ddd/repositories/load_node.py
- program_management/ddd/service/read/get_content_service.py
> OSIS-6340 : Corrections suite au 'test failed'

- program_management/ddd/repositories/tree_prerequisites.py
- program_management/ddd/validators/_has_or_is_prerequisite.py
Pull request automatique de hotfix/OSIS-6430 vers QA
> [hotfix/OSIS-6430 => QA] Catalogue > Contrôle des prérequis > se limiter à l_anac du groupement

- preparation_inscription/templates/preparation_inscription/tabs.html
> add tab liste_des_ues

- preparation_inscription/templates/preparation_inscription/consulter_contenu_groupement.html
- preparation_inscription/urls.py
- preparation_inscription/views/modification_contenu_groupement.py
> enable access to 'edit_properties' mockup with code_groupement in url

- base/auth/roles/program_manager.py
- ddd/logic/preparation_programme_annuel_etudiant/commands.py
- ddd/logic/preparation_programme_annuel_etudiant/repository/i_groupement_ajuste_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/use_case/write/remettre_programme_dans_etat_initial_service.py
- infrastructure/messages_bus.py
- infrastructure/preparation_programme_annuel_etudiant/repository/in_memory/groupement_ajuste_inscription_cours.py
- preparation_inscription/templates/preparation_inscription/blocks/tree_recursif.html
- preparation_inscription/templates/preparation_inscription/modal_confirmer_remettre_etat_initial_inner.html
- preparation_inscription/templates/preparation_inscription/preparation_inscription.html
- preparation_inscription/tests/views/test_remettre_etat_initial.py
- preparation_inscription/urls.py
- preparation_inscription/views/remettre_etat_initial.py
> OSIS-6364 : remettre programme dans etat initial 

- preparation_inscription/templates/mockup/blocks/mockup_consulter_contenu_groupement.html
- preparation_inscription/templates/mockup/blocks/mockup_tree_apres_ajout_groupements.html
- preparation_inscription/templates/preparation_inscription/ajouter_groupements.html
- preparation_inscription/templates/preparation_inscription/consulter_contenu_groupement.html
- preparation_inscription/urls.py
- preparation_inscription/views/ajouter_groupements.py
- preparation_inscription/views/mockup.py
> Mockups 08 02 2022

- ddd/logic/preparation_programme_annuel_etudiant/commands.py
> OSIS-6339 : adapt commands with code_programme and editable properties

- ddd/logic/preparation_programme_annuel_etudiant/commands.py
> OSIS-6339 : use only bloc for nominal case

- base/api/serializers/person.py
> OSIS-6508 user roles api return acronym based on cohort

- ddd/logic/preparation_programme_annuel_etudiant/domain/builder/groupement_ajuste_inscription_cours_builder.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/model/groupement_ajuste_inscription_cours.py
- ddd/logic/preparation_programme_annuel_etudiant/domain/service/modifier_unites_enseignement.py
- ddd/logic/preparation_programme_annuel_etudiant/tests/use_case/write/test_modifier_UE_du_programme_service.py
- ddd/logic/preparation_programme_annuel_etudiant/use_case/write/modifier_UE_du_programme_service.py
- infrastructure/messages_bus.py
> OSIS-6350 : use case

- infrastructure/learning_unit/repository/learning_unit.py
- infrastructure/tests/learning_unit/repository/test_learning_unit.py
> OSIS-6317 make learning unit search not case sensitive

- base/api/serializers/person.py
Pull request automatique de hotfix/OSIS-6508 vers MASTER
> Release 4.1.6

- ddd/locale/fr_BE/LC_MESSAGES/django.po
- preparation_inscription/templates/preparation_inscription/consulter_contenu_groupement.html
> Osis 6317 small fixes

- preparation_inscription/templates/mockup/blocks/mockup_consulter_contenu_groupement.html
> fix mockup

- preparation_inscription/locale/en/LC_MESSAGES/django.po
- preparation_inscription/locale/fr_BE/LC_MESSAGES/django.po
- preparation_inscription/templates/preparation_inscription/tabs.html
> OSIS-6512 : Modification intitulé "Formulaire" en "Vue formulaire"

- base/management/commands/run_test_until_first_fail.py
> Try to adapt to choose the number of try

- base/migrations/0619_remove_tutors_without_attribution.py
> Add the attribution dependency into the base-0619 migration

- preparation_inscription/locale/en/LC_MESSAGES/django.po
- preparation_inscription/locale/fr_BE/LC_MESSAGES/django.po
- preparation_inscription/templates/preparation_inscription/modal_confirmer_remettre_etat_initial_inner.html
- preparation_inscription/urls.py
- preparation_inscription/views/remettre_etat_initial.py
> OSIS-6364 : translations and success message

- reference/api/views/country.py
- reference/schema.yml
- reference/tests/api/views/test_country.py
> OSIS-6514 : filter by excluding iso_code

- base/locale/en/LC_MESSAGES/django.po
- base/locale/fr_BE/LC_MESSAGES/django.po
- base/templates/learning_unit/search/base.html
- program_management/locale/en/LC_MESSAGES/django.po
- program_management/locale/fr_BE/LC_MESSAGES/django.po
- program_management/templates/search.html
> OSIS-6501 : tooltip for regex

- base/forms/learning_unit/search/simple.py
- base/templates/learning_unit/blocks/form/search_form_summary_list.html
- base/tests/forms/learning_unit/test_search_form.py
- learning_unit/urls.py
- learning_unit/views/autocomplete.py
> OSIS-6462 implement multiple select for learning unit types

- base/forms/learning_unit/edition_volume.py
> OSIS-6526 fix permission check for simplified volume form

- base/forms/learning_unit/edition_volume.py
Pull request automatique de hotfix/OSIS-6526 vers MASTER
> Release 4.1.7

- base/static/css/osis.css
- base/templates/learning_unit/search/base.html
- program_management/templates/search.html
> OSIS-6501 : some ui fixes

- base/templates/learning_unit/search/base.html
> OSIS-6501 : move lightbulb next to action button

- base/business/academic_calendar.py
> OSIS-6232 order academic events by start date

- base/static/css/custom.css
- preparation_inscription/templates/preparation_inscription/blocks/contenu_groupement_ligne_unite_enseignement.html
- preparation_inscription/templates/preparation_inscription/blocks/modification_contenu_ligne_unite_enseignement.html
> Base pae custom stacked icons
